<?php

use Application\Controller\Helper\Constantes;
use Application\View\Helper\BotaoSimples;

$form = $this->AtivarFichaForm;
$form->prepare();
$form->setAttribute(Constantes::$ACTION, $this->url(Constantes::$ROUTE_CADASTRO, array(Constantes::$PAGINA => Constantes::$PAGINA_ATIVAR_RESERVA_REVISAO)));
?>
<div class="mw1000 center-block p10">
    <div class="row ">
        <div id="content" class="animated fadeIn">
            <div class="row">
                <!-- Cadastro de Pessoa -->
                <div class="admin-form " id="register1" role="tabpanel">
                    <blockquote class="blockquote-primary">
                        <p><?php echo $this->translate(Constantes::$TRADUCAO_ATIVAR_FICHA); ?></p>
                        <small><?php echo $this->translate(Constantes::$TRADUCAO_ATIVAR_FICHA_LABEL); ?></small>
                    </blockquote>
                    <div class="panel panel-primary heading-border">
                        <?php echo $this->form()->openTag($form); ?>
                        <div class="panel-body bg-light p25">
                            <?php echo $this->divMensagens(); ?>
                            <div id="inputCodigo">
                                <?php
                                echo $this->inputFormularioSimples(Constantes::$TRADUCAO_MATRICULA, $form->get(Constantes::$INPUT_CODIGO), 10);
                                echo '<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12 mt35">';
                                $funcaoPesquisar = 'onClick="if($(\'#codigo\').val()){consultarFicha();}"';
                                echo $this->botaoSimples('Pesquisar', $funcaoPesquisar, BotaoSimples::botaoImportante, BotaoSimples::larguraMaxima);
                                echo '</div>';
                                ?>
                            </div>    
                        </div>
                        <?php echo $this->formHidden($form->get(Constantes::$FORM_ID)); ?>
                        <?php echo $this->formHidden($form->get(Constantes::$INPUT_CSRF)); ?>
                        <!-- end .form-body section -->
                        <div class="panel-footer text-right">
                            <?php
                            $funcaoRelatorio = $this->funcaoOnClick('mostrarSplash(); funcaoCircuito("cadastroRelatorioFichasRevisao",' . $this->evento->getId() . ')');
                            echo $this->botaoSimples('Relatório', $funcaoRelatorio, BotaoSimples::botaoImportante, BotaoSimples::posicaoAEsquerda);
                            ?>
                            <span id='botaoLimparCampos' class='hidden'>
                                <?php
                                $stringNomeDaFuncaoOnClickLimparCampos = 'limparCampos()';
                                echo $this->botaoLink($this->translate(Constantes::$TRADUCAO_LIMPAR), Constantes::$STRING_HASHTAG, 2, $this->funcaoOnClick($stringNomeDaFuncaoOnClickLimparCampos));
                                ?>
                            </span>
                            <?php
                            $stringNomeDaFuncaoOnClickCadastro = 'mostrarSplash(); funcaoCadastro("' . Constantes::$PAGINA_ATIVAR_FICHAS . '", 0)';
                            echo $this->botaoLink($this->translate(Constantes::$TRADUCAO_VOLTAR), Constantes::$STRING_HASHTAG, 2, $this->funcaoOnClick($stringNomeDaFuncaoOnClickCadastro));
                            /* Submit */
                            $funcaoVerificarCadastroPessoa = $this->funcaoOnClick('mostrarSplash(); confirmar(this.form)');
                            echo $this->botaoSimples($this->translate(Constantes::$TRADUCAO_CONFIRMACAO), "id ='botaoBuscarFicha' type='submit' disabled " . $funcaoVerificarCadastroPessoa);
                            ?>
                        </div>
                        <!-- end .form-footer section -->
                        <?php echo $this->form()->closeTag() ?>
                    </div>
                    <br />
                    <!-- end .admin-form section -->
                </div>
                <!-- end: .admin-form -->
            </div>
        </div>
    </div>
</div>
<?php
/* Layout com javascript para tela de index */
echo $this->layoutJSAtivarFichaRevisao;
