<?php

use Application\Controller\Helper\Funcoes;

//echo 'turma->getId: ' . $this->turma->getId() . '<br />';
//echo 'turma->getData_criacao: ' . $this->turma->getData_criacao() . '<br />';
//echo 'turma->getData_revisao: ' . $this->turma->getData_revisao();
?>


<div align="center">
    <fieldset>
        <div style="display: block;">
            <div style="float: left; display: inline">
                <img src="/img/logos/logo_sara.jpg"  /> 
            </div>
            <div style="float: right; display: inline">
                <div id="qrcode" style="width:150px; height:150px; margin-top:15px; "></div>
                <?php echo $this->pessoa->getId(); ?>
            </div>
        </div>
        <div id="corpo" style="clear: both;">
        <br />
        FICHA DE INSCRI&Ccedil;&Atilde;O - REVIS&Atilde;O DE VIDAS - <?php echo Funcoes::mudarPadraoData($this->revisao->getData(), 1); ?> <br />


        <table style="width: 100%;">
            <tr>
                <td>MATRICULA: <b><span style="font-size: 16px;"><?php echo $this->pessoa->getId(); ?></span></b></td>
                <td>IGREJA: <?php echo "SNT CEILANDIA"; ?></td>
                <td>EQUIPE: <?php echo "TIME DAS 18"; ?></td>
            </tr>
        </table>

        <table style="width: 100%;">
            <tr>
                <td>NOME: <b><span style="font-size: 16px;"><?php echo $this->pessoa->getNome(); ?></span></b></td>      
                <td>TELEFONE(S): <?php echo $this->pessoa->getTelefone(); ?></td>                   
            </tr>
            <tr>
                <td>DATA NASCIMENTO: <?php echo Funcoes::mudarPadraoData($this->pessoa->getData_nascimento(), 1); ?></td>  
                <td>IDADE: <?php echo $this->pessoa->getIdade(); ?> ANOS</td>  
            </tr>
            <tr>

            </tr>
            <tr>
                <td>L&Iacute;DER DIRETO: <?php echo $this->pessoaLider->getNome(); ?></td>                   
                <td>CELULAR: <?php echo $this->pessoaLider->getTelefone(); ?></td>                   
            </tr>
        </table>
        <br />
        <?php if ($this->pessoa->getIdade() < 18) { ?>
            <hr />
            <fieldset>
                AUTORIZA&Ccedil;&Atilde;O
                (PARA MENORES DE 18 ANOS)
                <br />  
                <br />  
                Eu, ____________________________________________________ autorizo meu(inha) filho(a) _____________________________________________________
                a participar do Revis&atilde;o de Vida, no peri&oacute;do de ____ a ____ de ___________________
                de 20______.
                <br />
                <br />
                Estou ciente de que ele(a) estar&aacute; em um &ocirc;nibus fretado pela igreja Sara Nossa Terra e saindo na sexta-feira, &agrave;s 19 horas, aonde
                o(a) pegarei no domingo &agrave; noite.
                Nestes dias meus telefones de contato s&atilde;o: ______________________/_________________________, para falar comigo caso precisem.


                <br /> 
                <br />
                __________________________________________<br />


                <br />
                <div align="right">
                    ________________________________<br />
                    FACILITADOR&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </div>
            </fieldset>
        <?php } ?>
        <br />
        <hr />
        <h1>RECIBO</h1>
        FICHA DE INSCRI&Ccedil;&Atilde;O - REVIS&Atilde;O DE VIDAS - <?php echo Funcoes::mudarPadraoData($this->revisao->getData(), 1); ?> <br />


        <table style="width: 100%;">
            <tr>
                <td>MATRICULA: <b><span style="font-size: 16px;"><?php echo $this->pessoa->getId(); ?></span></b></td>
                <td>IGREJA: <?php echo "SNT CEILANDIA"; ?></td>
                <td>EQUIPE: <?php echo "TIME DAS 18"; ?></td>
            </tr>
        </table>

        <table style="width: 100%;">
            <tr>
                <td>NOME: <b><span style="font-size: 16px;"><?php echo $this->pessoa->getNome(); ?></span></b></td>      
                <td>TELEFONE(S): <?php echo $this->pessoa->getTelefone(); ?></td>                   
            </tr>
            <tr>
                <td style="height:20px;"></td>
            </tr>
            <tr>
                <td colspan="2" style="text-align: center;">
                    _____________________________________________________
                </td>                   
            </tr>
            <tr>
                <td colspan="2" class="text-center">
                    <input type="button" class="btn btn-black" value='VOLTAR' onclick="location.href = '../ciclo/lancamentoDadosCiclo.php?acao=filtrar&mes=<?php echo date('n'); ?>&ano=<?php echo date('Y'); ?>'" />
                    &nbsp;<input type="button" class="btn btn-black" value='IMPRIMIR' onclick="print();" />
                </td>
            </tr>
        </table>
        </div>
    </fieldset>
</div>



<!--END PAGE CONTENT WRAPPER -->
<?php echo $this->layoutJSFichaRevisao; ?>
<script>
    var qrcode = new QRCode(document.getElementById("qrcode"), {
        width: 150,
        height: 150
    });
    qrcode.makeCode('158.69.124.139/cadastroAtivacaoRevisao/<?php echo $this->pessoa->getId(); ?>');


</script>