<?php

use Application\Controller\Helper\Constantes;
use Application\Controller\Helper\Funcoes;

echo $this->doctype();
?>

<html lang="pt-BR">
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<?php
$NAME_APPLICATION = $this->translate(Constantes::$TRADUCAO_NOME_APLICACAO);
echo $this
	->headTitle($NAME_APPLICATION)
	->setSeparator(' - ')
	->setAutoEscape(false)
	;
?> 
		<!-- Meta Head -->
<?php
echo $this
	->headMeta()
	->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no')
	->appendName('theme-color', '#3498db')
	->appendName('google-site-verification', 'b4wOHXCDC8BakDzVfow_NeYwAGGBAEv-sCdKLsDAQUs')
	->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	;
?>
	</head>
	<body>
<?php
$alinhamento = "right";
echo "<div style=\"page-break-before: always\"></div>";
$contador = 0;
foreach ($this->lista['revisionistas'] as $revisionista) {
	if ($alinhamento == "right") {
		$alinhamento = "left";
	} else {
		$alinhamento = "right";
	}
	$fatoRevisao = $this->repositorio->getFatoRevisaoORM()->encontrarPorMatricula($revisionista);
	echo '<fieldset style="width: 8cm; height: 5cm; float: ' . $alinhamento . '; font-family: sans-serif; font-size: 10px;">';
	echo '<div align="center">';
	echo '<h2>Revisionista</h2>';
	echo '<h1>' . $fatoRevisao->nome . '</h1>';
	echo '</div>';
	echo '<hr />';
	echo '<div align="center" style="font-size:16px;">';
	echo 'Inscrição: ' . $revisionista . '<br />';
	echo $fatoRevisao->entidade. '<br />';
	echo Funcoes::mudarPadraoData($fatoRevisao->data_revisao, 1) . '<br />';
	echo 'L&iacute;der(es): ' . $fatoRevisao->lideres . '<br />';
	echo '</div>';
	echo '<br />';
	echo '</fieldset>';
	echo "<div style=\"page-break-before: always\"></div>";
}
$contador = 0;
foreach ($this->lista['lideres'] as $lider) {
	$eventoFrequencia = $this->repositorio->getEventoFrequenciaORM()->encontrarPorId($lider);
	$fatoRevisao = $this->repositorio->getFatoRevisaoORM()->encontrarPorMatricula($lider);
	echo '<fieldset style="width: 8cm; height: 5cm; float: ' . $alinhamento . '; font-family: sans-serif; font-size: 10px;">';
	echo '<div align="center">';
	echo '<h2>' . $fatoRevisao->hierarquia . '</h2>';
	echo '<h1>' . $fatoRevisao->nome . '</h1>';
	echo '</div>';
	echo '<hr />';
	echo '<div align="center" style="font-size:16px;">';
	echo $fatoRevisao->entidade. '<br />';
	echo Funcoes::mudarPadraoData($fatoRevisao->data_revisao, 1) . '<br />';
	echo 'L&iacute;der(es): ' . $fatoRevisao->lideres . '<br />';
	echo '</div>';
	echo '<br />';
	echo '</fieldset>';
	echo "<div style=\"page-break-before: always\"></div>";
}
?>
	</body>
</html>        
