<?php

use Application\Controller\Helper\Constantes;

$html = '';
$pessoas = array();
$frequencias = $this->evento->getEventoFrequencia();

if (count($frequencias) > 0) {
    foreach ($frequencias as $frequencia) {
        if ($frequencia->getFrequencia() == 'S') {
            $pessoa = $frequencia->getPessoa();
            if ($grupoRespossabilidades = $pessoa->getResponsabilidadesAtivas()) {
                $jaExiste = false;
                foreach ($pessoas as $pessoaParaVerificar) {
                    if ($pessoaParaVerificar->getId() === $pessoa->getId()) {
                        $jaExiste = true;
                    }
                }
                if (!$jaExiste) {
                    $pessoas[] = $pessoa;
                }
            }
        }
    }
}

/* Sem pessoas cadastrados */
if (count($pessoas) == 0) {
    $html .= '<div class="alert alert-warning"><i class="fa fa-warning pr10" aria-hidden="true"></i>&nbsp;Sem Líderes Cadastrados!</div>';
} else {
    /* Ordenacao */
    for ($indice1 = 0; $indice1 < count($pessoas); $indice1++) {
        for ($indice2 = 0; $indice2 < count($pessoas); $indice2++) {
            $pessoa1 = $pessoas[$indice1];
            $pessoa2 = $pessoas[$indice2];
            $relatorio1 = $pessoas[$indice1]->getResponsabilidadesAtivas()[0]->getGrupo()->getGrupoEquipe()->getEntidadeAtiva()->getId();
            $relatorio2 = $pessoas[$indice2]->getResponsabilidadesAtivas()[0]->getGrupo()->getGrupoEquipe()->getEntidadeAtiva()->getId();
            if ($relatorio1 > $relatorio2) {
                $pessoas[$indice1] = $pessoa2;
                $pessoas[$indice2] = $pessoa1;
            }
        }
    }

    $html .= $this->templateFormularioTopo('Listagem de Líderes para o Revisão de Vidas');
    $html .= '<div class="panel-body bg-light">';

    $html .= '<input id="fooFilter" type="text" class="form-control" placeholder="Filtro">';
    $html .= '<table class="table table-condensed table-hover bg-light mt15 footable" data-filter="#fooFilter">';
    $html .= '<thead>';
    $html .= '<tr>';

    $html .= '<th>';
    $html .= $this->translate(Constantes::$TRADUCAO_MATRICULA);
    $html .= '</th>';
    $html .= '<th>';
    $html .= $this->translate(Constantes::$TRADUCAO_NOME);
    $html .= '</th>';
    $html .= '<th>Time</th>';
    $html .= '</tr>';
    $html .= '</thead>';
    $html .= '<tbody>';
    foreach ($pessoas as $pessoa) {
        $html .= '<tr>';
        $html .= '<td>' . $pessoa->getId() . '</td>';
        $html .= '<td><span class="visible-lg visible-md">' . $pessoa->getNome() . '</span><span class="visible-sm visible-xs">' . $pessoa->getNomePrimeiroUltimo() . '</span></td>';
        $html .= '<td>' . $pessoa->getResponsabilidadesAtivas()[0]->getGrupo()->getEntidadeAtiva()->infoEntidade() . '</td>';
        $html .= '</tr>';
    }
    $html .= '</tbody>';
    $html .= '</table>';

    $html .= '</div>';

    $html .= $this->templateFormularioRodape();
}

echo $html;
echo $this->layoutJSEventosValidacao;
