<?php

use Application\Controller\Helper\Constantes;

$html = '';
$pessoas = array();
$frequencias = $this->evento->getEventoFrequencia();

if (count($frequencias) > 0) {
    foreach ($frequencias as $frequencia) {
        $pessoa = $frequencia->getPessoa();
        if ($grupoRespossabilidades = $pessoa->getResponsabilidadesAtivas()) {
            $pessoas[] = $pessoa;
        }
    }
}

/* Sem pessoas cadastrados */
if (count($pessoas) == 0) {
    $html .= '<div class="alert alert-warning"><i class="fa fa-warning pr10" aria-hidden="true"></i>&nbsp;Sem Líderes Cadastrados!</div>';
} else {
    /* Ordenacao */
    for ($indice1 = 0; $indice1 < count($pessoas); $indice1++) {
        for ($indice2 = 1; $indice2 < count($pessoas); $indice2++) {
            $pessoa1 = $pessoas[$indice1];
            $pessoa2 = $pessoas[$indice2];
            $relatorio1 = $pessoas[$indice1]->getResponsabilidadesAtivas()[0]->getGrupo()->getGrupoEquipe()->getEntidadeAtiva()->getId();
            $relatorio2 = $pessoas[$indice2]->getResponsabilidadesAtivas()[0]->getGrupo()->getGrupoEquipe()->getEntidadeAtiva()->getId();
            if($relatorio1 > $relatorio2){
                $pessoas[$indice1] = $pessoa2;
                $pessoas[$indice2] = $pessoa1;
            }            
        }
    }

    $html .= $this->templateFormularioTopo('Listagem de Líderes para o Revisão de Vidas');
    $html .= '<div class="panel-body bg-light">';

    $html .= '<table class="table">';
    $html .= '<thead>';
    $html .= '<tr>';

    $html .= '<th class="text-center">';
    $html .= $this->translate(Constantes::$TRADUCAO_MATRICULA);
    $html .= '</th>';
    $html .= '<th class="text-center">';
    $html .= $this->translate(Constantes::$TRADUCAO_NOME);
    $html .= '</th>';

    $html .= '<th class="text-center">Equipe</th>';

    $html .= '<th class="text-center"></th>';
    $html .= '</tr>';
    $html .= '</thead>';
    $html .= '<tbody>';

    foreach ($pessoas as $pessoa) {
        $html .= '<tr>';

        $html .= '<td>' . $pessoa->getId() . '</td>';

        $html .= '<td><span class="visible-lg visible-md">' . $pessoa->getNome() . '</span><span class="visible-sm visible-xs">' . $pessoa->getNomePrimeiroUltimo() . '</span></td>';

        $html .= '<td>' . $pessoa->getResponsabilidadesAtivas()[0]->getGrupo()->getGrupoEquipe()->getEntidadeAtiva()->getNome() . '</td>';

        $html .= '</tr>';
    }
    $html .= '</tbody>';
    $html .= '</table>';

    $html .= '</div>';

    $html .= $this->templateFormularioRodape();
}

echo $html;
echo $this->layoutJSEventosValidacao;
