<?php

use Application\Controller\Helper\Constantes;

$html = '';
$homens = array();
$mulheres = array();
$arrayDeEventos = Array();
if($this->multiplos){
  $arrayDeEventos = $this->arrayDeEventosRevisoes;
} else {
  $arrayDeEventos[] = $this->evento;
}

foreach ($arrayDeEventos as $evento) {
  $frequencias = $evento->getEventoFrequencia();
  if (count($frequencias) > 0) {
      foreach ($frequencias as $frequencia) {
          if ($frequencia->getFrequencia() == 'S') {
              $pessoa = $frequencia->getPessoa();
              if ($pessoa->getGrupoPessoaAtivo()) {
                  $jaExiste = false;
                  foreach ($pessoas as $pessoaParaVerificar) {
                      if ($pessoaParaVerificar->getId() === $pessoa->getId()) {
                          $jaExiste = true;
                      }
                  }
                  if (!$jaExiste) {
                      if ($pessoa->getSexo() == 'M') {
                          $homens[] = $pessoa;
                      } else {
                          $mulheres[] = $pessoa;
                      }
                  }
              }
          }
      }
  }
}
$html .= $this->templateFormularioTopo('Listagem de Revisionistas para o Revisão de Vidas');
$html .= '<div class="panel-body bg-light">';
$html .= '<h3>Homens: '.count($homens).' - Mulheres: '.count($mulheres).'</h3>';
if (count($homens) > 0) {
    $html .= '<h2>Revisionistas Homens</h2>';
    $html .= '<input id="fooFilterHomem" type="text" class="form-control" placeholder="Filtro">';
    $html .= '<table class="table table-condensed table-hover bg-light mt15 footable" data-filter="#fooFilterHomem">';
    $html .= '<thead>';
    $html .= '<tr>';
    $html .= '<th>';
    $html .= $this->translate(Constantes::$TRADUCAO_MATRICULA);
    $html .= '</th>';
    $html .= '<th>';
    $html .= $this->translate(Constantes::$TRADUCAO_NOME);
    $html .= '</th>';
    $html .= '<th>Sexo</th>';
    $html .= '<th>Igreja</th>';
    $html .= '<th>Time</th>';
    $html .= '<th>Idade</th>';
    $html .= '</tr>';
    $html .= '</thead>';
    $html .= '<tbody>';
    foreach ($homens as $homem) {
      $nomeEntidadeAcima = '';
      if($this->multiplos){
        $nomeEntidadeAcima = $homem->getGrupoPessoaAtivo()->getGrupo()->getGrupoPaiFilhoPaiAtivo()->getGrupoPaiFilhoPai()->getEntidadeAtiva()->getNome();
        if($nomeEntidadeAcima){
          $nomeEntidadeAcimaArrumado = ' - ' . $nomeEntidadeAcima;
        }
        if(!$nomeEntidadeAcima){
          $nomeEntidadeAcimaArrumado = ' - COORDENAÇÃO '. $homem->getGrupoPessoaAtivo()->getGrupo()->getGrupoPaiFilhoPaiAtivo()->getGrupoPaiFilhoPai()->getEntidadeAtiva()->getNumero();
        }
      }
      $sexo = $homem->getSexo();
      if(!$sexo) {
        $sexo = 'Não Informado';
      }
        $html .= '<tr>';
        $html .= '<td>' . $homem->getId() . '</td>';
        $html .= '<td><span class="visible-lg visible-md">' . $homem->getNome() . '</span><span class="visible-sm visible-xs">' . $homem->getNomePrimeiroUltimo() . '</span></td>';
        $html .= '<td>' . $homem->getSexo() . '</td>';
        $html .= '<td>' . $homem->getGrupoPessoaAtivo()->getGrupo()->getGrupoIgreja()->getEntidadeAtiva()->getNome() . '</td>';
        $html .= '<td>' . $homem->getGrupoPessoaAtivo()->getGrupo()->getEntidadeAtiva()->infoEntidade() . $nomeEntidadeAcimaArrumado . '</td>';
        $html .= '<td>' . $homem->getIdade() . '</td>';
        $html .= '</tr>';
    }
    $html .= '</tbody>';
    $html .= '</table>';
} else {
    $html .= '<div class="alert alert-warning"><i class="fa fa-warning pr10" aria-hidden="true"></i>&nbsp;Sem Homens Cadastrados!</div>';
}

if (count($mulheres) > 0) {
    $html .= '<h2>Revisionistas Mulheres</h2>';
    $html .= '<input id="fooFilterMulher" type="text" class="form-control" placeholder="Filtro">';
    $html .= '<table class="table table-condensed table-hover bg-light mt15 footable" data-filter="#fooFilterMulher">';
    $html .= '<thead>';
    $html .= '<tr>';
    $html .= '<th>';
    $html .= $this->translate(Constantes::$TRADUCAO_MATRICULA);
    $html .= '</th>';
    $html .= '<th>';
    $html .= $this->translate(Constantes::$TRADUCAO_NOME);
    $html .= '</th>';
    $html .= '<th>Sexo</th>';
    $html .= '<th>Igreja</th>';
    $html .= '<th>Time</th>';
    $html .= '<th>Idade</th>';
    $html .= '</tr>';
    $html .= '</thead>';
    $html .= '<tbody>';
    foreach ($mulheres as $mulher) {
      $nomeEntidadeAcima = '';
      if($this->multiplos){
        $nomeEntidadeAcima = $mulher->getGrupoPessoaAtivo()->getGrupo()->getGrupoPaiFilhoPaiAtivo()->getGrupoPaiFilhoPai()->getEntidadeAtiva()->getNome();
        if($nomeEntidadeAcima){
          $nomeEntidadeAcimaArrumado = ' - ' . $nomeEntidadeAcima;
        }
        if(!$nomeEntidadeAcima){
          $nomeEntidadeAcimaArrumado = ' - COORDENAÇÃO '. $mulher->getGrupoPessoaAtivo()->getGrupo()->getGrupoPaiFilhoPaiAtivo()->getGrupoPaiFilhoPai()->getEntidadeAtiva()->getNumero();
      }
    }
      $sexo = $homem->getSexo();
      if(!$sexo) {
        $sexo = 'Não Informado';
      }
        $html .= '<tr>';
        $html .= '<td>' . $mulher->getId() . '</td>';
        $html .= '<td><span class="visible-lg visible-md">' . $mulher->getNome() . '</span><span class="visible-sm visible-xs">' . $mulher->getNomePrimeiroUltimo() . '</span></td>';
        $html .= '<td>' . $mulher->getSexo() . '</td>';
        $html .= '<td>' . $mulher->getGrupoPessoaAtivo()->getGrupo()->getGrupoIgreja()->getEntidadeAtiva()->getNome() . '</td>';
        $html .= '<td>' . $mulher->getGrupoPessoaAtivo()->getGrupo()->getEntidadeAtiva()->infoEntidade() . $nomeEntidadeAcimaArrumado . '</td>';
        $html .= '<td>' . $mulher->getIdade() . '</td>';
        $html .= '</tr>';
    }
    $html .= '</tbody>';
    $html .= '</table>';
} else {
    $html .= '<div class="alert alert-warning"><i class="fa fa-warning pr10" aria-hidden="true"></i>&nbsp;Sem Mulheres Cadastradas!</div>';
}
$html .= '</div>';
$html .= $this->templateFormularioRodape();
echo $html;
