
<?php

use Application\Controller\Helper\Constantes;
use Application\View\Helper\BotaoSimples;

?>
<div class="mw1000 center-block p10">
	<div class="row ">
		<div id="content" class="animated fadeIn">
			<div class="row">
				<!-- Cadastro de Pessoa -->
				<div class="admin-form " id="register1" role="tabpanel">
					<blockquote class="blockquote-primary">
						<p>Lista de Líderes</p>
					</blockquote>
<?php
echo '<div class="alert alert-info">Homens: '.count($this->listas['M']).'</div>';
if(count($this->listas['M']) > 0){
	$html = '';
	$html .= '<div class="panel-body bg-light">';
	$html .= '<input id="fooFilter" type="text" class="form-control" placeholder="Filtro">';
	$html .= '<table class="table table-condensed table-hover bg-light mt15 footable" data-filter="#fooFilter">';
	$html .= '<thead>';
	$html .= '<tr class="dark">';
	$html .= '<th>Inscrição</th>';
	$html .= '<th>Líder</th>';
	$html .= '<th>Igreja</th>';
	$html .= '<th>Time</th>';
	$html .= '</tr>';
	$html .= '</thead>';
	$html .= '<tbody>';
	foreach($this->listas['M'] as $fatoRevisao){
		$html .= '<tr>';
		$html .= '<td>' . $fatoRevisao->matricula . '</td>';
		$html .= '<td>' . $fatoRevisao->nome . '</td>';
		$html .= '<td>' . $fatoRevisao->nome_igreja. '</td>';
		$html .= '<td>' . $fatoRevisao->entidade. '</td>';
		$html .= '</tr>';
	}
	$html .= '</tbody>';
	$html .= '</table>';
	$html .= '</div>';
	echo $html;
}else{
	echo '<div class="alert alert-warning">Sem Homens</div>';
}

echo '<div class="alert alert-info">Mulheres: '.count($this->listas['F']).'</div>';
if(count($this->listas['F']) > 0){
	$html = '';
	$html .= '<div class="panel-body bg-light">';
	$html .= '<input id="fooFilter2" type="text" class="form-control" placeholder="Filtro">';
	$html .= '<table class="table table-condensed table-hover bg-light mt15 footable" data-filter="#fooFilter2">';
	$html .= '<thead>';
	$html .= '<tr class="dark">';
	$html .= '<th>Inscrição</th>';
	$html .= '<th>Revisionista</th>';
	$html .= '<th>Igreja</th>';
	$html .= '<th>Time</th>';
	$html .= '</tr>';
	$html .= '</thead>';
	$html .= '<tbody>';
	foreach($this->listas['F'] as $fatoRevisao){
		$html .= '<tr>';
		$html .= '<td>' . $fatoRevisao->matricula . '</td>';
		$html .= '<td>' . $fatoRevisao->nome . '</td>';
		$html .= '<td>' . $fatoRevisao->nome_igreja. '</td>';
		$html .= '<td>' . $fatoRevisao->entidade. '</td>';
		$html .= '</tr>';
	}
	$html .= '</tbody>';
	$html .= '</table>';
	$html .= '</div>';
	echo $html;
}else{
	echo '<div class="alert alert-warning">Sem Mulheres</div>';
}

?>


					<!-- end .admin-form section -->
				</div>
				<!-- end: .admin-form -->
			</div>
		</div>
	</div>
</div>
<?php
/* Layout com javascript para tela de index */
echo $this->layoutJSAtivarFichaRevisao;
