<?php

use Application\Controller\Helper\Constantes;
use Zend\View\Helper\AbstractHelper;
use Application\Model\Entity\MetasOrdenacaoCriterio;

/**
 * Nome: consultar-ordenacao.phtml
 * @author Ivan Tavares <ivanlsjt@gmail.com>
 * Descricao: Página cadastrar as metas de ordenação.
 */
$cpf = '';
if($this->cpf){
    $cpf = $this->cpf;
}
$html = '';
$html .= $this->templateFormularioTopo('Cadastrar <b class="text-danger">Metas</b>');
// inicio div panel-body
$html .= '<div class="panel-body bg-light pbn">';
$html .= '<span id="spanMensagens" class="quebraDeLinhaDeSpan mt10 alert text-center alert-danger hidden"></span>';
$html .= '<form id="formConsultarOrdenacao" action="/cadastroMetas" method="post">';

foreach ($this->tiposDeMetasOrdenacao as $ordenacaoTipo) {
    $tipoBispo = 5;     
    //inicio row 1
    $html .= '<div class="row">';
    $html .= '<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">';
    $html .= '<div class="alert alert-primary text-center">'. $ordenacaoTipo->getNome() .'</div>';    
    $html .= '</div>';
    // fim row 1
    $html .= '</div>';
        
    if($ordenacaoTipo->getId() !== $tipoBispo){

        $html .= '<div class="section-divider mt20 mb30" id="spy5"><span style="color: red;">Meta para Jovens</span></div>';

        //inicio row 2
        $html .= '<div class="row">';
        $html .= '<div class="col-lg-3 col-md-3 col-sm-3 cpfcol-xs-12 mb15">';    
        $html .= '<input type="number" name="lideresJovens'.$ordenacaoTipo->getId().'" class="form-control"  placeholder="Meta Jovens: Lideres" pattern="\d*">';    
        $html .= '</div>';
        $html .= '<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 mb15">';    
        $html .= '<input type="number" name="membresiaJovens'.$ordenacaoTipo->getId().'" class="form-control"  placeholder="Meta Jovens: Membresia" pattern="\d*">';    
        $html .= '</div>';
        $html .= '<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 mb15">';    
        $html .= '<input type="number" name="pessoasEmCelulaJovens'.$ordenacaoTipo->getId().'" class="form-control"  placeholder="Meta Jovens: Pessoas em Célula" pattern="\d*">';    
        $html .= '</div>';
        $html .= '<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 mb15">';    
        $html .= '<input type="number" name="parceiroDeDeusJovens'.$ordenacaoTipo->getId().'" class="form-control"  placeholder="Meta Jovens: Parceiro de Deus" pattern="\d*">';    
        $html .= '</div>';
        // fim row 2
        $html .= '</div>';

        $html .= '<div class="section-divider mt20 mb30" id="spy5"><span style="color: red;">Meta para Adultos</span></div>';

        //inicio row 3
        $html .= '<div class="row">';
        $html .= '<div class="col-lg-3 col-md-3 col-sm-3 cpfcol-xs-12 mb15">';    
        $html .= '<input type="number" name="lideresAdultos'.$ordenacaoTipo->getId().'" class="form-control"  placeholder="Meta Adultos: Lideres" pattern="\d*">';    
        $html .= '</div>';
        $html .= '<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 mb15">';    
        $html .= '<input type="number" name="membresiaAdultos'.$ordenacaoTipo->getId().'" class="form-control"  placeholder="Meta Adultos: Membresia" pattern="\d*">';    
        $html .= '</div>';
        $html .= '<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 mb15">';    
        $html .= '<input type="number" name="pessoasEmCelulaAdultos'.$ordenacaoTipo->getId().'" class="form-control"  placeholder="Meta Adultos: Pessoas em Célula" pattern="\d*">';    
        $html .= '</div>';
        $html .= '<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 mb15">';    
        $html .= '<input type="number" name="parceiroDeDeusAdultos'.$ordenacaoTipo->getId().'" class="form-control"   placeholder="Meta Adultos: Parceiro de Deus" pattern="\d*">';    
        $html .= '</div>';
        // fim row 3
        $html .= '</div>';
    }
    if($ordenacaoTipo->getId() === $tipoBispo){

        $html .= '<div class="section-divider mt20 mb30" id="spy5"><span style="color: red;">Meta para Bispos</span></div>';

        //inicio row 3
        $html .= '<div class="row">';
        $html .= '<div class="col-lg-6 col-md-6 col-sm-6 cpfcol-xs-12 mb15">';    
        $html .= '<input type="number" name="parceiroDeDeusBispo" class="form-control"  placeholder="Meta Bispos: Parceiro de Deus" pattern="\d*">';    
        $html .= '</div>';
        $html .= '<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 mb15">';    
        $html .= '<input type="number" name="igrejas" class="form-control"  placeholder="Meta Adultos: Igrejas" pattern="\d*">';    
        $html .= '</div>';
        $html .= '</div>';
    }
}

//inicio row 4
$html .= '<div class="row">';
$html .= '<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">';
$html .= '<button type="button" onclick="this.form.submit();" class="btn ladda-button btn-primary btn-block mb15 pull-right" data-style="zoom-in">';
$html .= '<span class="ladda-label">Cadastrar</span>';
$html .= '<span class="ladda-spinner"></span></button>';
$html .= '</div>';
// fim row 4
$html .= '</div>';


$html .= '</form>';

//fim div panel-body
$html .= '</div>';

$html .= $this->templateFormularioRodape();
echo $html;   
        
?>

<script>
    function isNumber(n) {
        return !isNaN(parseFloat(n)) && isFinite(n);
    }
    function validarDados(){
        var temErro = false;
        var hidden = 'hidden';
        var spanMensagens = $('#spanMensagens');
        
        for (let index = 1; index < 6; index++) {
            var InputPessoasEmCelulaAdultos = $("#pessoasEmCelulaAdultos" + index);
            var InputPessoasEmCelulaJovens = $("#pessoasEmCelulaJovens" + index);
            
            var InputParceiroDeDeusAdultos = $("#parceiroDeDeusAdultos" + index);
            var InputParceiroDeDeusJovens = $("#parceiroDeDeusJovens" + index);
            
            var InputMembresiaAdultos = $("#membresiaAdultos" + index);
            var InputMembresiaJovens = $("#membresiaJovens" + index);

            var InputLideresAdultos = $("#lideresAdultos" + index);
            var InputLideresJovens = $("#lideresJovens" + index);  

            var pessoasEmCelulaAdultos = InputPessoasEmCelulaAdultos.val();
            var pessoasEmCelulaJovens = InputPessoasEmCelulaJovens.val();

            var parceiroDeDeusAdultos = InputParceiroDeDeusAdultos.val();
            var parceiroDeDeusJovens = InputParceiroDeDeusJovens.val();

            var membresiaAdultos = InputMembresiaAdultos.val();
            var membresiaJovens = InputMembresiaJovens.val();

            var lideresAdultos = InputLideresAdultos.val();
            var lideresJovens = InputLideresJovens.val();

            if(pessoasEmCelulaAdultos.length === 0 || !isNumber(pessoasEmCelulaAdultos) ||
            pessoasEmCelulaJovens.length === 0 || !isNumber(pessoasEmCelulaJovens) ||
            parceiroDeDeusAdultos.length === 0 || !isNumber(parceiroDeDeusAdultos) ||
            parceiroDeDeusJovens.length === 0 || !isNumber(parceiroDeDeusJovens) ||
            membresiaAdultos.length === 0 || !isNumber(membresiaAdultos) ||
            membresiaJovens.length === 0 || !isNumber(membresiaJovens) ||
            lideresAdultos.length === 0 || !isNumber(lideresAdultos) ||
            lideresJovens.length === 0 || !isNumber(lideresJovens) ||
                temErro  = true;
            }                                      
        }        
               
        var formConsultarOrdenacao = $("#formConsultarOrdenacao");
        var cpf = inputCPF.val();
        if (cpf.length === 0 || !isNumber(cpf) || cpf.length !== 11) {
            spanMensagens.removeClass(hidden);
            spanMensagens.text('<?php echo $this->translate(Constantes::$TRADUCAO_CPF_INVALIDO); ?>');            
            temErro = true;
        }
        if(!temErro){
            formConsultarOrdenacao.submit();
        }
    }
</script>