<?php

use Application\Controller\Helper\Constantes;
use Application\View\Helper\BotaoSimples;
use Application\Model\Entity\Entidade;

echo $this->templateFormularioTopo('Selecione para imprimir os crachás');
$form = $this->formulario;
$form->prepare();
$form->setAttribute(Constantes::$ACTION, $this->url(Constantes::$ROUTE_CADASTRO, array(Constantes::$PAGINA => Constantes::$PAGINA_GERAR_CRACHA)));
$form->setAttribute('target', '_blanck');
echo $this->form()->openTag($form);
?>
<style type="text/css">
    th {
        text-align: center;
    }
</style>
    <div class="panel-body bg-light p5">
        <?php
        $htmlBotaoGerar .= '<div class="text-center m20">';
        $funcao = $this->funcaoOnClick('this.form.submit()');
        $htmlBotaoGerar .= $this->botaoSimples('Gerar crachá 1 por página', $funcao, '', BotaoSimples::posicaoAoCentro);
		$htmlBotaoGerar .= '&nbsp;';
        $funcao = $this->funcaoOnClick('this.form.action = "/cadastroGerarCrachaOito"; this.form.submit()');
        $htmlBotaoGerar .= $this->botaoSimples('Gerar crachá 8 por página', $funcao, '', BotaoSimples::posicaoAoCentro);
        $htmlBotaoGerar .= '</div>';
        echo $htmlBotaoGerar;
 
        echo '<h2>Revisionistas - Homens: '.$this->quantidadeHomensRevisionistas.' - Mulheres: '.$this->quantidadeMulheresRevisionistas.'</h2>';

        if ($relatorioRevisionistas = $this->relatorio['revisionistas']) {
            echo '<input id="fooFilterRevisionistas" type="text" class="form-control" placeholder="Filtro">';
            echo '<table class="table table-condensed table-hover bg-light mt15 footable" data-filter="#fooFilterRevisionistas">';
            echo '<thead>';
            echo '<tr class="text-center">';
            echo '<th>Inscrição</th>';
            echo '<th>Revisionista</th>';
            echo '<th>Sexo</th>';
            echo '<th>Igreja</th>';
            echo '<th>Time</th>';
            echo '<th><input type="checkbox" onclick="marcarTodos(this);"/></th>';
            echo '</tr>';
            echo '</thead>';
            echo '<tbody>';
            foreach ($relatorioRevisionistas as $relatorio) {
              if($this->multiplos){ 
                $entidadeAcima = $relatorio->getPessoa()->getGrupoPessoaAtivo()->getGrupo()->getGrupoPaiFilhoPaiAtivo()->getGrupoPaiFilhoPai()->getEntidadeAtiva();
                if($entidadeAcima->getEntidadeTipo()->getId() === Entidade::EQUIPE || 
                    $entidadeAcima->getEntidadeTipo()->getId() === Entidade::IGREJA                         
                ){
                    $nomeEntidadeAcimaArrumado = ' - ' . $entidadeAcima->getNome();                    
                }
                if($entidadeAcima->getEntidadeTipo()->getId() === Entidade::SUBEQUIPE){                                  
                    $nomeEntidadeAcimaArrumado = ' - ' . $entidadeAcima->infoEntidade();                    
                }
                if($entidadeAcima->getEntidadeTipo()->getId() === Entidade::COORDENACAO){                                  
                    $nomeEntidadeAcimaArrumado = ' - COORDENAÇÃO: ' . $entidadeAcima->getNumero();                    
                }  
                if($entidadeAcima->getEntidadeTipo()->getId() === Entidade::REGIONAL){                                  
                    $nomeEntidadeAcimaArrumado = ' - REGIÃO: ' . $entidadeAcima->getNome();                    
                }               
              }
              
                $sexo = $relatorio->getPessoa()->getSexo();
                if(!$sexo) {
                  $sexo = 'Não Informado';
                }
                $grupoPessoa = $relatorio->getPessoa()->getGrupoPessoaAtivo()->getGrupo();
                echo '<tr class="text-center">';
                echo '<td>' . $relatorio->getId() . '</td>';
                echo '<td>' . $relatorio->getPessoa()->getNome() . '</td>';
                echo '<td>' . $sexo . '</td>';
                echo '<td>' . $grupoPessoa->getGrupoIgreja()->getEntidadeAtiva()->getNome() . '</td>';
                echo '<td>' . $grupoPessoa->getEntidadeAtiva()->infoEntidade() . $nomeEntidadeAcimaArrumado . '</td>';
                echo '<td><input type="checkbox" id="revisionista' . $relatorio->getId() . '" name="revisionista' . $relatorio->getId() . '" value="' . $relatorio->getId() . '"/></td>';
                echo '</tr>';
            }
            echo '</tbody>';
            echo '</table>';
        }
        if ($relatorioLideres = $this->relatorio['lideres']) {
            echo '<h2>Líderes - Homens: '.$this->quantidadeHomensLideres.' - Mulheres: '.$this->quantidadeMulheresLideres.'</h2>';
            echo '<input id="fooFilterLideres" type="text" class="form-control" placeholder="Filtro">';
            echo '<table class="table table-condensed table-hover bg-light mt15 footable" data-filter="#fooFilterLideres">';
            echo '<thead>';
            echo '<tr class="text-center">';
            echo '<th>Inscrição</th>';
            echo '<th>Líder</th>';
            echo '<th>Sexo</th>';
            echo '<th>Igreja</th>';
            echo '<th>Time</th>';
            echo '<th><input type="checkbox" onclick="marcarTodos(this);"/></th>';
            echo '</tr>';
            echo '</thead>';
            echo '<tbody>';
            foreach ($relatorioLideres as $relatorio) {
              if($this->multiplos){ 
                $entidadeAcima = $relatorio->getPessoa()->getResponsabilidadesAtivas()[0]->getGrupo()->getGrupoPaiFilhoPaiAtivo()->getGrupoPaiFilhoPai()->getEntidadeAtiva();
                if($entidadeAcima->getEntidadeTipo()->getId() === Entidade::EQUIPE || 
                    $entidadeAcima->getEntidadeTipo()->getId() === Entidade::IGREJA                         
                ){
                    $nomeEntidadeAcimaArrumado = ' - ' . $entidadeAcima->getNome();                    
                }
                if($entidadeAcima->getEntidadeTipo()->getId() === Entidade::SUBEQUIPE){                                  
                    $nomeEntidadeAcimaArrumado = ' - ' . $entidadeAcima->infoEntidade();                    
                }
                if($entidadeAcima->getEntidadeTipo()->getId() === Entidade::COORDENACAO){                                  
                    $nomeEntidadeAcimaArrumado = ' - COORDENAÇÃO: ' . $entidadeAcima->getNumero();                    
                }  
                if($entidadeAcima->getEntidadeTipo()->getId() === Entidade::REGIONAL){                                  
                    $nomeEntidadeAcimaArrumado = ' - REGIÃO: ' . $entidadeAcima->getNome();                    
                }               
              }              
                $sexo = $relatorio->getPessoa()->getSexo();
                if(!$sexo) {
                  $sexo = 'Não Informado';
                }
                $grupoPessoa = $relatorio->getPessoa()->getResponsabilidadesAtivas()[0]->getGrupo();
                echo '<tr class="text-center">';
                echo '<td>' . $relatorio->getId() . '</td>';
                echo '<td>' . $relatorio->getPessoa()->getNome() . '</td>';
                echo '<td>' . $sexo . '</td>';
                echo '<td>' . $grupoPessoa->getGrupoIgreja()->getEntidadeAtiva()->getNome() . '</td>';
                echo '<td>' . $grupoPessoa->getEntidadeAtiva()->infoEntidade() . $nomeEntidadeAcimaArrumado . '</td>';
                echo '<td><input type="checkbox" id="lider' . $relatorio->getId() . '" name="lider' . $relatorio->getId() . '" value="' . $relatorio->getId() . '"/></td>';
                echo '</tr>';
            }
            echo '</tbody>';
            echo '</table>';
        }
        echo $htmlBotaoGerar;
        ?>
    </div>

<?php
echo $this->form()->closeTag();
echo $this->templateFormularioRodape();
