<?php

use Application\Controller\Helper\Constantes;
use Application\View\Helper\BotaoSimples;
use Application\Model\Entity\Entidade;

echo $this->templateFormularioTopo('Selecione para imprimir os crachás');
$form = $this->formulario;
$form->prepare();
$form->setAttribute(Constantes::$ACTION, $this->url(Constantes::$ROUTE_CADASTRO, array(Constantes::$PAGINA => Constantes::$PAGINA_GERAR_CRACHA)));
$form->setAttribute('target', '_blanck');
echo $this->form()->openTag($form);
?>
<style type="text/css">
    th {
        text-align: center;
    }
</style>
    <div class="panel-body bg-light p5">
        <?php
 $htmlBotaoGerar .= '<div class="text-center m20">';
        $funcao = $this->funcaoOnClick('this.form.submit()');
        $htmlBotaoGerar .= $this->botaoSimples('Gerar crachá 1 por página', $funcao, '', BotaoSimples::posicaoAoCentro);
		$htmlBotaoGerar .= '&nbsp;';
        $funcao = $this->funcaoOnClick('this.form.action = "/cadastroGerarCrachaOito"; this.form.submit()');
        $htmlBotaoGerar .= $this->botaoSimples('Gerar crachá 8 por página', $funcao, '', BotaoSimples::posicaoAoCentro);
        $htmlBotaoGerar .= '</div>';
        echo $htmlBotaoGerar;
 
echo '<div class="alert alert-info">Revisionistas</div>';
if(count($this->listas[1]) > 0){
	$html = '';
	$html .= '<div class="panel-body bg-light">';
	$html .= '<input id="fooFilter" type="text" class="form-control" placeholder="Filtro">';
	$html .= '<table class="table table-condensed table-hover bg-light mt15 footable" data-filter="#fooFilter">';
	$html .= '<thead>';
	$html .= '<tr class="dark">';
	$html .= '<th>Inscrição</th>';
	$html .= '<th>Revisionista</th>';
	$html .= '<th>Sexo</th>';
	$html .= '<th>Idade</th>';
	$html .= '<th>Igreja</th>';
	$html .= '<th>Time</th>';
	$html .= '<td><input type="checkbox" onclick="marcarTodos(this);"/></td>';
	$html .= '</tr>';
	$html .= '</thead>';
	$html .= '<tbody>';
	foreach($this->listas[1] as $fatoRevisao){
		$html .= '<tr>';
		$html .= '<td>' . $fatoRevisao->matricula . '</td>';
		$html .= '<td>' . $fatoRevisao->nome . '</td>';
		$html .= '<td>' . $fatoRevisao->sexo . '</td>';
		$html .= '<td>' . $fatoRevisao->idade . '</td>';
		$html .= '<td>' . $fatoRevisao->nome_igreja . '</td>';
		$html .= '<td>' . $fatoRevisao->entidade. '</td>';
		$html .= '<td><input type="checkbox" id="revisionista' . $fatoRevisao->matricula . '" name="revisionista' . $fatoRevisao->matricula . '" value="' . $fatoRevisao->matricula . '"/></td>';
		$html .= '</tr>';
	}
	$html .= '</tbody>';
	$html .= '</table>';
	$html .= '</div>';
	echo $html;
}else{
	echo '<div class="alert alert-warning">Sem Revisionistas</div>';
}
echo '<div class="alert alert-info">Líderes</div>';

if(count($this->listas[2]) > 0){
	$html = '';
	$html .= '<div class="panel-body bg-light">';
	$html .= '<input id="fooFilter2" type="text" class="form-control" placeholder="Filtro">';
	$html .= '<table class="table table-condensed table-hover bg-light mt15 footable" data-filter="#fooFilter2">';
	$html .= '<thead>';
	$html .= '<tr class="dark">';
	$html .= '<th>Inscrição</th>';
	$html .= '<th>Líder</th>';
	$html .= '<th>Sexo</th>';
	$html .= '<th>Igreja</th>';
	$html .= '<th>Time</th>';
	$html .= '<td><input type="checkbox" onclick="marcarTodos(this);"/></td>';
	$html .= '</tr>';
	$html .= '</thead>';
	$html .= '<tbody>';
	foreach($this->listas[2] as $fatoRevisao){
		$html .= '<tr>';
		$html .= '<td>' . $fatoRevisao->matricula . '</td>';
		$html .= '<td>' . $fatoRevisao->nome . '</td>';
		$html .= '<td>' . $fatoRevisao->sexo . '</td>';
		$html .= '<td>' . $fatoRevisao->nome_igreja. '</td>';
		$html .= '<td>' . $fatoRevisao->entidade. '</td>';
		$html .= '<td><input type="checkbox" id="lider' . $fatoRevisao->matricula . '" name="lider' . $fatoRevisao->matricula . '" value="' . $fatoRevisao->matricula . '"/></td>';
		$html .= '</tr>';
	}
	$html .= '</tbody>';
	$html .= '</table>';
	$html .= '</div>';
	echo $html;
}else{
	echo '<div class="alert alert-warning">Sem Líderes</div>';
}
        echo $htmlBotaoGerar;
        ?>
    </div>

<?php
echo $this->form()->closeTag();
echo $this->templateFormularioRodape();
