<?php

use Application\Controller\Helper\Constantes;

/**
 * Nome: selecionar_revisionistas.phtml
 * @author Lucas Filipe de Carvalho Cunha <lucsacarvalho.esw@gmail.com> 
 * Descricao: Página de listagem de pessoas para o Revisao
 */
$form = $this->SelecionarLiderRevisaoForm;
$form->prepare();
$form->setAttribute(Constantes::$ACTION, $this->url(Constantes::$ROUTE_CADASTRO, array(Constantes::$PAGINA => Constantes::$PAGINA_ATIVAR_LIDERES_REVISAO)));
?>
<div class="mw1000 center-block p10">
    <div class="row ">
        <div id="content" class="animated fadeIn">
            <div class="row">
                <!-- Cadastro de Pessoa -->
                <div class="admin-form " id="register1" role="tabpanel">
                <blockquote class="blockquote-primary">
                        <p><?php echo $this->translate(Constantes::$TRADUCAO_SELECIONAR_LIDER_REVISAO_PRIMEIRO_LABEL); ?></p>
                        <small><?php echo $this->translate(Constantes::$TRADUCAO_SELECIONAR_LIDER_REVISAO_SEGUNDO_LABEL); ?></small>
                    </blockquote>
                <div class="panel panel-primary heading-border">
                    <?php echo $this->form()->openTag($form); ?>
                        
                        <div class="panel-body bg-light p25">
                            <?php
                            echo $this->formSelect($form->get(Constantes::$INPUT_LIDERES));
                            ?> 
                        </div>
                        <div class="panel-footer text-right">
                            <?php
                            
                            $stringNomeDaFuncaoOnClickCadastro = 'funcaoCadastro("' . Constantes::$PAGINA_LIDERES_REVISAO . '", 0)';
                            echo $this->botaoLink($this->translate(Constantes::$TRADUCAO_VOLTAR), Constantes::$STRING_HASHTAG, 2, $this->funcaoOnClick($stringNomeDaFuncaoOnClickCadastro));
                            $funcaoVerificarCadastroPessoa = $this->funcaoOnClick('confirmar(this.form)');
                            echo $this->botaoSimples(Constantes::$TRADUCAO_ATIVAR, "id ='botaoBuscarFicha' ".$funcaoVerificarCadastroPessoa);
                            ?>
                        </div>
                    <?php echo $this->form()->closeTag() ?>
                </div>
                <!-- end: .admin-form -->
            </div>
        </div>
    </div>
</div>
<?php
/* Layout com javascript para tela de index */
echo $this->layoutJSSelecionarLiderRevisao;
