<?php

use Application\Controller\Helper\Constantes;
use Application\View\Helper\BotaoSimples;

echo $this->templateFormularioTopo('Selecione para imprimir os crachás');
$form = $this->formulario;
$form->prepare();
$form->setAttribute(Constantes::$ACTION, $this->url(Constantes::$ROUTE_CADASTRO, array(Constantes::$PAGINA => Constantes::$PAGINA_GERAR_CRACHA)));
$form->setAttribute('target', '_blanck');
echo $this->form()->openTag($form);
?>
<style type="text/css">
    th {
        text-align: center;
    }
</style>
    <div class="panel-body bg-light p5">
        <?php
        $htmlBotaoGerar .= '<div class="text-center m20">';
        $funcao = $this->funcaoOnClick('this.form.submit()');
        $htmlBotaoGerar .= $this->botaoSimples('Gerar Crachá', $funcao, '', BotaoSimples::posicaoAoCentro);
        $htmlBotaoGerar .= '</div>';
        echo $htmlBotaoGerar;
        echo '<h2>Revisionistas - Homens: '.$this->quantidadeHomensRevisionistas.' - Mulheres: '.$this->quantidadeMulheresRevisionistas.'</h2>';

        if ($relatorioRevisionistas = $this->relatorio['revisionistas']) {
            echo '<input id="fooFilterRevisionistas" type="text" class="form-control" placeholder="Filtro">';
            echo '<table class="table table-condensed table-hover bg-light mt15 footable" data-filter="#fooFilterRevisionistas">';
            echo '<thead>';
            echo '<tr class="text-center">';
            echo '<th>Inscrição</th>';
            echo '<th>Revisionista</th>';
            echo '<th>Sexo</th>';
            echo '<th>Time</th>';
            echo '<th><input type="checkbox" onclick="marcarTodos(this);"/></th>';
            echo '</tr>';
            echo '</thead>';
            echo '<tbody>';
            foreach ($relatorioRevisionistas as $relatorio) {
              $nomeEntidadeAcima = '';
              if($this->multiplos){
                $nomeEntidadeAcima = $relatorio->getPessoa()->getGrupoPessoaAtivo()->getGrupo()->getGrupoPaiFilhoPaiAtivo()->getGrupoPaiFilhoPai()->getEntidadeAtiva()->getNome();
                if(!$nomeEntidadeAcima){
                  $nomeEntidadeAcima = ' - COORDENAÇÃO '. $relatorio->getPessoa()->getGrupoPessoaAtivo()->getGrupo()->getGrupoPaiFilhoPaiAtivo()->getGrupoPaiFilhoPai()->getEntidadeAtiva()->getNumero();
                }
              }
                $sexo = $relatorio->getPessoa()->getSexo();
                if(!$sexo) {
                  $sexo = 'Não Informado';
                }
                echo '<tr class="text-center">';
                echo '<td>' . $relatorio->getId() . '</td>';
                echo '<td>' . $relatorio->getPessoa()->getNome() . '</td>';
                echo '<td>' . $sexo . '</td>';
                echo '<td>' . $relatorio->getPessoa()->getGrupoPessoaAtivo()->getGrupo()->getEntidadeAtiva()->infoEntidade() . $nomeEntidadeAcima . '</td>';
                echo '<td><input type="checkbox" id="revisionista' . $relatorio->getId() . '" name="revisionista' . $relatorio->getId() . '" value="' . $relatorio->getId() . '"/></td>';
                echo '</tr>';
            }
            echo '</tbody>';
            echo '</table>';
        }
        if ($relatorioLideres = $this->relatorio['lideres']) {
            echo '<h2>Líderes - Homens: '.$this->quantidadeHomensLideres.' - Mulheres: '.$this->quantidadeMulheresLideres.'</h2>';
            echo '<input id="fooFilterLideres" type="text" class="form-control" placeholder="Filtro">';
            echo '<table class="table table-condensed table-hover bg-light mt15 footable" data-filter="#fooFilterLideres">';
            echo '<thead>';
            echo '<tr class="text-center">';
            echo '<th>Inscrição</th>';
            echo '<th>Líder</th>';
            echo '<th>Sexo</th>';
            echo '<th>Time</th>';
            echo '<th><input type="checkbox" onclick="marcarTodos(this);"/></th>';
            echo '</tr>';
            echo '</thead>';
            echo '<tbody>';
            foreach ($relatorioLideres as $relatorio) {
              $nomeEntidadeAcima = '';
              if($this->multiplos){
                $nomeEntidadeAcima = $relatorio->getPessoa()->getResponsabilidadesAtivas()[0]->getGrupo()->getGrupoPaiFilhoPaiAtivo()->getGrupoPaiFilhoPai()->getEntidadeAtiva()->getNome();
                if(!$nomeEntidadeAcima){
                  $nomeEntidadeAcima = ' - COORDENAÇÃO '. $relatorio->getPessoa()->getResponsabilidadesAtivas()[0]->getGrupo()->getGrupoPaiFilhoPaiAtivo()->getGrupoPaiFilhoPai()->getEntidadeAtiva()->getNumero();
                }
              }
                $sexo = $relatorio->getPessoa()->getSexo();
                $sexo ? $sexo : 'Não Informado';
                echo '<tr class="text-center">';
                echo '<td>' . $relatorio->getId() . '</td>';
                echo '<td>' . $relatorio->getPessoa()->getNome() . '</td>';
                echo '<td>' . $sexo . '</td>';
                echo '<td>' . $relatorio->getPessoa()->getResponsabilidadesAtivas()[0]->getGrupo()->getEntidadeAtiva()->infoEntidade() . $nomeEntidadeAcima . '</td>';
                echo '<td><input type="checkbox" id="lider' . $relatorio->getId() . '" name="lider' . $relatorio->getId() . '" value="' . $relatorio->getId() . '"/></td>';
                echo '</tr>';
            }
            echo '</tbody>';
            echo '</table>';
        }
        echo $htmlBotaoGerar;
        ?>
    </div>

<?php
echo $this->form()->closeTag();
echo $this->templateFormularioRodape();
