<?php

use Application\Controller\Helper\Constantes;
use Application\Model\Entity\EntidadeTipo;
use Application\Model\Entity\Situacao;
use Application\Model\Entity\SolicitacaoTipo;

$html = '';
$html .= $this->templateFormularioTopo($this->titulo);
$html .= '<div class="panel-body bg-light">';
if ($this->solicitacoes) {
    $html .= '<table class="table">';

    $html .= '<thead>';

    $html .= '<tr>';
    $html .= '<th class="hidden-xs">Tipo</th>';
    $html .= '<th class="hidden-xs">Solicitado em</th>';
//    $html .= '<th class="hidden-xs">Por</th>';
    $html .= '<th>O que ou quem?</th>';
    $html .= '<th>Para</th>';
    $html .= '<th>Status</th>';
    $html .= '</tr>';

    $html .= '</thead>';

    $html .= '<tbody>';

    foreach ($this->solicitacoes as $solicitacao) {
        $html .= '<tr>';
        $html .= '<td class="hidden-xs">' . $solicitacao->getSolicitacaoTipo()->getNome() . '</td>';
        $html .= '<td class="hidden-xs">' . $solicitacao->getData_criacaoStringPadraoBrasil() . '</td>';
//        $html .= '<td class="hidden-xs">' . $solicitacao->getPessoa()->getNomePrimeiroUltimo() . '</td>';

        $html .= '<td>';
        $objeto = $solicitacao->getObjeto1();
        $grupo = $this->repositorio->getGrupoORM()->encontrarPorId($objeto);
        $html .= $grupo->getNomeLideresAtivos();
        $html .= '</td>';
        $html .= '<td>';
        if ($solicitacao->getSolicitacaoTipo()->getId() === SolicitacaoTipo::TRANSFERIR_LIDER_NA_PROPRIA_EQUIPE ||
                $solicitacao->getSolicitacaoTipo()->getId() === SolicitacaoTipo::UNIR_CASAL) {
            $objeto = $solicitacao->getObjeto2();
            $grupo = $this->repositorio->getGrupoORM()->encontrarPorId($objeto);
            $html .= $grupo->getNomeLideresAtivos();
        }
        if ($solicitacao->getSolicitacaoTipo()->getId() === SolicitacaoTipo::TRANSFERIR_LIDER_PARA_OUTRA_EQUIPE) {
            $objeto = $solicitacao->getObjeto2();
            $grupo = $this->repositorio->getGrupoORM()->encontrarPorId($objeto);
            if ($grupo->getEntidadeAtiva()->getEntidadeTipo()->getId() === EntidadeTipo::equipe) {
                $html .= '<b>' . $grupo->getEntidadeAtiva()->getNome() . '</b>';
            }
            if ($grupo->getEntidadeAtiva()->getEntidadeTipo()->getId() === EntidadeTipo::subEquipe) {
                $html .= '<b>' . $grupo->getEntidadeAtiva()->infoEntidade() . '</b>';
            }
        }
        $html .= '</td>';
        if ($solicitacao->getSolicitacaoSituacaoAtiva()) {
            $html .= '<td>' . $solicitacao->getSolicitacaoSituacaoAtiva()->getSituacao()->getNome() . '</td>';
        }
        if ($solicitacao->getSolicitacaoTipo()->getId() === SolicitacaoTipo::TRANSFERIR_LIDER_PARA_OUTRA_EQUIPE) {
            if ($this->grupo->getId() == $grupo->getId()) {
                $stringNomeDaFuncaoOnClick = 'funcaoCircuito("cadastroSolicitacaoReceber", ' . $solicitacao->getId() . ')';
                $extra = $this->funcaoOnClick($stringNomeDaFuncaoOnClick);
                $html .= '<td>';
                $html .= $this->botaoSimples('Receber', $extra);
                $html .= '</td>';
            }
            if ($solicitacao->getSolicitacaoSituacaoAtiva()->getSituacao()->getId() === Situacao::ACEITO_AGENDADO) {
                $idPessoa = $solicitacao->getReceptor_id();
                $pessoa = $this->repositorio->getPessoaORM()->encontrarPorId($idPessoa);

                $html .= '<td>';
                $html .= 'Receptor <b>' . $pessoa->getNomePrimeiroUltimo() . '</b>';
                $html .= '</td>';
            }
        }

        $html .= '</tr>';
    }

    $html .= '</tbody>';

    $html .= '</table>';
} else {
    $html .= '<div class="alert alert-warning"><i class="fa fa-warning pr10" aria-hidden="true"></i>&nbsp;Sem solicitações!</div>';
}
$html .= '</div>';

$html .= '<div class="panel-footer text-right">';
$stringNomeDaFuncaoOnClickCadastro = 'funcaoCircuito("cadastroSolicitacao", 0)';
$html .= $this->botaoLink($this->translate(Constantes::$TRADUCAO_CADASTRAR), Constantes::$STRING_HASHTAG, 0, $this->funcaoOnClick($stringNomeDaFuncaoOnClickCadastro));
$html .= '</div>';

$html .= $this->templateFormularioRodape();
echo $html;

