<?php

use Application\Controller\Helper\Constantes;
use Application\Controller\CursoController;
use Application\Model\Entity\EntidadeTipo;
use Application\View\Helper\BotaoSimples;

$labelVoltar = $this->translate(Constantes::$TRADUCAO_VOLTAR);

$form = $this->Form;
$form->prepare();
$form->setAttribute(Constantes::$FORM_ACTION, Constantes::$ROUTE_CADASTRO . 'SolicitacaoFinalizar');
echo $this->form()->openTag($form);
?>
<div align="center">
<div class="panel mw600">
<div class="panel-heading text-center"><?php echo $this->titulo; ?></div>
<div class="panel-body bg-light">
	<!--divSolicitacaoTipo-->
	<div id="divSolicitacaoTipo">
		<div class="section-divider mt20">
			<span>Selecione uma das opções abaixo</span>
		</div>
		Tipo de solicitação
		<select id="solicitacaoTipo" class="mt10 form-control" onchange="mostrarBotaoContinuar();">
			<option value="0">SELECIONE</option>
<?php
foreach ($this->solicitacaoTipos as $solicitacaoTipo) {
	echo '<option value="' . $solicitacaoTipo->getId() . '">' . $solicitacaoTipo->getNome() . '</option>';
}
?>
		</select>
		<div id="divBotaoContinuarSelecionarTipo" class="hidden mt10">
<?php
echo $this->botaoSimples(Constantes::$TRADUCAO_CONTINUAR, $this->funcaoOnClick('selecionarTipo()'));
?>
		</div>
	</div>
	<!-- Progress Bar -->
	<div id="divProgress"  class="col-xs-12 hidden mt10 mb10">
		<div class="progress">
			<div id="divProgressBar" class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
				0%
			</div>
		</div>
	</div>
	<!--divObjetos-->
	<div id="divObjetos" class="hidden">
<?php
for ($indiceDeObejtos = 1; $indiceDeObejtos <= 3; $indiceDeObejtos++) {
	$funcaoOnclick = 'abrirSelecionarObjeto(' . $indiceDeObejtos . ', ' . $this->grupo->getId() . ')';
	$mostrarBotaoAdicionar = '';
	if ($indiceDeObejtos === 1) {
		$stringSelecioneOObjeto = 'Selecione o líder que será transferido';
	}
	if ($indiceDeObejtos === 2) {
		$mostrarBotaoAdicionar = 'hidden';
		$stringSelecioneOObjeto = 'Selecione o líder que receberá a transfêrencia';
	}
	if ($indiceDeObejtos === 3) {
		$mostrarBotaoAdicionar = 'hidden';
		$stringSelecioneOObjeto = 'Selecione os dados complementares';
	}
?>
			<!-- Bloco objeto -->
			<div id="blocoObjeto<?php echo $indiceDeObejtos; ?>" class="well col-xs-12 text-left">
				<div class="col-md-12">
					<span id="spanSelecioneObjeto<?php echo $indiceDeObejtos; ?>"><?php echo $stringSelecioneOObjeto; ?></span>
					<span id="spanObjeto<?php echo $indiceDeObejtos; ?>"></span>
					<span class="hidden" id="spanLoader<?php echo $indiceDeObejtos; ?>">Carregando <img src="/img/loader.gif" /></span>
				</div>
				<div class="col-md-6">
					<span id="spanFotos<?php echo $indiceDeObejtos; ?>"></span>
				</div>
				<div class="col-md-6">
					<span class="quebraDeLinhaDeSpan" id="spanNomeLideres<?php echo $indiceDeObejtos; ?>"></span>
					<span class="quebraDeLinhaDeSpan" id="spanCelulaQuantidade<?php echo $indiceDeObejtos; ?>"></span>
					<span class="quebraDeLinhaDeSpan" id="spanQuantidadeLideres<?php echo $indiceDeObejtos; ?>"></span>
				</div>
				<div id="divBotaoSelecionar<?php echo $indiceDeObejtos; ?>" class="<?php echo $mostrarBotaoAdicionar ?>">
<?php
	echo $this->botaoSimples(Constantes::$TRADUCAO_SELECIONAR, $this->funcaoOnClick($funcaoOnclick), BotaoSimples::botaoPequenoImportante);
?>
				</div>
				<div id="divBotaoLimpar<?php echo $indiceDeObejtos; ?>" class="hidden">
					<button type="button" onClick='limparObjeto(<?php echo $indiceDeObejtos; ?>);' style="float: right;" onclick='location.href = "#";' class="btn ladda-button btn-default dark btn-xs mr5" data-style="zoom-in">
						<span class="ladda-label">Limpar</span>
					</button>
				</div>
				<div id="divCheckDadosInseridos<?php echo $indiceDeObejtos; ?>" class="checkDadosInseridos hidden">
					<span class="glyphicon glyphicon-ok text-success"></span>
				</div>
			</div>
<?php
}
?>
	</div>

<?php if($this->entidade->getEntidadeTipo()->getId() !== EntidadeTipo::regiao){ ?>
	<!--divSelecionarLider-->
	<div id="divSelecionarLider" class="hidden">
	<select id="idLider" class="form-control" onChange="mostrarBotaoSelecionarLider();">
	<option value="0"><?php echo $this->translate(Constantes::$TRADUCAO_SELECIONE); ?></option>
	<?php echo $this->listagemLideresTransferencia($this->discipulos); ?>
	</select>
	<div id="divBotaoSelecionarLider" class="hidden mt10">
	<?php
		echo $this->botaoSimples(Constantes::$TRADUCAO_SELECIONAR, $this->funcaoOnClick('selecionarLider()'));
	?>
	</div>
	</div>
	<!--divSelecionarEquipe-->
	<div id="divSelecionarEquipe" class="hidden">
	<select id="idEquipe" class="form-control" onChange="mostrarBotaoSelecionarEquipe();">
		<option value="0">SELECIONE</option>
	<?php
		foreach ($this->grupoPaiFilhoEquipes as $grupoPaiFilhoEquipe) {
			$grupo = $grupoPaiFilhoEquipe->getGrupoPaiFilhoFilho();
			echo '<option value="' . $grupo->getId() . '" >' . $grupo->getEntidadeAtiva()->infoEntidade() . '</option>';
		}
	?>
	</select>
	<div id="divBotaoSelecionarEquipe" class="hidden mt10">
	<?php
		echo $this->botaoSimples(Constantes::$TRADUCAO_SELECIONAR, $this->funcaoOnClick('selecionarEquipe()'));
	?>
	</div>
	</div>
	<!--divSelecionarHomem-->
	<div id="divSelecionarHomem" class="hidden">
<?php
if (count($this->grupoPaiFilhoHomens) === 0) {
	echo 'Sem homens para casar';
} else {
?>
	<select id="idHomem" class="form-control" onChange="mostrarBotaoSelecionarHomem();">
		<option value="0">SELECIONE</option>
<?php
	foreach ($this->grupoPaiFilhoHomens as $grupoPaiFilhoHomem) {
		$grupo = $grupoPaiFilhoHomem['grupo']->getGrupoPaiFilhoFilho();
		echo '<option id="homem'.$grupo->getId().'" class="'.$grupoPaiFilhoHomem['hierarquia'].'" value="' . $grupo->getId() . '" >' . $grupo->getEntidadeAtiva()->infoEntidade() . ' - ' . $grupo->getGrupoResponsavelAtivo()->getPessoa()->getNomePrimeiroUltimo().'</option>';
}
?>
	</select>
	<div id="divBotaoSelecionarHomem" class="hidden mt10">
	<?php
		echo $this->botaoSimples(Constantes::$TRADUCAO_SELECIONAR, $this->funcaoOnClick('selecionarHomem()'));
	?>
	</div>	
	<?php } ?>
	</div>
	<!--divSelecionarMulher-->
	<div id="divSelecionarMulher" class="hidden">
<?php
if (count($this->grupoPaiFilhoMulheres) === 0) {
	echo 'Sem mulheres para casar';
} else {
?>
	<h2>Somente aparecerá para unir mulheres discípulas do mesmo líder</h2>
	<select id="idMulher" class="form-control" onChange="mostrarBotaoSelecionarMulher();">
		<option value="0">SELECIONE</option>
<?php
	foreach ($this->grupoPaiFilhoMulheres as $grupoPaiFilhoMulher) {
		$grupo = $grupoPaiFilhoMulher['grupo']->getGrupoPaiFilhoFilho();
		echo '<option class="mulheres '.$grupoPaiFilhoMulher['hierarquia'].'" value="' . $grupo->getId() . '" >' . $grupo->getEntidadeAtiva()->infoEntidade() . ' - ' . $grupo->getGrupoResponsavelAtivo()->getPessoa()->getNomePrimeiroUltimo().'</option>';
}
?>
	</select>
	<div id="divBotaoSelecionarMulher" class="hidden mt10">
	<?php
		echo $this->botaoSimples(Constantes::$TRADUCAO_SELECIONAR, $this->funcaoOnClick('selecionarMulher()'));
	?>
	</div>
	<?php } ?>
	</div>

	<!--divSelecionarCasal-->
	<div id="divSelecionarCasal" class="hidden">
<?php
if (count($this->grupoPaiFilhoCasais) === 0) {
	echo 'Sem casais para a solicitação';
} else {
?>
	<h3>Selecione o casal</h3>
	<select id="idCasal" class="form-control" onChange="mostrarBotaoSelecionarCasal();">
		<option value="0">SELECIONE</option>
<?php
	foreach ($this->grupoPaiFilhoCasais as $grupoPaiFilhoCasal) {
		$grupo = $grupoPaiFilhoCasal['grupo']->getGrupoPaiFilhoFilho();
		echo '<option class="casais '.$grupoPaiFilhoCasal['hierarquia'].'" value="' . $grupo->getId() . '" >' . $grupo->getEntidadeAtiva()->infoEntidade(). ' - ' . $grupo->getNomeLideresAtivos().'</option>';
}
?>
	</select>
	<div id="divBotaoSelecionarCasal" class="hidden mt10">
	<?php
		echo $this->botaoSimples(Constantes::$TRADUCAO_SELECIONAR, $this->funcaoOnClick('selecionarCasal()'));
	?>
	</div>
	<?php } ?>
	</div>

	<!--divSelecionarAluno-->
	<div id="divSelecionarAluno" class="hidden">
<?php
if (count($this->alunos) === 0) {
	echo 'Sem alunos para transferir';
} else {
?>
	<select id="idAluno" class="form-control" onChange="mostrarBotaoSelecionarAluno();">
		<option value="0">SELECIONE</option>
<?php
	foreach ($this->alunos as $aluno) {
		$grupoPessoaAtivo = $aluno->getPessoa()->getGrupoPessoaAtivo();
		$pessoa = $aluno->getPessoa();
		$nomeEquipe = CursoController::nomeEquipeTurmaPessoa($aluno, $grupoPessoaAtivo);
		echo '<option  value="' . $aluno->getId() . '" >' . $aluno->getId() . ' - ' . $nomeEquipe . ' - '.  $pessoa->getNome() . '</option>';
}
?>
	</select>
	<div id="divBotaoSelecionarAluno" class="hidden mt10">
	<?php
		echo $this->botaoSimples(Constantes::$TRADUCAO_SELECIONAR, $this->funcaoOnClick('selecionarAluno()'));
	?>
	</div>
	<?php } ?>
	</div>

	<!--divSelecionarLideresIgreja-->
	<div id="divSelecionarLiderIgreja" class="hidden">
	<select id="idLiderIgreja" class="form-control" onChange="mostrarBotaoSelecionarLiderIgreja();">
	<option value="0"><?php echo $this->translate(Constantes::$TRADUCAO_SELECIONE); ?></option>
	<?php echo $this->listagemLideresTransferencia($this->discipulosIgreja); ?>
	</select>
	<div id="divBotaoSelecionarLiderIgreja" class="hidden mt10">
	<?php
		echo $this->botaoSimples(Constantes::$TRADUCAO_SELECIONAR, $this->funcaoOnClick('selecionarLiderIgreja()'));
	?>
	</div>
	</div>

<!--divSelecionarQuemSaira-->
	<div id="divSelecionarQuemSaira" class="hidden">
	<div class="section-divider mt20">
	<span>Selecione quem do casal vai sair</span>
	</div>
	<select id="quemVaiSair" name="quemVaiSair" class="mt10 form-control">
	<option value="0">SELECIONE</option>
	<option value="1">HOMEM</option>
	<option value="2">MULHER</option>
	</select>
	<button type="button" onClick='selecionarQuemSaira()' style="float: right;" class="mt10 btn ladda-button btn-primary mr5" data-style="zoom-in">
	<span class="ladda-label">Selecionar</span>
	</button>
	</div>
	<!--divSelecionarNumeracao-->
	<div id="divSelecionarNumeracao" class="hidden">
	<div class="section-divider mt20">
	<span>Selecione uma numeração</span>
	</div>
	<select id="numero" class="mt10 form-control">
	<option value="0">SELECIONE</option>
<?php
for ($indiceNumeracao = 1; $indiceNumeracao <= 24; $indiceNumeracao++) {
	echo "<option value='$indiceNumeracao'>$indiceNumeracao</option>";
}
?>
	</select>
	<button type="button" onClick='selecionarNumeracao()' style="float: right;" class="mt10 btn ladda-button btn-primary mr5" data-style="zoom-in">
	<span class="ladda-label">Selecionar</span>
	</button>
	</div>
	<!-- divSelecionarMotivo -->
	<div id="divSelecionarMotivo" class="hidden">
	<div class="section-divider mt20">
	<span>Selecione o motivo</span>
	</div>
	<select id="motivo" name="motivo" class="form-control" onChange="if($('#motivo').val() != 0){$('#divMotivo').removeClass('hidden')}else{$('#divMotivo').addClass('hidden')}">
	<option value="0">Saiu da Igreja</option>
	<option value="outro">Outro</option>
	</select>
	<div id="divMotivo" class="hidden mt20">
	<textarea name="textareaMotivo" id="textareaMotivo" rows="4" cols="50" class="form-control"></textarea>
	</div>
<?php
echo '<div class="mt20">';
echo $this->botaoSimples('Selecionar', $this->funcaoOnClick('selecionarMotivo()'), BotaoSimples::botaoSucesso);
echo '</div>';
?>
	</div>
	<!-- divSelecionarCelula -->
	<div id="divSelecionarCelula" class="hidden">
	<div class="section-divider mt20">
	<span>Selecione a célula para remover</span>
	</div>
	<select class="form-control" id="idGrupoEvento" name="idGrupoEvento" onChange="if($('#idGrupoEvento').val() != 0){$('#divBotaoSelecionarCelula').removeClass('hidden')}else{$('#divBotaoSelecionarCelula').addClass('hidden')}">
	<option value="0">SELECIONE</option>
	</select>
<?php
echo '<div id="divBotaoSelecionarCelula" class="mt20 hidden">';
echo $this->botaoSimples('Selecionar', $this->funcaoOnClick('selecionarCelula()'), BotaoSimples::botaoSucesso);
echo '</div>';
?>
	</div>

	<!--divNomeEquipe-->
	<div id="divNomeEquipe" class="hidden">
	<div class="section-divider mt20">
	<span>Nome da Equipe</span>
	</div>
	<input type='text' id='nomeEquipe' name='nomeEquipe' class='form-control'/>
	<button type="button" onClick='selecionarNomeEquipe()' style="float: right;" class="mt10 btn ladda-button btn-primary mr5" data-style="zoom-in">
	<span class="ladda-label">Selecionar</span>
	</button>
	</div>

<?php } ?>

<div id="divSelecionarPessoa" class="hidden">
	<span id="spanStatus" class="quebraDeLinhaDeSpan mt50 alert alert-danger text-center hidden"></span>	
    <input type="number" name="cpf" class="form-control" id="cpf" placeholder="Digite o CPF" pattern="\d*">	
	<div id="divBotaoSelecionarPessoaParaSerSecretario" class="mt10">
	<?php
		echo $this->botaoSimples('FILTRAR', $this->funcaoOnClick('selecionarPessoaParaSerSecretario()'));
	?>
	</div>
</div>

<div id="divSelecionarPessoaParaSerSecretarioProsseguir" class="hidden">	
	<span id="spanPessoa" class="quebraDeLinhaDeSpan mt50 alert alert-success text-center hidden"></span>	
	<input type="hidden" name="idPessoa" id="idPessoa">
	<?php
		$botaoMenorImportancia = 2;				
		echo $this->botaoSimples('CONFIRMAR', $this->funcaoOnClick('prosseguirSecretarario()'));
		echo $this->botaoSimples('VOLTAR', $this->funcaoOnClick('voltarSelecionarSecretario()'), $botaoMenorImportancia);		
	?>
</div>

<div id="divSelecionarEntidadeSecretarioParaInativar" class="hidden">		
	<select class="form-control mb10" id="selecionarEntidadeSecretarioParaInativar" name="selecionarEntidadeSecretarioParaInativar"  onChange="mostrarBotaoInativarSecretario();"></select>	
		<div class="hidden" id="botaoProsseguirSecretarioParaInativar" name="botaoProsseguirSecretarioParaInativar">
			<?php echo $this->botaoSimples('CONFIRMAR', $this->funcaoOnClick('prosseguirInativarSecretarario()')); ?>
		</div>
		<?php
		$botaoMenorImportancia = 2;				
		echo $this->botaoSimples('VOLTAR', $this->funcaoOnClick('voltarSelecionarSecretario()'), $botaoMenorImportancia);		
	?>
</div>

<?php if($this->entidade->getEntidadeTipo()->getId() === EntidadeTipo::regiao){ ?>
	<div id="divSelecionarIgreja" class="hidden">
<?php
if (count($this->igrejas) === 0) {
	echo 'Sem igrejas para transferir';
} else {
?>
	<select id="idIgreja" class="form-control" onChange="mostrarBotaoSelecionarIgreja();">
		<option value="0">SELECIONE</option>
<?php
	foreach ($this->igrejas as $igreja) {
		$nomeIgreja = $igreja->getEntidadeAtiva()->getNome();
		echo '<option  value="' . $igreja->getId() . '" >' . $igreja->getId() . ' - ' . $nomeIgreja . '</option>';
}
?>
	</select>
	<div id="divBotaoSelecionarIgreja" class="hidden mt10">
	<?php
		echo $this->botaoSimples(Constantes::$TRADUCAO_SELECIONAR, $this->funcaoOnClick('selecionarIgreja()'));
	?>
	</div>
	<?php } ?>
	</div>

	<div id="divSelecionarParaOndeTransferir" class="hidden">
<?php
if (count($this->igrejas) === 0) {
	echo 'Sem ipara onde transferir a igreja';
} else {
?>
	<select id="idParaOndeTransferir" class="form-control" onChange="mostrarBotaoSelecionarParaOndeTransferir();">
		<option value="0">SELECIONE</option>
<?php
	foreach ($this->paraOndeTransferir as $coisa) {
		$informacao = '';
		if($coisa->getEntidadeAtiva()->getEntidadeTipo()->getId() === EntidadeTipo::regiao){
			$informacao = 'REGIÃO ' . $coisa->getEntidadeAtiva()->getNome();
		}
		if($coisa->getEntidadeAtiva()->getEntidadeTipo()->getId() === EntidadeTipo::coordenacao){
			$informacao = 'COORDENAÇÃO ' . $coisa->getEntidadeAtiva()->getNumero();
		}
		
		echo '<option  value="' . $coisa->getId() . '" >' . $coisa->getId() . ' - ' . $informacao . '</option>';
}
?>
	</select>
	<div id="divBotaoSelecionarParaOndeTransferir" class="hidden mt10">
	<?php
		echo $this->botaoSimples(Constantes::$TRADUCAO_SELECIONAR, $this->funcaoOnClick('selecionarParaOndeTransferir()'));
	?>
	</div>
	<?php } ?>
	</div>

<?php } ?>


	<!--divBotaoContinuar-->
	<div id="divBotaoContinuar" class="hidden">
<?php
echo $this->botaoSimples(Constantes::$TRADUCAO_CONTINUAR, $this->funcaoOnClick('continuarParaConfimacao()'), BotaoSimples::botaoSucesso);
?>
	</div>
	<!--divTelaConfirmacao-->
	<div id="divTelaConfirmacao" class="hidden">
	<div class="panel heading-border panel-info">
	<div class="panel-body">
	<address id="spanMensagemDeConfirmacao">Confirma a transfêrencia desse líder na sua própria equipe? Somente no próximo período será feito a transfêrencia!</address>
	</div>
	</div>
	<div class="row">
	<div class="col-sm-12 col-xs-12">
	<div class="section text-center">
	<label class="option block mt15">
	<input type="checkbox" name="checked" value="checked" onclick="pedirSenha();">
	<span class="checkbox"></span>
	Confirmo isso
	</label>
	</div>
	</div>
	</div>
<?php
$stringNomeDaFuncaoOnClickVoltar = 'voltaAosObjetos()';
echo $this->botaoSimples($labelVoltar, $this->funcaoOnClick($stringNomeDaFuncaoOnClickVoltar), BotaoSimples::botaoMenorImportancia);
?>
	</div>
	<!--divSenha-->
	<div id="divSenha" class="hidden">
	<div class="">
	<div class="section-divider">
	<span>Confirma essa solicitação?</span>
	</div>
	<?php echo $this->divMensagens(); ?>
<div class="row">
	<div class="col-sm-12 col-xs-12">
	<div class="section text-center mb10">
	<input id="senha" type="password" class="form-control" placeholder="<?php echo $this->translate(Constantes::$TRADUCAO_SENHA); ?>" />
	</div>
	</div>
	</div>
	</div>
	<div class="text-right" style="height:65px;">
<?php
/* Botões */
$labelConfirmar = $this->translate(Constantes::$TRADUCAO_CONFIRMACAO);
$stringNomeDaFuncaoOnClickVoltarConfirmacao = 'continuarParaConfimacao()';
$stringNomeDaFuncaoOnClickConfimarSolicitacao = 'validarSenha(this.form)';
echo $this->botaoSimples($labelConfirmar, $this->funcaoOnClick($stringNomeDaFuncaoOnClickConfimarSolicitacao), BotaoSimples::botaoPerigoso);
echo $this->botaoSimples($labelVoltar, $this->funcaoOnClick($stringNomeDaFuncaoOnClickVoltarConfirmacao), BotaoSimples::botaoMenorImportancia);
?>
	</div>
	</div>
	</div>
	</div>
<?php
echo $this->formHidden($form->get('solicitacaoTipoId'));
echo $this->formHidden($form->get('objeto1'));
echo $this->formHidden($form->get('objeto2'));
echo $this->formHidden($form->get('numeracao'));
echo $this->form()->closeTag();
