<?php
echo $this->templateFormularioTopo('Transferência');
?>
<div class="panel-body bg-light">
    <?php echo $this->passoAPasso($this->Form); ?>
    <div id="divLideresParaTransferir">
        <div class="panel-menu">
            <input id="fooFilter" type="text" class="form-control" placeholder="Filtro">
        </div>
        <table class="table footable no-paging" data-filter="#fooFilter" data-page-navigation=".pagination" data-page-size="5">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Equipe</th>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                <?php echo $this->listagemLideresTransferencia($this->discipulos); ?>
            </tbody>
            <tfoot class="footer-menu">
                <tr>
                    <td colspan="3">
                        <nav class="text-right">
                            <ul class="pagination hide-if-no-paging"></ul>
                        </nav>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div id="divDadosSelecionados" class="hidden alert alert-info" role="alert">
        <span id="spanLiderParaSerTransferido"></span>
    </div>
    <div id="divLideresParaQuemSeraTransferido" class="hidden">
        <div class="panel-menu">
            <input id="fooFilter2" type="text" class="form-control" placeholder="Filtro">
        </div>
        <table class="table footable no-paging" data-filter="#fooFilter2" data-page-navigation=".pagination" data-page-size="5">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Equipe</th>
                    <td class="text-right"></td>
                </tr>
            </thead>
            <tbody>
                <?php echo $this->listagemLideresTransferencia($this->discipulos, 2); ?>           
            </tbody>
            <tfoot class="footer-menu">
                <tr>
                    <td colspan="3">
                        <nav class="text-right">
                            <ul class="pagination hide-if-no-paging"></ul>
                        </nav>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div id="divConfirmacao" class="hidden">
        <blockquote>
            <p>Voce inativará a Equipe BLACKBELT 5.4 Leonardo & Vivian</p>          
        </blockquote>
        <blockquote>
            <p>Será tranferida para a Equipe BALCKBELT 1 com numeração/nome de BALCKBELT 1.20.1.5</p>
        </blockquote>
        <div class="text-center mt10">
            <button class="btn btn-primary">Confirmo</button>
        </div>
    </div>
    <div class="hidden">
        <input type="password" class="form-control" placeholder="Senha" />

        <div class="text-center mt10">
            <button class="btn btn-primary">Transferir</button>
        </div>
    </div>
</div>

<script type="text/javascript">
    /**
     * Nome: layout-js-transferencia-validacao.js
     * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com>
     * Descricao: Funções para cadastro de transferência
     */

    /* Dados */
    var idGrupoParaTransferir = 0;
    var idGrupoNovoLider = 0;
    var iconeTime = '<i class="fa fa-times" aria-hidden="true"></i>';
    var iconeCheck = '<i class="fa fa-check" aria-hidden="true"></i>';
    var hidden = 'hidden';
    var textDanger = 'text-danger';
    var textSuccess = 'text-success';
    var stringNBSP = '&nbsp;';
    var alertDanger = 'alert-danger';
    var alertSuccess = 'alert-success';
    var btnDefault = 'btn-default';
    var btnPrimary = 'btn-primary';

    function selecionarLiderParaTransferir(idGrupo, informacao) {
        idGrupoParaTransferir = idGrupo;
        $('#botaoPasso2')
                .removeClass('btn-default')
                .addClass('btn-primary');
        $('#divLideresParaTransferir').addClass(hidden);
        $('#divDadosSelecionados').removeClass(hidden);
        $('#divLideresParaQuemSeraTransferido').removeClass(hidden);
        $('#spanLiderParaSerTransferido').html('Lider que será transferido: '+informacao);
    }

    function selecionarDeQuemSeraDiscipulo(idGrupo) {
        idGrupoNovoLider = idGrupo;
        $('#botaoPasso3')
                .removeClass('btn-default')
                .addClass('btn-primary');
        $('#divLideresParaQuemSeraTransferido').addClass(hidden);
        $('#divConfirmacao').removeClass(hidden);
    }
</script>