<?php

use Application\Controller\Helper\Constantes;

echo $this->templateFormularioTopo('Transferência');
?>
<div class="panel-body bg-light">
    <?php echo $this->passoAPasso($this->Form); ?>
    <div id="divLideresParaTransferir">
        <div class="panel-menu">
            <input id="fooFilter" type="text" class="form-control" placeholder="Filtro">
        </div>
        <table class="table footable no-paging" data-filter="#fooFilter" data-page-navigation=".pagination" data-page-size="5">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Equipe</th>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                <?php echo $this->listagemLideresTransferencia($this->discipulos); ?>
            </tbody>
            <tfoot class="footer-menu">
                <tr>
                    <td colspan="3">
                        <nav class="text-right">
                            <ul class="pagination hide-if-no-paging"></ul>
                        </nav>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div id="divDadosSelecionados" class="hidden text-center">
        <div class="alert alert-info" role="alert">
            <span class="mb10 quebraDeLinhaDeSpan" id="spanLiderParaSerTransferido"></span>
            <span class="mb10 quebraDeLinhaDeSpan" id="spanLideresParaQuemSeraTransferido"></span>
            <select id="numero" class="hidden mb10 form-control">
                <option>1</option>
            </select>
        </div>
        <div id="botaoConfirmacao" class="hidden">
            <?php
            $funcaoPedirSenha = $this->funcaoOnclick('pedirSenha();');
            echo $this->botaoSimples('Confirmar', $funcaoPedirSenha);
            ?>
        </div>
    </div>
    <div id="divLideresParaQuemSeraTransferido" class="hidden">
        <div class="panel-menu">
            <input id="fooFilter2" type="text" class="form-control" placeholder="Filtro">
        </div>
        <table class="table footable no-paging" data-filter="#fooFilter2" data-page-navigation=".pagination" data-page-size="5">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Equipe</th>
                    <td class="text-right"></td>
                </tr>
            </thead>
            <tbody>
                <?php echo $this->listagemLideresTransferencia($this->discipulos, 2); ?>           
            </tbody>
            <tfoot class="footer-menu">
                <tr>
                    <td colspan="3">
                        <nav class="text-right">
                            <ul class="pagination hide-if-no-paging"></ul>
                        </nav>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>    
    <div id="divSenha" class="hidden">
        <div class="panel-body bg-light">
            <div class="section-divider">
                <span><?php echo $this->translate(Constantes::$TRADUCAO_DIGITE_SENHA_EXCUSAO_SENHA); ?></span>
            </div>
            <div class="row">
                <div class="col-sm-12 col-xs-12">
                    <div class="section text-center">
                        <input type="password" class="gui-input" placeholder="<?php echo $this->translate(Constantes::$TRADUCAO_SENHA); ?>" />
                    </div>
                    <?php
                    $funcaoPedirSenha = $this->funcaoOnclick('pedirSenha();');
                    echo $this->botaoSimples('Confirmar', $funcaoPedirSenha);
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    /**
     * Nome: layout-js-transferencia-validacao.js
     * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com>
     * Descricao: Funções para cadastro de transferência
     */

    /* Dados */
    var idGrupoParaTransferir = 0;
    var idGrupoNovoLider = 0;
    var iconeTime = '<i class="fa fa-times" aria-hidden="true"></i>';
    var iconeCheck = '<i class="fa fa-check" aria-hidden="true"></i>';
    var hidden = 'hidden';
    var textDanger = 'text-danger';
    var textSuccess = 'text-success';
    var stringNBSP = '&nbsp;';
    var alertDanger = 'alert-danger';
    var alertSuccess = 'alert-success';
    var btnDefault = 'btn-default';
    var btnPrimary = 'btn-primary';

    function selecionarLiderParaTransferir(idGrupo, informacao) {
        idGrupoParaTransferir = idGrupo;
        $('#botaoPasso2')
                .removeClass('btn-default')
                .addClass('btn-primary');
        $('#divLideresParaTransferir').addClass(hidden);
        $('#divDadosSelecionados').removeClass(hidden);
        $('#divLideresParaQuemSeraTransferido').removeClass(hidden);
        $('#spanLiderParaSerTransferido').html('Lider que será transferido: ' + informacao);
    }

    function selecionarDeQuemSeraDiscipulo(idGrupo, informacao) {
        idGrupoNovoLider = idGrupo;
        $('#botaoPasso3')
                .removeClass('btn-default')
                .addClass('btn-primary');
        $('#divLideresParaQuemSeraTransferido').addClass(hidden);
        $('#spanLideresParaQuemSeraTransferido').html('Será discipulo de: ' + informacao);
        $('#divConfirmacao').removeClass(hidden);
        $('#nome').removeClass(hidden);
        $('#numero').removeClass(hidden);
        $('#botaoConfirmacao').removeClass(hidden);
    }

    function pedirSenha() {
        $('#botaoPasso4')
                .removeClass('btn-default')
                .addClass('btn-primary');
        $('#divDadosSelecionados').addClass(hidden);
        $('#divSenha').removeClass(hidden);
    }
</script>