<?php

use Application\Controller\Helper\Constantes;
use Application\View\Helper\BotaoSimples;

?>
		
<div class="center-block col-lg-6 col-md-6 col-sm-12 col-xs-12">
   	<div class="admin-form theme-primary">	    
        <blockquote class = "blockquote-primary">
			<small id="tituloDaPagina">
				<b class="text-danger">Troca</b> de Responsabilidades
			</small>
        </blockquote>
		<div class="panel heading-border panel-primary">
			<div class="panel-body bg-light">
				<span id="spanCarregando">Carregando ...</span>				
				
				<div id="divSelectTimes" class="hidden">
					<div class="row p10">
						<div class="section-divider mt20 mb30" id="spy5"><span style="color: red;">Passo 1</span></div>
						<div class="form-group col-lg-12 col-xs-12">
							<label class="field-label text-muted text-center fs18 mb10">Times para selecionar</label>
							<select class="form-control" id="selectTimes">
							</select>
						</div>
					</div>

					<div class="row p10">
						<button type="button" onClick="adicionarTime()" class="btn ladda-button btn-primary pull-right ml10 " data-style="zoom-in">
							<span class="ladda-label">Adicionar</span>
							<span class="ladda-spinner"></span>
						</button>
					</div>
				</div>

				<div id="divListaDeTimesSelecionados" class="hidden">
					<div class="section-divider mt20 mb30" id="spy5"><span style="color: red;">Times Selecionados</span></div>
					<ul class="fa-ul" id="listaDeTimesSelecionados">
						<li>Nenhum time selecionado</li>
					</ul>
					<button id="botaoSegundoPasso" type="button" onClick="mostrarSegundoPasso()" class="btn ladda-button btn-primary pull-right ml10 hidden" data-style="zoom-in">
						<span class="ladda-label">Próximo Passo</span>
						<span class="ladda-spinner"></span>
					</button>
					
				</div>

				<div id="divSegundoPasso" class="hidden">
					<div class="row p10">
						<div class="section-divider mt20 mb30" id="spy5"><span style="color: red;">Passo 2</span></div>
						<div id="divSelectTimesSelecionados">
							<div class="form-group col-lg-12 col-xs-12">
								<label class="field-label text-muted text-center fs18 mb10">Selecione o time e as responsabilidades para ele</label>
								<select class="form-control" id="selectTimesSelecionados">
								</select>
							</div>				
							<div class="row p10">					
								<button id="botaoSegundoPasso" type="button" onClick="mostrarResponsabilidadesParaSelecionar()" class="btn ladda-button btn-primary pull-right ml10" data-style="zoom-in">
									<span class="ladda-label">Selecionar</span>
									<span class="ladda-spinner"></span>
								</button>		
								<button id="botaoSegundoPasso" type="button" onClick="voltarPassoUm()" class="btn ladda-button btn-default pull-right ml10" data-style="zoom-in">
									<span class="ladda-label">Voltar</span>
									<span class="ladda-spinner"></span>
								</button>			
							</div>
						</div>
					</div>
				</div>

				<!-- fim divSelectTimesSelecionado -->

				<div id="divResponsabilidadesDisponiveis" class="hidden">	
					<div class="row p10">			
						<div class="form-group col-lg-12 col-xs-12">
							<label class="field-label text-muted text-center fs18 mb10">
								Responsabilidades Disponiveis - Time: <span id="spanTimeSelecionadoParaIncluirResponsabilidades"></span>
							</label>
							<select class="form-control" id="selectResponsabilidadesDisponiveis">
							</select>
						</div>
						<button type="button" onClick="selecionarResponsabilidadeParaOGrupo()" class="btn ladda-button btn-primary pull-right ml10" data-style="zoom-in">
							<span class="ladda-label">Selecionar</span>
							<span class="ladda-spinner"></span>
						</button>
						<button type="button" onClick="mostrarSelectTimesSelecionados()" class="btn ladda-button btn-default pull-right ml10" data-style="zoom-in">
							<span class="ladda-label">Voltar</span>
							<span class="ladda-spinner"></span>
						</button>			
					</div>	
					<div class="row p10">
						<div class="section-divider mt20 mb30" id="spy5"><span style="color: red;">Como Ficará</span></div>
						<ul class="fa-ul" id="listaDeTimesEResponsabilidades">
							<li>Nenhuma Responsabilidade Atribuida</li>
						</ul>
					</div>
				</div>

				<div id="divBotaoFinalizar" class="row p10 hidden">			
					<button id="botaoFinalizar" class="btn btn-success ladda-button pull-right ml10" onClick="finalizar()">Finalizar</button>
					<!--divTelaConfirmacao-->
					<div id="divTelaConfirmacao" class="hidden">
						<div class="section-divider mt20 mb30" id="spy5"><span style="color: red;">Confirmação</span></div>	
						<div class="panel heading-border panel-danger">
							<div class="panel-body">
								<address id="spanMensagemDeConfirmacao">Confirma realizar essa troca de responsável? Essa operação não poderá ser desfeita após concluída. Somente no próximo período será feito a troca!</address>
							</div>
						</div>
						<div class="row">
							<div class="col-sm-12 col-xs-12">
								<div class="section text-center">
									<label class="option option-success block mt15">
										<input type="checkbox" name="checked" value="checked" onclick="pedirSenha();">
										<span class="checkbox"></span>
										Confirmo isso
									</label>
								</div>
							</div>
						</div>
					</div>
					<!--divSenha-->
					<div id="divSenha" class="hidden">
						<div class="">				
							<?php echo $this->divMensagens(); ?>
							<div class="row">
								<div class="col-sm-12 col-xs-12">
									<div class="form-group col-lg-12 col-xs-12">
										<label class="field-label text-muted text-center fs18 mb10">Digite sua senha para prosseguir</label>
										<input id="senha" type="password" class="form-control" placeholder="<?php echo $this->translate(Constantes::$TRADUCAO_SENHA); ?>" />
									</div>
									<div class="text-right" style="height:65px;">
										<?php
										/* Botões */
										$labelConfirmar = $this->translate(Constantes::$TRADUCAO_CONFIRMACAO);
										$stringNomeDaFuncaoOnClickConfimarSolicitacao = 'validarSenha()';
										echo $this->botaoSimples($labelConfirmar, $this->funcaoOnClick($stringNomeDaFuncaoOnClickConfimarSolicitacao), BotaoSimples::botaoPerigoso);							
										?>							
										<button class="btn btn-warning ladda-button pull-right ml10" onClick="recomecar()">Recomeçar</button>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>		
	</div>
</div>

<script>
	let listaDeTimesSelecionados = []
	let times = []
	let responsabilidadesParaSelecionar = []
	let listaDeTimesEResponsabilidades = []

	function buscarTimesAte1728(){
		const url = '/principalBuscarTimes'
		fetch(
			url,
			{
				method: 'POST',	
				body: JSON.stringify({
					"token": "<?php echo $this->grupo->getId(); ?>",
				}),
			},
		)
		.then(resultado => {
			if(!resultado.ok){
				alert('erro ao buscar dados')
			}
			return resultado.json()
		})
		.then(json => {
			times = json.resultado.times
			document.getElementById('spanCarregando').classList.add('hidden')
			document.getElementById('divListaDeTimesSelecionados').classList.remove('hidden')
			document.getElementById('divSelectTimes').classList.remove('hidden')
			escreverListaDeTimes()
		})
	}
	buscarTimesAte1728()

	function adicionarTime(){
		const id = document.getElementById("selectTimes").value;
		if(parseInt(id) !== 0){
			const timeSelecionado = times.find(time => parseInt(time.id) === parseInt(id))
			times = times.filter(time => parseInt(time.id) !== parseInt(id))
			escreverListaDeTimes()
			listaDeTimesSelecionados.push(timeSelecionado)

			const responsabilidade= {}
			responsabilidade.id = timeSelecionado.id
			responsabilidade.entidade = timeSelecionado.entidade
			responsabilidade.informacao = timeSelecionado.informacao
			responsabilidadesParaSelecionar.push(responsabilidade)

			document.getElementById('selectTimes').value = 0
			escreverListaDeTimesSelecionados()

			if(listaDeTimesSelecionados.length >= 2){
				mostrarBotaoSegundoPasso()
			}
		}
	}

	function pedirSenha() {
		$('#divTelaConfirmacao').addClass('hidden');
		$('#divSenha').removeClass('hidden');
	}

	function removerTime(id){
		listaDeTimesSelecionados = listaDeTimesSelecionados.filter(item => parseInt(item.id) !== parseInt(id))
		responsabilidadesParaSelecionar = responsabilidadesParaSelecionar.filter(item => parseInt(item.id) !== parseInt(id))
		escreverListaDeTimesSelecionados()
	}

	function escreverListaDeTimes(){
		let html = ''
		html += '<option value="0">SELECIONE</option>'
		times.forEach(item => {
			html += `<option value="${item.id}">${item.entidade}: ${item.informacao} - ${item.lideres}</option>`
		})
		document.getElementById('selectTimes').innerHTML = html
	}

	function escreverListaDeTimesSelecionados(){		
		let html = ''
		listaDeTimesSelecionados.forEach(item => {	
			let button = `<button type="button" onClick="removerTime(${item.id})" class="btn ladda-button btn-danger dark btn-xs mr5 " data-style="zoom-in"><span class="ladda-label"><i class="fa fa-times"></i></span><span class="ladda-spinner"></span></button>`
			html += `<li class="mb5">`
			html += button
			html += `${item.entidade}: ${item.informacao} - ${item.lideres}`
			html += `</li>`
		})
		document.getElementById('listaDeTimesSelecionados').innerHTML = html
	}

	function esconderListaDeTimesSelecionados(){
		document.getElementById('divListaDeTimesSelecionados').classList.add('hidden')
	}

	function mostrarBotaoSegundoPasso(){
		document.getElementById('botaoSegundoPasso').classList.remove('hidden')
	}

	function mostrarSegundoPasso(){
		document.getElementById('divSelectTimes').classList.add('hidden')
		document.getElementById('divListaDeTimesSelecionados').classList.add('hidden')
		document.getElementById('divSegundoPasso').classList.remove('hidden')
		let html = ''
		html += '<option value="0">SELECIONE</option>'
		listaDeTimesSelecionados.forEach(item => {
			html += `<option value="${item.id}">${item.lideres}</option>`
		})
		document.getElementById('selectTimesSelecionados').innerHTML = html
	}

	function voltarPassoUm(){
		document.getElementById('divSelectTimes').classList.remove('hidden')
		document.getElementById('divListaDeTimesSelecionados').classList.remove('hidden')
		document.getElementById('divSegundoPasso').classList.add('hidden')
	}

	function mostrarResponsabilidadesParaSelecionar(){
		const idTime = document.getElementById("selectTimesSelecionados").value;
		if(parseInt(idTime) !== 0){
			const select = document.getElementById('selectTimesSelecionados')
			document.getElementById('spanTimeSelecionadoParaIncluirResponsabilidades').innerHTML = select.options[select.selectedIndex].text
			document.getElementById('divSelectTimesSelecionados').classList.add('hidden')
			document.getElementById('divResponsabilidadesDisponiveis').classList.remove('hidden')
			escreverListaDeResponsabilidadesDisponiveis()
		}
	}

	function escreverListaDeResponsabilidadesDisponiveis(){
		let html = ''
		html += '<option value="0">SELECIONE</option>'
		responsabilidadesParaSelecionar.forEach((item, indice) => {
			html += `<option value="${item.id}">${item.entidade}: ${item.informacao}</option>`
		})
		document.getElementById('selectResponsabilidadesDisponiveis').innerHTML = html
	}

	function selecionarResponsabilidadeParaOGrupo(){
		const idTime = document.getElementById("selectTimesSelecionados").value;
		const idResponsabilidade = document.getElementById("selectResponsabilidadesDisponiveis").value;
		if(parseInt(idResponsabilidade) !== 0){
			let responsabilidade = null
			if(idResponsabilidade !== 'remover'){
				responsabilidade = responsabilidadesParaSelecionar.find(responsabilidade => parseInt(responsabilidade.id) === parseInt(idResponsabilidade))
				responsabilidadesParaSelecionar = responsabilidadesParaSelecionar.filter(responsabilidade => parseInt(responsabilidade.id) !== parseInt(idResponsabilidade))
				escreverListaDeResponsabilidadesDisponiveis()
			}else{
				responsabilidade = {id: 'remover',}
			}
	
			let grupoResponsabilidades = listaDeTimesEResponsabilidades.find(item => parseInt(item.idTime) === parseInt(idTime))
			if(grupoResponsabilidades){
				grupoResponsabilidades.responsabilidades.push(responsabilidade)
				listaDeTimesEResponsabilidades = listaDeTimesEResponsabilidades.map(item => {
					if(parseInt(item.idTime) === parseInt(idTime)){
						return grupoResponsabilidades
					}else{
						return item
					}
				})
			}else{
				const item = {
					idTime,
					responsabilidades: [responsabilidade],
				}
				listaDeTimesEResponsabilidades.push(item)
			}

			/* validar se todas as responsabilidades foram redirecionadas */			
			if(responsabilidadesParaSelecionar.length === 0){
				if(listaDeTimesEResponsabilidades.length !== listaDeTimesSelecionados.length){
					let listaDeNaoInclusos = []
					listaDeTimesSelecionados.forEach(item => {
						let jaEstaAtribuida = false
						listaDeTimesEResponsabilidades.forEach(itemParaTestar => {
							if(parseInt(itemParaTestar.idTime) === parseInt(item.id)){
								jaEstaAtribuida = true
							}
						})
						if(!jaEstaAtribuida){
							listaDeNaoInclusos.push(item.id)
						}
					})
					listaDeNaoInclusos.forEach(item => {
						const itemParaRemover = {
							idTime: item,
							responsabilidades: [{id: 'removido'}],
						}
						listaDeTimesEResponsabilidades.push(itemParaRemover)
					})
				}
				document.getElementById('divBotaoFinalizar').classList.remove('hidden')
			}
			escreverListaDeTimesEResponsabilidades()
		}
	}

	function escreverListaDeTimesEResponsabilidades(){
		let html = ''
		listaDeTimesEResponsabilidades.forEach(item => {
			const time = listaDeTimesSelecionados.find(time => parseInt(time.id) === parseInt(item.idTime))
			html += `<li class="mb10"><i class="fa-li fa fa-circle"></i>${time.lideres}:`
			html += `<ul class="fa-ul">`
			item.responsabilidades.forEach(responsabilidade => {
				if(responsabilidade.entidade){
					html += `<li class="text-success mt5"><i class="fa-li fa fa-arrow-right"></i><b>${responsabilidade.entidade} - ${responsabilidade.informacao}</b></li>`
				}else{
					html += `<li class="text-danger mt5"><i class="fa-li fa fa-arrow-right"></i><b>REMOVER</b></li>`
				}
			})
			html += `</ul>`
			html += `</li>`
		})
		document.getElementById('listaDeTimesEResponsabilidades').innerHTML = html
	}

	function mostrarSelectTimesSelecionados(){
		document.getElementById('selectTimesSelecionados').value = 0
		document.getElementById('selectResponsabilidadesDisponiveis').value = 0
		document.getElementById('divBotaoFinalizar').classList.add('hidden')
		document.getElementById('divSelectTimesSelecionados').classList.remove('hidden')
		document.getElementById('divResponsabilidadesDisponiveis').classList.add('hidden')
	}

	function finalizar(){
		//document.getElementById('divSenha').classList.remove('hidden')
		document.getElementById('divResponsabilidadesDisponiveis').classList.add('hidden')
		document.getElementById('botaoFinalizar').classList.add('hidden')
		$('#divSegundoPasso').addClass('hidden');
		$('#divTelaConfirmacao').removeClass('hidden');
		$('#divSenha').addClass('hidden');
	}

	function recomecar(){
		document.getElementById('spanCarregando').classList.remove('hidden')
		document.getElementById('botaoSegundoPasso').classList.add('hidden')
		listaDeTimesSelecionados = []
		times = []
		responsabilidadesParaSelecionar = []
		listaDeTimesEResponsabilidades = []
		buscarTimesAte1728()		
		escreverListaDeTimesSelecionados()
		escreverListaDeTimesEResponsabilidades()
		document.getElementById('divListaDeTimesSelecionados').classList.add('hidden')
		document.getElementById('divSegundoPasso').classList.add('hidden')
		document.getElementById('divBotaoFinalizar').classList.add('hidden')
		document.getElementById('divSelectTimesSelecionados').classList.remove('hidden')
		document.getElementById('divResponsabilidadesDisponiveis').classList.add('hidden')
		document.getElementById('botaoFinalizar').classList.remove('hidden')
		document.getElementById('divSenha').classList.add('hidden')
	}

	function validarSenha(){
	    const inputSenha = document.getElementById('senha')
	    const divMensagens = document.getElementById('divMensagens')
	    if (inputSenha.value.length === 0) {
	        divMensagens.innerHTML = 'Preencha a senha'
	        divMensagens.classList.remove('alert-success')
	        divMensagens.classList.remove('hidden')
	        divMensagens.classList.add('alert-danger')
	        return false;
	    } else {
			const url = '/validarSenha'
			fetch(
				url,
				{
					method: 'POST',	
					body: JSON.stringify({
						"senha": inputSenha.value,
					}),
				},
			)
			.then(resultado => {
				if(!resultado.ok){
					alert('erro ao validar')
				}
				return resultado.json()
			})
			.then(json => {
				if(json.response){
			        divMensagens.classList.add('hidden')
					mostrarSplash()
					const url = '/cadastroTrocarResponsabilidadesFinalizar'
					console.log(listaDeTimesEResponsabilidades);
					fetch(
						url,
						{
							method: 'POST',	
							body: JSON.stringify({
								listaDeTimesEResponsabilidades,
							}),
						},
					)
					.then(resultado => {
						console.log(resultado);
						if(!resultado.ok){
							alert('erro ao salvar')
						}
						return resultado.json()
					})
					.then(json => {
						console.log(json)
						if(json.solicitacoesPendentes){
							divMensagens.innerHTML = 'Alguma das pessoas envolvidas nessa troca possui solicitações pendentes. Por favor, clique em recomeçar.'
							divMensagens.classList.remove('alert-success')
							divMensagens.classList.remove('hidden')
							divMensagens.classList.add('alert-danger')
						}
						if(!json.solicitacoesPendentes){
							window.location.href = '/cadastroSolicitacoes';
						}
					})
				}else{
	        		divMensagens.innerHTML = 'Senha Invalida'
			        divMensagens.classList.remove('alert-success')
			        divMensagens.classList.remove('hidden')
			        divMensagens.classList.add('alert-danger')
				}	
			})
		}
	}

</script>
