<?php

use Login\Controller\Helper\Constantes;

/** Nome: acesso.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com>
 * Descricao: Página de acesso
 */
$formRecuperarAcesso = $this->formRecuperarAcesso;
$formRecuperarAcesso->prepare();
$formRecuperarAcesso->setAttribute('action', $this->url('login', array('action' => 'recuperarAcesso')));
?>

<?php echo $this->form()->openTag($formRecuperarAcesso); ?>
<div class="panel panel-default col-md-offset-4 col-md-4">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate(Constantes::$TRADUCAO_ESQUECEU_SENHA); ?></h3>
    </div>
    <div class="panel-body">
        <?php echo $this->formRadio($formRecuperarAcesso->get(Constantes::$INPUT_OPCAO)); ?>
    </div>
    <div class="panel-footer">
        <div class="row">
            <p>
                <?php echo $this->formButton($formRecuperarAcesso->get(Constantes::$INPUT_BOTAO_CANCELAR)); ?>
                <?php echo $this->formButton($formRecuperarAcesso->get(Constantes::$INPUT_BOTAO_CONTINUAR)); ?>
            </p>
        </div>
    </div>
</div>

<div class="panel panel-default col-md-offset-4 col-md-4">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate(Constantes::$TRADUCAO_ESQUECI_MINHA_SENHA); ?></h3>
    </div>
    <div class="panel-body">
        <!-- Mensagens -->
        <div id="divCapslock" class="alert alert-danger hidden">
            <?php echo $this->translate(Constantes::$TRADUCAO_CAPSLOCK); ?> 
        </div>
        <div class="row">
            <div class="col-lg-12">
                <?php echo $this->formInput($formRecuperarAcesso->get(Constantes::$INPUT_EMAIL)); ?>
            </div><!-- /.col-lg-12 -->
        </div><!-- /.row --> 
        <?php echo $this->formRow($formRecuperarAcesso->get(Constantes::$INPUT_CAPTCHA)); ?>
    </div>
    <div class="panel-footer">
        <div class="row">
            <p>
                <?php echo $this->formButton($formRecuperarAcesso->get(Constantes::$INPUT_BOTAO_CANCELAR)); ?>
                <?php echo $this->formSubmit($formRecuperarAcesso->get(Constantes::$INPUT_BOTAO_ENVIAR_EMAIL)); ?>
            </p>
        </div>
    </div>
</div>

<div class="panel panel-default col-md-offset-4 col-md-4">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate(Constantes::$TRADUCAO_ESQUECI_MEU_USUARIO); ?></h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12">
                <?php echo $this->formInput($formRecuperarAcesso->get(Constantes::$INPUT_CPF)); ?>
            </div><!-- /.col-lg-12 -->
        </div><!-- /.row --> 
        <div class="row">
            <div class="col-lg-12">
                <?php echo $this->formInput($formRecuperarAcesso->get(Constantes::$INPUT_DATA_NASCIMENTO)); ?>
            </div><!-- /.col-lg-12 -->
        </div><!-- /.row --> 
        <?php echo $this->formRow($formRecuperarAcesso->get(Constantes::$INPUT_CAPTCHA)); ?>
    </div>
    <div class="panel-footer">
        <div class="row">
            <p>
                <?php echo $this->formButton($formRecuperarAcesso->get(Constantes::$INPUT_BOTAO_CANCELAR)); ?>
                <?php echo $this->formSubmit($formRecuperarAcesso->get(Constantes::$INPUT_BOTAO_VERIFICAR_USUARIO)); ?>
            </p>
        </div>
    </div>
</div>
<?php
echo $this->form()->closeTag();
