<?php
$formLogin = $this->formLogin;
$formLogin->prepare();
$formLogin->setAttribute('action', $this->url('login', array('action' => 'logar')));
?>
<h1>CIRCUITO DA VISAO ZF2 COM DOCTRINE - <?php echo $this->translate('User') ?></h1>
<?php echo $this->form()->openTag($formLogin) ?>
<div class="panel panel-primary text-center" style="width: 500px;">
    <div class="panel-heading">
        <div class="panel-title">
            Login          
        </div>
    </div>
    <div class="panel-body">
        <div class="form-group">
            <div>
                <?php
                // renderiza html input
                echo $this->formInput($formLogin->get('email'));
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formLogin->get('email'));
                ?>
            </div>
        </div>
        <div class="form-group">
            <div>
                <?php
                // renderiza html input
                echo $this->formInput($formLogin->get('senha'));
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formLogin->get('senha'));
                ?>
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <button type="submit" class="btn btn-primary">Logar</button>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>