<?php

use Login\Controller\Helper\Constantes;

/** Nome: index.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com> e Sergio Bezerra da Silva <sergio.silva.unb@gmail.com>
 * Descricao: Página de login
 */
$formLogin = $this->formLogin;
$formLogin->prepare();
$formLogin->setAttribute('action', $this->url('login', array('action' => 'logar')));

$classMensagem = $this->hidden;
?> 
<!-- Start: Main -->
<div id="main" class="animated fadeIn">

    <!-- Start: Content-Wrapper -->
    <section id="content_wrapper">

        <!-- Begin: Content -->
        <section id="content">

            <div class="admin-form theme-info mw500" id="login">

                <!-- Login Logo -->
                <div class="row table-layout">
                    <a href="/" title="<?php echo $this->translate(Constantes::$TRADUCAO_NOME_APLICACAO); ?>">
                        <img src="<?php echo Constantes::$IMAGEM_LOGO; ?>" title="<?php echo $this->translate(Constantes::$TRADUCAO_NOME_APLICACAO); ?>" class="center-block img-responsive" style="max-width: 275px;">
                    </a>
                </div>

                <!-- Login Panel/Form -->
                <div class="panel mt30 mb25">
                    <?php echo $this->form()->openTag($formLogin); ?>

                    <div class="panel-body bg-light p25 pb15">

                        <div id="mensagem" class="alert alert-danger alert-dismissable <?php echo $classMensagem; ?>">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            <?php echo $this->translate(Constantes::$TRADUCAO_FALHA_LOGIN); ?>
                        </div>

                        <!-- Username Input -->
                        <div class="section">
                            <label for="<?php echo Constantes::$TRADUCAO_USUARIO; ?>" class="field-label text-muted fs18 mb10"><?php echo $this->translate(Constantes::$TRADUCAO_USUARIO); ?></label>
                            <label for="<?php echo Constantes::$TRADUCAO_USUARIO; ?>" class="field prepend-icon">
                                <?php echo $this->formInput($formLogin->get(Constantes::$INPUT_EMAIL)); ?>
                                <label for="<?php echo Constantes::$TRADUCAO_USUARIO; ?>" class="field-icon">
                                    <i class="fa fa-user"></i>
                                </label>
                            </label>
                        </div>

                        <!-- Password Input -->
                        <div class="section">
                            <label for="<?php echo Constantes::$TRADUCAO_SENHA; ?>" class="field-label text-muted fs18 mb10"><?php echo $this->translate(Constantes::$TRADUCAO_SENHA); ?></label>
                            <label for="<?php echo Constantes::$TRADUCAO_SENHA; ?>" class="field prepend-icon">
                                <?php echo $this->formInput($formLogin->get(Constantes::$INPUT_SENHA)); ?>
                                <label for="<?php echo Constantes::$TRADUCAO_SENHA; ?>" class="field-icon">
                                    <i class="fa fa-lock"></i>
                                </label>
                            </label>
                        </div>
                    </div>

                    <div class="panel-footer clearfix">
                        <?php echo $this->formHidden($formLogin->get('csrf')); ?>
                        <button type="submit" class="button btn-primary-circuito mr10 pull-right"><?php echo $this->translate(Constantes::$TRADUCAO_ENTRAR); ?></button>
                    </div>

                    <?php echo $this->form()->closeTag() ?>

                </div>

                <!-- Registration Links -->
                <div class="login-links">
                    <p>
                        <a href="/" class="active" ><?php echo $this->translate(Constantes::$TRADUCAO_ESQUECEU_SENHA); ?></a>
                    </p>
                </div>

            </div>

        </section>
        <!-- End: Content -->

    </section>
    <!-- End: Content-Wrapper -->

</div>
<!-- End: Main -->