<?php

use Login\Controller\Helper\Constantes;

/** Nome: recuperar-acesso.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com> e Sergio Bezerra da Silva <sergio.silva.unb@gmail.com>
 * Descricao: Página com email do usuário
 */
?>
<div class="admin-form theme-info mw500" style="margin-top: 10%;" id="login">
    <div class="row mb15 table-layout">
        <div class="col-xs-12 pln">
            <div class="col-xs-12 text-center">
                <span class="imoon imoon-checkbox-checked text-circuito-visao big-icone"></span>
            </div>
            <div class="alert alert-default mb30 text-center">
                <h3 class="mt5"><?php echo $this->resposta; ?></h3>
            </div>
        </div>      
    </div>   
    <div class="col-xs-12 text-center">
        <a href="<?php echo Constantes::$INDEX ?>" class="button btn-primary-circuito mr10"><?php echo $this->translate(Constantes::$TRADUCAO_VOLTAR); ?></a>
    </div>
</div>  
<?php
/* Layout com javascript para telas de recuperação de acessos */
echo $this->layoutJSRecuperarAcesso;

