<?php
/** Nome: selecionar-perfil.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com>
 * Descricao: Página para selecionar perfil
 */
?>
<div class="row mb10 mt70 table-layout">
    <?php
    /* Laço para mostrar as responsabilidades ativas */
    foreach ($this->responsabilidades as $responsabilidade) {
        /* Grupo da responsabilidades */
        $grupo = $responsabilidade->getGrupo();
        /* Entidades do grupo */
        $entidades = $grupo->getEntidade();
        foreach ($entidades as $entidade) {
            if ($entidade->verificarSeEstaAtivo()) {
                echo $this->perfilIcone($entidade);

                echo $this->perfilDropDown($entidade, 2);
            }
        }
    }
    ?>
</div>