<?php

use Login\Controller\Helper\Constantes;

/** Nome: selecionar-perfil.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com>
 * Descricao: Página para selecionar perfil
 */
?>
<!-- Start: Main -->
<div id="main" class="animated fadeIn">
    <!-- Start: Header -->
    <header class="navbar-fixed-top" style="background:transparent; padding-left:20px; padding-top:25px;">
        <a href="<?php echo Constantes::$INDEX; ?>">
            <img src="<?php echo Constantes::$IMAGEM_LOGO_PEQUENA; ?>" title="<?php echo $this->translate(Constantes::$TRADUCAO_NOME_APLICACAO) ?>" class="img-responsive" style="max-width: 275px;">
        </a>
    </header>
    <!-- End: Header -->
    <!-- Start: Content-Wrapper -->
    <section id="content_wrapper">
        <h1 class="mtn mt70" style="text-align: center;"><?php echo $this->translate(Constantes::$TRADUCAO_QUAL_PERFIL); ?>
            <br>
            <small><?php echo $this->translate(Constantes::$TRADUCAO_SELECIONE_PERFIL); ?></small>
        </h1>

        <!-- Begin: Content -->
        <section id="content" class="table-layout animated fadeIn">

            <!-- begin: .tray-left -->
            <!-- end: .tray-left -->
            <div class="tray tray-center">
                <div class="row mb10">
                    <?php
                    /* Laço para mostrar as responsabilidades ativas */
                    foreach ($this->responsabilidades as $responsabilidade) {
                        /* Grupo da responsabilidades */
                        $grupo = $responsabilidade->getGrupo();
                        /* Entidades do grupo */
                        $entidades = $grupo->getEntidade();
                        foreach ($entidades as $entidade) {
                            if ($entidade->verificarSeEstaAtivo()) {
                                echo $this->perfilIcone($entidade, count($this->responsabilidades));
                            }
                        }
                    }
                    ?>
                </div>
            </div>
        </section>
        <!-- End: Content -->
    </section>
    <!-- End: Content-Wrapper -->
</div>
<!-- End: Main -->