<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Model\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pessoa extends \Application\Model\Entity\Pessoa implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'inputFilter', 'inputFilterPessoaFrequencia', 'grupoResponsavel', 'turmaAluno', 'eventoFrequencia', 'grupoPessoa', 'pessoaHierarquia', 'nome', 'telefone', 'email', 'senha', 'data_nascimento', 'documento', 'token', 'token_data', 'token_hora', 'data_revisao', 'foto', 'sexo', 'atualizar_dados', 'tipo', 'transferido', 'dataTransferido', 'dataInativacao', 'idGrupoPessoa', 'ativo', 'matriculaAtual', 'id', 'data_criacao', 'hora_criacao', 'data_inativacao', 'hora_inativacao');
        }

        return array('__isInitialized__', 'inputFilter', 'inputFilterPessoaFrequencia', 'grupoResponsavel', 'turmaAluno', 'eventoFrequencia', 'grupoPessoa', 'pessoaHierarquia', 'nome', 'telefone', 'email', 'senha', 'data_nascimento', 'documento', 'token', 'token_data', 'token_hora', 'data_revisao', 'foto', 'sexo', 'atualizar_dados', 'tipo', 'transferido', 'dataTransferido', 'dataInativacao', 'idGrupoPessoa', 'ativo', 'matriculaAtual', 'id', 'data_criacao', 'hora_criacao', 'data_inativacao', 'hora_inativacao');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pessoa $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function exchangeArray($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'exchangeArray', array($data));

        return parent::exchangeArray($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsabilidadesAtivas($todasResposabilidades = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsabilidadesAtivas', array($todasResposabilidades));

        return parent::getResponsabilidadesAtivas($todasResposabilidades);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomePrimeiroUltimo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomePrimeiroUltimo', array());

        return parent::getNomePrimeiroUltimo();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomePrimeiro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomePrimeiro', array());

        return parent::getNomePrimeiro();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomePrimeiroPrimeiraSiglaUltimo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomePrimeiroPrimeiraSiglaUltimo', array());

        return parent::getNomePrimeiroPrimeiraSiglaUltimo();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeListaDeLancamento($tipo = 0)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeListaDeLancamento', array($tipo));

        return parent::getNomeListaDeLancamento($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventoFrequenciasFiltradosPorEventoEDia($idEvento, $dia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventoFrequenciasFiltradosPorEventoEDia', array($idEvento, $dia));

        return parent::getEventoFrequenciasFiltradosPorEventoEDia($idEvento, $dia);
    }

    /**
     * {@inheritDoc}
     */
    public function verificarSeFoiTransferido($mes, $ano, $tipo = 0)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'verificarSeFoiTransferido', array($mes, $ano, $tipo));

        return parent::verificarSeFoiTransferido($mes, $ano, $tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function verificarSeTemAlgumaResponsabilidadeInativadoNaDataInformado($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'verificarSeTemAlgumaResponsabilidadeInativadoNaDataInformado', array($data));

        return parent::verificarSeTemAlgumaResponsabilidadeInativadoNaDataInformado($data);
    }

    /**
     * {@inheritDoc}
     */
    public function verificarSeTemAlgumaResponsabilidadeAtiva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'verificarSeTemAlgumaResponsabilidadeAtiva', array());

        return parent::verificarSeTemAlgumaResponsabilidadeAtiva();
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenha', array());

        return parent::getSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_nascimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_nascimento', array());

        return parent::getData_nascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_nascimentoFormatada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_nascimentoFormatada', array());

        return parent::getData_nascimentoFormatada();
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumento', array());

        return parent::getDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setSenha($senha, $adicionarMD5 = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenha', array($senha, $adicionarMD5));

        return parent::setSenha($senha, $adicionarMD5);
    }

    /**
     * {@inheritDoc}
     */
    public function setData_nascimento($data_nascimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData_nascimento', array($data_nascimento));

        return parent::setData_nascimento($data_nascimento);
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumento($documento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumento', array($documento));

        return parent::setDocumento($documento);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken', array());

        return parent::getToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken($token)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken', array($token));

        return parent::setToken($token);
    }

    /**
     * {@inheritDoc}
     */
    public function gerarToken($tipo = 0)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'gerarToken', array($tipo));

        return parent::gerarToken($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken_data()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken_data', array());

        return parent::getToken_data();
    }

    /**
     * {@inheritDoc}
     */
    public function getToken_data_ano()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken_data_ano', array());

        return parent::getToken_data_ano();
    }

    /**
     * {@inheritDoc}
     */
    public function getToken_data_mes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken_data_mes', array());

        return parent::getToken_data_mes();
    }

    /**
     * {@inheritDoc}
     */
    public function getToken_data_dia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken_data_dia', array());

        return parent::getToken_data_dia();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken_data($token_data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken_data', array($token_data));

        return parent::setToken_data($token_data);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken_hora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken_hora', array());

        return parent::getToken_hora();
    }

    /**
     * {@inheritDoc}
     */
    public function getToken_hora_hora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken_hora_hora', array());

        return parent::getToken_hora_hora();
    }

    /**
     * {@inheritDoc}
     */
    public function getToken_hora_minutos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken_hora_minutos', array());

        return parent::getToken_hora_minutos();
    }

    /**
     * {@inheritDoc}
     */
    public function getToken_hora_segundos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken_hora_segundos', array());

        return parent::getToken_hora_segundos();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken_hora($token_hora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken_hora', array($token_hora));

        return parent::setToken_hora($token_hora);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoResponsavel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoResponsavel', array());

        return parent::getGrupoResponsavel();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupoResponsavel($grupoResponsavel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupoResponsavel', array($grupoResponsavel));

        return parent::setGrupoResponsavel($grupoResponsavel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefone', array());

        return parent::getTelefone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefone($telefone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefone', array($telefone));

        return parent::setTelefone($telefone);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventoFrequencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventoFrequencia', array());

        return parent::getEventoFrequencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventoFrequencia($eventoFrequencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventoFrequencia', array($eventoFrequencia));

        return parent::setEventoFrequencia($eventoFrequencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', array());

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', array($tipo));

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFoto', array());

        return parent::getFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFoto($foto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFoto', array($foto));

        return parent::setFoto($foto);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransferido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransferido', array());

        return parent::getTransferido();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransferido($transferido, $dataTransferencia, $dataInativacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransferido', array($transferido, $dataTransferencia, $dataInativacao));

        return parent::setTransferido($transferido, $dataTransferencia, $dataInativacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataTransferido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataTransferido', array());

        return parent::getDataTransferido();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataTransferido($dataTransferido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataTransferido', array($dataTransferido));

        return parent::setDataTransferido($dataTransferido);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataTransferidoAno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataTransferidoAno', array());

        return parent::getDataTransferidoAno();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataTransferidoMes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataTransferidoMes', array());

        return parent::getDataTransferidoMes();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataTransferidoDia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataTransferidoDia', array());

        return parent::getDataTransferidoDia();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdGrupoPessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdGrupoPessoa', array());

        return parent::getIdGrupoPessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdGrupoPessoa($idGrupoPessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdGrupoPessoa', array($idGrupoPessoa));

        return parent::setIdGrupoPessoa($idGrupoPessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtivo', array());

        return parent::getAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtivo($ativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtivo', array($ativo));

        return parent::setAtivo($ativo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataInativacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataInativacao', array());

        return parent::getDataInativacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataInativacao($dataInativacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataInativacao', array($dataInativacao));

        return parent::setDataInativacao($dataInativacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getData_revisao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_revisao', array());

        return parent::getData_revisao();
    }

    /**
     * {@inheritDoc}
     */
    public function setData_revisao($data_revisao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData_revisao', array($data_revisao));

        return parent::setData_revisao($data_revisao);
    }

    /**
     * {@inheritDoc}
     */
    public function getTurmaAluno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTurmaAluno', array());

        return parent::getTurmaAluno();
    }

    /**
     * {@inheritDoc}
     */
    public function getTurmaAlunoAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTurmaAlunoAtivo', array());

        return parent::getTurmaAlunoAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getPessoaHierarquiaAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPessoaHierarquiaAtivo', array());

        return parent::getPessoaHierarquiaAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoPessoaAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoPessoaAtivo', array());

        return parent::getGrupoPessoaAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTurmaAluno($turmaAluno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTurmaAluno', array($turmaAluno));

        return parent::setTurmaAluno($turmaAluno);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoPessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoPessoa', array());

        return parent::getGrupoPessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupoPessoa($grupoPessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupoPessoa', array($grupoPessoa));

        return parent::setGrupoPessoa($grupoPessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdade', array());

        return parent::getIdade();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataNascimentoFormatada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataNascimentoFormatada', array());

        return parent::getDataNascimentoFormatada();
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', array());

        return parent::getInputFilter();
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilterPessoaFrequencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilterPessoaFrequencia', array());

        return parent::getInputFilterPessoaFrequencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', array($inputFilter));

        return parent::setInputFilter($inputFilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getPessoaHierarquia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPessoaHierarquia', array());

        return parent::getPessoaHierarquia();
    }

    /**
     * {@inheritDoc}
     */
    public function setPessoaHierarquia($pessoaHierarquia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPessoaHierarquia', array($pessoaHierarquia));

        return parent::setPessoaHierarquia($pessoaHierarquia);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', array());

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexo($sexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexo', array($sexo));

        return parent::setSexo($sexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatriculaAtual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatriculaAtual', array());

        return parent::getMatriculaAtual();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatriculaAtual($matriculaAtual)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatriculaAtual', array($matriculaAtual));

        return parent::setMatriculaAtual($matriculaAtual);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtualizar_dados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtualizar_dados', array());

        return parent::getAtualizar_dados();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtualizar_dados($atualizar_dados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtualizar_dados', array($atualizar_dados));

        return parent::setAtualizar_dados($atualizar_dados);
    }

    /**
     * {@inheritDoc}
     */
    public function dadosAtualizados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'dadosAtualizados', array());

        return parent::dadosAtualizados();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataEHoraDeCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataEHoraDeCriacao', array());

        return parent::setDataEHoraDeCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataEHoraDeInativacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataEHoraDeInativacao', array());

        return parent::setDataEHoraDeInativacao();
    }

    /**
     * {@inheritDoc}
     */
    public function verificarSeEstaAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'verificarSeEstaAtivo', array());

        return parent::verificarSeEstaAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacao', array());

        return parent::getData_criacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getHora_criacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHora_criacao', array());

        return parent::getHora_criacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_inativacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_inativacao', array());

        return parent::getData_inativacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getHora_inativacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHora_inativacao', array());

        return parent::getHora_inativacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setData_criacao($data_criacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData_criacao', array($data_criacao));

        return parent::setData_criacao($data_criacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setHora_criacao($hora_criacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHora_criacao', array($hora_criacao));

        return parent::setHora_criacao($hora_criacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setData_inativacao($data_inativacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData_inativacao', array($data_inativacao));

        return parent::setData_inativacao($data_inativacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setHora_inativacao($hora_inativacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHora_inativacao', array($hora_inativacao));

        return parent::setHora_inativacao($hora_inativacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoAno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoAno', array());

        return parent::getData_criacaoAno();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoMes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoMes', array());

        return parent::getData_criacaoMes();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoDia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoDia', array());

        return parent::getData_criacaoDia();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_inativacaoAno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_inativacaoAno', array());

        return parent::getData_inativacaoAno();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_inativacaoMes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_inativacaoMes', array());

        return parent::getData_inativacaoMes();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_inativacaoDia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_inativacaoDia', array());

        return parent::getData_inativacaoDia();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoStringPadraoBrasil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoStringPadraoBrasil', array());

        return parent::getData_criacaoStringPadraoBrasil();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoStringPadraoBanco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoStringPadraoBanco', array());

        return parent::getData_criacaoStringPadraoBanco();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_inativacaoStringPadraoBanco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_inativacaoStringPadraoBanco', array());

        return parent::getData_inativacaoStringPadraoBanco();
    }

}
