<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Model\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evento extends \Application\Model\Entity\Evento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'inputFilter', 'idAntigo', '' . "\0" . 'Application\\Model\\Entity\\Evento' . "\0" . 'eventoCelula', 'grupoEvento', 'eventoFrequencia', '' . "\0" . 'Application\\Model\\Entity\\Evento' . "\0" . 'eventoTipo', 'dia', 'nome', 'hora', 'data', 'tipo_id', 'id', 'data_criacao', 'hora_criacao', 'data_inativacao', 'hora_inativacao');
        }

        return array('__isInitialized__', 'inputFilter', 'idAntigo', '' . "\0" . 'Application\\Model\\Entity\\Evento' . "\0" . 'eventoCelula', 'grupoEvento', 'eventoFrequencia', '' . "\0" . 'Application\\Model\\Entity\\Evento' . "\0" . 'eventoTipo', 'dia', 'nome', 'hora', 'data', 'tipo_id', 'id', 'data_criacao', 'hora_criacao', 'data_inativacao', 'hora_inativacao');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Evento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getEventoTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventoTipo', array());

        return parent::getEventoTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function getDia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDia', array());

        return parent::getDia();
    }

    /**
     * {@inheritDoc}
     */
    public function getDiaAjustado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiaAjustado', array());

        return parent::getDiaAjustado();
    }

    /**
     * {@inheritDoc}
     */
    public function getHora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHora', array());

        return parent::getHora();
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraSemMinutosESegundos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraSemMinutosESegundos', array());

        return parent::getHoraSemMinutosESegundos();
    }

    /**
     * {@inheritDoc}
     */
    public function getMinutosSemHorasESegundos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinutosSemHorasESegundos', array());

        return parent::getMinutosSemHorasESegundos();
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraFormatoHoraMinuto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraFormatoHoraMinuto', array());

        return parent::getHoraFormatoHoraMinuto();
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraFormatoHoraMinutoParaListagem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraFormatoHoraMinutoParaListagem', array());

        return parent::getHoraFormatoHoraMinutoParaListagem();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventoTipo($eventoTipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventoTipo', array($eventoTipo));

        return parent::setEventoTipo($eventoTipo);
    }

    /**
     * {@inheritDoc}
     */
    public function setDia($dia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDia', array($dia));

        return parent::setDia($dia);
    }

    /**
     * {@inheritDoc}
     */
    public function setHora($hora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHora', array($hora));

        return parent::setHora($hora);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoEvento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoEvento', array());

        return parent::getGrupoEvento();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoEventoAtivos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoEventoAtivos', array());

        return parent::getGrupoEventoAtivos();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupoEvento($grupoEvento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupoEvento', array($grupoEvento));

        return parent::setGrupoEvento($grupoEvento);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventoCelula()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventoCelula', array());

        return parent::getEventoCelula();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventoCelula($eventoCelula)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventoCelula', array($eventoCelula));

        return parent::setEventoCelula($eventoCelula);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventoFrequencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventoFrequencia', array());

        return parent::getEventoFrequencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventoFrequencia($eventoFrequencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventoFrequencia', array($eventoFrequencia));

        return parent::setEventoFrequencia($eventoFrequencia);
    }

    /**
     * {@inheritDoc}
     */
    public function verificaSeECelula()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'verificaSeECelula', array());

        return parent::verificaSeECelula();
    }

    /**
     * {@inheritDoc}
     */
    public function verificaSeECulto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'verificaSeECulto', array());

        return parent::verificaSeECulto();
    }

    /**
     * {@inheritDoc}
     */
    public function verificaSeERevisao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'verificaSeERevisao', array());

        return parent::verificaSeERevisao();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo_id()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo_id', array());

        return parent::getTipo_id();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo_id($tipo_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo_id', array($tipo_id));

        return parent::setTipo_id($tipo_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', array());

        return parent::getInputFilter();
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', array($inputFilter));

        return parent::setInputFilter($inputFilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeAjustado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeAjustado', array());

        return parent::getNomeAjustado();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function exchangeArray($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'exchangeArray', array($data));

        return parent::exchangeArray($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAntigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAntigo', array());

        return parent::getIdAntigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAntigo($idAntigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAntigo', array($idAntigo));

        return parent::setIdAntigo($idAntigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', array());

        return parent::getData();
    }

    /**
     * {@inheritDoc}
     */
    public function setData($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', array($data));

        return parent::setData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataEHoraDeCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataEHoraDeCriacao', array());

        return parent::setDataEHoraDeCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataEHoraDeInativacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataEHoraDeInativacao', array());

        return parent::setDataEHoraDeInativacao();
    }

    /**
     * {@inheritDoc}
     */
    public function verificarSeEstaAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'verificarSeEstaAtivo', array());

        return parent::verificarSeEstaAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacao', array());

        return parent::getData_criacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getHora_criacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHora_criacao', array());

        return parent::getHora_criacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_inativacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_inativacao', array());

        return parent::getData_inativacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getHora_inativacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHora_inativacao', array());

        return parent::getHora_inativacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setData_criacao($data_criacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData_criacao', array($data_criacao));

        return parent::setData_criacao($data_criacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setHora_criacao($hora_criacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHora_criacao', array($hora_criacao));

        return parent::setHora_criacao($hora_criacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setData_inativacao($data_inativacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData_inativacao', array($data_inativacao));

        return parent::setData_inativacao($data_inativacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setHora_inativacao($hora_inativacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHora_inativacao', array($hora_inativacao));

        return parent::setHora_inativacao($hora_inativacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoAno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoAno', array());

        return parent::getData_criacaoAno();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoMes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoMes', array());

        return parent::getData_criacaoMes();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoDia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoDia', array());

        return parent::getData_criacaoDia();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_inativacaoAno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_inativacaoAno', array());

        return parent::getData_inativacaoAno();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_inativacaoMes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_inativacaoMes', array());

        return parent::getData_inativacaoMes();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_inativacaoDia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_inativacaoDia', array());

        return parent::getData_inativacaoDia();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoStringPadraoBrasil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoStringPadraoBrasil', array());

        return parent::getData_criacaoStringPadraoBrasil();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoStringPadraoBanco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoStringPadraoBanco', array());

        return parent::getData_criacaoStringPadraoBanco();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_inativacaoStringPadraoBanco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_inativacaoStringPadraoBanco', array());

        return parent::getData_inativacaoStringPadraoBanco();
    }

}
