<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Model\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Grupo extends \Application\Model\Entity\Grupo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'ciclo', 'eventos', '' . "\0" . 'Application\\Model\\Entity\\Grupo' . "\0" . 'grupoCv', 'entidade', 'grupoResponsavel', 'grupoAluno', 'grupoEvento', 'grupoPessoa', 'grupoAtendimento', 'grupoPaiFilhoFilhos', 'grupoPaiFilhoPai', 'id', 'data_criacao', 'hora_criacao', 'data_inativacao', 'hora_inativacao');
        }

        return array('__isInitialized__', 'ciclo', 'eventos', '' . "\0" . 'Application\\Model\\Entity\\Grupo' . "\0" . 'grupoCv', 'entidade', 'grupoResponsavel', 'grupoAluno', 'grupoEvento', 'grupoPessoa', 'grupoAtendimento', 'grupoPaiFilhoFilhos', 'grupoPaiFilhoPai', 'id', 'data_criacao', 'hora_criacao', 'data_inativacao', 'hora_inativacao');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Grupo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getEntidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntidade', array());

        return parent::getEntidade();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntidadeAtiva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntidadeAtiva', array());

        return parent::getEntidadeAtiva();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoResponsavel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoResponsavel', array());

        return parent::getGrupoResponsavel();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoResponsavelAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoResponsavelAtivo', array());

        return parent::getGrupoResponsavelAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsabilidadesAtivas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsabilidadesAtivas', array());

        return parent::getResponsabilidadesAtivas();
    }

    /**
     * {@inheritDoc}
     */
    public function totalDeAtendimentos($mes, $ano)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'totalDeAtendimentos', array($mes, $ano));

        return parent::totalDeAtendimentos($mes, $ano);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoPaiFilhoFilhosAtivos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoPaiFilhoFilhosAtivos', array());

        return parent::getGrupoPaiFilhoFilhosAtivos();
    }

    /**
     * {@inheritDoc}
     */
    public function getPessoasAtivas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPessoasAtivas', array());

        return parent::getPessoasAtivas();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeLideresAtivos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeLideresAtivos', array());

        return parent::getNomeLideresAtivos();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntidade($entidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntidade', array($entidade));

        return parent::setEntidade($entidade);
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupoResponsavel($grupoResponsavel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupoResponsavel', array($grupoResponsavel));

        return parent::setGrupoResponsavel($grupoResponsavel);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoEvento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoEvento', array());

        return parent::getGrupoEvento();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoEventoOrdenadosPorDiaDaSemana()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoEventoOrdenadosPorDiaDaSemana', array());

        return parent::getGrupoEventoOrdenadosPorDiaDaSemana();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoEventoRevisao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoEventoRevisao', array());

        return parent::getGrupoEventoRevisao();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoIgreja()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoIgreja', array());

        return parent::getGrupoIgreja();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoEquipe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoEquipe', array());

        return parent::getGrupoEquipe();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoEventoAtivos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoEventoAtivos', array());

        return parent::getGrupoEventoAtivos();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoEventoAtivosPorTipo($tipo = 0)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoEventoAtivosPorTipo', array($tipo));

        return parent::getGrupoEventoAtivosPorTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoAlunoAtivos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoAlunoAtivos', array());

        return parent::getGrupoAlunoAtivos();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoAlunoAtivosSemCadastro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoAlunoAtivosSemCadastro', array());

        return parent::getGrupoAlunoAtivosSemCadastro();
    }

    /**
     * {@inheritDoc}
     */
    public function verificaSeParticipaDoEvento($idEvento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'verificaSeParticipaDoEvento', array($idEvento));

        return parent::verificaSeParticipaDoEvento($idEvento);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoEventoNoPeriodo($periodo, $apenasCelulas = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoEventoNoPeriodo', array($periodo, $apenasCelulas));

        return parent::getGrupoEventoNoPeriodo($periodo, $apenasCelulas);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoPessoasNoPeriodo($periodo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoPessoasNoPeriodo', array($periodo));

        return parent::getGrupoPessoasNoPeriodo($periodo);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoEventoNoCiclo($ciclo = 1, $mes = 5, $ano = 2016)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoEventoNoCiclo', array($ciclo, $mes, $ano));

        return parent::getGrupoEventoNoCiclo($ciclo, $mes, $ano);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoEventoCelula()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoEventoCelula', array());

        return parent::getGrupoEventoCelula();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoEventoCulto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoEventoCulto', array());

        return parent::getGrupoEventoCulto();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupoEvento($grupoEvento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupoEvento', array($grupoEvento));

        return parent::setGrupoEvento($grupoEvento);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoPessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoPessoa', array());

        return parent::getGrupoPessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoPessoaAtivasEDoMes($mes, $ano, $ciclo = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoPessoaAtivasEDoMes', array($mes, $ano, $ciclo));

        return parent::getGrupoPessoaAtivasEDoMes($mes, $ano, $ciclo);
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupoPessoa($grupoPessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupoPessoa', array($grupoPessoa));

        return parent::setGrupoPessoa($grupoPessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getCiclo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiclo', array());

        return parent::getCiclo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCiclo($ciclo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCiclo', array($ciclo));

        return parent::setCiclo($ciclo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventos', array());

        return parent::getEventos();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventos($eventos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventos', array($eventos));

        return parent::setEventos($eventos);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoPaiFilhoFilhos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoPaiFilhoFilhos', array());

        return parent::getGrupoPaiFilhoFilhos();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupoPaiFilhoFilhos($grupoPaiFilhoFilhos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupoPaiFilhoFilhos', array($grupoPaiFilhoFilhos));

        return parent::setGrupoPaiFilhoFilhos($grupoPaiFilhoFilhos);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoPaiFilhoPai()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoPaiFilhoPai', array());

        return parent::getGrupoPaiFilhoPai();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupoPaiFilhoPai($grupoPaiFilhoPai)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupoPaiFilhoPai', array($grupoPaiFilhoPai));

        return parent::setGrupoPaiFilhoPai($grupoPaiFilhoPai);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoAluno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoAluno', array());

        return parent::getGrupoAluno();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupoAluno($grupoAluno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupoAluno', array($grupoAluno));

        return parent::setGrupoAluno($grupoAluno);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoAtendimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoAtendimento', array());

        return parent::getGrupoAtendimento();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupoAtendimento($grupoAtendimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupoAtendimento', array($grupoAtendimento));

        return parent::setGrupoAtendimento($grupoAtendimento);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoCv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoCv', array());

        return parent::getGrupoCv();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupoCv($grupoCv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupoCv', array($grupoCv));

        return parent::setGrupoCv($grupoCv);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataEHoraDeCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataEHoraDeCriacao', array());

        return parent::setDataEHoraDeCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataEHoraDeInativacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataEHoraDeInativacao', array());

        return parent::setDataEHoraDeInativacao();
    }

    /**
     * {@inheritDoc}
     */
    public function verificarSeEstaAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'verificarSeEstaAtivo', array());

        return parent::verificarSeEstaAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacao', array());

        return parent::getData_criacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getHora_criacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHora_criacao', array());

        return parent::getHora_criacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_inativacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_inativacao', array());

        return parent::getData_inativacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getHora_inativacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHora_inativacao', array());

        return parent::getHora_inativacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setData_criacao($data_criacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData_criacao', array($data_criacao));

        return parent::setData_criacao($data_criacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setHora_criacao($hora_criacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHora_criacao', array($hora_criacao));

        return parent::setHora_criacao($hora_criacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setData_inativacao($data_inativacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData_inativacao', array($data_inativacao));

        return parent::setData_inativacao($data_inativacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setHora_inativacao($hora_inativacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHora_inativacao', array($hora_inativacao));

        return parent::setHora_inativacao($hora_inativacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoAno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoAno', array());

        return parent::getData_criacaoAno();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoMes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoMes', array());

        return parent::getData_criacaoMes();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoDia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoDia', array());

        return parent::getData_criacaoDia();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_inativacaoAno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_inativacaoAno', array());

        return parent::getData_inativacaoAno();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_inativacaoMes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_inativacaoMes', array());

        return parent::getData_inativacaoMes();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_inativacaoDia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_inativacaoDia', array());

        return parent::getData_inativacaoDia();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoStringPadraoBrasil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoStringPadraoBrasil', array());

        return parent::getData_criacaoStringPadraoBrasil();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoStringPadraoBanco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoStringPadraoBanco', array());

        return parent::getData_criacaoStringPadraoBanco();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_inativacaoStringPadraoBanco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_inativacaoStringPadraoBanco', array());

        return parent::getData_inativacaoStringPadraoBanco();
    }

}
