<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Model\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FatoCiclo extends \Application\Model\Entity\FatoCiclo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'dimensao', 'fatoCelula', 'numero_identificador', 'id', 'data_criacao', 'hora_criacao', 'data_inativacao', 'hora_inativacao');
        }

        return array('__isInitialized__', 'dimensao', 'fatoCelula', 'numero_identificador', 'id', 'data_criacao', 'hora_criacao', 'data_inativacao', 'hora_inativacao');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FatoCiclo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNumero_identificador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero_identificador', array());

        return parent::getNumero_identificador();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero_identificador($numero_identificador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero_identificador', array($numero_identificador));

        return parent::setNumero_identificador($numero_identificador);
    }

    /**
     * {@inheritDoc}
     */
    public function getDimensao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDimensao', array());

        return parent::getDimensao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDimensao($dimensao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDimensao', array($dimensao));

        return parent::setDimensao($dimensao);
    }

    /**
     * {@inheritDoc}
     */
    public function getFatoCelula()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFatoCelula', array());

        return parent::getFatoCelula();
    }

    /**
     * {@inheritDoc}
     */
    public function setFatoCelula($fatoCelula)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFatoCelula', array($fatoCelula));

        return parent::setFatoCelula($fatoCelula);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataEHoraDeCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataEHoraDeCriacao', array());

        return parent::setDataEHoraDeCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataEHoraDeInativacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataEHoraDeInativacao', array());

        return parent::setDataEHoraDeInativacao();
    }

    /**
     * {@inheritDoc}
     */
    public function verificarSeEstaAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'verificarSeEstaAtivo', array());

        return parent::verificarSeEstaAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacao', array());

        return parent::getData_criacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getHora_criacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHora_criacao', array());

        return parent::getHora_criacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_inativacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_inativacao', array());

        return parent::getData_inativacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getHora_inativacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHora_inativacao', array());

        return parent::getHora_inativacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setData_criacao($data_criacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData_criacao', array($data_criacao));

        return parent::setData_criacao($data_criacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setHora_criacao($hora_criacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHora_criacao', array($hora_criacao));

        return parent::setHora_criacao($hora_criacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setData_inativacao($data_inativacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData_inativacao', array($data_inativacao));

        return parent::setData_inativacao($data_inativacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setHora_inativacao($hora_inativacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHora_inativacao', array($hora_inativacao));

        return parent::setHora_inativacao($hora_inativacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoAno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoAno', array());

        return parent::getData_criacaoAno();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoMes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoMes', array());

        return parent::getData_criacaoMes();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoDia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoDia', array());

        return parent::getData_criacaoDia();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_inativacaoAno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_inativacaoAno', array());

        return parent::getData_inativacaoAno();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_inativacaoMes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_inativacaoMes', array());

        return parent::getData_inativacaoMes();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_inativacaoDia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_inativacaoDia', array());

        return parent::getData_inativacaoDia();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoStringPadraoBrasil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoStringPadraoBrasil', array());

        return parent::getData_criacaoStringPadraoBrasil();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoStringPadraoBanco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoStringPadraoBanco', array());

        return parent::getData_criacaoStringPadraoBanco();
    }

}
