<?php

$versao = '?v=06';

echo $this
        ->headScript()
        ->prependFile($this->basePath() . '/js/circuito_da_visao/mudar-frequencia.js' . $versao)
        ->prependFile($this->basePath() . '/js/circuito_da_visao/modal-selecionar-aba.js' . $versao)
        ->prependFile($this->basePath() . '/js/circuito_da_visao/ajustar-tabela-lancamento.js' . $versao)
;
echo $this->inlineScript();
?>