<?php

use Lancamento\Controller\Helper\ConstantesLancamento;
?>
<script type="text/javascript">
    window.onload = initPage;
    /**
     * Nome: validar-formulario-cadastrar-pessoa-lancamento.js
     * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com> & Sergio Bezerra da Silva <sergio.silva.unb@gmail.com>
     * Descricao: Função para validar os campos do formulário de cadastro de pessoas na linha de lançamento
     */
    function initPage() {

        $("#CadastrarPessoaForm").validate({
            /* @validation states + elements 
             ------------------------------------------- */

            errorClass: "state-error",
            validClass: "state-success",
            errorElement: "em",
            /* @validation rules 
             ------------------------------------------ */

            rules: {
                nome: {
                    required: true,
                    minlength: 3,
                    maxlength: 80
                },
                ddd: {
                    required: true,
                    minlength: 2,
                    maxlength: 2,
                    number: true
                },
                telefone: {
                    required: true,
                    minlength: 8,
                    maxlength: 9,
                    number: true
                },
                tipo: {
                    required: true
                }
            },
            /* @validation error messages 
             ---------------------------------------------- */

            messages: {
                nome: {
                    required: '<?php echo $this->translate(ConstantesLancamento::$TRADUCAO_VALIDACAO_NOME_VAZIO); ?>',
                    minlength: '<?php echo $this->translate(ConstantesLancamento::$TRADUCAO_VALIDACAO_NOME_MIN); ?>',
                    maxlength: '<?php echo $this->translate(ConstantesLancamento::$TRADUCAO_VALIDACAO_NOME_MAX); ?>'
                },
                ddd: {
                    required: '<?php echo $this->translate(ConstantesLancamento::$TRADUCAO_VALIDACAO_DDD_VAZIO); ?>',
                    number: '<?php echo $this->translate(ConstantesLancamento::$TRADUCAO_VALIDACAO_DDD_NUMERO); ?>',
                    minlength: '<?php echo $this->translate(ConstantesLancamento::$TRADUCAO_VALIDACAO_DDD_MIN); ?>',
                    maxlength: '<?php echo $this->translate(ConstantesLancamento::$TRADUCAO_VALIDACAO_DDD_MAX); ?>'
                },
                telefone: {
                    required: '<?php echo $this->translate(ConstantesLancamento::$TRADUCAO_VALIDACAO_TELEFONE_VAZIO); ?>',
                    number: '<?php echo $this->translate(ConstantesLancamento::$TRADUCAO_VALIDACAO_TELEFONE_NUMERO); ?>',
                    minlength: '<?php echo $this->translate(ConstantesLancamento::$TRADUCAO_VALIDACAO_TELEFONE_MIN); ?>',
                    maxlength: '<?php echo $this->translate(ConstantesLancamento::$TRADUCAO_VALIDACAO_TELEFONE_MAX); ?>'
                },
                tipo: {
                    required: '<?php echo $this->translate(ConstantesLancamento::$TRADUCAO_VALIDACAO_TIPO_VAZIO); ?>'
                }
            },
            /* @validation highlighting + error placement  
             ---------------------------------------------------- */

            highlight: function (element, errorClass, validClass) {
                $(element).closest('.field').addClass(errorClass).removeClass(validClass);
            },
            unhighlight: function (element, errorClass, validClass) {
                $(element).closest('.field').removeClass(errorClass).addClass(validClass);
            },
            errorPlacement: function (error, element) {
                if (element.is(":radio") || element.is(":checkbox")) {
                    element.closest('.option-group').after(error);
                } else {
                    error.insertAfter(element.parent());
                }
            }

        });
    }
    ;
</script>
