<?php

$versao = '?v=1.3';

echo $this
        ->headScript()
        ->prependFile($this->basePath() . '/js/circuito_da_visao/funcao-pessoa-lancamento.js' . $versao)
        ->prependFile($this->basePath() . '/js/circuito_da_visao/alterar-nome.js' . $versao)
        ->prependFile($this->basePath() . '/js/circuito_da_visao/mudar-frequencia.js' . $versao)
        ->prependFile($this->basePath() . '/js/circuito_da_visao/modal-selecionar-aba.js' . $versao)
        ->prependFile($this->basePath() . '/js/circuito_da_visao/ajustar-tabela-lancamento.js' . $versao)
        ->prependFile($this->basePath() . '/js/circuito_da_visao/remover-pessoa-lancamento.js' . $versao)
        ->prependFile($this->basePath() . '/js/circuito_da_visao/modal-muitos-cadastros.js' . $versao)
;
echo $this->inlineScript();
