<?php

use Application\Controller\Helper\Constantes;

$html = '';
$html .= $this->templateFormularioTopo('Abrir Aula', '', 'style="margin-top: 50px"');
$html .= '<form action="/cursoSalvarAula" method="post">';
$html .= '<div class="panel-body bg-light">';
$html .= '<select class="form-control" id="idAula" name="idAula">';
$html .= '<option value="0">SELECIONE</option>';
foreach ($this->opcoes as $key => $value) {
    $html .= '<option value="' . $key . '" ' . $value[1] . '>' . $value[0] . '</option>';
}
$html .= '</select>';
$html .= '</div>';
$html .= '<div class="panel-footer">';
$stringNomeDaFuncaoOnClickCadastro = 'mostrarSplash(); funcaoCircuito("' . Constantes::$ROUTE_CURSO . Constantes::$PAGINA_LISTAR_TURMA . '", 0)';
$html .= $this->botaoLink($this->translate(Constantes::$TRADUCAO_VOLTAR), Constantes::$STRING_HASHTAG, 2, $this->funcaoOnClick($stringNomeDaFuncaoOnClickCadastro));
$html .= $this->botaoSimples('Salvar', $this->funcaoOnClick('mostrarSplash(); this.form.submit()'));
$html .= '</div>';
$html .= '</form>';
$html .= $this->templateFormularioRodape();
echo $html;
