<?php

use Application\Controller\CursoController;
use Application\Controller\Helper\Funcoes;
use Application\Model\Entity\Curso;
use Application\Model\Entity\Disciplina;
use Application\Model\Entity\Situacao;
use Application\Model\Entity\EntidadeTipo;
use Application\Model\Entity\CursoAcesso;
use Application\View\Helper\BotaoSimples;

$html = '';

$ehTurmaDoInstitutoDeVencedores = $this->turmaPessoa->getTurma()->getCurso()->getId() === Curso::INSTITUTO_DE_VENCEDORES;

$disabled = '';
if (!$this->turmaPessoa->verificarSeEstaAtivo()) {
	$disabled = 'disabled';
}

$corSituacao = 'success';
if ($this->turmaPessoa->getTurmaPessoaSituacaoAtiva()->getSituacao()->getId() === Situacao::ESPECIAL) {
	$corSituacao = 'primary';
}
$urlGerarCarterinha = '/cursoGerarCarterinha/' . $this->turmaPessoa->getId();
$funcaoGerarCarterinha = $this->funcaoOnClick('window.open("' . $urlGerarCarterinha . '","_blanck")');

$botaoGerarCarterinha = $this->botaoSimples(
	$this->turmaPessoa->getId(). ' <i class="fa fa-user"></i>', $funcaoGerarCarterinha, BotaoSimples::botaoMuitoPequenoImportante, BotaoSimples::posicaoAEsquerda);

$botaoMudarNome = '';

if($this->possoAcessarIsso){
	$botaoMudarNome .= '<div class="btn-group dropdown">';
	$botaoMudarNome .= '<a id="menudrop_' . $this->turmaPessoa->getPessoa()->getId() . '" class="tdNome text-left dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">';
	$botaoMudarNome .= '<span class="btn btn-primary btn-xs hidden-lg" id="span_nome_' . $this->turmaPessoa->getPessoa()->getId() . '" >';
	$botaoMudarNome .= $this->turmaPessoa->getPessoa()->getNomeListaDeLancamento(5);
	$botaoMudarNome .= '</span>';
	$botaoMudarNome .= '<span class="btn btn-primary btn-xs  hidden-xs hidden-sm hidden-md" id="span_nome_lg_' . $this->turmaPessoa->getPessoa()->getId() . '" >';
	$botaoMudarNome .= $this->turmaPessoa->getPessoa()->getNome();
	$botaoMudarNome .= '</span>';
	$botaoMudarNome .= '</a>';
	$botaoMudarNome .= '<ul class="dropdown-menu sobrepor-elementos modal-edicao-nome">';
	$botaoMudarNome .= '<span class="editable-container editable-inline">';
	$botaoMudarNome .= '<div class="ml10 campo-edicao-nome">';
	$botaoMudarNome .= '<form class="form-inline editableform">';
	$botaoMudarNome .= '<div class="control-group form-group">';
	$botaoMudarNome .= '<div>';
	$botaoMudarNome .= '<div class="input-group">';
	$botaoMudarNome .= '<input type="text" class="form-control" id="nome_' . $this->turmaPessoa->getPessoa()->getId() . '" value="' . $this->turmaPessoa->getPessoa()->getNome() . '" />';
	$botaoMudarNome .= '<span class="input-group-btn">';
	$botaoMudarNome .= '<span onclick="alterarNome(' . $this->turmaPessoa->getPessoa()->getId() . ')" class="btn ladda-button btn-primary" data-style="zoom-in"><span class="ladda-label"><i class="fa fa-check"></i></span></span>';
	$botaoMudarNome .= '</span>';
	$botaoMudarNome .= '</div>';
	$botaoMudarNome .= '</div>';
	$botaoMudarNome .= '</div>';
}
if(!$this->possoAcessarIsso){	
	$botaoMudarNome .= $this->turmaPessoa->getPessoa()->getNome();	
}
$html .= '</div>';

$selectMudarSituacao = '';
$selectMudarSituacao .= '<select id="selectMudarSituacao" class="form-control hidden" onChange="mudarSituacao(this,' . $this->turmaPessoa->getId() . ')">';
foreach ($this->situacoes as $situacao) {
	if ($situacao->getId() !== 2 &&
		$situacao->getId() !== 3 &&
		$situacao->getId() !== 4 &&
		$situacao->getId() !== 5) {
			$selected = '';
			if ($situacao->getId() === $this->fatoCurso->getSituacao_id()) {
				$selected = 'selected';
			}
			$selectMudarSituacao .= '<option value="' . $situacao->getId() . '" ' . $selected . '>' . $situacao->getNome() . '</option>';
		}
}
$selectMudarSituacao .= '</select>';
if (
	$this->situacao->getId() === Situacao::ATIVO ||
	$this->situacao->getId() === Situacao::DESISTENTE ||
	$this->situacao->getId() === Situacao::REPROVADO_POR_FALTA ||
	$this->situacao->getId() === Situacao::REPROVADO_POR_FINANCEIRO ||
	$this->situacao->getId() === Situacao::ESPECIAL){
		$botaoMudarSituacao = 
			$this->botaoSimples($this->situacao->getNome() . ' <i class="fa fa-pencil"></i>', ' id="botaoSituacao" ' . $this->funcaoOnClick('$("#selectMudarSituacao").removeClass("hidden"); $("#botaoSituacao").addClass("hidden")'), BotaoSimples::botaoMuitoPequenoMenosImportante, BotaoSimples::posicaoAEsquerda);
		$botaoMudarSituacao .= $selectMudarSituacao;
	} else {
		$botaoMudarSituacao = $this->situacao->getNome();
	}


$funcaoRemoverDaTurma = $this->funcaoOnClick('removerDaTurma(' . $this->turmaPessoa->getId() . ')');
$botaoRemoverDaTurma = $this->botaoSimples('Remover da Turma <i class="fa fa-user-times"></i>', $funcaoRemoverDaTurma, BotaoSimples::botaoMuitoPequenoPerigoso, BotaoSimples::posicaoAEsquerda);

$html = '';
$html .= '<div class="row">';

if($turmaPessoa->getTurma()->getTurmaAulaAtiva()){
	$html .= '<div class="row mt10 alert alert-info text-center">' . $turmaPessoa->getTurma()->getTurmaAulaAtiva()->getAula()->getDisciplina()->getNome() . ' - Aula ' . $turmaPessoa->getTurma()->getTurmaAulaAtiva()->getAula()->getPosicao() . '</div>';
}
$html .= '<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">';
$html .= '<div class="panel panel-default">';
$html .= '<div class="panel-heading" style="padding: 0px 8px;">Nova Consulta</div>';
$html .= '<div class="panel-body">';
$html .= '<input type="number" id="matricula" class="mb10 form-control" placeholder="Matrícula"  />';
$html .=  $this->botaoSimples('Pesquisar', $this->funcaoOnClick('acessarMatricula()'), BotaoSimples::botaoImportante, BotaoSimples::larguraMaxima);
$html .= '</div>';
$html .= '</div>';


if(!$turmaPessoa->getTurma()->verificarSeEstaAtivo()){
	$html .= '<div id="alertSituacao" class="alert alert-danger">';	
	$html .= '<h3 id="h3Situacao" class="text-center">Aluno Reprovado</h3>';	
	$html .= '</div>';

	$html .= '<div id="alertFinanceiroSituacao" class="alert alert-danger">';	
	$html .= '<h3 id="h3financeiroSituacao" class="text-center">Financeiro Pendente</h3>';	
	$html .= '</div>';	
}


$html .= '<div class="panel panel-default">';
$html .= '<div class="panel-heading" style="padding: 0px 8px;">Dados do Aluno</div>';
$html .= '<div class="panel-body" style="overflow: hidden;">';
$html .= '<div class="table-responsive">';
$html .= '<table class="table table-condesed">';
$html .= '<tbody>';
if ($this->turmaPessoa->verificarSeEstaAtivo()) {
	$html .= '<tr><td>Matrícula</td><td>' . $botaoGerarCarterinha . '</td></tr>';
	$html .= '<tr><td>Nome</td><td>' . $botaoMudarNome . '</td></tr>';
} else {
	$html .= '<tr><td>Matricula</td><td>' . $this->turmaPessoa->getId(). '</td></tr>';
	$html .= '<tr><td>Nome</td><td>' . $this->turmaPessoa->getPessoa()->getNome() . '</td></tr>';
}
$html .= '<tr><td>Equipe</td><td>' . $this->nomeEquipe . '</td></tr>';
if ($this->turmaPessoa->verificarSeEstaAtivo()) {
	$html .= '<tr><td>Curso</td><td>' . $this->turmaPessoa->getTurma()->getCurso()->getNome() . ' - ' . Funcoes::mesPorExtenso($this->turmaPessoa->getTurma()->getMes()) . '/' . $this->turmaPessoa->getTurma()->getAno() . '</td></tr>';

	if ($this->entidade->getEntidadeTipo()->getId() === EntidadeTipo::igreja ||
		$this->pessoa->getPessoaCursoAcessoAtivo() &&
		(
			$this->pessoa->getPessoaCursoAcessoAtivo()->getCursoAcesso()->getId() === CursoAcesso::COORDENADOR ||
			$this->pessoa->getPessoaCursoAcessoAtivo()->getCursoAcesso()->getId() === CursoAcesso::FACILITADOR ||
		$this->pessoa->getPessoaCursoAcessoAtivo()->getCursoAcesso()->getId() === CursoAcesso::SUPERVISOR)){
			$html .= '<tr><td>Situa&ccedil;&atilde;o</td><td>' . $botaoMudarSituacao . '</td></tr>';
		}

	if ($this->entidade->getEntidadeTipo()->getId() === EntidadeTipo::igreja ||
		$this->pessoa->getPessoaCursoAcessoAtivo() &&
		($this->pessoa->getPessoaCursoAcessoAtivo()->getCursoAcesso()->getId() === CursoAcesso::COORDENADOR)){
			$html .= '<tr><td>Remover</td><td>' . $botaoRemoverDaTurma . '</td></tr>';
		}

} else {
	$html .= '<tr><td colspan="2" class="text-center"><span class="label label-danger">Aluno Removido da turma</span></td></tr>';
}
$html .= '</tbody>';
$html .= '</table>';
$html .= '</div>';
$html .= '</div>';
$html .= '</div>';

$html .= '</div>';

$html .= '<div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">';
if ($this->turmaPessoa->verificarSeEstaAtivo()) {
	$html .= '<div id="dadosDoCurso">';
	/* Presenças */
	$html .= '<div class="panel panel-default">';
	$html .= '<div class="panel-heading" style="padding: 0px 8px;">Aulas</div>';
	$html .= '<div class="panel-body">';
	$html .= '<div class="table-responsive">';
	$html .= '<table class="table table-condensed">';
	$html .= '<thead>';
	$html .= '<tr>';
	$html .= '<th colspan="13">Legenda'
		. ' - <span class="label label-xs label-danger"><i class="fa fa-times"></i> Falta</span>'
		. ' - <span class="label label-xs label-warning"><i class="fa fa-file"></i> Reposi&ccedil;&atilde;o</span>'
		. ' - <span class="label label-xs label-success"><i class="fa fa-check"></i> Presen&ccedil;a</span></th>';
	$html .= '</tr>';
	$html .= '<tr>';
	$html .= '<th>Diciplinas</th>';
	$html .= '<th colspan="12">Aulas</th>';
	$html .= '</tr>';
	$html .= '</thead>';
	$html .= '<tbody>';
	$pontosPresenca = Array();
	foreach ($this->turmaPessoa->getTurma()->getCurso()->getDisciplina() as $disciplina) {
		$html .= '<tr>';
		$html .= '<td>' . $disciplina->getNome() . '</td>';		
		foreach ($disciplina->getAulaOrdenadasPorPosicao() as $aula) {
			$extra = '';
			$reposicao = false;

			$icone = 'fa-times';
			$corDoBotao = BotaoSimples::botaoMuitoPequenoPerigoso;
			if (count($this->turmaPessoa->getTurmaPessoaAula()) > 0) {
				foreach ($this->turmaPessoa->getTurmaPessoaAula() as $turmaPessoaAula) {
					if ($turmaPessoaAula->getAula()->getId() === $aula->getId() && $turmaPessoaAula->verificarSeEstaAtivo()) {
						$icone = 'fa-check';
						$corDoBotao = BotaoSimples::botaoMuitoPequenoSucesso;
						if ($turmaPessoaAula->getReposicao() == 'S') {
							$extra = ' disabled ';
							$icone = 'fa-file';
							$corDoBotao = BotaoSimples::botaoMuitoPequenoWarning;
							$reposicao = true;
						}
						if ($turmaPessoaAula->getReposicao() != 'S') {
							$pontosPresenca[$disciplina->getNome()]++;
						}
					}
				}
			}

			$iconeBotao = '<i class="fa ' . $icone . '"></i>';
			if (!$reposicao) {
				$idBotao = 'botao_' . $this->turmaPessoa->getId() . '_' . $aula->getId() . '_1';
				$extra = ' id="' . $idBotao . '" ' . $this->funcaoOnClick('mudarPresencaOuVistoOuFinanceiro(' . $this->turmaPessoa->getId() . ', ' . $aula->getId() . ')');
			}
			$html .= '<td class="text-center">';
			if($this->possoAcessarIsso){
				$html .= $aula->getPosicao() . ' ' . $this->botaoSimples($iconeBotao, $extra, $corDoBotao, BotaoSimples::posicaoAoCentro);
			}
			if(!$this->possoAcessarIsso){
				if($corDoBotao == BotaoSimples::botaoMuitoPequenoSucesso){
					$corDoSpan = 'success';
				}
				if($corDoBotao == BotaoSimples::botaoMuitoPequenoWarning){
					$corDoSpan = 'warning';
				}
				if($corDoBotao == BotaoSimples::botaoMuitoPequenoPerigoso){
					$corDoSpan = 'danger';
				}
				$html .= $aula->getPosicao() . ' ';
				$html .= '<span class="btn-xs btn-'.$corDoSpan.' hidden-xs hidden-sm hidden-md">';
				$html .= $iconeBotao;
				$html .= '</span>';				
			}
			
			$html .= '</td>';
		}
		$html .= '</tr>';
	}
	$html .= '</tbody>';
	$html .= '</table>';
	$html .= '</div>';
	$html .= '</div>';
	$html .= '</div>';


	if ($ehTurmaDoInstitutoDeVencedores) {
		$html .= '<div class="row">';
		$html .= '<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">';

		/* Pedagogico */
		$html .= '<div class="panel panel-default mt10">';
		$html .= '<div class="panel-heading" style="padding: 0px 8px;">Avaliações</div>';
		$html .= '<div class="panel-body">';
		$html .= '<div class="table-responsive">';
		$html .= '<table class="table table-condensed">';
		$html .= '<thead>';

		$html .= '<tr>';
		$html .= '<th colspan="4">Legenda'
			. ' - <span class="label label-xs label-danger"><i class="fa fa-times"></i> Não Entregado</span>'
			. ' - <span class="label label-xs label-success"><i class="fa fa-check"></i> Entregado</span></th>';
		$html .= '</tr>';

		$html .= '<tr>';
		$html .= '<th>Diciplinas</th>';
		$html .= '<th class="text-center">A. 1</th>';
		$html .= '<th class="text-center">A. 2</th>';
		$html .= '<th class="text-center">Ex.</th>';		
		$html .= '</tr>';
		$html .= '</thead>';
		$html .= '<tbody>';
		$pontosPedagogico = Array();
		foreach ($this->turmaPessoa->getTurma()->getCurso()->getDisciplina() as $disciplina) {
			if ($disciplina->getId() !== Disciplina::POS_REVISAO) {
				$html .= '<tr>';
				$html .= '<td>' . $disciplina->getNome() . '</td>';


				for ($indiceAvaliacao = 1; $indiceAvaliacao <= 3; $indiceAvaliacao++) {
					$extra = '';
					$validacao = false;
					$icone = 'fa-times';
					$corDoBotao = BotaoSimples::botaoMuitoPequenoPerigoso;

					if (count($this->turmaPessoa->getTurmaPessoaAvaliacao()) > 0) {
						foreach ($this->turmaPessoa->getTurmaPessoaAvaliacao() as $turmaPessoaAvaliacao) {
							if ($turmaPessoaAvaliacao->getDisciplina()->getId() === $disciplina->getId()) {
								switch ($indiceAvaliacao) {
								case 1:
									if ($turmaPessoaAvaliacao->getAvaliacao1() === 'S') {
										$validacao = true;
										$pontosPedagogico[$disciplina->getNome()] += 2;
									}
									break;
								case 2:
									if ($turmaPessoaAvaliacao->getAvaliacao2() === 'S') {
										$validacao = true;
										$pontosPedagogico[$disciplina->getNome()] += 2;
									}
									break;
								case 3:
									if ($turmaPessoaAvaliacao->getExtra() === 'S') {
										$validacao = true;
										$pontosPedagogico[$disciplina->getNome()] += 1;
									}
									break;
								}
							}
						}
					}
					if ($validacao) {
						$icone = 'fa-check';
						$corDoBotao = BotaoSimples::botaoMuitoPequenoSucesso;
					}
				
					$iconeBotao = '<i class="fa ' . $icone . '"></i>';
					$idBotao = 'botao_' . $this->turmaPessoa->getId() . '_' . $disciplina->getId() . '_4_' . $indiceAvaliacao;
					$extra = ' id="' . $idBotao . '" ' . $this->funcaoOnClick('mudarPresencaOuVistoOuFinanceiro(' . $this->turmaPessoa->getId() . ', ' . $disciplina->getId() . ', 4,' . $indiceAvaliacao . ')');

					$html .= '<td class="text-center">';
					if($this->possoAcessarIsso){
						$html .= $aula->getPosicao() . ' ' . $this->botaoSimples($iconeBotao, $extra, $corDoBotao, BotaoSimples::posicaoAoCentro);
					}
					if(!$this->possoAcessarIsso){
						if($corDoBotao == BotaoSimples::botaoMuitoPequenoSucesso){
							$corDoSpan = 'success';
						}
						if($corDoBotao == BotaoSimples::botaoMuitoPequenoPerigoso){
							$corDoSpan = 'danger';
						}
						$html .= $aula->getPosicao() . ' ';
						$html .= '<span class="btn-xs btn-'.$corDoSpan.' hidden-xs hidden-sm hidden-md">';
						$html .= $iconeBotao;
						$html .= '</span>';				
					}					
					$html .= '</td>';
				}

				$html .= '</tr>';
			}
		}

		$html .= '</tbody>';
		$html .= '</table>';
		$html .= '</div>';
		$html .= '</div>';
		$html .= '</div>';	

		$html .= '</div>';	

		$html .= '<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">';

		/* Pedagogico */
		$html .= '<div class="panel panel-default mt10">';
		$html .= '<div class="panel-heading" style="padding: 0px 8px;">Vistos</div>';
		$html .= '<div class="panel-body">';
		$html .= '<div class="table-responsive">';
		$html .= '<table class="table table-condensed">';
		$html .= '<thead>';

		$html .= '<tr>';
		$html .= '<th colspan="12">Legenda'
			. ' - <span class="label label-xs label-danger"><i class="fa fa-times"></i> Sem Visto</span>'
			. ' - <span class="label label-xs label-success"><i class="fa fa-check"></i> Vistado</span></th>';
		$html .= '</tr>';

		$html .= '<tr>';
		$html .= '<th>Diciplinas</th>';		
		$html .= '<th colspan="12">Aulas</th>';
		$html .= '</tr>';
		$html .= '</thead>';
		$html .= '<tbody>';
		foreach ($this->turmaPessoa->getTurma()->getCurso()->getDisciplina() as $disciplina) {
			if ($disciplina->getId() !== Disciplina::POS_REVISAO) {		
				$html .= '<tr>';
				$html .= '<td>' . $disciplina->getNome() . '</td>';	
				foreach ($disciplina->getAulaOrdenadasPorPosicao() as $aula) {
					$extra = '';
					$icone = 'fa-times';
					$corDoBotao = BotaoSimples::botaoMuitoPequenoPerigoso;

					if (count($this->turmaPessoa->getTurmaPessoaVisto()) > 0) {
						foreach ($this->turmaPessoa->getTurmaPessoaVisto() as $turmaPessoaVisto) {
							if ($turmaPessoaVisto->getAula()->getId() === $aula->getId() && $turmaPessoaVisto->verificarSeEstaAtivo()) {
								$icone = 'fa-check';
								$corDoBotao = BotaoSimples::botaoMuitoPequenoSucesso;
								$pontosPedagogico[$disciplina->getNome()] += 0.5;
							}
						}
					}

					$iconeBotao = '<i class="fa ' . $icone . '"></i>';
					$idBotao = 'botao_' . $this->turmaPessoa->getId() . '_' . $aula->getId() . '_2';
					$extra = ' id="' . $idBotao . '" ' . $this->funcaoOnClick('mudarPresencaOuVistoOuFinanceiro(' . $this->turmaPessoa->getId() . ', ' . $aula->getId() . ', 2)');
					$html .= '<td class="text-center">';
					if($this->possoAcessarIsso){
						$html .= $aula->getPosicao() . ' ' . $this->botaoSimples($iconeBotao, $extra, $corDoBotao, BotaoSimples::posicaoAoCentro);
					}
					if(!$this->possoAcessarIsso){
						if($corDoBotao == BotaoSimples::botaoMuitoPequenoSucesso){
							$corDoSpan = 'success';
						}
						if($corDoBotao == BotaoSimples::botaoMuitoPequenoPerigoso){
							$corDoSpan = 'danger';
						}
						$html .= $aula->getPosicao() . ' ';
						$html .= '<span class="btn-xs btn-'.$corDoSpan.' hidden-xs hidden-sm hidden-md">';
						$html .= $iconeBotao;
						$html .= '</span>';				
					}						
					$html .= '</td>';
				}

				$html .= '</tr>';
			}
		}
		$html .= '</tbody>';
		$html .= '</table>';
		$html .= '</div>';
		$html .= '</div>';
		$html .= '</div>';		

		$html .= '</div>';	
		$html .= '</div>'; // Fim da row

		$iconeBotao = '<i class="fa fa-times"></i>';
		$corBotao = BotaoSimples::botaoMuitoPequenoPerigoso;
		$botaoModuloUm = $this->botaoSimples($iconeBotao, '#', $corBotao, BotaoSimples::posicaoAoCentro);
		$botaoModuloDois = $this->botaoSimples($iconeBotao, '#', $corBotao, BotaoSimples::posicaoAoCentro);
		$botaoModuloTres = $this->botaoSimples($iconeBotao, '#', $corBotao, BotaoSimples::posicaoAoCentro);

		$html .= '<div class="row">';
		
		/* Situação Financeiro */
		$html .= '<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">';
		$html .= '<div class="panel panel-default mt10">';
		$html .= '<div class="panel-heading" style="padding: 0px 8px;">Financeiro</div>';
		$html .= '<div class="panel-body">';
		$html .= '<div class="table-responsive">';
		$html .= '<table class="table table-condensed">';
		$html .= '<thead>';

		$html .= '<tr>';
		$html .= '<th colspan="3">Legenda'
			. ' - <span class="label label-xs label-danger"><i class="fa fa-times"></i> Sem Pagamento</span>'
			. ' - <span class="label label-xs label-success"><i class="fa fa-check"></i> Pago</span></th>';
		$html .= '</tr>';

		$html .= '<tr>';
		$html .= '<th>Diciplinas</th>';
		$html .= '<th colspan="3" class="text-center">Mensalidade</th>';
		if($this->possoAcessarIsso){
			$html .= '<th class="text-center hidden-xs hidden-sm hidden-md"">Recibo</th>';
		}		
		$html .= '</tr>';
		$html .= '</thead>';
		$html .= '<tbody>';
		$pontosFinanceiro = Array();		
		$validacaoFinanceiro = 1;		
		foreach ($this->turmaPessoa->getTurma()->getCurso()->getDisciplina() as $disciplina) {
			if ($disciplina->getId() !== Disciplina::POS_REVISAO) {				
				//$botaoFinanceiro = $this->botaoSimples($iconeBotao, '#', $corBotao, BotaoSimples::posicaoAoCentro);

				$html .= '<tr>';	
				$html .= '<td>' . $disciplina->getNome() . '</td>';			
				if (count($this->turmaPessoa->getTurmaPessoaFinanceiro()) > 0) {
					$mensalidadeFinanceiro = Array();
					foreach ($this->turmaPessoa->getTurmaPessoaFinanceiro() as $turmaPessoaFinanceiro) {
						if ($turmaPessoaFinanceiro->getDisciplina()->getId() === $disciplina->getId() && $turmaPessoaFinanceiro->verificarSeEstaAtivo()) {							
							$mensalidadeFinanceiro['valor1'] = $turmaPessoaFinanceiro->getValor1();
							$mensalidadeFinanceiro['valor2'] = $turmaPessoaFinanceiro->getValor2();
							$mensalidadeFinanceiro['valor3'] = $turmaPessoaFinanceiro->getValor3();
						}
					}
				}

				for ($indiceMensalidade=1; $indiceMensalidade <= 3 ; $indiceMensalidade++) { 
					$extra = '';
					$icone = 'fa-times';
					$corDoBotao = BotaoSimples::botaoMuitoPequenoPerigoso;				
									
					if($mensalidadeFinanceiro['valor'.$indiceMensalidade] == 'S'){
						$pontosFinanceiro[$disciplina->getNome()] += 1;
						$icone = 'fa-check';
						$corDoBotao = BotaoSimples::botaoMuitoPequenoSucesso;
					}
					$iconeBotao = '<i class="fa ' . $icone . '"></i>';
					$idBotao = 'botao_' . $this->turmaPessoa->getId() . '_' . $disciplina->getId() . '_3' . '_' . $indiceMensalidade;
					$extra = ' id="' . $idBotao . '" ' . $this->funcaoOnClick('mudarPresencaOuVistoOuFinanceiro(' . $this->turmaPessoa->getId() . ', ' . $disciplina->getId() . ', 3 ,' . $indiceMensalidade . ')');

					$html .= '<td>';
					if($this->possoAcessarIsso){
						$html .= $this->botaoSimples($iconeBotao, $extra, $corDoBotao, BotaoSimples::posicaoAoCentro);
					}
					if(!$this->possoAcessarIsso){
						if($corDoBotao == BotaoSimples::botaoMuitoPequenoSucesso){
							$corDoSpan = 'success';
						}
						if($corDoBotao == BotaoSimples::botaoMuitoPequenoPerigoso){
							$corDoSpan = 'danger';
						}						
						$html .= '<span class="btn-xs btn-'.$corDoSpan.' hidden-xs hidden-sm hidden-md">';
						$html .= $iconeBotao;
						$html .= '</span>';				
					}
					
					$html .= '</td>';
				}

				

				if($pontosFinanceiro[$disciplina->getNome()] < 3){
					$validacaoFinanceiro = 0;
				}				

				if($this->possoAcessarIsso){
					$html .= '<td class="text-center hidden-xs hidden-sm hidden-md""><a target="_blanck" href="/cursoReciboFinanceiro/' . $this->turmaPessoa->getId().'9999999999'.$disciplina->getId() . '" class="btn btn-xs btn-primary" ><i class="fa fa-print"></i></a></td>';
				}			

				$html .= '</tr>';
			}
		}
		$html .= '</tbody>';
		$html .= '</table>';
		$html .= '</div>';
		$html .= '</div>';
		$html .= '</div>';		
		$html .= '</div>';

		/* Situação Presenças */
		$html .= '<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">';
		$html .= '<div class="panel panel-default mt10">';
		$html .= '<div class="panel-heading" style="padding: 0px 8px;">Presenças</div>';
		$html .= '<div class="panel-body">';
		$html .= '<div class="table-responsive">';
		$html .= '<table class="table table-condensed">';
		$html .= '<thead>';		

		$html .= '<tr>';
		$html .= '<th colspan="3">Mínimo de presenças para aprovação: 9</th>';
		$html .= '</tr>';

		$html .= '<tr>';
		$html .= '<th>Diciplinas</th>';				
		$html .= '<th class="text-center">Presenças</th>';
		$html .= '<th class="text-center">Situação</th>';
		$html .= '</tr>';
		$html .= '</thead>';
		$html .= '<tbody>';		
		$validacaoGeral = 1;		
		foreach ($this->turmaPessoa->getTurma()->getCurso()->getDisciplina() as $disciplina) {
			if ($disciplina->getId() !== Disciplina::POS_REVISAO) {
				$situacaoDoAluno = $this->turmaPessoa->getTurmaPessoaSituacaoAtiva()->getSituacao()->getId();
				$labelAprovacao = '<span class="label label-danger">Reprovado</span>';		
				$html .= '<tr>';
				$html .= '<td>' . $disciplina->getNome() . '</td>';
				if ($pontosPresenca[$disciplina->getNome()] > 8 || $situacaoDoAluno === Situacao::ESPECIAL) {				
					$labelAprovacao = '<span class="label label-success">Aprovado</span>';										
				}
				if ($pontosPresenca[$disciplina->getNome()] < 9 && $situacaoDoAluno !== Situacao::ESPECIAL) {				
					$validacaoGeral = 0;										
				}	
				$html .= '<td class="text-center">';
				if ($pontosPresenca[$disciplina->getNome()]) {				
					$html .= $pontosPresenca[$disciplina->getNome()];										
				} 

				if (!$pontosPresenca[$disciplina->getNome()]) {				
					$html .= '0';										
				} 				
				$html .= '</td>';		
				$html .= '<td class="text-center">';
				$html .= $labelAprovacao;
				$html .= '</td>';				

				$html .= '</tr>';
			}
		}
		$html .= '</tbody>';
		$html .= '</table>';
		$html .= '</div>';
		$html .= '</div>';
		$html .= '</div>';		
		$html .= '</div>';

		/* Situação Pedagógico */
		$html .= '<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">';
		$html .= '<div class="panel panel-default mt10">';
		$html .= '<div class="panel-heading" style="padding: 0px 8px;">Pedagógico</div>';
		$html .= '<div class="panel-body">';
		$html .= '<div class="table-responsive">';
		$html .= '<table class="table table-condensed">';
		$html .= '<thead>';		

		$html .= '<tr>';
		$html .= '<th colspan="3">Mínimo de média para aprovação: 7.0</th>';
		$html .= '</tr>';

		$html .= '<tr>';
		$html .= '<th>Diciplinas</th>';		
		$html .= '<th class="text-center">Média</th>';
		$html .= '<th class="text-center">Situação</th>';

		$html .= '</tr>';
		$html .= '</thead>';
		$html .= '<tbody>';		
		foreach ($this->turmaPessoa->getTurma()->getCurso()->getDisciplina() as $disciplina) {
			if ($disciplina->getId() !== Disciplina::POS_REVISAO) {	
				$labelAprovacao = '<span class="label label-danger">Reprovado</span>';		
				$html .= '<tr>';
				$html .= '<td>' . $disciplina->getNome() . '</td>';
				if ($pontosPedagogico[$disciplina->getNome()] >= 7) {				
					$labelAprovacao = '<span class="label label-success">Aprovado</span>';											
				}
				if ($pontosPedagogico[$disciplina->getNome()] < 7) {				
					$validacaoGeral = 0;
				}
				$html .= '<td class="text-center">';
				if ($pontosPedagogico[$disciplina->getNome()]) {				
					$html .= $pontosPedagogico[$disciplina->getNome()];
				}
				if (!$pontosPedagogico[$disciplina->getNome()]) {				
					$html .= '0';	
				}				
				$html .= '</td>';	
				$html .= '<td class="text-center">';
				$html .= $labelAprovacao;
				$html .= '</td>';		

				$html .= '</tr>';
			}
		}
		$html .= '</tbody>';
		$html .= '</table>';
		$html .= '</div>';
		$html .= '</div>';
		$html .= '</div>';		
		$html .= '</div>';

		$html .= '</div>'; /* fim row */
	}

	$html .= '</div>'; /* Fim  dadosDoCurso */
}
$html .= '</div>'; /* Fim col-lg-7 col-md-7 col-sm-7 col-xs-12 */

$html .= '</div>'; /* Fim row */
$html .= '<input type="hidden" id="validacaoGeralDoAluno" value="' . $validacaoGeral .  '" />';
$html .= '<input type="hidden" id="validacaoDoFinanceiro" value="' . $validacaoFinanceiro . '" />';
echo $html;

$versao = '?v=1.1.32';

echo $this
	->headScript()
	->prependFile($this->basePath() . '/js/circuito_da_visao/alterar-nome.js' . $versao)
	->prependFile($this->basePath() . '/js/circuito_da_visao/aluno.js' . $versao)
	;
echo $this->inlineScript();

?>

