<?php

use Application\Controller\CursoController;
use Application\Controller\Helper\Constantes;
use Application\Controller\Helper\Funcoes;
use Application\Model\Entity\EntidadeTipo;
use Application\Model\Entity\Situacao;
use Application\Model\Entity\CursoAcesso;
use Application\View\Helper\BotaoSimples;
use Application\View\Helper\FiltroCurso;
?>
<style type="text/css">
	table{
		font-size: 12px;
	}
</style>
<?php

$html = '';
$html .= '<blockquote class="mt50 blockquote-primary"><small>' . $this->translate('Chamada') . '</small></blockquote>';
$html .= '<div class="panel heading-border panel-primary">';
$html .= '<div class="panel-body bg-light">';

$html .= $this->filtroCursos('cursoChamada');

if($this->filtrado){
	$html .= '<input id="fooFilter" type="text" class="form-control mt20" placeholder="Filtro">';
	foreach ($this->turmas as $turma) {
		if($this->postado['idTurma'] == 0 || $turma->getId() == $this->postado['idTurma']){
			$html .= '<div class="table-responsive">';
			$html .= '<table  class="table table-bordered table-condensed footable" data-filter="#fooFilter">';

			$html .= '<thead>';
			$html .= '<tr>';
			$html .= '<th colspan="3" class="text-center hidden-xs">' . $turma->getCurso()->getNome() . ' - ' . Funcoes::mesPorExtenso($turma->getMes()) . '/' . $turma->getAno() . '</th>';
			$html .= '<th colspan="2" class="text-center hidden-sm hidden-md hidden-lg">' . $turma->getCurso()->getNomeSigla() . ' - ' . Funcoes::mesPorExtenso($turma->getMes()) . '/' . $turma->getAno() . '</th>';
			foreach ($turma->getCurso()->getDisciplina() as $disciplina) {
				$mostrar = false;
				if ($turma->getTurmaAulaAtiva() && $turma->getTurmaAulaAtiva()->getAula()->getDisciplina()->getId() === $disciplina->getId()) {
					$mostrar = true;
				}
				if ($mostrar) {
					$html .= '<th colspan="' . count($disciplina->getAula()) . '" class="text-center">' . $disciplina->getNome() . '</th>';
				}
			}
			$html .= '</tr>';
			$html .= '<tr>';
			$html .= '<th class="text-center">Situa&ccedil;&atilde;o</th>';
			$html .= '<th class="text-center">Matricula</th>';
			$html .= '<th class="text-center">Aluno</th>';
			$html .= '<th class="text-center">Equipe</th>';

			if($this->postado['mostrarAulas'] == 1){
				foreach ($turma->getCurso()->getDisciplina() as $disciplina) {
					$mostrar = false;
					if ($turma->getTurmaAulaAtiva() && $turma->getTurmaAulaAtiva()->getAula()->getDisciplina()->getId() === $disciplina->getId()) {
						$mostrar = true;
					}
					if ($mostrar) {
						foreach ($disciplina->getAulaOrdenadasPorPosicao() as $aula) {
							if($turma->getTurmaAulaAtiva()->getAula()->getId() === $aula->getId()){
								break;
							}
							$html .= '<td class="text-center">A' . $aula->getPosicao() . '</td>';
						}
					}
				}
			}
			$html .= '</tr>';
			$html .= '</thead>';

			$html .= '<tbody>';
			if ($turma->getTurmaPessoa()) {
				foreach ($turma->getTurmaPessoa() as $turmaPessoa) {
					$mostrar = false;

					if($turmaPessoa->verificarSeEstaAtivo()){
						if ($this->postado['idEquipe'] == 0) {
							$mostrar = true;
						} else {
							if ($turmaPessoa->getPessoa()->getGrupoPessoaAtivo()) {
								if($turmaPessoa->getPessoa()->getGrupoPessoaAtivo()->getGrupo()->getGrupoEquipe()->getId() == $this->postado['idEquipe']){
									$mostrar = true;
								}
							}
						}
					}
					if ($mostrar) {
						$nomeEquipe = CursoController::nomeEquipeTurmaPessoa($turmaPessoa);

						$mostrarSituacao = false;
						if($this->postado['idSituacao'] == 0 && ($turmaPessoa->getTurmaPessoaSituacaoAtiva()->getSituacao()->getId() === Situacao::ATIVO || 
						$turmaPessoa->getTurmaPessoaSituacaoAtiva()->getSituacao()->getId() === Situacao::ESPECIAL)){
							$mostrarSituacao = true;
						}else{
							if($turmaPessoa->getTurmaPessoaSituacaoAtiva()->getSituacao()->getId() == $this->postado['idSituacao']){
								$mostrarSituacao = true;
							}
						}

						if($mostrarSituacao){

							$mostrarSub = false;
							if($this->postado['idSub'] == 0){
								$mostrarSub = true;
							}else{
								$mostrarSub = CursoController::verificarSeParticipaDeUmaSub($turmaPessoa, $this->postado['idSub']);
							}	
							if($mostrarSub){

								switch ($turmaPessoa->getTurmaPessoaSituacaoAtiva()->getSituacao()->getId()) {
								case Situacao::ESPECIAL:
									$corSituacao = 'primary';
									break;
								case Situacao::DESISTENTE:
									$corSituacao = 'warning';
									break;
								case Situacao::REPROVADO_POR_FALTA:
									$corSituacao = 'danger';
									break;
								default:
									$corSituacao = 'success';
								}

								$stringSituacao = '<span class="label label-' . $corSituacao . '">' . $turmaPessoa->getTurmaPessoaSituacaoAtiva()->getSituacao()->getNome() . '</span>';
								$idSituacao = $turmaPessoa->getTurmaPessoaSituacaoAtiva()->getSituacao()->getId();

								$html .= '<tr class="'.$corSituacao.'">';
								$html .= '<td class="text-center">' . $stringSituacao . '</td>';
								if ($this->entidade->getEntidadeTipo()->getId() === EntidadeTipo::igreja || $this->pessoa->getPessoaCursoAcessoAtivo() && ($this->pessoa->getPessoaCursoAcessoAtivo()->getCursoAcesso()->getId() === CursoAcesso::COORDENADOR ||
									$this->pessoa->getPessoaCursoAcessoAtivo()->getCursoAcesso()->getId() === CursoAcesso::SUPERVISOR ||
									$this->pessoa->getPessoaCursoAcessoAtivo()->getCursoAcesso()->getId() === CursoAcesso::FACILITADOR)) {
										$html .= '<td><a target="_blanck" href="/cursoAluno/' . $turmaPessoa->getId() . '" class="btn btn-xs btn-primary" >' . str_pad($turmaPessoa->getId(), 8, 0, STR_PAD_LEFT) . '</a></td>';
									}else{
										$html .= '<td><span class="label label-default">'.$turmaPessoa->getId().'</span></td>';
									}
								$html .= '<td>'. $turmaPessoa->getPessoa()->getNome() . '</td>';
								$html .= '<th class="text-center">' . $nomeEquipe . '</th>';
								if($this->postado['mostrarAulas'] == 1){
									foreach ($turma->getCurso()->getDisciplina() as $disciplina) {
										$mostrar = false;
										if ($turma->getTurmaAulaAtiva() && $turma->getTurmaAulaAtiva()->getAula()->getDisciplina()->getId() === $disciplina->getId()) {
											$mostrar = true;
										}
										if ($mostrar) {
											$aulaAtiva = $turma->getTurmaAulaAtiva()->getAula();
											foreach ($disciplina->getAulaOrdenadasPorPosicao() as $aula) {
												if($turma->getTurmaAulaAtiva()->getAula()->getId() === $aula->getId()){
													break;
												}

												$html .= '<td class="text-center">';
												if ($aula->getPosicao() <= ($aulaAtiva->getPosicao() - 1)) {
													$frequencia = false;
													$icone = 'fa-times';
													$corDoBotao = BotaoSimples::botaoMuitoPequenoPerigoso;

													if (count($turmaPessoa->getTurmaPessoaAula()) > 0) {
														foreach ($turmaPessoa->getTurmaPessoaAula() as $turmaPessoaAula) {
															if ($turmaPessoaAula->getAula()->getId() === $aula->getId()) {
																$frequencia = true;
																$icone = 'fa-check';
																$corDoBotao = BotaoSimples::botaoMuitoPequenoSucesso;
																if ($turmaPessoaAula->getReposicao() == 'S') {
																	$icone = 'fa-file';
																	$corDoBotao = BotaoSimples::botaoMuitoPequenoWarning;
																}
															}
														}
													}
												} else {
													$icone = 'fa-clock-o';
													$corDoBotao = BotaoSimples::botaoMuitoPequenoImportante;
												}

												$iconeBotao = '<i class="fa ' . $icone . '"></i>';
												$extra = ' disabled ';
												$html .= $this->botaoSimples($iconeBotao, $extra, $corDoBotao, BotaoSimples::posicaoAoCentro);
												$html .= '</td>';
											}
										}
									}
								}
								$html .= '</tr>';
							}
						}
					}
				}
			}

			$html .= '</tbody>';

			$html .= '</table>';
			$html .= '</div>';
		}
	}
}
$html .= '</div>';
$html .= '</div>';

echo $html;

?>
<script type="text/javascript">

function selecionarEquipe(){
	$('#loaderSub').removeClass('hidden')
	let idEquipe = $('#selecionaEquipe').val()
	if(idEquipe != 0){
		$.post(
			"/cursoBuscarSubs",
			{ id: idEquipe, },
			function (data) {
				$('#loaderSub').addClass('hidden')
				$('#selecionarSub').html('<option value="0">Todas</option>')
				data.filhos.map((filho) => $('#selecionarSub').append('<option value="'+filho.id+'">'+filho.informacao+'</option>'))
			}, 'json');
	}else{
		$('#loaderSub').addClass('hidden')
	}
}

</script>
