<?php

use Application\Controller\Helper\Constantes;

echo $this->doctype();
?>
<html lang="pt-BR">
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<?php
$NAME_APPLICATION = $this->translate(Constantes::$TRADUCAO_NOME_APLICACAO);
echo $this
	->headTitle($NAME_APPLICATION)
	->setSeparator(' - ')
	->setAutoEscape(false)
	;
?> 
		<!-- Meta Head -->
<?php
echo $this
	->headMeta()
	->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no')
	->appendName('theme-color', '#3498db')
	->appendName('google-site-verification', 'b4wOHXCDC8BakDzVfow_NeYwAGGBAEv-sCdKLsDAQUs')
	->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	;
?>
	</head>
	<body>
<?php
echo $this
	->headScript()
	->prependFile($this->basePath() . '/js/circuito_da_visao/jquery-barcode.js' . $versao)
	->prependFile($this->basePath() . '/vendor/jquery/jquery-1.11.1.min.js')
	;
echo $this->inlineScript();
foreach ($this->reposicoes as $reposicao) {
	$aula = $this->repositorio->getAulaORM()->encontrarPorId($reposicao['idAula']);
	$pessoa = $this->repositorio->getPessoaORM()->encontrarPorId($reposicao['idPessoa']);
	$grupoEquipe = $this->repositorio->getGrupoORM()->encontrarPorId($reposicao['idGrupoEquipe']);

	$labelAula = $aula->getDisciplina()->getNome() . ' - AULA ' . $aula->getPosicao() . ' - ' . $aula->getNome();
	$nomePessoa = $pessoa->getNome();
	$nomeEquipe = $grupoEquipe->getEntidadeAtiva()->infoEntidade();

	$codigoDeBarra = str_pad($reposicao['idTurmaPessoa'], 10, 0, STR_PAD_LEFT) . str_pad($reposicao['idAula'], 10, 0, STR_PAD_LEFT);
	echo '<div id="bcTarget' . $codigoDeBarra . '"  class="float-right"></div>';
	echo '<script type="text/javascript">$("#bcTarget' . $codigoDeBarra . '").barcode("' . $codigoDeBarra . '", "code93", {barWidth:2, barHeight:40}); </script>';
?>
			<div align="center">
				<p>REPOSI&Ccedil;&Atilde;O DE AULA - MATRÍCULA: <?php echo $reposicao['idTurmaPessoa']; ?></p>
				<p>EQUIPE: <?php echo "$nomeEquipe"; ?> - <?php echo $nomePessoa; ?> - DATA: <?php echo date("d/m/Y"); ?></p>
				<p><?php echo $labelAula; ?></p>
				<div>
					<fieldset>
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
						_______________________________________________________________________________________________<br />
					</fieldset>
				</div>
				<p>__________________________________________<br />ASSINATURA L&Iacute;DER</p>
				<p>__________________________________________<br />ASSINATURA ALUNO</p>
				<br />
				<fieldset>
					<p>COMPROVANTE DE ENTREGA - VIA L&Iacute;DER - MATRÍCULA: <?php echo $reposicao['idTurmaPessoa']; ?></p>
					<p>EQUIPE: <?php echo "$nomeEquipe"; ?> - <?php echo $nomePessoa; ?> - DATA: <?php echo date("d/m/Y"); ?></p>
					<p><?php echo $labelAula; ?></p> 
					<p>RECEBIDO POR:_________________________________________</p>
					<p> ASSINATURA:________________________</p>
				</fieldset>
			</div>
<?php
	echo '<div style="page-break-after: always"></div>';
}
?>
	</body>
</html>
