<?php

use Application\Controller\Helper\Funcoes;

echo $this
        ->headScript()
        ->prependFile($this->basePath() . '/js/circuito_da_visao/jquery-barcode.js' . $versao)
        ->prependFile($this->basePath() . '/vendor/jquery/jquery-1.11.1.min.js')
;
echo $this->inlineScript();
echo "<div style=\"page-break-before: always\"></div>";
foreach ($this->alunosId as $idTurmaPessoa) {
    if ($alinhamento == "right") {
        $alinhamento = "left";
    } else {
        $alinhamento = "right";
    }
    $turmaPessoa = $this->repositorio->getTurmaPessoaORM()->encontrarPorId($idTurmaPessoa);

    echo '<fieldset style="width: 8cm; height: 5cm; float: ' . $alinhamento . '; font-family: sans-serif; font-size: 10px;">';
    echo '<div align="center">';
    echo '<img style="padding: 10px;" src="/img/logos/logo_circuito.png" />';
    echo '</div>';
    echo '<hr />';
    echo '<div align="left">';
    echo 'Nome: ' . $turmaPessoa->getPessoa()->getNome() . '<br />';
    echo 'Equipe: ' . $turmaPessoa->getPessoa()->getGrupoPessoaAtivo()->getGrupo()->getEntidadeAtiva()->infoEntidade() . '<br />';
    echo 'Revis&atilde;o: ' . Funcoes::mesPorExtenso($turmaPessoa->getTurma()->getMes()) . '/' . $turmaPessoa->getTurma()->getAno() . '<br />';
    echo '</div>';
    echo '<br />';

    echo '<div align="center" style="margin-top: 20px;">';
    echo '<div id="code' . $turmaPessoa->getId() . '"></div>';
    echo '<script type="text/javascript">$("#code' . $turmaPessoa->getId() . '").barcode("' . $turmaPessoa->getId() . '", "code93", {barWidth: 2, barHeight: 40});</script>';
    echo '</div>';

    echo '</fieldset>';
    $cont8++;
    if ($cont8 == 8) {
        $cont8 = 0;
        echo "<div style=\"page-break-before: always\"></div>";
    }
}
echo $this->botaoSimples('IMPRIMIR', $this->funcaoOnClick('print()'));
