<?php

use Application\Controller\Helper\Funcoes;

echo $this->layoutJSFichaRevisao;
echo "<div style=\"page-break-before: always\"></div>";
foreach ($this->alunosId as $idTurmaPessoa) {
    if ($alinhamento == "right") {
        $alinhamento = "left";
    } else {
        $alinhamento = "right";
    }
    $turmaPessoa = $this->repositorio->getTurmaPessoaORM()->encontrarPorId($idTurmaPessoa);
    ?>
    <fieldset style="width: 8cm; height: 5cm; float: <?php echo $alinhamento; ?>; font-family: sans-serif; font-size: 10px;">
        <?php
        echo '<div style="display: block;">';
        echo '<div style="display: inline">';
        echo '<div id="qrcode' . $turmaPessoa->getId() . '" style="width:100px; height:100px; margin-top:15px; "></div>';
        echo '</div>';
        echo '</div>';
        echo '<div id="corpo" style="clear: both;">';
        echo '<hr />';
        echo '<div class="text-left">';
        echo 'Nome: ' . $turmaPessoa->getPessoa()->getNome() . '<br />';
        echo 'Equipe: ' . $turmaPessoa->getPessoa()->getGrupoPessoaAtivo()->getGrupo()->getEntidadeAtiva()->infoEntidade() . '<br />';
        echo 'Revis&atilde;o: ' . Funcoes::mesPorExtenso($turmaPessoa->getTurma()->getMes()) . '/' . $turmaPessoa->getTurma()->getAno() . '<br />';
        echo "</div>";


        echo '<script type="text/javascript">'
        . 'var qrcode = new QRCode(document.getElementById("qrcode' . $turmaPessoa->getId() . '"), {width: 100, height: 100});'
        . 'qrcode.makeCode("' . $turmaPessoa->getId() . '");'
        . '</script>';
        ?>
    </fieldset>

    <?php
    $cont8++;
    if ($cont8 == 8) {
        $cont8 = 0;
        echo "<div style=\"page-break-before: always\"></div>";
    }
}