<?php

use Application\Controller\Helper\Constantes;
use Application\Controller\Helper\Funcoes;

$html .= '<div class="mw1200 center-block p10">';
$html .= '<div class="panel heading-border panel-primary">';
$html .= '<div class="panel-body bg-light">';

$html .= '<div class="table-responsive">';
$html .= '<table class="table table-bordered table-condensed table-hover">';
$html .= '<thead>';
$html .= '<tr class="dark"><th colspan="'.(4+(count($this->turmasValidas)*2)).'">GERADOR DE FALTAS - ' . date('d/m/Y') . '</th></tr>';
$html .= '<tr class="dark">';
$html .= '<th></th>';
foreach($this->turmasValidas as $turma){
	$html .= '<th colspan="2">'.$this->translate(Funcoes::mesPorExtenso($turma->getMes(),1)).'/'.$turma->getAno().' - '. $turma->getTurmaAulaAtiva()->getAula()->getDisciplina()->getNome().'</th>';
}
$html .= '<th colspan="2"></th>';
$html .= '</tr>';
$html .= '<tr class="dark">';
$html .= '<th>Time</th>';
foreach($this->turmasValidas as $turma){
	$html .= '<th>Faltas</th>';
	$html .= '<th>Valor</th>';
}
$html .= '<th colspan="2">Total</th>';
$html .= '</tr>';
$html .= '</thead>';
$html .= '<tbody>';
$soma = 0;
foreach ($this->contadorDeFaltas as $key => $value) {
	$somaParcial = 0;
	$html .= '<tr>';
	$html .= '<td>' . $key . '</td>';
	foreach($this->turmasValidas as $turma){
		$quantidadeDeFaltas = $value[$turma->getId()];
		$soma += $quantidadeDeFaltas;
		$somaParcial += $quantidadeDeFaltas;
		$html .= '<td>' . $quantidadeDeFaltas . '</td>';
		$html .= '<td>' . number_format($quantidadeDeFaltas * Constantes::$VALOR_MULTA, 2, ',', '.') . '</td>';
	}
	$html .= '<td>' . $somaParcial . '</td>';
	$html .= '<td>' . number_format($somaParcial * Constantes::$VALOR_MULTA, 2, ',', '.') . '</td>';
	$html .= '</tr>';
}
$html .= '<tr class="dark">';
$html .= '<td class="text-right" colspan="'.(1+(count($this->turmasValidas)*2)).'">TOTAL</td>';
$html .= '<td>' . $soma . '</td>';
$html .= '<td>' . number_format($soma * Constantes::$VALOR_MULTA, 2, ',', '.') . '</td>';
$html .= '</tr>';
$html .= '</tbody>';
$html .= '</table>';

$html .= '</div>';
$html .= '</div>';
$html .= '</div>';
$html .= '</div>';
echo $html;
