<?php

use Application\View\Helper\BotaoSimples;

echo $this->templateFormularioTopo($this->titulo);
echo '<div class="panel-body bg-light">';
echo '<div class="block-center">';
echo '<div class="row">';
echo '<div class="col-lg-8 col-md-8 col-md-8 col-xs-8">';
echo '<input type="number" id="matricula" class="form-control" placeholder="Mátricula" onBlur="verificarMatricula()"/>';
echo '</div>';
echo '<div class="col-lg-4 col-md-4 col-md-4 col-xs-4">';
echo $this->botaoSimples('Pesquisar', $this->funcaoOnClick('verificarMatricula()'), BotaoSimples::botaoImportante, BotaoSimples::larguraMaxima);
echo '</div>';
echo '</div>';
echo '<div id="mensagem" class="row alert mt10 hidden"></div>';
echo '</div>';
echo '<div id="botaoLancar" class="col-lg-12 col-md-12 col-md-12 col-xs-12 hidden">';
echo '<input type="hidden" id="matriculaConsultada" />';
echo $this->botaoSimples('Lan&ccedil;ar', $this->funcaoOnClick('mudarFrequencia()'), BotaoSimples::botaoImportante, BotaoSimples::larguraMaxima);
echo '</div>';
echo $this->templateFormularioRodape();
?>

<script type="text/javascript">
document.getElementById('matricula').focus()

	function verificarMatricula() {
		let mensagem = $('#mensagem');
		let botaoLancar = $('#botaoLancar');
		mensagem.addClass('hidden');
		botaoLancar.addClass('hidden');
		let idTurmaPessoa = $('#matricula');
		if (idTurmaPessoa.val().length != 0) {
			$.post(
				"/cursoConsultarMatricula",
		{
			id: idTurmaPessoa.val(),
					},
					function (data) {
						if (data.response) {
							let informacaoAluno = '<p>Curso: ' + data.curso +
								'</p><p>Turma: ' + data.turma +
								'</p><p>Equipe: ' + data.equipe +
								'</p><p>Aluno: ' + data.pessoa +
								'</p><p>Matrícula: ' + idTurmaPessoa.val() + '</p>';
							mensagem
								.addClass('alert-info')
								.removeClass('alert-danger')
								.removeClass('hidden')
								.html(informacaoAluno);
							$('#matriculaConsultada').val(idTurmaPessoa.val());
							idTurmaPessoa.val('');
							botaoLancar.removeClass('hidden');
						} else {
							mensagem
								.addClass('alert-danger')
								.removeClass('alert-info')
								.removeClass('hidden')
								.html('Matrícula NÃO encontrada!');
						}
					}, 'json');
		} else {
			mensagem
				.addClass('alert-danger')
				.removeClass('alert-info')
				.removeClass('hidden')
				.html('Informe a Mátricula!');
		}
	}

	function mudarFrequencia() {
		let mensagem = $('#mensagem');
		mensagem.addClass('hidden');
		let matricula = $('#matriculaConsultada');
		let botaoLancar = $('#botaoLancar');
		if (matricula.val().length != 0) {
			let now = new Date;
			let matriculaDataEHora = matricula.val() + '_'
				+ now.getFullYear() + "-" + (now.getMonth() + 1) + "-" + now.getDate() + '_'
				+ now.getHours() + ':' + now.getMinutes() + ':' + now.getSeconds();
			mostrarSplash()
				$.post(
					"/migracaoReceberFrequencia",
		{
			id: matriculaDataEHora,
					},
					function (data) {
						$('#matricula').focus()
							esconderSplash()
							if (data.response) {
								mensagem
									.addClass('alert-info')
									.removeClass('alert-danger')
									.removeClass('hidden')
									.html('Frequência registrada com sucesso!');
								matricula.val('');
								botaoLancar.addClass('hidden');
						} else {
							mensagem
								.addClass('alert-danger')
								.removeClass('alert-info')
								.removeClass('hidden')
								.html('Frequência NÃO registrada!');
						}
					}, 'json');
		} else {
			mensagem
				.addClass('alert-danger')
				.removeClass('alert-info')
				.removeClass('hidden')
				.html('Informe a Mátricula!');
		}
	}
</script>
