<?php

use Application\View\Helper\BotaoSimples;
?>
<style type="text/css">
	table{
		font-size: 12px;
	}
</style>
<?php

$html = '';
$html .= '<blockquote class="blockquote-primary"><small>' . $this->translate('Cadastro de Professor') . '</small></blockquote>';
$html .= '<div class="panel heading-border panel-primary">';
$html .= '<div class="panel-body bg-light">';
$html .= '<p class="text-center">TURMA '.$this->turmaAula->getTurma()->getCurso()->getNome().' - '.str_pad($this->turmaAula->getTurma()->getMes(), 2, 0, STR_PAD_LEFT).'/'.$this->turmaAula->getTurma()->getAno().'</p>';
$html .= '<p class="text-center">AULA ABERTA - AULA '.$this->turmaAula->getAula()->getPosicao().'</p>';

$html .= '<form method="post" action="/cursoLiberarSalvar">';
$html .= '<input type="hidden" id="idTurmaAula" name="idTurmaAula" value="'.$this->turmaAula->getId().'" />';

$html .= '<div class="form-group">';
$html .= '<label for="selecionaEquipe">' . $this->translate('Informe a Palavra Chave') . '</label>';
$html .= '<input type="text" class="form-control" name="chave" id="chave" /> ';
$html .= '</div>';

$html .= $this->botaoSimples('LIBERAR', $this->funcaoOnClick('validar(this.form)'), BotaoSimples::botaoSucesso, BotaoSimples::larguraMaxima);

$html .= '</form>';

$html .= '</div>';
$html .= '</div>';

echo $html;

?>
<script type="text/javascript">

function validar(form){
	if(form.chave.value === ''){
		alert('Informe a Palavra Chave')
		return false
	}
	mostrarSplash(); 
	form.submit()
}

</script>
