<?php

use Application\Controller\Helper\Funcoes;

echo $this->templateFormularioTopo('Pagamentos feitos pelos alunos');
?>
	<div class="panel-body bg-light" style="padding: 15px 5px 5px 5px;">
<?php
$url = $this->mes . '/' . $this->ano;
echo '<form action="/cursoPagamentos/' . $url . '" method="post">';
$mesInicial = 1;
$mesFinal = 12;
$anoInicial = 2020;
$anoFinal = date('Y');

?>
<div class="row p5">
	<div class="col-lg-1 col-md-1 col-sm-1 col-xs-12 pb10 pt10">Mês</div>
		<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
			<select name="mes" id="mes" class="form-control">
<?php 
for ($indice = $mesInicial; $indice <= $mesFinal; $indice++) {
	$selected = '';
	if ($this->mes == $indice) {
		$selected = 'selected';
	}

	echo '<option value="' . $indice . '" ' . $selected . '>' . Funcoes::mesPorExtenso($indice, 1) . '</option>';
}
?>
			</select>
		</div>
		<div class="col-lg-1 col-md-1 col-sm-1 col-xs-12 pb10 pt10">Ano</div>
		<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
			<select name="ano" id="ano" class="form-control">
<?php 					
for ($indice = $anoFinal; $indice >= $anoInicial; $indice--) {
	$selected = '';
	if ($this->ano == $indice) {
		$selected = 'selected';
	}
	echo '<option value="' . $indice . '" ' . $selected . '>' . $indice . '</option>';
}
?>
			</select>
		</div>
<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
	<button type="button" onclick="this.form.submit();" class="btn ladda-button btn-primary btn-block " data-style="zoom-in">
	<span class="ladda-label">Filtrar</span>
	<span class="ladda-spinner"></span>
	</button>
	</div>
	</div>
<?php
echo '</form>';

if(count($this->contadorDePagamentos) > 0){
?>
<div class="p5">
<table class="text-center table table-condensed table-hover bg-light" style="font-size:8px;">
<thead>
<tr class="dark">
<th>TIME</th>
<th>VALOR</th>
</tr>
</thead>
<tbody>
<?php 
$html = '';
$soma = 0;
foreach ($this->contadorDePagamentos as $key => $value) {
	$html .= '<tr>';
	$html .= '<td>' . $key . '</td>';
	$html .= '<td>' . number_format($value, 2, ',', '.') . '</td>';
	$html .= '</tr>';
	$soma += $value;
}
$html .= '<tr class="dark">';
$html .= '<td class="text-right">TOTAL</td>';
$html .= '<td>' . number_format($soma, 2, ',', '.') . '</td>';
$html .= '</tr>';
echo $html;
?>
</tbody>
</table>
<?php }else{
echo '<div class="alert alert-warning m5">Sem pagamento para o periíodo</div>';
} ?>

</div>
</div>
<?php
echo $this->templateFormularioRodape();
?>
