<?php

use Application\View\Helper\BotaoSimples;
use Application\View\Helper\FiltroCurso;
?>
<style type="text/css">
	table{
		font-size: 12px;
	}
</style>
<?php

$html = '';
$html .= '<blockquote class="blockquote-primary"><small>' . $this->translate('Professores') . '</small></blockquote>';
$html .= '<div class="panel heading-border panel-primary">';
$html .= '<div class="panel-body bg-light">';
$html .= '<table class="table table-condensed">';
$html .= '<thead>';
$html .= '<tr>';
$html .= '<td>Curso</td>';
$html .= '<td>Mês/Ano</td>';
$html .= '<td>Observação</td>';
$html .= '<td>Adicionar</td>';
$html .= '</tr>';
$html .= '</thead>';
$html .= '<tbody>';
foreach($this->turmas as $turma){
	$html .= '<tr class="dark">';
	$html .= '<td>'.$turma->getCurso()->getNome().'</td>';
	$html .= '<td>'.str_pad($turma->getMes(), 2, 0, STR_PAD_LEFT).'/'.$turma->getAno().'</td>';
	$html .= '<td>'.$turma->getObservacao().'</td>';
	$html .= '<td><button type="button" class="btn btn-primary btn-xs" onClick="funcaoCircuito(\'cursoProfessor\', '.$turma->getId().')">Adicionar</button></td>';
	$html .= '</tr>';
	$turmaProfessores = $turma->getTurmaProfessor();
	if($turmaProfessores && count($turmaProfessores)){
		foreach($turmaProfessores as $turmaProfessor){
			$html .= '<tr>';
			$html .= '<td colspan="4" class="text-center">'.$turmaProfessor->getPessoa()->getNome().'</td>';
			$html .= '</tr>';
		}
	}else{
		$html .= '<tr>';
		$html .= '<td colspan="4" class="text-center">Sem Professores Cadastrados!</td>';
		$html .= '</tr>';
	}
	$html .= '<tr>';
	$html .= '<td colspan="4" class="text-center"></td>';
	$html .= '</tr>';
}
$html .= '</tbody>';
$html .= '</table>';

$html .= '</div>';
$html .= '</div>';

echo $html;
