<?php

use Application\Controller\Helper\Constantes;
echo $this->doctype();
?>

<html lang="pt-BR">
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<?php
$NAME_APPLICATION = $this->translate(Constantes::$TRADUCAO_NOME_APLICACAO);
echo $this
	->headTitle($NAME_APPLICATION)
	->setSeparator(' - ')
	->setAutoEscape(false)
	;
?>
		<!-- Meta Head -->
<?php
echo $this
	->headMeta()
	->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no')
	->appendName('theme-color', '#3498db')
	->appendName('google-site-verification', 'b4wOHXCDC8BakDzVfow_NeYwAGGBAEv-sCdKLsDAQUs')
	->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	;
?>
	</head>
	<body>
<div align="center">
<filedset style="width: 500px">
<legend>Recibo de Pagamento</legend>
<p>Matrícula: <?php echo $this->turmaPessoa->getId(); ?></p>
<p>Aluno: <?php echo $this->turmaPessoa->getPessoa()->getNome(); ?></p>
<p>Time: <?php echo $this->turmaPessoa->getPessoa()->getGrupoPessoaAtivo()->getGrupo()->getEntidadeAtiva()->infoEntidade(); ?></p>
<p>Referente a: <?php echo $this->disciplina->getNome(); ?></p>
<p>Mensalidade: <?php echo $this->mensalidade; ?></p>
<p>Data: <?php echo date('d/m/Y'); ?></p>
<p>Financeiro</p>
<p>_________________________________________________</p>
</filedset>
<hr />
<filedset style="width: 500px">
<legend>Recibo de Pagamento</legend>
<p>Matrícula: <?php echo $this->turmaPessoa->getId(); ?></p>
<p>Aluno: <?php echo $this->turmaPessoa->getPessoa()->getNome(); ?></p>
<p>Time: <?php echo $this->turmaPessoa->getPessoa()->getGrupoPessoaAtivo()->getGrupo()->getEntidadeAtiva()->infoEntidade(); ?></p>
<p>Referente a: <?php echo $this->disciplina->getNome(); ?></p>
<p>Mensalidade: <?php echo $this->mensalidade; ?></p>
<p>Data: <?php echo date('d/m/Y'); ?></p>
<p>Financeiro</p>
<p>_________________________________________________</p>
</filedset>
</div>
	</body>
</html>
