<?php

use Application\Controller\Helper\Constantes;

/**
 * Nome: cadastrar-pessoa-revisao.phtml
 * @author Lucas Filipe de Carvalho Cunha <lucascarvalho.esw@gmail.com>
 * Descricao: Página de cadastro de pessoa para o revisao de vidas.
 */
$form = $this->formulario;
$form->prepare();
$form->setAttribute(Constantes::$ACTION, $this->url(Constantes::$ROUTE_CURSO, array(Constantes::$ACTION => 'ReentradaFinalizar')));
echo $this->templateFormularioTopo($this->titulo);
echo $this->form()->openTag($form);
?>
<div class="panel-body bg-light">
    <?php
    echo $this->divMensagens();
    echo $this->formHidden($form->get(Constantes::$ID . 'Turma'));
    echo $this->inputFormularioSimples(Constantes::$TRADUCAO_PRIMEIRO_NOME, $form->get(Constantes::$INPUT_PRIMEIRO_NOME), 6);
    echo $this->inputFormularioSimples(Constantes::$TRADUCAO_ULTIMO_NOME, $form->get(Constantes::$INPUT_ULTIMO_NOME), 6);
    echo $this->inputFormularioSimples(Constantes::$TRADUCAO_DDD, $form->get(Constantes::$INPUT_DDD), 3);
    echo $this->inputFormularioSimples(Constantes::$TRADUCAO_TELEFONE, $form->get(Constantes::$INPUT_TELEFONE), 9);
    echo $this->inputFormularioSimples(Constantes::$TRADUCAO_DATA_NASCIMENTO, $form->get(Constantes::$FORM_INPUT_DIA), 4, 2);
    echo $this->inputFormularioSimples('&nbsp;', $form->get(Constantes::$FORM_INPUT_MES), 4, 2);
    echo $this->inputFormularioSimples('&nbsp;', $form->get(Constantes::$FORM_INPUT_ANO), 4, 2);
    echo $this->inputFormularioSimples(Constantes::$TRADUCAO_SEXO, $form->get(Constantes::$INPUT_NUCLEO_PERFEITO), null, 3);
    echo $this->inputFormularioSimples('SELECIONE A TURMA', $form->get(Constantes::$INPUT_ID_TURMA), null, 2);
    echo $this->inputFormularioSimples('SELECIONE O LÍDER', $form->get(Constantes::$INPUT_ID_GRUPO), null, 2);
    ?>
</div>
<!-- end .form-body section -->
<div class="panel-footer text-right">
    <?php echo $this->formHidden($form->get(Constantes::$FORM_ID)); ?>
    <?php echo $this->formHidden($form->get(Constantes::$INPUT_CSRF)); ?>
    <?php
    $stringNomeDaFuncaoOnClickCadastro = 'mostrarSplash(); funcaoCircuito("cursoListarTurma", 0)';
    echo $this->botaoLink($this->translate(Constantes::$TRADUCAO_VOLTAR), Constantes::$STRING_HASHTAG, 2, $this->funcaoOnClick($stringNomeDaFuncaoOnClickCadastro));
    ?>
    <?php
    /* Submit */
    $funcaoVerificarCadastroPessoa = $this->funcaoOnClick('validar(this.form)');
    echo $this->botaoSimples(Constantes::$TRADUCAO_CADASTRAR, $funcaoVerificarCadastroPessoa);
    ?>
</div>
<?php
echo $this->templateFormularioRodape();
echo $this->form()->closeTag();
/* Layout com javascript para tela de index */
echo $this->layoutJSCadastrarPessoaRevisao;
?>
<script type="text/javascript">
    function validar(form) {
        let primeiroNome = $('#primeiro-nome').val();
        let ultimoNome = $('#ultimo-nome').val();
        let ddd = $('#ddd').val();
        let telefone = $('#telefone').val();
        let Dia = $('#Dia').val();
        let Mes = $('#Mes').val();
        let Ano = $('#Ano').val();
        let idGrupo = $('#idGrupo').val();

        let temErro = false;
        let divMensagens = $('#divMensagens');
        let mensagem = '';
        let mensagemReal = '';

        if (primeiroNome.length === 0) {
            temErro = true;
            if (mensagem !== '') {
                mensagem += ', ';
            }
            mensagem += 'Primeiro Nome';
        } else {
            let reg = /^[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ ]+$/;
            if (!reg.exec(primeiroNome)) {
                temErro = true;
                if (mensagem !== '') {
                    mensagem += ', ';
                }
                mensagem += 'Primeiro Nome Inválido';
            }
            if (primeiroNome.length > 15) {
                temErro = true;
                if (mensagem !== '') {
                    mensagem += ', ';
                }
                mensagem += 'Primeiro Nome pode ter no máximo 15 caracteres';
            }
        }

        if (ultimoNome.length === 0) {
            temErro = true;
            if (mensagem !== '') {
                mensagem += ', ';
            }
            mensagem += 'Último Nome';
        } else {
            let reg = /^[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ ]+$/;
            if (!reg.exec(ultimoNome)) {
                temErro = true;
                if (mensagem !== '') {
                    mensagem += ', ';
                }
                mensagem += 'Último Nome Inválido';
            }
            if (ultimoNome.length > 15) {
                temErro = true;
                if (mensagem !== '') {
                    mensagem += ', ';
                }
                mensagem += 'Último Nome pode ter no máximo 15 caracteres';
            }
        }

        if (ddd.length === 0) {
            temErro = true;
            if (mensagem !== '') {
                mensagem += ', ';
            }
            mensagem += 'DDD';
        } else {
            if (ddd.length !== 2) {
                temErro = true;
                if (mensagem !== '') {
                    mensagem += ', ';
                }
                mensagem += 'DDD Inválido';
            }
        }
        if (telefone.length === 0) {
            temErro = true;
            if (mensagem !== '') {
                mensagem += ', ';
            }
            mensagem += 'Telefone';
        } else {
            if (!(telefone.length >= 8 && telefone.length <= 9)) {
                temErro = true;
                if (mensagem !== '') {
                    mensagem += ', ';
                }
                mensagem += 'Telefone Inválido';
            }
        }


        if (Dia === '0') {

            temErro = true;
            if (mensagem == '') {
                mensagem = 'Dia';
            } else {
                mensagem += ', Dia';
            }
        }
        if (Mes === '0') {
            temErro = true;
            if (mensagem == '') {
                mensagem = 'Mês';
            } else {
                mensagem += ', Mês';
            }
        }
        if (Ano === '0') {
            temErro = true;
            if (mensagem == '') {
                mensagem = 'Ano';
            } else {
                mensagem += ', Ano';
            }
        }

        if (!$("input[type='radio'][name='nucleoPerfeito']").is(':checked')) {
            temErro = true;
            if (mensagem == '') {
                mensagem = 'Sexo';
            } else {
                mensagem += ', Sexo';
            }

        }

        if (idGrupo === '0') {
            temErro = true;
            if (mensagem == '') {
                mensagem = 'Líder';
            } else {
                mensagem += ', Líder';
            }
        }

        if (temErro) {
            mensagemReal = 'Preencha o(s) seguinte(s) campo(s): ' + mensagem;
            divMensagens
                    .html(mensagemReal)
                    .removeClass('alert-success')
                    .removeClass('hidden')
                    .addClass('alert-danger');
        } else {
            mostrarSplash();
            divMensagens
                    .addClass('hidden');
            form.submit();
        }
    }
</script>
