<?php

use Application\Controller\Helper\Constantes;
use Application\Controller\Helper\Funcoes;
use Application\Controller\CursoController;
use Application\Model\Entity\Situacao;
use Application\View\Helper\BotaoSimples;
use Application\View\Helper\FiltroCursos;

$html = '';
$html .= '<blockquote class="blockquote-primary"><small>' . $this->translate('Gerar Carterinhas') . '</small></blockquote>';
$html .= '<div class="panel heading-border panel-primary">';
$html .= '<div class="panel-body bg-light">';

$html .= $this->filtroCursos("cursoSelecionarParaCarterinha");

$form = $this->formulario;
$form->prepare();
$form->setAttribute(Constantes::$ACTION, $this->url(Constantes::$ROUTE_CURSO, array(Constantes::$ACTION => 'GerarCarterinha')));
$form->setAttribute('target', '_blanck');
$html .= $this->form()->openTag($form);

if($this->filtrado){
	$html .= '<div class="text-center m20">';
	$funcao = $this->funcaoOnClick('this.form.submit()');
	$html .= $this->botaoSimples('Gerar Carterinha', $funcao, '', BotaoSimples::posicaoAoCentro);
	$html .= '</div>';

	$html .= '<input id="fooFilter" type="text" class="form-control mt20" placeholder="Filtro">';
	foreach ($this->turmas as $turma) {
		if($this->postado['idTurma'] == 0 || $turma->getId() == $this->postado['idTurma']){
			$html .= '<div class="table-responsive">';
			$html .= '<table  class="table table-bordered table-condensed footable" data-filter="#fooFilter">';

			$html .= '<thead>';
			$html .= '<tr>';
			$html .= '<th colspan="3" class="text-center">' . $turma->getCurso()->getNome() . ' - ' . Funcoes::mesPorExtenso($turma->getMes()) . '/' . $turma->getAno() . '</th>';
			foreach ($turma->getCurso()->getDisciplina() as $disciplina) {
				$mostrar = false;
				if ($turma->getTurmaAulaAtiva() && $turma->getTurmaAulaAtiva()->getAula()->getDisciplina()->getId() === $disciplina->getId()) {
					$mostrar = true;
				}
				if ($mostrar) {
					$html .= '<th colspan="2" class="text-center">' . $disciplina->getNome() . '</th>';
				}
			}
			$html .= '</tr>';
			$html .= '<tr>';
			$html .= '<th class="text-center">Situa&ccedil;&atilde;o</th>';
			$html .= '<th class="text-center">Matricula</th>';
			$html .= '<th class="text-center">Aluno</th>';
			$html .= '<th class="text-center">Equipe</th>';
			$html .= '<td class="text-center"><input type="checkbox" onClick="marcarTodos(this);" /></td>';
			$html .= '</tr>';
			$html .= '</thead>';

			$html .= '<tbody>';
			if ($turma->getTurmaPessoa()) {
				foreach ($turma->getTurmaPessoa() as $turmaPessoa) {
					$mostrar = false;
					if ($this->postado['idEquipe'] == 0) {
						$mostrar = true;
					} else {
						if ($turmaPessoa->getPessoa()->getGrupoPessoaAtivo()) {
							if($turmaPessoa->getPessoa()->getGrupoPessoaAtivo()->getGrupo()->getGrupoEquipe()->getId() == $this->postado['idEquipe']){
								$mostrar = true;
							}
						}
					}
					if ($mostrar) {
						$fatoCurso = $this->repositorio->getFatoCursoORM()->encontrarFatoCursoPorTurmaPessoa($turmaPessoa->getId())[0];															
						if(!$fatoCurso){
							$fatoCurso = $this->repositorio->getFatoCursoORM()->encontrarUltimoFatoCursoPorTurmaPessoa($turmaPessoa->getId());
						}
						$idGrupo = substr($fatoCurso->getNumero_identificador(), (count($fatoCurso->getNumero_identificador())-8));
						$nomeEquipe = 'TIME INATIVADO';
						if($grupo = $this->repositorio->getGrupoORM()->encontrarPorId($idGrupo)){
							if($grupo->getEntidadeAtiva()){
								$nomeEquipe = $grupo->getEntidadeAtiva()->infoEntidade();
							}
							if($nomeEquipe == ''){
								$nomeEquipe = $grupo->getGrupoEquipe()->getEntidadeAtiva()->getNome();
							}						
						}

						$mostrarSituacao = false;
						switch ($turmaPessoa->getTurmaPessoaSituacaoAtiva()->getSituacao()->getId()) {
						case Situacao::ESPECIAL:
							$corSituacao = 'primary';
							$mostrarSituacao = true;
							break;
						case Situacao::DESISTENTE:
							$mostrarSituacao = false;
							break;
						case Situacao::REPROVADO_POR_FALTA:
							$mostrarSituacao = false;
							break;
						default:
							$corSituacao = 'success';
							$mostrarSituacao = true;
						}

						if($mostrarSituacao){
							$stringSituacao = '<span class="label label-' . $corSituacao . '">' . $turmaPessoa->getTurmaPessoaSituacaoAtiva()->getSituacao()->getNome() . '</span>';
							$idSituacao = $turmaPessoa->getTurmaPessoaSituacaoAtiva()->getSituacao()->getId();

							$html .= '<tr class="'.$corSituacao.'">';
							$html .= '<td class="text-center">' . $stringSituacao . '</td>';
							$html .= '<td><span class="label label-default">'.$turmaPessoa->getId().'</span></td>';
							$html .= '<td>'. $turmaPessoa->getPessoa()->getNome() . '</td>';
							$html .= '<td class="text-center">' . $nomeEquipe . '</td>';
							$html .= '<td class="text-center"><input type="checkbox" id="aluno' . $turmaPessoa->getId() . '" name="aluno' . $turmaPessoa->getId() . '" value="' . $turmaPessoa->getId() . '"/></td>';
							$html .= '</tr>';
						}
					}
				}
			}
			$html .= '</tbody>';
			$html .= '</table>';
			$html .= '</div>';
		}
	}
	$html .= '<div class="text-center mt20">';
	$html .= $this->botaoSimples('Gerar Carterinha', $funcao, '', BotaoSimples::posicaoAoCentro);
	$html .= '</div>';
}
$html .= '</div>';
$html .= '</div>';

$html .= $this->form()->closeTag();

echo $html;
