<?php

use Application\Controller\Helper\Constantes;
use Application\Controller\CursoController;
use Application\View\Helper\BotaoSimples;

$html = '';
$html .= '<blockquote class="blockquote-primary"><small>' . $this->translate('Gerar Reposições') . '</small></blockquote>';
$html .= '<div class="panel heading-border panel-primary">';
$html .= '<div class="panel-body bg-light">';

$html .= $this->filtroCursos('cursoSelecionarReposicoes');

if($this->filtrado){
	$form = $this->formulario;
	$form->prepare();
	$form->setAttribute(Constantes::$ACTION, $this->url(Constantes::$ROUTE_CURSO, array(Constantes::$ACTION => 'GerarReposicao')));
	$form->setAttribute('target', '_blanck');
	$html .= $this->form()->openTag($form);

	$html .= '<div class="text-center m20">';
	$funcao = $this->funcaoOnClick('this.form.submit()');
	$html .= $this->botaoSimples('Gerar Reposi&ccedil;&atilde;o', $funcao, '', BotaoSimples::posicaoAoCentro);
	$html .= '</div>';

	$html .= '<input id="fooFilter" type="text" class="form-control mt20" placeholder="Filtro">';
	foreach ($this->turmasFiltradas as $turma) {
		if($turma->getTurmaAulaAtiva()){

			$html .= '<table  class="table table-bordered table-condensed footable" data-filter="#fooFilter">';

			$html .= '<thead>';
			$html .= '<tr>';
			$html .= '<th colspan="4" class="text-center">' . $turma->getCurso()->getNome() . ' - ' . str_pad($turma->getMes(), 2, 0, STR_PAD_LEFT) . '/' . $turma->getAno() . ' - ' . $turma->getTurmaAulaAtiva()->getAula()->getDisciplina()->getNome() . '</th>';
			$html .= '</tr>';
			$html .= '<tr>';
			$html .= '<th class="text-center">Matricula</th>';
			$html .= '<th class="text-center">Aluno</th>';
			$html .= '<th class="text-center">Time</th>';
			$html .= '<td>Marcar Todos <input type="checkbox" onclick="marcarTodos(this);"/></td>';
			$html .= '</tr>';

			$html .= '</thead>';
			$html .= '<tbody>';
			if (count($this->alunosComReposições[$turma->getId()]) > 0) {
				foreach ($this->alunosComReposições[$turma->getId()] as $turmaPessoa) {
					$mostrar = true;
					if ($mostrar) {						
						$fatoCurso = $this->repositorio->getFatoCursoORM()->encontrarFatoCursoPorTurmaPessoa($turmaPessoa->getId())[0];
						$idGrupo = substr($fatoCurso->getNumero_identificador(), (count($fatoCurso->getNumero_identificador())-8));
						$grupo = $this->repositorio->getGrupoORM()->encontrarPorId($idGrupo);
						$nomeEquipe = '';
						if($grupo && $grupo->getEntidadeAtiva()){
							$nomeEquipe = $grupo->getEntidadeAtiva()->infoEntidade();
						}
						if($nomeEquipe == ''){
							if($grupo && $grupo->getEntidadeAtiva()){
								$nomeEquipe = $grupo->getGrupoEquipe()->getEntidadeAtiva()->getNome();
							}
						}
						$html .= '<tr>';
						$html .= '<td>' . $turmaPessoa->getId() . '</td>';
						$html .= '<td>' . $turmaPessoa->getPessoa()->getNome() . '</td>';
						$html .= '<td>' . $nomeEquipe. '</td>';
						$html .= '<td>';
						foreach ($this->faltas[$turma->getId()][$turmaPessoa->getId()] as $falta) {
							$html .= $falta[0] . ' <input type="checkbox" id="aula' . $falta[1] . '_' . $turmaPessoa->GetId() . '" name="aula' . $falta[1] . '_' . $turmaPessoa->getId() . '" value="' . $falta[1] . '_' . $turmaPessoa->getId() . '"/> | ';
						}
						$html .= '</td>';
						$html .= '</tr>';
					}
				}
			}
			$html .= '</tbody>';
			$html .= '</table>';
		}
	}
	$html .= '<div class="text-center mt20">';
	$html .= $this->botaoSimples('Gerar Reposi&ccedil;&atilde;o', $funcao, '', BotaoSimples::posicaoAoCentro);
	$html .= '</div>';

	$html .= '</div>';
	$html .= '</div>';
	$html .= '</div>';
	$html .= $this->form()->closeTag();
}
echo $html;
