<?php

use Application\Controller\Helper\Constantes;
use Application\View\Helper\BotaoSimples;

$form = $this->formulario;
$form->prepare();
$form->setAttribute(Constantes::$ACTION, $this->url(Constantes::$ROUTE_CURSO, array(Constantes::$ACTION => 'GerarCarterinha')));
$form->setAttribute('target', '_blanck');
$html = '';
$html .= $this->form()->openTag($form);
$html .= '<div class="mw800 center-block p10 mt40">';
$html .= '<div class="panel heading-border panel-primary">';
$html .= '<div class="panel-body bg-light">';

$html .= '<div class="text-center m20">';
$funcao = $this->funcaoOnClick('this.form.submit()');
$html .= $this->botaoSimples('Gerar Carterinha', $funcao, '', BotaoSimples::posicaoAoCentro);
$html .= '</div>';

foreach ($this->turmas as $turma) {
	$html .= '<h2>Turma ' . $turma->getCurso()->getNome() . ' - ' . str_pad($turma->getMes(), 2, 0, STR_PAD_LEFT) . '/' . $turma->getAno();
	$html .= $this->botaoSimples('Ver turma', $this->funcaoOnClick('$("#turma'.$turma->getId().'").toggleClass("hidden")')) . '</h2>';
	$html .= '<table class="table table-bordered table-condensed hidden" id="turma'.$turma->getId().'">';

	$html .= '<thead>';
	$html .= '<tr>';
	$html .= '<th colspan="3" class="text-center">' . $turma->getCurso()->getNome() . ' - ' . str_pad($turma->getMes(), 2, 0, STR_PAD_LEFT) . '/' . $turma->getAno() . '</th>';
	$html .= '</tr>';
	$html .= '<tr>';
	$html .= '<th class="text-center">Matricula</th>';
	$html .= '<th class="text-center">Aluno</th>';
	$html .= '<th class="text-center"><input type="checkbox" onclick="marcarTodos(this);"/></th>';
	$html .= '</tr>';


	$html .= '</thead>';

	$html .= '<tbody>';
	if ($turma->getTurmaPessoa()) {
		foreach ($turma->getTurmaPessoa() as $turmaPessoa) {
			$mostrar = true;
			if ($mostrar) {
				$html .= '<tr>';
				$html .= '<td>' . str_pad($turmaPessoa->getId(), 8, 0, STR_PAD_LEFT) . '</td>';
				$html .= '<td>' . $turmaPessoa->getPessoa()->getNome() . '</td>';
				$html .= '<td class="text-center"><input type="checkbox" id="aluno' . $turmaPessoa->getId() . '" name="aluno' . $turmaPessoa->getId() . '" value="' . $turmaPessoa->getId() . '"/></td>';
				$html .= '</tr>';
			}
		}
	}

	$html .= '</tbody>';

	$html .= '</table>';
}

$html .= '<div class="text-center mt20">';
$html .= $this->botaoSimples('Gerar Carterinha', $funcao, '', BotaoSimples::posicaoAoCentro);
$html .= '</div>';

$html .= '</div>';
$html .= '</div>';
$html .= '</div>';

$html .= $this->form()->closeTag();

echo $html;

