<?php

use Application\Controller\Helper\Constantes;
use Application\View\Helper\BotaoSimples;

$form = $this->formulario;
$form->prepare();
$form->setAttribute(Constantes::$ACTION, $this->url(Constantes::$ROUTE_CURSO, array(Constantes::$ACTION => 'GerarReposicao')));
$html = '';
$html .= $this->form()->openTag($form);
$html .= '<div class="mw1200 center-block p10 mt40">';
$html .= '<div class="panel heading-border panel-primary">';
$html .= '<div class="panel-body bg-light">';
$funcao = $this->funcaoOnClick('mostrarSplash(); this.form.submit()');
$html .= $this->botaoSimples('Gerar Reposi&ccedil;&atilde;o', $funcao, '', BotaoSimples::posicaoAoCentro);

foreach ($this->turmas as $turma) {
    $html .= '<table class="table table-bordered table-condensed">';

    $html .= '<thead>';
    $html .= '<tr>';
    $html .= '<th colspan="2" class="text-center">' . $turma->getCurso()->getNome() . ' - ' . str_pad($turma->getMes(), 2, 0, STR_PAD_LEFT) . '/' . $turma->getAno() . '</th>';
    $html .= '</tr>';
    $html .= '<tr>';
    $html .= '<th class="text-center">Matricula</th>';
    $html .= '<th class="text-center">Aluno</th>';
    $html .= '<th class="text-center">Marcar Todos <input type="checkbox" onclick="marcarTodos(this);"/></th>';
    $html .= '</tr>';


    $html .= '</thead>';

    $html .= '<tbody>';
    if ($turma->getTurmaPessoa()) {
        $alunosComReposições = array();
        $turmaAulaAtiva = $turma->getTurmaAulaAtiva();
        $faltas = array();

        $teste[] = $turma->getTurmaPessoa()[0];
        $teste[] = $turma->getTurmaPessoa()[1];
//        foreach ($turma->getTurmaPessoa() as $turmaPessoa) {    
        foreach ($teste as $turmaPessoa) {
            $mostrar = false;
            $turmaPessoaAulas = $turmaPessoa->getTurmaPessoaAula();
            $parar = false;
            foreach ($turma->getCurso()->getDisciplina() as $disciplina) {
                if (!$parar) {
                    foreach ($disciplina->getAula() as $aula) {
                        $naoEncontreiPresencaNaAula = true;
                        foreach ($turmaPessoaAulas as $turmaPessoaAula) {
                            if ($turmaPessoaAula->getAula()->getId() === $aula->getId()) {
                                $naoEncontreiPresencaNaAula = false;
                            }
                        }
                        if ($naoEncontreiPresencaNaAula) {
                            $mostrar = true;
                            $faltas[$turmaPessoa->getId()][] = [$aula->getDisciplina()->getNome() . ' Aula ' . $aula->getPosicao(), $aula->getId()];
                        }
                        if ($aula->getId() == $turmaAulaAtiva->getAula()->getId()) {
                            $parar = true;
                            break;
                        }
                    }
                }
            }
            if ($mostrar) {
                $alunosComReposições[] = $turmaPessoa;
            }
        }
        if (count($alunosComReposições) > 0) {
            foreach ($alunosComReposições as $turmaPessoa) {
                $mostrar = true;
                if ($mostrar) {
                    $html .= '<tr>';
                    $html .= '<td>' . str_pad($turmaPessoa->getId(), 8, 0, STR_PAD_LEFT) . '</td>';
                    $html .= '<td>' . $turmaPessoa->getPessoa()->getNome() . '</td>';
                    $html .= '<td>';
                    foreach ($faltas[$turmaPessoa->getId()] as $falta) {
                        $html .= $falta[0] . ' <input type="checkbox" id="aula' . $falta[1] . '" name="aula' . $falta[1] . '" value="' . $falta[1] . '_' . $turmaPessoa->getId() . '"/> | ';
                    }
                    $html .= '</td>';
                    $html .= '</tr>';
                }
            }
        }
    }

    $html .= '</tbody>';

    $html .= '</table>';
}
$html .= '</div>';
$html .= '</div>';
$html .= '</div>';
$html .= $this->form()->closeTag();

echo $html;

