<?php

use Application\Controller\Helper\Constantes;

/**
 * Nome: selecionar_revisionistas.phtml
 * @author Lucas Filipe de Carvalho Cunha <lucsacarvalho.esw@gmail.com>
 * Descricao: Página de listagem de pessoas para o Revisao
 */
?>
<form class="mt50" id="form" action="cursoCadastrarTurmaPessoa" method="post">
    <input type="hidden" name="idEvento" id="idEvento" value="<?php echo $this->evento->getId(); ?>" />
    <?php
    /* Monta a listagem de eventos baseada no tipo do Evento passado */
    echo $this->listagemPessoasRevisao();
    ?>
</form>
<div class="mw1200 center-block hidden" id="painelExcluidos">
    <div class="admin-form theme-primary">
        <div class="panel-body bg-light">
            <div class="section-divider">
                <span>
                    <?php
                    echo "Adicionar essas pessoas a turma?";
                    ?>
                </span>
            </div>
            <div class="panel heading-border panel-primary">
                <div class="panel-body">
                    <div id="pessoasSelecionadas"></div>
                </div>
            </div>
            <div id="divBotaoVoltar" class="panel-footer text-right" style="height:65px;">
                <?php
                $stringNomeDaFuncaoOnClickVoltar = 'mostrarAlunos()';
                echo $this->botaoLink($this->translate(Constantes::$TRADUCAO_VOLTAR), Constantes::$STRING_HASHTAG, 2, $this->funcaoOnClick($stringNomeDaFuncaoOnClickVoltar));
                $stringNomeDaFuncaoOnClickProsseguir = 'mostrarSplash(); document.getElementById("form").submit()';
                echo $this->botaoLink($this->translate(Constantes::$TRADUCAO_CONFIRMACAO), Constantes::$STRING_HASHTAG, 0, $this->funcaoOnClick($stringNomeDaFuncaoOnClickProsseguir));
                ?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function mostrarMotivos() {
        $('#divMotivo').toggleClass('hidden');
        $('#divBotaoVoltar').toggleClass('hidden');
    }

    function mostrarResumo() {
        $('#painelAlunos').toggleClass('hidden');
        $('#painelExcluidos').toggleClass('hidden');
        var escolhidos = $('input:checked');
        if (escolhidos.length > 0) {
            var contador = '';
            var selecionados = escolhidos.map(function () {
                var produto = {nome: this.name, value: this.value};
                contador += '<strong>' + this.id + '</strong><br/>';
                return produto;
            }).get();
            $('#pessoasSelecionadas').html(contador);
        } else {
            $('#pessoasSelecionadas').html("Nenhum aluno foi selecionado!!");
        }
    }
    function mostrarAlunos() {
        $('#painelAlunos').toggleClass('hidden');
        $('#painelExcluidos').toggleClass('hidden');
    }

</script>
<?php
echo $this->layoutJSEventosValidacao;
