<?php

use Application\Controller\Helper\Constantes;

/**
 * Nome: turma.phtml
 * @author Lucas Filipe de Carvalho Cunha <lucascarvalho.esw@gmail.com>
 * Descricao: Página de cadastro de turmas no IV.
 */
$form = $this->formCadastroTurma;
$form->prepare();
$form->setAttribute(Constantes::$ACTION, $this->url(Constantes::$ROUTE_CURSO, array(Constantes::$ACTION => Constantes::$PAGINA_SALVAR_TURMA)));

echo $this->templateFormularioTopo('Editar Turma', '', 'style="margin-top: 0px"');
                        echo $this->form()->openTag($form); ?>
                        <div class="panel-body bg-light">
                            <?php
                            echo $this->divMensagens();
                            echo $this->inputFormularioSimples(Constantes::$TRADUCAO_TIPO, $form->get(Constantes::$FORM_ID_CURSO), 12, 2);
                            echo $this->inputFormularioSimples(Constantes::$TRADUCAO_MES, $form->get(Constantes::$FORM_INPUT_MES), 12, 2);
                            echo $this->inputFormularioSimples(Constantes::$TRADUCAO_ANO, $form->get(Constantes::$FORM_INPUT_ANO), 12, 2);
                            echo $this->inputFormularioSimples(Constantes::$TRADUCAO_OBSERVACAO, $form->get(Constantes::$FORM_OBSERVACAO), 12);
                            ?>
                        </div>
                        <!-- end .form-body section -->
                        <div class="panel-footer text-right">
                            <?php
                            echo $this->formHidden($form->get(Constantes::$FORM_ID));
                            echo $this->formHidden($form->get(Constantes::$INPUT_CSRF));
                            $stringNomeDaFuncaoOnClickCadastro = 'funcaoCircuito("' .Constantes::$ROUTE_CURSO. Constantes::$PAGINA_LISTAR_TURMA . '", 0)';
                            echo $this->botaoLink($this->translate(Constantes::$TRADUCAO_VOLTAR), Constantes::$STRING_HASHTAG, 2, $this->funcaoOnClick($stringNomeDaFuncaoOnClickCadastro));
                            /* Submit */
                            $funcaoVerificarCadastroPessoa = $this->funcaoOnClick('validarLancamentoCadastrarTurma(this.form)');
                            echo $this->botaoSimples('Cadastrar', $funcaoVerificarCadastroPessoa);
                            ?>
                        </div>
                        <!-- end .form-footer section -->
<?php echo $this->form()->closeTag(); 
echo $this->templateFormularioRodape();
?>
      
<script type="application/javascript">
function validarLancamentoCadastrarTurma(form) {
    var tipo = $('#Tipo').val();
    var Mes = $('#Mes').val();
    var Ano = $('#Ano').val();
    var observacao = $('#observacao').val();
    var temErro = false;
    var divMensagens = $('#divMensagens');
    var mensagem = '';
    var mensagemReal = '';
    if (tipo === '0') {
        temErro = true;
        if (mensagem == '') {
            mensagem = 'Tipo';
        } else {
            mensagem += ', Tipo';
        }
    }
    if (Mes === '0') {
        temErro = true;
        if (mensagem == '') {
            mensagem = 'Mês';
        } else {
            mensagem += ', Mês';
        }
    }
    if (Ano === '0') {
        temErro = true;
        if (mensagem == '') {
            mensagem = 'Ano';
        } else {
            mensagem += ', Ano';
        }
    }
    if (temErro) {
        mensagemReal = 'Preencha o(s) seguinte(s) campo(s): ' + mensagem;
        divMensagens
                .html(mensagemReal)
                .removeClass('alert-success')
                .removeClass('hidden')
                .addClass('alert-danger');
    } else {
        divMensagens
                .addClass('hidden');
        form.submit();
    }
}
</script>