<?php

use Application\Controller\RelatorioController;
?>
<div class="mw800 center-block">
    <div class="panel">
        <div class="panel-heading">
            <span class="panel-title">Supervis&atilde;o</span>
        </div>
        <div class="panel-body pn">
            <table class="table mbn tc-med-1 tc-bold-last">
                <tr>
                    <td colspan="3" class="text-center">Celulas N&atilde;o Realizadas</td>
                </tr>

                <?php
                if ($this->discipulos) {
                    foreach ($this->discipulos as $gpFilho) {
                        $grupoFilho = $gpFilho->getGrupoPaiFilhoFilho();
                        $nomeLideres = $grupoFilho->getNomeLideresAtivos();

                        $relatorioDiscipulo = $this->discipulosRelatorio[$grupoFilho->getId()];
                        echo '<tr>';
                        echo '<td>' . $nomeLideres . '</td>';
                        echo '<td>' . $relatorioDiscipulo['celulaQuantidade'] . '</td>';
                        echo '<td>' . $relatorioDiscipulo['celulaRealizadas'] . '</td>';
                        echo '</tr>';
                    }
                }
                ?>
            </table>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <span class="panel-title">Pessoal - <?php echo $this->periodo; ?></span>
        </div>
        <div class="panel-body pn">
            <table class="table mbn tc-med-1 tc-bold-last">
                <tr>
                    <td></td>
                    <td>Meta</td>
                    <td>Valor</td>
                    <td>Perf.%</td>
                </tr>
                <tr class="<?php echo $this->relatorio['membresiaPerformanceClass']; ?>">
                    <td>Membresia</td>
                    <td><?php echo $this->relatorio['membresiaMeta']; ?></td>
                    <td><?php echo RelatorioController::formataNumeroRelatorio($this->relatorio['membresia']); ?></td>
                    <td><?php echo RelatorioController::formataNumeroRelatorio($this->relatorio['membresiaPerformance']); ?>%</td>
                </tr>
                <tr class="<?php echo $this->relatorio['celulaPerformanceClass']; ?>">
                    <td>Célula</td>
                    <td><?php echo $this->relatorio['membresiaMeta']; ?></td>
                    <td><?php echo $this->relatorio['celula']; ?></td>
                    <td><?php echo RelatorioController::formataNumeroRelatorio($this->relatorio['celulaPerformance']); ?>%</td>
                </tr>
                <tr class="<?php echo $this->relatorio['celulaRealizadasPerformanceClass']; ?>">
                    <td>Cél. Realizadas</td>
                    <td><?php echo $this->relatorio['celulaQuantidade']; ?></td>
                    <td><?php echo $this->relatorio['celulaRealizadas']; ?></td>
                    <td><?php echo RelatorioController::formataNumeroRelatorio($this->relatorio['celulaRealizadasPerformance']); ?>%</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <span class="panel-title">Equipe - <?php echo $this->periodo; ?></span>
        </div>
        <div class="panel-body pn">
            <table class="table mbn tc-med-1 tc-bold-last">
                <tr>
                    <td></td>
                    <td>Meta</td>
                    <td>Valor</td>
                    <td>Perf.%</td>
                </tr>
                <tr class="<?php echo $this->relatorioEquipe['membresiaPerformanceClass']; ?>">
                    <td>Membresia</td>
                    <td><?php echo $this->relatorioEquipe['membresiaMeta']; ?></td>
                    <td><?php echo RelatorioController::formataNumeroRelatorio($this->relatorioEquipe['membresia']); ?></td>
                    <td><?php echo RelatorioController::formataNumeroRelatorio($this->relatorioEquipe['membresiaPerformance']); ?>%</td>
                </tr>
                <tr class="<?php echo $this->relatorioEquipe['celulaPerformanceClass']; ?>">
                    <td>Célula</td>
                    <td><?php echo $this->relatorioEquipe['membresiaMeta']; ?></td>
                    <td><?php echo $this->relatorioEquipe['celula']; ?></td>
                    <td><?php echo RelatorioController::formataNumeroRelatorio($this->relatorioEquipe['celulaPerformance']); ?>%</td>
                </tr>
                <tr class="<?php echo $this->relatorioEquipe['celulaRealizadasPerformanceClass']; ?>">
                    <td>Cél. Realizadas</td>
                    <td><?php echo $this->relatorioEquipe['celulaQuantidade']; ?></td>
                    <td><?php echo $this->relatorioEquipe['celulaRealizadas']; ?></td>
                    <td><?php echo RelatorioController::formataNumeroRelatorio($this->relatorioEquipe['celulaRealizadasPerformance']); ?>%</td>
                </tr>
            </table>
        </div>
    </div>        
</div>
