<?php

use Application\View\Helper\BotaoSimples;
use Application\Controller\Helper\Funcoes;
use Application\Controller\RelatorioController;
use Application\Model\Entity\FuncoesEntidade;
use Application\Model\Entity\EntidadeTipo;
use Application\Model\Entity\Situacao;
use Application\Model\Entity\Hierarquia;

$stringEntidade = $this->entidade->getNome();
if($this->entidade->getEntidadeTipo()->getId() === EntidadeTipo::subEquipe){
	$stringEntidade = $this->entidade->infoEntidade($somenteNumeros = true);
}
if($this->entidade->getEntidadeTipo()->getId() === EntidadeTipo::coordenacao){
	$stringEntidade = $this->entidade->getNumero();
}

if ($this->mostrarPrincipal) {
	$fotos = $this->grupo->getFotosLideresAtivos(128);
	echo '<div class="alert alert-default">';
	echo $this->sitemap('principal');
	echo '</div>';
?>
<div class="panel mt10">
<div class="panel-body ">

<div class="media clearfix">
<div class="media-left pr5">
<?php
	echo '<img src="/img/fotos/'.$this->pessoa->getFoto().'" class="user-avatar" width="100px" height="100px" />'; 
?>
</div>
<div class="media-body va-m">
<h4><?php echo $this->pessoa->getNomePrimeiroUltimo(); ?></h4>
<small>
<?php 
	echo $this->entidade->getEntidadeTipo()->getNome() . ' - ' . $stringEntidade; 
?>
</small>
<p class="mt10">
<?php
	if($this->pessoaLogada->getId() === $this->pessoa->getId()){
		$funcaoOnClickPerfil = 'location.href="/perfil"';
		echo $this->botaoSimples('<i class="fa fa-user"></i> Perfil', $this->funcaoOnClick($funcaoOnClickPerfil), BotaoSimples::botaoMuitoPequenoImportante, BotaoSimples::posicaoAEsquerda);
	} else {
		$funcaoOnClick = 'funcaoCircuito("principalVer", '.$grupo->getId().')';
		echo $this->botaoSimples('<i class="fa fa-cog"></i>', $this->funcaoOnClick($funcaoOnClick), BotaoSimples::botaoMuitoPequenoImportante, BotaoSimples::posicaoAEsquerda); 
	}
?>
</p>
</div>
</div>

</div>
</div>

<!-- fim panel meus dados -->
<?php if($this->vendoPessoaLogada){ ?>
<div class="alert alert-default text-center">
<form action="/principal" method="post">
<?php echo $this->cabecalhoDeMeses(); ?>
</form>
</div>
<?php } ?>


<?php
echo '<div class="row mb10">';

$totalDeIndices = 11;

for($indiceNumeroGrandes = 1; $indiceNumeroGrandes <= $totalDeIndices; $indiceNumeroGrandes++){
	$idValor = '';
	$label = '';
	$idDiv = '';
	$hidden = '';

	switch($indiceNumeroGrandes){
	case 1: 
		$idValor = 'idValorLideres';
		$label = 'Líder(es)';
		break;
	case 2: 
		$idValor = 'idValorCelulas';
		$label = 'Célula(s)';
		break;
	case 3: 
		$idValor = 'idValorDiscipulados';
		$label = 'Discipulado(s)';
		break;
	case 4: 
		$idValor = 'idValorAlunos';
		$label = 'Aluno(s)';
		break;
	case 5: 
		$idValor = 'idValorRegioes';
		$label = 'Região(ões)';
		$idDiv = 'divRegioes';
		$hidden = 'hidden';
		break;
	case 6: 
		$idValor = 'idValorCoordenacoes';
		$label = 'Coordenação(ões)';
		$idDiv = 'divCoordenacoes';
		$hidden = 'hidden';
		break;
	case 7: 
		$idValor = 'idValorIgrejas';
		$label = 'Igrejas';
		$idDiv = 'divIgrejas';
		$hidden = 'hidden';
		break;
	case 8: 
		$idValor = 'idValorParceiro';
		$label = 'Parceiro de Deus';
		break;
	case 9: 
		$idValor = 'idValorDiscipulado';
		$label = 'Meu Discipulado';
		$idDiv = 'divDiscipulado';
		$hidden = 'hidden';
		break;
	case 10: 
		$idValor = 'idValorDiscipuladoHomens';
		$label = 'Time de Homens';
		$idDiv = 'divDiscipuladoHomens';
		$hidden = 'hidden';
		break;
	case 11: 
		$idValor = 'idValorDiscipuladoMulheres';
		$label = 'Time de Mulheres';
		$idDiv = 'divDiscipuladoMulheres';
		$hidden = 'hidden';
		break;
	}
	echo '<div id="'.$idDiv.'" class="col-lg-3 col-md-3 col-sm-3 col-xs-6 '.$hidden.'">';
	echo '<div class="panel text-center br-a br-grey">';
	echo '<div class="panel-body">';
	echo '<h1 id="'.$idValor.'" class="fs16 mt5 mbn"><img src="/img/loader.gif" /></h1>';
	echo '<h6 class="text-info">'.$label.'</h6>';
	echo '</div>';
	echo '</div>';
	echo '</div>';
}

echo '</div>';
?>

<?php
if($this->entidade->getEntidadeTipo()->getId() !== EntidadeTipo::regiao
	&& $this->entidade->getEntidadeTipo()->getId() !== EntidadeTipo::coordenacao){
?>
<!-- dados membresia -->
<div class="row mb10">
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 admin-grid">
<div class="panel panel-collapsed" id="p1">
<div class="panel-heading ui-sortable-handle">
Membresia
<span class="panel-controls">
<a href="#" class="panel-control-collapse" onClick="buscarDadosPrincipaisMembresia()"></a>
</span>
</div>
<div class="panel-body pn pt10" style="display: none;">

<div class="col-xs-12 col-md-12 col-lg-12 p20">
</div>

<?php
$class = 'class = "col-lg-3 col-md-3 col-sm-6 col-xs-12"';
$numeroIndices = 4;
for ($indice = 1; $indice <= $numeroIndices; $indice++) {
	$idValor = '';
	$idLista = '';
	switch ($indice) {
	case 1:
		$label = 'PESSOAS CHEIAS DE F&Eacute;';
		$idValor = 'valorMediaCultos';
		$idLista = 'listaCultos';
		break;
	case 2:
		$label = 'PESSOAS APAIXONADAS';
		$idValor = 'valorMediaArena';
		$idLista = 'listaArena';
		break;
	case 3:
		$label = 'PESSOAS ALIAN&Ccedil;ADAS';
		$idValor = 'valorMediaDomingo';
		$idLista = 'listaDomingo';
		break;
	case 4: 
		$label = 'MEMBROS ASS&Iacute;DUOS';
		$idValor = 'valorMediaMembresia';
		$idLista = 'listaMembresia';
		break;
	}
?>
								<div <?php echo $class; ?>>
									<div class="panel panel-tile text-center br-a br-grey">
										<div class="panel-body" style="padding-bottom: 0px;">
											<h1 class="fs30 mt5 mbn">
<?php
	echo '<span id="'.$idValor.'" class="relatorioPessoal"><img src="img/loader.gif" /></span>';
?>
											</h1>
											<h6><?php echo $label; ?></h6>
										</div>
										<div class="panel-footer br-t p12">
											<span class="fs11">
											<span id="<?php echo $idLista; ?>" class="relatorioPessoal" style="font-size: 10px;"><img src="img/loader.gif" /></span>
											</span>
										</div>
									</div>
								</div>
<?php } ?>
</div>
</div>
</div>
</div>
<!-- fim membresia -->

<!-- dados celula -->
<div class="row mb10">
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 admin-grid">
<div class="panel panel-collapsed" id="p1">
<div class="panel-heading ui-sortable-handle">
Célula
<span class="panel-controls">
<a href="#" class="panel-control-collapse" onClick="buscarDadosPrincipaisCelula()"></a>
</span>
</div>
<div class="panel-body pn pt10" style="display: none;">

<div class="col-xs-12 col-md-12 col-lg-12 p20">
</div>

<?php
$class = 'class = "col-lg-3 col-md-3 col-sm-6 col-xs-12"';
$numeroIndices = 3;
for ($indice = 1; $indice <= $numeroIndices; $indice++) {
	$idValor = '';
	$idLista = '';
	switch ($indice) {
	case 1:
		$label = 'TOTAL DE CÉLULAS DE MULTIPLICAÇÃO';
		$idValor = 'mediaCelulaQuantidade';
		$idLista = 'listaCelulaQuantidade';
		break;
	case 2:
		$label = 'PESSOAS FREQUENTES';
		$idValor = 'mediaPessoasFrequentes';
		$idLista = 'listaPessoasFrequentes';
		break;
	case 3:
		$label = 'CÉLULAS REALIZADAS';
		$idValor = 'mediaCelulaRealizadas';
		$idLista = 'listaCelulaRealizadas';
		break;
	}
?>
								<div <?php echo $class; ?>>
									<div class="panel panel-tile text-center br-a br-grey">
										<div class="panel-body" style="padding-bottom: 0px;">
											<h1 class="fs30 mt5 mbn">
<?php
	echo '<span id="'.$idValor.'" class="relatorioPessoal"><img src="img/loader.gif" /></span>';
?>
											</h1>
											<h6><?php echo $label; ?></h6>
										</div>
										<div class="panel-footer br-t p12">
											<span class="fs11">
											<span id="<?php echo $idLista; ?>" class="relatorioPessoal" style="font-size: 10px;"><img src="img/loader.gif" /></span>
											</span>
										</div>
									</div>
								</div>
<?php } ?>
</div>
</div>
</div>
</div>
<!-- fim celula -->
<?php } ?>

<?php
if(count($this->discipulos) > 0){
?>
<div class="panel user-group-widget">

<div class="panel-heading">
<span class="panel-icon">
<i class="fa fa-users"></i>
</span>
<span class="panel-title">Discípulos</span>
</div>

<div class="panel-body pn">

<?php
	$contadorDeDiscipulosPorLinha = 0;
	foreach($this->discipulos as $discipulo){
		$grupoFilho = $discipulo->getGrupoPaiFilhoFilho();
		$entidade = $grupoFilho->getEntidadeAtiva();
		foreach($grupoFilho->getPessoasAtivas() as $pessoa){
			$vendoDiscipulosAbaixo = 'vendoDiscipulosAbaixoPaginaPrincipal';
			$idSessao = $pessoa->getId() . '_' . $entidade->getId() . '_' . $vendoDiscipulosAbaixo;
			$funcaoOnClick = 'mostrarSplash(); funcaoCircuito("principal", "'.$idSessao.'")';
			$nomeHierarquia = $pessoa->getPessoaHierarquiaAtivo()->getHierarquia()->getNome();
			if ($pessoa->getSexo() === 'F') {
				if ($nomeFeminino = $pessoa->getPessoaHierarquiaAtivo()->getHierarquia()->getNome_feminino()) {
					$nomeHierarquia = $nomeFeminino;
				}
			}
			if($contadorDeDiscipulosPorLinha === 0){
				echo '<div class="row p10">';
			}
			echo '<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 p10 text-center">';
			echo '<img src="/img/fotos/'.$pessoa->getFoto().'" class="user-avatar" width="128px" height="128px" '. $this->funcaoOnClick($funcaoOnClick) .'/ style="margin:auto;">';
			echo '<div class="caption">';
			echo '<h5>'.$pessoa->getNomePrimeiro();
			echo '<br />';
			echo '<small>'.$nomeHierarquia. '<small>';
			echo '<br /><small>'.$grupoFilho->getEntidadeAtiva()->infoEntidade(). '<small>';
			echo '</h5>';
			echo '</div>';
			echo '</div>';
			$contadorDeDiscipulosPorLinha++;
			if($contadorDeDiscipulosPorLinha === 3){
				echo '</div>';
				$contadorDeDiscipulosPorLinha = 0;
			}
		}
	}
?>

</div>

</div>

</div>

<!-- fim panel discipulos -->
<?php
}
?>

<?php
}
?>

<script>
	function buscarDadosPrincipais(){
		const url = '/principalBuscarDadosPrincipais'
		fetch(
			url,
			{
				method: 'POST',	
				body: JSON.stringify({
					"token": "<?php echo $this->grupo->getId(); ?>",
					"mes": "<?php echo $this->mes; ?>",
					"ano": "<?php echo $this->ano; ?>",
				}),
			},
		)
		.then(resultado => {
			if(!resultado.ok){
				alert('erro ao buscar dados principais')
			}
			return resultado.json()
		})
		.then(json => {
			document.getElementById('idValorLideres').innerHTML = json.resultado.lideres
			document.getElementById('idValorCelulas').innerHTML = json.resultado.celulas
			document.getElementById('idValorDiscipulados').innerHTML = json.resultado.discipulados
			document.getElementById('idValorAlunos').innerHTML = json.resultado.alunos
			let parceiro = '0.00'
			if(json.resultado.parceiro){
				parceiro = parseFloat(json.resultado.parceiro).toFixed(2)
			}
			document.getElementById('idValorParceiro').innerHTML = 'R$ ' + parceiro
			if(json.resultado.mostrarRegioes){
				document.getElementById('divRegioes').classList.remove('hidden')
				document.getElementById('idValorRegioes').innerHTML = json.resultado.regioes
			}
			if(json.resultado.mostrarCoordenacoes){
				document.getElementById('divCoordenacoes').classList.remove('hidden')
				document.getElementById('idValorCoordenacoes').innerHTML = json.resultado.coordenacoes
			}
			if(json.resultado.mostrarIgrejas){
				document.getElementById('divIgrejas').classList.remove('hidden')
				document.getElementById('idValorIgrejas').innerHTML = json.resultado.igrejas
			}
			if(json.resultado.mostrarDiscipulado){
				document.getElementById('divDiscipulado').classList.remove('hidden')
				document.getElementById('divDiscipuladoHomens').classList.remove('hidden')
				document.getElementById('divDiscipuladoMulheres').classList.remove('hidden')
				let valor = ''
				for(let indice = 1; indice <= 5; indice++){
					if(json.resultado.discipulado >= indice){
						valor += '<i class="fa fa-star"></i>'
					}else{
						valor += '<i class="fa fa-star-o"></i>'
					}
				}
				document.getElementById('idValorDiscipulado').innerHTML = valor
				document.getElementById('idValorDiscipuladoHomens').innerHTML = json.resultado.discipuladoHomens
				document.getElementById('idValorDiscipuladoMulheres').innerHTML = json.resultado.discipuladoMulheres
			}
		})
	}

	function buscarDadosPrincipaisMembresia(){
		const url = '/principalBuscarDadosPrincipaisMembresia'
		fetch(
			url,
			{
				method: 'POST',	
				body: JSON.stringify({
					"token": "<?php echo $this->grupo->getId(); ?>",
					"mes": "<?php echo $this->mes; ?>",
					"ano": "<?php echo $this->ano; ?>",
				}),
			},
		)
		.then(resultado => {
			if(!resultado.ok){
				alert('erro ao buscar dados principais membresia')
			}
			return resultado.json()
		})
		.then(json => {
			document.getElementById('valorMediaCultos').innerHTML = json.resultado.mediaCultos.toFixed(2)
			document.getElementById('valorMediaArena').innerHTML = json.resultado.mediaArena.toFixed(2)
			document.getElementById('valorMediaDomingo').innerHTML = json.resultado.mediaDomingo.toFixed(2)
			document.getElementById('valorMediaMembresia').innerHTML = json.resultado.mediaMembresia.toFixed(2)
			let valor = ''
			json.resultado.listaCultos.forEach(item => {
				if(item){
				if(valor === ''){
					valor += item
				}else{
					valor += '|' + item
				}
				}
			})
			document.getElementById('listaCultos').innerHTML = valor
			valor = ''
			json.resultado.listaArena.forEach(item => {
				if(item){
				if(valor === ''){
					valor += item
				}else{
					valor += '|' + item
				}
				}
			})
			document.getElementById('listaArena').innerHTML = valor
			valor = ''
			json.resultado.listaDomingo.forEach(item => {
				if(item){
				if(valor === ''){
					valor += item
				}else{
					valor += '|' + item
				}
				}
			})
			document.getElementById('listaDomingo').innerHTML = valor
			valor = ''
			json.resultado.listaMembresia.forEach(item => {
				if(item){
				if(valor === ''){
					valor += item.toFixed(2)
				}else{
					valor += '|' + item.toFixed(2)
				}
				}
			})
			document.getElementById('listaMembresia').innerHTML = valor
		})
	}
	function buscarDadosPrincipaisCelula(){
		const url = '/principalBuscarDadosPrincipaisCelula'
		fetch(
			url,
			{
				method: 'POST',	
				body: JSON.stringify({
					"token": "<?php echo $this->grupo->getId(); ?>",
					"mes": "<?php echo $this->mes; ?>",
					"ano": "<?php echo $this->ano; ?>",
				}),
			},
		)
		.then(resultado => {
			if(!resultado.ok){
				alert('erro ao buscar dados principais celula')
			}
			return resultado.json()
		})
		.then(json => {
			document.getElementById('mediaCelulaQuantidade').innerHTML = json.resultado.mediaCelulaQuantidade.toFixed(2)
			document.getElementById('mediaPessoasFrequentes').innerHTML = json.resultado.mediaPessoasFrequentes.toFixed(2)
			document.getElementById('mediaCelulaRealizadas').innerHTML = json.resultado.mediaCelulaRealizadas.toFixed(2)
			let valor = ''
				json.resultado.listaCelulaQuantidade.forEach(item => {
					if(item){
					if(valor === ''){
						valor += item
					}else{
						valor += '|' + item
					}
					}
				})
			document.getElementById('listaCelulaQuantidade').innerHTML = valor
			valor = ''
				json.resultado.listaPessoasFrequentes.forEach(item => {
					if(item){
					if(valor === ''){
						valor += item
					}else{
						valor += '|' + item
					}
					}
				})
			document.getElementById('listaPessoasFrequentes').innerHTML = valor
			valor = ''
				json.resultado.listaCelulaRealizadas.forEach(item => {
					if(item){
					if(valor === ''){
						valor += item.toFixed(2)
					}else{
						valor += '|' + item.toFixed(2)
					}
					}
				})
			document.getElementById('listaCelulaRealizadas').innerHTML = valor
		})
	}
	buscarDadosPrincipais()
</script>
