<?php
$label = '<b class="text-danger">Notas de Atualizações</b>';
echo $this->templateFormularioTopo($label);
 ?>
<div class="panel-body bg-light" style="padding: 15px 5px 5px 5px;">
  <div class='p5'>
    <h1 class='text-primary'>Notas da Atualização 1.0 - 07 de  Janeiro de 2019.</h1>
    <h2>O que mudou da antiga versão para a nova versão do sistema?</h2>
    <p><span class='fa fa-quote-left'></span> Olá Usuário! Criamos esta seção para te deixar a par das mudanças que ocorreram e que ocorrerão no sistema Circuito da Visão.</p>
    <p><b class='text-danger'>Solicitações:</b> Cadastro de transferências (de alunos e líderes), o processo de inativar pessoas ou casa-las, foram unificados em um só módulo: "Solicitações", até a data dessa atualização as solicitações possuem quatro situações: Pendente, Recusada, Agendada e Concluída. Líderes de equipe ou acima conseguem cadastrar solicitações, uma vez cadastrada, as solicitações <b class='text-danger'>"Remover somente uma célula" e "Remover Líder com sua célula"</b> aparecem para o líder da respectiva igreja como pendente e como pendente fica até o momento que o líder de igreja aceite ou recuse a solicitação, após ser aceita ela passa para a situação de "agendada" e no período seguinte a solicitação é realizada, passando para a situação "concluída. As demais solicitações já são cadastradas com a situação "Agendada" e são concluídas no período seguinte. </p>
    <p><b class='text-danger'>Períodos:</b> Para facilitar alguns processos, o novo sistema não trabalha mais com ciclos e sim com períodos, o sistema de ciclos confundia as vezes os usuários pelo fato de alguns meses possuírem ciclos quebrados possuindo apenas alguns dias. Um período sempre possui 7 dias, sempre se inicia na segunda e termina no domingo (independente do mês), sendo assim na virada de mês o mesmo período pode abranger o final de um mês e o início de um mês.</p>
    <p><b class='text-danger'>Prazos:</b> Assim como citado sobre as solicitações, para melhor funcionamento do sistema, assim como um banco o sistema passa a possuir prazos em determinadas operações para serem concluídas. Quando uma célula é cadastrada, ela é lançada e efetivada no próximo período. Seguindo o raciocínio, cadastro de time e  culto também são cadastrados e efetivados no período seguinte.<p>
    <p><b class='text-danger'>Instituto de Vencedores:</b> Algumas mudanças no Instituto de Vencedores ocorreram, agora ele fica dentro do módulo "Cursos" e algumas novas regras foram adicionadas, nessa nova versão só é possível uma aula estar aberta por vez e funcionalidades como chamada, reentrada e outras relacionadas ao IV só funcionarão caso o curso possua alguma aula em aberto. <span class='fa fa-quote-right'></span></p>
</div>
</div>
<?php
echo $this->templateFormularioRodape();
 ?>
