<?php

use Application\Controller\Helper\Constantes;

$formulario = $this->formulario;
$formulario->prepare();
$formulario->setAttribute(Constantes::$ACTION, $this->url('principal', array(Constantes::$ACTION => 'NumeracaoSalvar')));
echo $this->form()->openTag($formulario);
echo $this->templateFormularioTopo('Alterar Numeração');
?>
<div class="panel-body bg-light">
    <div class="alert alert-info">
        <p><?php echo $this->grupo->getEntidadeAtiva()->infoEntidade(); ?></p>
    </div>
    <?php
    echo $this->divMensagens();
    echo $this->inputFormularioSimples(Constantes::$TRADUCAO_NUMERACAO, $formulario->get(Constantes::$FORM_NUMERACAO), 12, 2);

    echo $this->formHidden($formulario->get(Constantes::$INPUT_CSRF));
    echo $this->formHidden($formulario->get(Constantes::$FORM_ID));
    $funcao = $this->funcaoOnClick('validarPrincipalAlterarNumeracao(this.form);');
    echo $this->botaoSimples(Constantes::$TRADUCAO_ALTERAR, $funcao);
    ?>
</div>
<?php
echo $this->templateFormularioRodape();
echo $this->form()->closeTag();
