<?php

use Application\Controller\Helper\Constantes;
?>
<div class="panel-body bg-light text-center mt50">
    <h1><span class = "text-success"><?php echo $this->translate('Chamado enviado com sucesso!'); ?></span></h1>
    <?php echo $this->translate('Em breve a nossa equipe de suporte responderá seu email para ajuda-lo. Até logo!'); ?>

    <div class = "col-xs-12">
        <h2 class = "text-default mbn confirmation-header"><i class = "fa fa-check text-success"></i></h2>
    </div>    
</div>
