<?php

use Application\Controller\Helper\Constantes;
use Application\Form\PerfilForm;
use Application\Model\Entity\EntidadeTipo;
use Application\View\Helper\BotaoSimples;

echo '<div class="alert alert-default">';
echo $this->sitemap('principal');
echo '</div>';
echo '<div class="panel panel-primary mw1000 center-block">';
echo '<div class="panel-heading">';
echo 'Perfil - Criação: ' . $this->entidade->getGrupo()->getData_criacaoStringPadraoBrasil() . ' - Matrícula: ' . $this->entidade->getGrupo_id();
echo '</div>';
echo '<div class="panel-body">';
$tamangoMdELg = 12;
if (count($this->responsabilidades) == 2) {
	$tamangoMdELg = 6;
}
foreach ($this->responsabilidades as $responsavel) {
	$pessoa = $responsavel->getPessoa();
	$formulario = new PerfilForm('formulario', $pessoa, $this->profissoes);
	echo '<div class="admin-form col-xs-12 col-sm-12 col-md-' . $tamangoMdELg . ' col-lg-' . $tamangoMdELg . '">';
	echo $this->perfil($pessoa, $formulario, $naoMostrarOpcoes = false);
	echo '</div>';
}
echo '</div>';
echo '</div>';

if ($this->mostrarParaReenviarEmails) {
	echo '<div class="panel panel-danger mw1000 center-block">';
	echo '<div class="panel-heading">';
	echo 'Reenviar Email de acesso';
	echo '</div>';
	echo '<div class="panel-body">';	
	
	foreach ($this->responsabilidades as $grupoResponsavel) {			
		$pessoa = $grupoResponsavel->getPessoa();
		$nome = $pessoa->getNomePrimeiro();
		$email = $pessoa->getEmail();
		if ($pessoa->getToken()) {			
			$extraBotaoEmailOutro = $this->funcaoOnClick('funcaoCircuito("principalNovoEmailParaEnviar", ' . $pessoa->getId() . ')');
			$labelBotaoOutro = 'ENVIAR PARA OUTRO EMAIL: ' . $nome;
			echo '<div class="row text-center">';
			echo '<div class="p5 col-lg-6 col-sm-12 col-xs-12">';
			echo $this->botaoSimples($labelBotaoOutro, $extraBotaoEmailOutro, BotaoSimples::botaoMenorImportancia, BotaoSimples::posicaoAoCentro);
			echo '</div>';
			$enviandoParaOMesmoEmail = true;
			$dadosEnviarEmail = $pessoa->getId() . '_' . $enviandoParaOMesmoEmail;
			$funcaoOnClick = 'mostrarSplash(); funcaoCircuito("principalenviarEmail", "'.$dadosEnviarEmail.'")';
			$extraBotaoEmailMesmo = $this->funcaoOnClick($funcaoOnClick);
			$labelBotaoMesmo = 'ENVIAR PARA O EMAIL: ' . $email;
			echo '<div class="p5 col-lg-6 col-sm-12 col-xs-12">';
			echo $this->botaoSimples($labelBotaoMesmo, $extraBotaoEmailMesmo, BotaoSimples::botaoMenorImportancia, BotaoSimples::posicaoAoCentro);
			echo '</div>';
			echo '</div>';
		}
	}
	
	echo '</div>';
	echo '</div>';
}

echo '<div class="panel panel-primary mw1000 center-block">';
echo '<div class="panel-heading">';
if(count($this->eventos) === 0) {
	$extraBotaoArrumarFatoLider = $this->funcaoOnClick('mostrarSplash(); funcaoCircuito("principalArrumarFatoLider", ' . $this->idGrupo . ')');
	$botaoArrumarFatoLider = $this->botaoSimples('C&eacute;lula(s)', $extraBotaoArrumarFatoLider, BotaoSimples::botaoImportante, BotaoSimples::larguraMaxima);
	echo $botaoArrumarFatoLider;
}else{
	echo 'C&eacute;lula(s)';
}
echo '</div>';
echo '<div class="panel-body">';
echo $this->listagemDeEventos('', $this->eventos);

echo '</div>';
echo '</div>';

if ($this->entidade->getEntidadeTipo()->getId() === EntidadeTipo::subEquipe) {
	echo '<div class="panel panel-primary mw1000 center-block">';
	echo '<div class="panel-heading">';
	echo 'Time';
	echo '</div>';

	echo '<div class="panel-body center-block">';
	$extraAlterarNumeracao = $this->funcaoOnClick('mostrarSplash(); funcaoCircuito("principalNumeracao", ' . $this->idGrupo . ')');
	$botaoAlterarNumeracao = $this->botaoSimples('Alterar Numeração', $extraAlterarNumeracao, BotaoSimples::botaoImportante, BotaoSimples::larguraMaxima);

	echo '<div class="col-lg-6 col-md-6 col-sm-6">';
	echo '<div class="btn btn-default btn-block" disabled>'.$this->entidade->infoEntidade().'</div>';
	echo '</div>';
	echo '<div class="col-lg-6 col-md-6 col-sm-6">';
	echo $botaoAlterarNumeracao;
	echo '</div>';

	echo '</div>';
	echo '</div>';
}

if ($this->entidade->getEntidadeTipo()->getId() === EntidadeTipo::equipe) {
	echo '<div class="panel panel-primary mw1000 center-block">';
	echo '<div class="panel-heading">';
	echo 'Time';
	echo '</div>';

	echo '<div class="panel-body center-block">';
	$extraAlterarNumeracao = $this->funcaoOnClick('mostrarSplash(); funcaoCircuito("principalNome", ' . $this->idGrupo . ')');
	$botaoAlterarNumeracao = $this->botaoSimples('Alterar Dados', $extraAlterarNumeracao, BotaoSimples::botaoImportante, BotaoSimples::larguraMaxima);

	echo '<div class="col-lg-6 col-md-6 col-sm-6">';
	echo '<div class="btn btn-default btn-block" disabled>'.$this->entidade->infoEntidade().'</div>';
	echo '</div>';
	echo '<div class="col-lg-6 col-md-6 col-sm-6">';
	echo $botaoAlterarNumeracao;
	echo '</div>';

	echo '</div>';
	echo '</div>';
}

echo '<div class="panel panel-primary mw1000 center-block">';
echo '<div class="panel-heading">';
echo 'Ajustes';
echo '</div>';
echo '<div class="panel-body">';
$extraBotaoArrumarLinhaDeLancamento = $this->funcaoOnClick('mostrarSplash(); funcaoCircuito("principalArrumarLinhaDeLancamento", ' . $pessoa->getId() . ')');
$botaoArrumarLinhaDeLancamento = $this->botaoSimples('Arrumar linha de lançamento', $extraBotaoArrumarLinhaDeLancamento, BotaoSimples::botaoImportante, BotaoSimples::larguraMaxima);
echo $botaoArrumarLinhaDeLancamento;
echo '</div>';
echo '</div>';
