<?php

use Application\Controller\Helper\Constantes;
use Application\Form\PerfilForm;
use Application\Model\Entity\EntidadeTipo;
use Application\View\Helper\BotaoSimples;

echo '<div class="panel panel-primary mw1000 center-block mt50">';
echo '<div class="panel-heading">';
echo 'Perfil';
echo '</div>';
echo '<div class="panel-body">';
$tamangoMdELg = 12;
if (count($this->responsabilidades) == 2) {
    $tamangoMdELg = 6;
}
foreach ($this->responsabilidades as $responsavel) {
    $pessoa = $responsavel->getPessoa();
    $formulario = new PerfilForm('formulario', $pessoa);
    echo '<div class="admin-form col-xs-12 col-sm-12 col-md-' . $tamangoMdELg . ' col-lg-' . $tamangoMdELg . '">';
    echo $this->perfil($pessoa, $formulario, $naoMostrarOpcoes = false);
    echo '</div>';
}
echo '</div>';
echo '</div>';

echo '<div class="panel panel-danger mw1000 center-block">';
echo '<div class="panel-heading">';
echo 'Inativar';
echo '</div>';
echo '<div class="panel-body">';
if ($this->naoPodeInativar) {
    echo '<div class="alert alert-warning mt10">Tenho discipulos nao posso inativar ou solicitações pendentes!</div>';
} else {
    echo '<div class="panel mt10">';
    echo '<div class="panel-body">';

    if ($this->idEntidadeTipo === EntidadeTipo::equipe || $this->idEntidadeTipo === EntidadeTipo::igreja) {
        $extraBotaoInativar = 'onclick="funcaoCircuito(\'principalGrupoExclusao\', ' . $this->idGrupo . ');"';
        echo $this->botaoSimples(
                'Inativar', $extraBotaoInativar, BotaoSimples::botaoPerigoso, BotaoSimples::posicaoAEsquerda);
    }
    if ($this->mostrarParaReenviarEmails) {
        foreach ($this->responsabilidades as $grupoResponsavel) {
            echo Constantes::$NBSP;
            $pessoa = $grupoResponsavel->getPessoa();
            if ($pessoa->getToken()) {
                $nome = $pessoa->getNomePrimeiro();
                $extraBotaoEmail = $this->funcaoOnClick('funcaoCircuito("principalNovoEmailParaEnviar", ' . $pessoa->getId() . ')');

                $labelBotao = 'Reenviar Email de acesso: ' . $nome;
                echo $this->botaoSimples(
                        $labelBotao, $extraBotaoEmail, BotaoSimples::botaoMenorImportancia, BotaoSimples::posicaoAEsquerda);
            }
        }
    }
    echo '</div>';
    echo '</div>';
}
echo '</div>';
echo '</div>';

echo '<div class="panel panel-info mw1000 center-block">';
echo '<div class="panel-heading">';
echo 'C&eacute;lula(s)';
echo '</div>';
echo '<div class="panel-body">';
echo $this->listagemDeEventos('', $this->eventos);
echo'</div>';
echo'</div>';



