<?php

use Cadastro\Controller\Helper\ConstantesCadastro;
use Cadastro\Form\ConstantesForm;
use Lancamento\Controller\Helper\ConstantesLancamento;
use Login\Controller\Helper\Constantes;

/**
 * Nome: celula.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com> e Sergio Bezerra da Silva <sergio.silva.unb@gmail.com>
 * Descricao: Página de cadastro de célula
 */
$form = $this->CelulaForm;
$form->prepare();
$form->setAttribute(ConstantesForm::$FORM_ACTION, $this->url(ConstantesCadastro::$ROUTE_CADASTRO, array(ConstantesCadastro::$PAGINA => ConstantesCadastro::$PAGINA_SALVAR_CELULA)));
?>
<div class="mw1000 center-block p10">
    <div class="admin-form theme-danger">
        <blockquote class="blockquote-danger">
            <small><?php echo $this->translate(ConstantesForm::$TRADUCAO_CADASTRO_CELULA); ?> <b class="text-danger"><?php echo $this->translate(ConstantesForm::$TRADUCAO_MULTIPLICACAO); ?></b></small>
        </blockquote>
        <div class="panel heading-border panel-danger">
            <?php echo $this->form()->openTag($form); ?>
            <div class="panel-body bg-light">
                <div class="section-divider mv40">
                    <span><?php echo $this->translate(ConstantesForm::$TRADUCAO_DIA_HORA); ?></span>
                </div>
                <!--.section-divider -->

                <div class="section row">
                    <div class="row">
                        <div class="col-sm-12 col-xs-12">
                            <div class="section">
                                <label for="<?php echo ConstantesForm::$TRADUCAO_DIA_DA_SEMANA; ?>" class="field-label">
                                    <?php echo $this->translate(ConstantesForm::$TRADUCAO_DIA_DA_SEMANA); ?>
                                </label>
                                <label for="<?php echo ConstantesForm::$TRADUCAO_DIA_DA_SEMANA; ?>" class="field prepend-icon">
                                    <?php echo $this->formSelect($form->get(ConstantesForm::$FORM_DIA_DA_SEMANA)); ?>
                                </label>   
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-6 col-xs-6">
                            <div class="section">
                                <label for="<?php echo ConstantesForm::$TRADUCAO_HORA; ?>" class="field-label">
                                    <?php echo $this->translate(ConstantesForm::$TRADUCAO_HORA); ?>
                                </label>
                                <label for="<?php echo ConstantesForm::$TRADUCAO_HORA; ?>" class="field prepend-icon">
                                    <?php echo $this->formSelect($form->get(ConstantesForm::$FORM_HORA)); ?>
                                </label>  
                            </div>
                        </div>
                        <div class="col-sm-6 col-xs-6">
                            <div class="section">
                                <label for="<?php echo ConstantesForm::$TRADUCAO_MINUTOS; ?>" class="field-label">
                                    <?php echo $this->translate(ConstantesForm::$TRADUCAO_MINUTOS); ?>
                                </label>
                                <label for="<?php echo ConstantesForm::$TRADUCAO_MINUTOS; ?>" class="field prepend-icon">
                                    <?php echo $this->formSelect($form->get(ConstantesForm::$FORM_MINUTOS)); ?>
                                </label>                                                  
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="section">
                                <?php echo $this->inputFormulario(ConstantesForm::$TRADUCAO_CEP_LOGRADOURO, $form, ConstantesForm::$FORM_CEP_LOGRADOURO, ConstantesForm::$FORM_ICONE_COMPLEMENTO); ?>

                            </div> 
                        </div>
                    </div>

                    <div id="resultadoBusca"></div>
                    <div id="endereco" class="<?php echo $this->enderecoHidden; ?>">
                        <div class="row">
                            <div class="col-md-6 col-sm-12">
                                <div class="section">
                                    <?php echo $this->inputFormulario(ConstantesForm::$TRADUCAO_UF, $form, ConstantesForm::$FORM_UF, ConstantesForm::$FORM_ICONE_COMPLEMENTO, 2); ?>
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-12">
                                <div class="section">
                                    <?php echo $this->inputFormulario(ConstantesForm::$TRADUCAO_BAIRRO, $form, ConstantesForm::$FORM_BAIRRO, ConstantesForm::$FORM_ICONE_COMPLEMENTO, 2); ?>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="section">
                                    <?php echo $this->inputFormulario(ConstantesForm::$TRADUCAO_CIDADE, $form, ConstantesForm::$FORM_CIDADE, ConstantesForm::$FORM_ICONE_COMPLEMENTO, 2); ?>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="section">
                                    <?php echo $this->inputFormulario(ConstantesForm::$TRADUCAO_LOGRADOURO, $form, ConstantesForm::$FORM_LOGRADOURO, ConstantesForm::$FORM_ICONE_COMPLEMENTO, 2); ?>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="section">
                                    <?php echo $this->inputFormulario(ConstantesForm::$TRADUCAO_COMPLEMENTO, $form, ConstantesForm::$FORM_COMPLEMENTO, ConstantesForm::$FORM_ICONE_COMPLEMENTO); ?>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <!--end .section row section -->

                <div class="section-divider mv40">
                    <span><?php echo $this->translate(ConstantesForm::$TRADUCAO_DADOS_DO_HOSPEDEIRO); ?></span>
                </div>
                <!--.section-divider -->

                <div class="section row">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="section">
                                <?php echo $this->inputFormulario(ConstantesForm::$TRADUCAO_NOME_HOSPEDEIRO, $form, ConstantesForm::$FORM_NOME_HOSPEDEIRO, ConstantesForm::$FORM_ICONE_NOME_HOSPEDEIRO); ?>
                            </div>
                        </div>
                    </div>
                    <!--end .colm section -->
                    <div class="section">
                        <div class="row">
                            <div class="col-xs-5 col-sm-5 col-md-2">
                                <?php echo $this->inputFormulario(ConstantesForm::$TRADUCAO_DDD_HOSPEDEIRO, $form, ConstantesForm::$FORM_DDD_HOSPEDEIRO, ConstantesForm::$FORM_ICONE_DDD_HOSPEDEIRO); ?>
                            </div>
                            <div class="col-xs-7 col-sm-7 col-md-10">
                                <?php echo $this->inputFormulario(ConstantesForm::$TRADUCAO_TELEFONE_HOSPEDEIRO, $form, ConstantesForm::$FORM_TELEFONE_HOSPEDEIRO, ConstantesForm::$FORM_ICONE_TELEFONE_HOSPEDEIRO); ?>
                            </div>
                        </div>
                    </div>
                </div> 

                <!--end .section row section -->
            </div>
            <!--end .form-body section -->
            <div class="panel-footer text-right" style="height:65px;">
                <button onclick="location.href = '/cadastroCelulas';" data-style="zoom-in" type="button" class="btn ladda-button btn-dark"><i class="fa fa-arrow-left" aria-hidden="true"></i> <?php echo $this->translate(Constantes::$TRADUCAO_VOLTAR); ?></button>
                &nbsp;
                <?php
                echo $this->formHidden($form->get(ConstantesForm::$FORM_CSRF));
                echo $this->formHidden($form->get(ConstantesForm::$FORM_ID));
                if (empty($form->get(ConstantesForm::$FORM_ID)->getValue())) {
                    echo $this->botaoSubmitDesabilitado(ConstantesLancamento::$TRADUCAO_CADASTRAR, ConstantesForm::$FORM_SUBMIT, '', ConstantesLancamento::$CLASS_BTN_DANGER_DARK);
                } else {
                    echo $this->botaoSubmit(ConstantesForm::$TRADUCAO_ALTERAR, ConstantesLancamento::$CLASS_BTN_DANGER_DARK);
                }
                ?>
            </div>
            <!--end .form-footer section -->
            <?php echo $this->form()->closeTag() ?>
        </div>
    </div>
</div>           
<?php
/* Layout com javascript para tela de cadastro de celula */
echo $this->layoutJSCelulaValidacao;
