<?php

use Cadastro\Controller\Helper\ConstantesCadastro;
use Cadastro\Form\ConstantesForm;
use Lancamento\Controller\Helper\ConstantesLancamento;

/**
 * Nome: celula.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com> e Sergio Bezerra da Silva <sergio.silva.unb@gmail.com>
 * Descricao: Página de cadastro de célula
 */
$form = $this->CelulaForm;
$form->prepare();
$form->setAttribute(ConstantesForm::$FORM_ACTION, $this->url(ConstantesCadastro::$ROUTE_CADASTRO, array(ConstantesCadastro::$PAGINA => ConstantesCadastro::$PAGINA_SALVAR_CELULA)));
?>
<div class="row background-mobile">
    <div id="content">
        <div class="row">
            <div class="admin-form theme-danger tab-pane mw700 pl20 pr20">
                <div class="row">
                    <div class="admin-form theme-danger tab-pane mw800 pl20 pr20" id="survey1" role="tabpanel">
                        <blockquote class="blockquote-danger">
                            <p><?php echo $this->translate(ConstantesForm::$TRADUCAO_CADASTRO_CELULA); ?></p>
                            <small><?php echo $this->translate(ConstantesForm::$TRADUCAO_MULTIPLICACAO); ?></small>
                        </blockquote>
                        <div class="panel panel-danger heading-border">
                            <?php echo $this->form()->openTag($form); ?>
                            <div class="panel-body p25">
                                <div class="section-divider mv40">
                                    <span><?php echo $this->translate(ConstantesForm::$TRADUCAO_DIA_HORA); ?></span>
                                </div>
                                <!--.section-divider -->

                                <div class="section row">
                                    <div class="col-md-8">
                                        <div class="section">
                                            <label for="<?php echo ConstantesForm::$TRADUCAO_DIA_DA_SEMANA; ?>" class="field-label">
                                                <?php echo $this->translate(ConstantesForm::$TRADUCAO_DIA_DA_SEMANA); ?>
                                            </label>
                                            <label for="<?php echo ConstantesForm::$TRADUCAO_DIA_DA_SEMANA; ?>" class="field prepend-icon">
                                                <?php echo $this->formSelect($form->get(ConstantesForm::$FORM_DIA_DA_SEMANA)); ?>
                                            </label>   
                                        </div>
                                        <!--end section -->
                                    </div>
                                    <!--end .colm section -->

                                    <div class="col-md-4">
                                        <div class="section">
                                            <?php echo $this->inputFormulario(ConstantesForm::$TRADUCAO_HORA, $form, ConstantesForm::$FORM_HORA, ConstantesForm::$FORM_ICONE_HORA); ?>
                                        </div>
                                    </div>
                                    <!--end .colm section -->

                                    <div class="col-md-12">
                                        <div class="section">
                                            <?php echo $this->inputFormulario(ConstantesForm::$TRADUCAO_CEP_LOGRADOURO, $form, ConstantesForm::$FORM_CEP_LOGRADOURO, '', 1, ConstantesForm::$FORM_ONCLICK . '=\'' . ConstantesForm::$FORM_FUNCAO_BUSCAR_CEP . '\''); ?>
                                        </div>
                                    </div>
                                    
                                    <div id="resultadoBusca"></div>
                                    
                                    
                                        <div class="col-md-6 col-sm-9">
                                            <div class="section">
                                                <?php echo $this->inputFormulario(ConstantesForm::$TRADUCAO_CEP_LOGRADOURO, $form, ConstantesForm::$FORM_CEP_LOGRADOURO, '', 1, ConstantesForm::$FORM_ONCLICK . '=\'' . ConstantesForm::$FORM_FUNCAO_BUSCAR_CEP . '\''); ?>
                                            </div>
                                            <div class="section">
                                                <?php echo $this->inputFormulario(ConstantesForm::$TRADUCAO_UF, $form, ConstantesForm::$FORM_UF, ConstantesForm::$FORM_ICONE_COMPLEMENTO, 2); ?>
                                            </div>
                                        </div>

                                    <div class="col-md-2 col-sm-3">
                                        <div class="section">
                                            <label for="Hour" class="field-label">PPK</label>
                                            <label for="Hour" class="field">
                                                <button type="submit" class="button btn-danger">
                                                    <i class="fa fa-search"></i>
                                                </button>
                                            </label>
                                        </div>
                                    </div>

                                    <div class="col-md-4 col-sm-12">
                                        <div class="section">
                                            <label for="Hour" class="field-label">Correios</label>
                                            <label for="Hour" class="field">
                                                <button type="submit" class="button btn-danger" style="width:100%;">
                                                    <span>Website Correios</span>
                                                </button>
                                            </label>
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-6 col-sm-12">
                                        <div class="section">
                                            <?php echo $this->inputFormulario(ConstantesForm::$TRADUCAO_BAIRRO, $form, ConstantesForm::$FORM_BAIRRO, ConstantesForm::$FORM_ICONE_COMPLEMENTO, 2); ?>
                                        </div>
                                    </div>
                                    
                                    
                                    <div class="col-md-6">
                                        <div class="section">
                                            <?php echo $this->inputFormulario(ConstantesForm::$TRADUCAO_CIDADE, $form, ConstantesForm::$FORM_CIDADE, ConstantesForm::$FORM_ICONE_COMPLEMENTO, 2); ?>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="section">
                                            <?php echo $this->inputFormulario(ConstantesForm::$TRADUCAO_LOGRADOURO, $form, ConstantesForm::$FORM_LOGRADOURO, ConstantesForm::$FORM_ICONE_COMPLEMENTO, 2); ?>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="section">
                                            <?php echo $this->inputFormulario(ConstantesForm::$TRADUCAO_COMPLEMENTO, $form, ConstantesForm::$FORM_COMPLEMENTO, ConstantesForm::$FORM_ICONE_COMPLEMENTO); ?>
                                        </div>
                                        <!--end section -->
                                    </div>

                                </div>
                                <!--end .section row section -->

                                <div class="section-divider mv40">
                                    <span><?php echo $this->translate(ConstantesForm::$TRADUCAO_DADOS_DO_HOSPEDEIRO); ?></span>
                                </div>
                                <!--.section-divider -->

                                <div class="section row">
                                    <div class="col-md-12">
                                        <div class="section">
                                            <?php echo $this->inputFormulario(ConstantesForm::$TRADUCAO_NOME_HOSPEDEIRO, $form, ConstantesForm::$FORM_NOME_HOSPEDEIRO, ConstantesForm::$FORM_ICONE_NOME_HOSPEDEIRO); ?>
                                        </div>
                                    </div>
                                    <!--end .colm section -->
                                    <div class="section">
                                        <div class="col-xs-5 col-sm-5 col-md-2">
                                            <?php echo $this->inputFormulario(ConstantesForm::$TRADUCAO_DDD_HOSPEDEIRO, $form, ConstantesForm::$FORM_DDD_HOSPEDEIRO, ConstantesForm::$FORM_ICONE_DDD_HOSPEDEIRO); ?>
                                        </div>
                                        <div class="col-xs-7 col-sm-7 col-md-10">
                                            <?php echo $this->inputFormulario(ConstantesForm::$TRADUCAO_TELEFONE_HOSPEDEIRO, $form, ConstantesForm::$FORM_TELEFONE_HOSPEDEIRO, ConstantesForm::$FORM_ICONE_TELEFONE_HOSPEDEIRO); ?>
                                        </div>
                                    </div>
                                </div> 

                                <!--end .section row section -->
                            </div>
                            <!--end .form-body section -->
                            <div class="panel-footer text-right" style="height:65px;">
                                <?php echo $this->formHidden($form->get(ConstantesForm::$FORM_CSRF)); ?>
                                <?php echo $this->botaoSubmitDesabilitado(ConstantesLancamento::$TRADUCAO_CADASTRAR, ConstantesForm::$FORM_SUBMIT, '', ConstantesLancamento::$CLASS_BTN_DANGER_DARK); ?>
                            </div>
                            <!--end .form-footer section -->
                            <?php echo $this->form()->closeTag() ?>
                        </div>
                        <!--end .admin-form section -->
                    </div>
                    <!--end: .admin-form -->
                </div>
            </div>
        </div>
    </div>
</div>
<?php
/* Layout com javascript para tela de cadastro de celula */
echo $this->layoutJSCelulaValidacao;
