<?php

use Cadastro\Form\ConstantesForm;
use Lancamento\Controller\Helper\FuncoesLancamento;
use Login\Controller\Helper\Constantes;

$eventoCelula = $this->celula;
$evento = $eventoCelula->getEvento();
$diaDaSemanaAjustado = FuncoesLancamento::diaDaSemanaPorDia($evento->getDia(), 1);
?>
<div class="mw1000 center-block p10">
    <div class="admin-form theme-danger">
        <blockquote class="blockquote-danger">
            <small><?php echo $this->translate(ConstantesForm::$TRADUCAO_CONFIRMACAO_CADASTRO_CELULA); ?></small>
        </blockquote>
        <div class="panel heading-border panel-danger">
            <div class="panel-body bg-light">
                <div class="section-divider">
                    <span><?php echo $this->translate(ConstantesForm::$TRADUCAO_PERGUNTA_CADASTRO_CELULA); ?></span>
                </div>
                <div class="panel heading-border panel-danger">
                    <div class="panel-body">
                        <address>
                            <?php echo $this->dadosEntidade(); ?>
                        </address>
                        <address>
                            <div><strong><?php echo $this->translate(ConstantesForm::$TRADUCAO_DIA_DA_SEMANA_SIMPLIFICADO) . '/' . $this->translate(ConstantesForm::$TRADUCAO_HORA); ?></strong></div>
                            <div><?php echo $diaDaSemanaAjustado . '/' . $evento->getHoraFormatoHoraMinutoParaListagem(); ?></div>
                        </address>
                        <address>
                            <div><strong><?php echo $this->translate(ConstantesForm::$TRADUCAO_HOSPEDEIRO); ?></strong></div>
                            <div><?php echo $celula->getNome_hospedeiro(); ?></div>
                            <div>Phone: <?php echo $celula->getTelefone_hospedeiroFormatado(); ?></div>
                        </address>                     
                        <address>
                            <div><strong><?php echo $this->translate(ConstantesForm::$TRADUCAO_ENDERECO); ?></strong></div>
                            <div><?php echo $celula->getLogradouro() . '&nbsp;' . $celula->getComplemento(); ?></div>
                            <div><?php echo $celula->getCidade() . '&nbsp;-&nbsp;' . $celula->getBairro() . ',&nbsp;' . $celula->getUf() . '&nbsp; CEP:' . $celula->getCep(); ?></div>                  
                        </address>
                    </div>                 
                </div>

                <div class="row">
                    <div class="col-sm-12 col-xs-12">
                        <div class="section text-center">
                            <label class="option block mt15">
                                <input type="checkbox" name="checked" value="checked" onclick="
                                        $('#divConfirmacao').toggleClass('hidden');
                                       ">
                                <span class="checkbox"></span><?php echo $this->translate(ConstantesForm::$TRADUCAO_CIENCIA_CADASTRO_CELULA); ?></label> 
                        </div>
                    </div>
                </div>
            </div>
            <div id="divConfirmacao" class="panel-footer text-right hidden" style="height:65px;">
                <button onclick="location.href = '/cadastroCelulas';" data-style="zoom-in" type="button" class="btn ladda-button btn-dark">
                    <i class="fa fa-arrow-left" aria-hidden="true"></i> <?php echo $this->translate(Constantes::$TRADUCAO_VOLTAR); ?>
                </button>
                &nbsp;
                <button onclick="location.href = '/cadastroCelulas';" data-style="zoom-in" type="button" class="btn ladda-button btn-danger">
                    <?php echo $this->translate(ConstantesForm::$TRADUCAO_CONFIRMACAO); ?>
                </button>                
            </div>
        </div>
    </div>
</div>