<div class="background-mobile">
    <div class="mw1000 center-block p10">
        <div class="row">
            <div id="content">
                <div class="row">
                    <div class="admin-form theme-success">
                        <blockquote class="blockquote-success">
                            <p>Confirm your <b class="text-success">registration</b></p>
                            <small>Your data is correct?</small>
                        </blockquote>
                        <div class="panel heading-border panel-success">
                            <div class="panel-body bg-light">

                                <address>
                                    <strong>Day / Hour</strong>
                                    <br>SUNDAY/17.
                                    <br>11:00PM
                                    <br>
                                    <br>
                                    <strong>Address</strong>
                                    <br>QNN 20 Conjunto A Casa 9
                                    <br>Brasília - Ceilândia Sul, DF 72.220-200                    
                                </address>
                                <address>
                                    <strong>Data from Host</strong>
                                    <br>Sérgio Bezerra da Silva
                                    <br>
                                    <abbr title="Telefone">Phone: </abbr>(61) 000 000 000
                                </address>
                            </div>
                            
                            <div class="panel-footer">
                                <div class="text-right">
                                    <button data-style="zoom-in" type="button" class="btn ladda-button btn-default btn-sm">
                                        <span>Corrigir</span>
                                    </button>
                                    <button data-style="zoom-in" type="button" class="btn ladda-button btn-success btn-sm">
                                        <span>Confirmar</span>
                                    </button>
                                </div>
                                <div class="text-left">
                                        <div class="option-group field">
                                            <label class="block mt15 option option-success">
                                                <input type="checkbox" name="parents" id="parents" value="parents">
                                                <span class="checkbox"></span> Confirmo que os dados estão corretos
                                            </label>
                                        </div>
                                        <!-- end .option-group section -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="mw1000 center-block p10">
        <div class="row">
            <div id="content">
                <div class="row">
                    <div class="admin-form theme-danger">
                        <blockquote class="blockquote-danger">
                            <p>Confirm your <b class="text-danger">edition</b></p>
                            <small>Your data is correct?</small>
                        </blockquote>
                        <div class="panel heading-border panel-danger">
                            <div class="panel-body bg-light">
                                <div class="section-divider mv40">
                                    <span>Informações Editadas</span>
                                </div>
                                <!--.section-divider -->
                                <address>
                                    <strong>Day of Week:</strong>
                                    <br>SUNDAY for <i class="text-danger">TUESDAY</i>
                                    <br>
                                    <br>
                                    <strong>CEP:</strong>
                                    <br>72000000 for <i class="text-danger">72220200</i>                   
                                </address>
                                <address>
                                    <strong>Phone Host:</strong>
                                    <abbr title="Telefone">Phone: </abbr>96175424 for <i class="text-danger">983476211</i>
                                </address>
                                
                                <div class="section-divider mv40">
                                    <span>Informações Não Editadas</span>
                                </div>
                                <!--.section-divider -->
                                
                                <address>
                                    <strong>Hour / Minutes:</strong>
                                    <br>11:30
                                    <br>
                                    <br>
                                    <strong>Name Host:</strong>
                                    <br>Sérgio Bezerra da Silva 
                                    <br>
                                    <br>
                                    <strong>DDD:</strong>
                                    <br>61 
                                </address>
                            </div>
                            <div class="panel-footer">
                                <div class="text-right">
                                    <button data-style="zoom-in" type="button" class="btn ladda-button btn-default btn-sm">
                                        <span>Voltar</span>
                                    </button>
                                    <button data-style="zoom-in" type="button" class="btn ladda-button btn-danger btn-sm">
                                        <span>Editar</span>
                                    </button>
                                </div>
                                <div class="text-left p15" style="position:absolute; bottom:7px;">
                                <div class="option-group field">
                                    <label class="option option-danger">
                                        <input type="checkbox" name="parents" id="parents" value="parents">
                                        <span class="checkbox"></span> Confirmo que os dados estão corretos
                                    </label>
                                </div>
                                <!-- end .option-group section -->
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    
    <!---->
    <div class="mw1000 center-block p10">
        <div class="admin-form theme-danger">
            <blockquote class="blockquote-danger">
                <p class="text-danger">Edited Information</p>
                <small>Day of Week: SUNDAY for <i class="text-danger">TUESDAY</i></small>
                <small>CEP: 72000000 for <i class="text-danger">72220200</i></small>
                <small>Phone Host: 96175424 for <i class="text-danger">983476211</i></small>
            </blockquote>
            <div class="text-right">
                <p>Tempo para preenchimento <b>20:00</b> minutos.</p>
            </div>
            <div class="panel heading-border panel-danger">
                <form method="POST" name="CelulaForm" action="/cadastroSalvarCelula" id="CelulaForm">
                    <div class="panel-body bg-light">
                        <div class="section-divider mv40">
                            <span>Day / Hour</span>
                        </div>
                        <!--.section-divider -->

                        <div class="section row">
                            <div class="row">
                                <div class="col-sm-12 col-xs-12">
                                    <div class="section">
                                        <label for="Day of Week" class="field-label">
                                            Day of Week                                </label>
                                        <label for="Day of Week" class="field prepend-icon state-error">
                                            <select name="dia_da_semana" class="gui-input" id="dia_da_semana"><option value="">SELECIONE</option>
                                                <option value="1">SUNDAY</option>
                                                <option value="2">MONDAY</option>
                                                <option value="3" selected="selected">TUESDAY</option>
                                                <option value="4">WEDNESDAY</option>
                                                <option value="5">THURSDAY</option>
                                                <option value="6">FRIDAY</option>
                                                <option value="7">SATURDAY</option></select>
                                        </label>   
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-6 col-xs-6">
                                    <div class="section">
                                        <label for="Hour" class="field-label">
                                            Hour                                </label>
                                        <label for="Hour" class="field prepend-icon">
                                            <select name="hora" class="gui-input" id="hora"><option value="">SELECIONE</option>
                                                <option value="0">00</option>
                                                <option value="1">01</option>
                                                <option value="2">02</option>
                                                <option value="3">03</option>
                                                <option value="4">04</option>
                                                <option value="5">05</option>
                                                <option value="6">06</option>
                                                <option value="7">07</option>
                                                <option value="8">08</option>
                                                <option value="9">09</option>
                                                <option value="10">10</option>
                                                <option value="11" selected="selected">11</option>
                                                <option value="12">12</option>
                                                <option value="13">13</option>
                                                <option value="14">14</option>
                                                <option value="15">15</option>
                                                <option value="16">16</option>
                                                <option value="17">17</option>
                                                <option value="18">18</option>
                                                <option value="19">19</option>
                                                <option value="20">20</option>
                                                <option value="21">21</option>
                                                <option value="22">22</option>
                                                <option value="23">23</option>
                                            </select>
                                        </label>  
                                    </div>
                                </div>
                                <div class="col-sm-6 col-xs-6">
                                    <div class="section">
                                        <label for="Minutes" class="field-label">Minutes</label>
                                        <label for="Minutes" class="field prepend-icon">
                                            <select name="minutos" class="gui-input" id="minutos"><option value="">SELECIONE</option>
                                                <option value="0">00</option>
                                                <option value="1">01</option>
                                                <option value="2">02</option>
                                                <option value="3">03</option>
                                                <option value="4">04</option>
                                                <option value="5">05</option>
                                                <option value="6">06</option>
                                                <option value="7">07</option>
                                                <option value="8">08</option>
                                                <option value="9">09</option>
                                                <option value="10">10</option>
                                                <option value="11">11</option>
                                                <option value="12">12</option>
                                                <option value="13">13</option>
                                                <option value="14">14</option>
                                                <option value="15">15</option>
                                                <option value="16">16</option>
                                                <option value="17">17</option>
                                                <option value="18">18</option>
                                                <option value="19">19</option>
                                                <option value="20">20</option>
                                                <option value="21">21</option>
                                                <option value="22">22</option>
                                                <option value="23">23</option>
                                                <option value="24">24</option>
                                                <option value="25">25</option>
                                                <option value="26">26</option>
                                                <option value="27">27</option>
                                                <option value="28">28</option>
                                                <option value="29">29</option>
                                                <option value="30" selected="selected">30</option>
                                                <option value="31">31</option>
                                                <option value="32">32</option>
                                                <option value="33">33</option>
                                                <option value="34">34</option>
                                                <option value="35">35</option>
                                                <option value="36">36</option>
                                                <option value="37">37</option>
                                                <option value="38">38</option>
                                                <option value="39">39</option>
                                                <option value="40">40</option>
                                                <option value="41">41</option>
                                                <option value="42">42</option>
                                                <option value="43">43</option>
                                                <option value="44">44</option>
                                                <option value="45">45</option>
                                                <option value="46">46</option>
                                                <option value="47">47</option>
                                                <option value="48">48</option>
                                                <option value="49">49</option>
                                                <option value="50">50</option>
                                                <option value="51">51</option>
                                                <option value="52">52</option>
                                                <option value="53">53</option>
                                                <option value="54">54</option>
                                                <option value="55">55</option>
                                                <option value="56">56</option>
                                                <option value="57">57</option>
                                                <option value="58">58</option>
                                                <option value="59">59</option>
                                            </select>
                                        </label>                                                  
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <div class="section">
                                        <label for="CEP" class="field-label">CEP - Do not know your ZIP code <u><a target="_blank" href="http://www.buscacep.correios.com.br/sistemas/buscacep/">Click Here</a><u></u></u></label>
                                        <u>
                                            <u>
                                                <label for="CEP" class="field prepend-icon state-error">
                                                    <input type="text" name="cep_logradouro" class="gui-input" id="cep_logradouro" onblur="buscarEndereco(document.getElementById('cep_logradouro').value);" onkeypress="return submitEnter(this, event)" value="72220200">
                                                    <label for="CEP" class="field-icon">
                                                        <i class="fa fa-location-arrow"></i>&nbsp;<img id="loadercep_logradouro" class="hidden" src="/img/loader.gif">
                                                    </label>
                                                </label>
                                            </u>
                                        </u>
                                    </div>
                                    <u>
                                        <u> 
                                        </u>   
                                    </u>
                                </div>
                                <u>
                                    <u>
                                    </u> 
                                </u>
                            </div>
                            <u>
                                <u>
                                    <div id="resultadoBusca"></div>
                                    <div id="endereco" class="hidden">
                                        <div class="row">
                                            <div class="col-md-6 col-sm-12">
                                                <div class="section">
                                                    <input type="hidden" id="hiddenuf" name="hiddenuf" value=""><label for="UF" class="field-label">UF</label><label for="UF" class="field prepend-icon"><input type="text" name="uf" class="gui-input" id="uf" placeholder="UF" disabled="disabled" value=""><label for="UF" class="field-icon"><i class="fa fa-location-arrow"></i>&nbsp;<img id="loaderuf" class="hidden" src="/img/loader.gif"></label></label></div>
                                            </div>
                                            <div class="col-md-6 col-sm-12">
                                                <div class="section">
                                                    <input type="hidden" id="hiddenbairro" name="hiddenbairro" value=""><label for="Neighborhood" class="field-label">Neighborhood</label><label for="Neighborhood" class="field prepend-icon"><input type="text" name="bairro" class="gui-input" id="bairro" placeholder="Neighborhood" disabled="disabled" value=""><label for="Neighborhood" class="field-icon"><i class="fa fa-location-arrow"></i>&nbsp;<img id="loaderbairro" class="hidden" src="/img/loader.gif"></label></label></div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="section">
                                                    <input type="hidden" id="hiddencidade" name="hiddencidade" value=""><label for="City" class="field-label">City</label><label for="City" class="field prepend-icon"><input type="text" name="cidade" class="gui-input" id="cidade" placeholder="City" disabled="disabled" value=""><label for="City" class="field-icon"><i class="fa fa-location-arrow"></i>&nbsp;<img id="loadercidade" class="hidden" src="/img/loader.gif"></label></label></div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="section">
                                                    <input type="hidden" id="hiddenlogradouro" name="hiddenlogradouro" value=""><label for="Public" place="" class="field-label">Public Place</label><label for="Public Place" class="field prepend-icon"><input type="text" name="logradouro" class="gui-input" id="logradouro" placeholder="Public Place" disabled="disabled" value=""><label for="Public Place" class="field-icon"><i class="fa fa-location-arrow"></i>&nbsp;<img id="loaderlogradouro" class="hidden" src="/img/loader.gif"></label></label></div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="section">
                                                    <label for="Complement" class="field-label">Complement</label><label for="Complement" class="field prepend-icon"><input type="text" name="complemento" class="gui-input" id="complemento" placeholder="Complement" value=""><label for="Complement" class="field-icon"><i class="fa fa-location-arrow"></i>&nbsp;<img id="loadercomplemento" class="hidden" src="/img/loader.gif"></label></label></div>
                                            </div>
                                        </div>

                                    </div>
                                </u></u></div><u><u>
                                <!--end .section row section -->

                                <div class="section-divider mv40">
                                    <span>Data from Host</span>
                                </div>
                                <!--.section-divider -->

                                <div class="section row">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="section">
                                                <label for="Name" host="" class="field-label">Name Host</label><label for="Name Host" class="field prepend-icon"><input type="text" name="nome_hospedeiro" class="gui-input" id="nome_hospedeiro" placeholder="Name Host" value="Sérgio Bezerra da Silva"><label for="Name Host" class="field-icon"><i class="fa fa-terminal"></i>&nbsp;<img id="loadernome_hospedeiro" class="hidden" src="/img/loader.gif"></label></label></div>
                                        </div>
                                    </div>
                                    <!--end .colm section -->
                                    <div class="section">
                                        <div class="row">
                                            <div class="col-xs-5 col-sm-5 col-md-2">
                                                <label for="DDD" class="field-label">DDD</label><label for="DDD" class="field prepend-icon"><input type="text" name="ddd_hospedeiro" class="gui-input" id="ddd_hospedeiro" placeholder="DDD" value="61"><label for="DDD" class="field-icon"><i class="fa fa-phone-square"></i>&nbsp;<img id="loaderddd_hospedeiro" class="hidden" src="/img/loader.gif"></label>                            </label></div>
                                            <div class="col-xs-7 col-sm-7 col-md-10">
                                                <label for="Phone" host="" class="field-label">Phone Host</label><label for="Phone Host" class="field prepend-icon state-error"><input type="text" name="telefone_hospedeiro" class="gui-input" id="telefone_hospedeiro" placeholder="Phone Host" value="983746211"><label for="Phone Host" class="field-icon"><i class="fa fa-phone-square"></i>&nbsp;<img id="loadertelefone_hospedeiro" class="hidden" src="/img/loader.gif"></label>                            </label></div>
                                        </div>
                                    </div>
                                </div> 

                                <!--end .section row section -->
                            </u></u></div><u><u>
                            <!--end .form-body section -->
                            <div class="panel-footer text-right" style="height:65px;">
                                <button onclick="location.href = '/cadastroCelulas';" data-style="zoom-in" type="button" class="btn ladda-button btn-default"><span class="ladda-label">Cancelar</span><span class="ladda-spinner"></span></button>
                                &nbsp;
                                <input type="hidden" name="csrf" value="fc4cc9aac1b988d96ead8360aad78b00-5a4060c8bb36b077db5643ddb396d1b0"><input type="hidden" name="id" id="id" value=""><button id="submit" name="submit" class="btn ladda-button btn-danger dark mr10 pull-right" data-style="zoom-in" disabled="disabled"><span class="ladda-label">Editar</span><span class="ladda-spinner"></span></button></div>
                            <!--end .form-footer section -->
                        </u></u></form></div><u><u>
                </u></u></div><u><u>
            </u></u>
    </div>
    
    <div class="mw1000 center-block p10">
        <div class="admin-form theme-danger">
            <blockquote class="blockquote-danger">
                <p>Listagem de  Células de <b class="text-danger">Multiplication</b></p>
            </blockquote>
            <div class="panel heading-border panel-danger">
                <div class="panel-body bg-light">
                    <table class="table">
                        <thead>
                            <tr class="">
                                <th class="text-center">Day/Hour</th>
                                <th class="text-center">Name Host</th>
                                <th class="text-center visible-lg visible-md visible-sm">Phone Host</th>
                                <th class="text-center visible-lg visible-md visible-sm">Public Place</th>
                                <th class="text-center"></th>
                            </tr>
                        </thead>
                        <tbody>  
                            <tr>
                                <td class="text-center">SAT/19H</td>
                                <td class="text-center">SERGIO</td>
                                <td class="text-center visible-lg visible-md visible-sm">61985071955</td>
                                <td class="text-center visible-lg visible-md visible-sm">QR 314 Conjunto 11</td>
                                <td class="text-center">
                                    <button data-style="zoom-in" type="button" class="btn ladda-button btn-default btn-xs">
                                        <span class="">
                                            <i class="fa fa-eye" aria-hidden="true"></i>
                                        </span>
                                        <span>
                                            
                                        </span>
                                    </button>
                                    &nbsp;
                                    <button data-style="zoom-in" type="button" class="btn btn-danger btn-xs" onclick="javascript:confirm('Deseja deletar esta célula?');">
                                        <span class="ladda-label">
                                            <i class="fa fa-times" aria-hidden="true"></i>
                                        </span>
                                        <span class="ladda-spinner"></span>
                                    </button>
                                </td>
                            </tr>
                            <tr>
                                <td class="text-center">THU/21.</td>
                                <td class="text-center">JHOBERT</td>
                                <td class="text-center visible-lg visible-md visible-sm">6198766655</td>
                                <td class="text-center visible-lg visible-md visible-sm">QR 314 Conjunto 11</td>
                                <td class="text-center">
                                    <button data-style="zoom-in" type="button" class="btn ladda-button btn-default btn-xs" onclick="funcaoCadastro('Celula', 37);">
                                        <span class="ladda-label">
                                            <i class="fa fa-eye" aria-hidden="true"></i>
                                        </span>
                                        <span class="ladda-spinner"></span>
                                    </button>
                                    &nbsp;
                                    <button data-style="zoom-in" type="button" class="btn btn-danger btn-xs" onclick="javascript:confirm('Deseja deletar esta célula?');">
                                        <span class="ladda-label">
                                            <i class="fa fa-times" aria-hidden="true"></i>
                                        </span>
                                        <span class="ladda-spinner"></span>
                                    </button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="panel-footer">
                    <div class="alert alert-warning"><i class="fa fa-warning pr10" aria-hidden="true"></i>&nbsp;Número máximo de células alcançado!</div>
                </div>
            </div>
            
            <div class="panel panel-widget mw700 center-block chat-widget">
                <div class="panel-heading">
                    <span class="panel-icon">
                        <i class="fa fa-pencil"></i>
                    </span>
                    <span class="panel-title"> Chat Widget</span>
                </div>
                <div class="panel-body bg-light dark panel-scroller scroller-lg pn scroller scroller-active"><div class="scroller-bar" style="height: 399px;"><div class="scroller-track" style="height: 389px; margin-bottom: 5px; margin-top: 5px;"><div class="scroller-handle" style="height: 281.79px; top: 107.21px;"></div></div></div><div class="scroller-content">
                        <div class="media">
                            <div class="media-left">
                                <a href="#">
                                    <img class="media-object" alt="64x64" src="assets/img/avatars/2.jpg">
                                </a>
                            </div>
                            <div class="media-body">
                                <span class="media-status"></span>
                                <h5 class="media-heading">Courtney Faught
                                    <small> - 12:30am</small>
                                </h5> Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo.
                            </div>
                        </div>
                        <div class="media">
                            <div class="media-body">
                                <span class="media-status offline"></span>
                                <h5 class="media-heading">Joe Gibbons
                                    <small> - 12:30am</small>
                                </h5> Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo.
                            </div>
                            <div class="media-right">
                                <a href="#">
                                    <img class="media-object" alt="64x64" src="assets/img/avatars/1.jpg">
                                </a>
                            </div>
                        </div>
                        <div class="media">
                            <div class="media-left">
                                <a href="#">
                                    <img class="media-object" alt="64x64" src="assets/img/avatars/2.jpg">
                                </a>
                            </div>
                            <div class="media-body">
                                <span class="media-status online"></span>
                                <h5 class="media-heading">Courtney Faught
                                    <small> - 12:30am</small>
                                </h5> Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo.
                            </div>
                        </div>
                        <div class="media">
                            <div class="media-body">
                                <span class="media-status offline"></span>
                                <h5 class="media-heading">Joe Gibbons
                                    <small> - 12:30am</small>
                                </h5> Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo.
                            </div>
                            <div class="media-right">
                                <a href="#">
                                    <img class="media-object" alt="64x64" src="assets/img/avatars/1.jpg">
                                </a>
                            </div>
                        </div>
                        <div class="media">
                            <div class="media-left">
                                <a href="#">
                                    <img class="media-object" alt="64x64" src="assets/img/avatars/2.jpg">
                                </a>
                            </div>
                            <div class="media-body">
                                <span class="media-status online"></span>
                                <h5 class="media-heading">Courtney Faught
                                    <small> - 12:30am</small>
                                </h5> Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo.
                            </div>
                        </div>
                        <div class="media">
                            <div class="media-body">
                                <span class="media-status offline"></span>
                                <h5 class="media-heading">Joe Gibbons
                                    <small> - 12:30am</small>
                                </h5> Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo.
                            </div>
                            <div class="media-right">
                                <a href="#">
                                    <img class="media-object" alt="64x64" src="assets/img/avatars/1.jpg">
                                </a>
                            </div>
                        </div>
                    </div></div>
                <div class="panel-footer">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Enter your message here...">
                        <span class="input-group-btn">
                            <button class="btn btn-default btn-gradient" type="button">Send Message</button>
                        </span>
                    </div>
                    <!-- /input-group -->
                </div>
            </div>
        </div>
    </div>
</div>