<?php

use Cadastro\Controller\Helper\ConstantesCadastro;
use Cadastro\Form\ConstantesForm;
use Lancamento\Controller\Helper\ConstantesLancamento;
use Login\Controller\Helper\Constantes;

/**
 * Nome: celula.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com> e Sergio Bezerra da Silva <sergio.silva.unb@gmail.com>
 * Descricao: Página de cadastro de célula
 */
$tituloDaPagina = $this->translate(ConstantesForm::$TRADUCAO_CADASTRO_CELULA) . ' <b class="text-danger">' . $this->translate(ConstantesForm::$TRADUCAO_MULTIPLICACAO) . '</b>';

$form = $this->Form;
$form->prepare();
$form->setAttribute(ConstantesForm::$FORM_ACTION, $this->url(ConstantesCadastro::$ROUTE_CADASTRO, array(ConstantesCadastro::$PAGINA => ConstantesCadastro::$PAGINA_CELULA_PERSISTIR)));

echo $this->form()->openTag($form);
echo $this->formHidden($form->get(ConstantesForm::$FORM_CSRF));
echo $this->formHidden($form->get(ConstantesForm::$FORM_ID));
echo $this->templateFormularioTopo($tituloDaPagina);
?>
<div id="divFormulario">
    <!-- Inicio panel-body -->
    <div class="panel-body bg-light">
        <div class="section-divider mv40">
            <span><?php echo $this->translate(ConstantesForm::$TRADUCAO_DIA_HORA); ?></span>
        </div>
        <div class="section row">
            <!-- Input Dia da Semana Hora e Minuto -->
            <?php
            echo $this->inputDiaDaSemanaHoraMinuto($form);
            echo $this->inputExtras($form);
            ?>          
        </div>
    </div>
    <!-- Fim panel-body -->
    <!-- Inicio panel-footer -->
    <div class="panel-footer text-right" style="height:65px;">
        <?php
        $labelVoltar = ConstantesForm::$STRING_ICONE_ARROW_LEFT . ' ' . $this->translate(Constantes::$TRADUCAO_VOLTAR);
        $labelContinuar = $this->translate(ConstantesForm::$TRADUCAO_CONTINUAR) . ' ' . ConstantesForm::$STRING_ICONE_ARROW_RIGHT;
        /* Botões */
        echo $this->botaoLink($labelVoltar, ConstantesCadastro::$ROUTE_CADASTRO . ConstantesCadastro::$PAGINA_CELULAS, 2, '');
        echo $this->botaoLink($labelContinuar, ConstantesForm::$STRING_HASHTAG, 0, $this->funcaoOnClick(ConstantesForm::$STRING_FUNCAO_PRE_VALIDACAO) . ' disabled id="botaoContinuar"');
        ?>
    </div>
    <!-- Fim panel-footer -->
</div>
</div>
<div id="divDados" class="hidden">
    <div class="panel-body bg-light">
        <div class="section-divider">
            <span><?php echo $this->translate(ConstantesForm::$TRADUCAO_PERGUNTA_CADASTRO_CELULA); ?></span>
        </div>
        <div class="panel heading-border panel-danger">
            <div class="panel-body">
                <address>
                    <div><strong><?php echo $this->translate(ConstantesForm::$TRADUCAO_DIA_DA_SEMANA_SIMPLIFICADO) . ' / ' . $this->translate(ConstantesForm::$TRADUCAO_HORA); ?></strong></div>
                    <div><span id="spanDiaHora"></span></div>
                </address>
                <address>
                    <div><strong><?php echo $this->translate(ConstantesForm::$TRADUCAO_HOSPEDEIRO); ?></strong></div>
                    <div><span id="spanNome"></span></div>
                    <div><span id="spanTelefone"></span></div>
                </address>                     
                <address>
                    <div><strong><?php echo $this->translate(ConstantesForm::$TRADUCAO_ENDERECO); ?></strong></div>
                    <div><span id="spanLogradouroComplemento"></span></div>
                    <div><span id="spanEndereco"></span></div>                  
                </address>
            </div>                 
        </div>
    </div>
    <div id="divBotaoVoltar" class="panel-footer text-right" style="height:65px;">
        <?php
        $labelVoltar = ConstantesForm::$STRING_ICONE_ARROW_LEFT . ' ' . $this->translate(Constantes::$TRADUCAO_VOLTAR);
        $stringNomeDaFuncaoOnClickVoltarParaOCadastro = '$("#divDados").toggleClass("' . ConstantesForm::$FORM_HIDDEN . '");' .
                '$("#divFormulario").toggleClass("' . ConstantesForm::$FORM_HIDDEN . '")';
        $traducaoDoBotao = ConstantesLancamento::$TRADUCAO_CADASTRAR;
        if (!empty($form->get(ConstantesForm::$FORM_ID)->getValue())) {
            $traducaoDoBotao = ConstantesForm::$TRADUCAO_ALTERAR;
        }
        /* Botões */
        echo $this->botaoLink($labelVoltar, ConstantesForm::$STRING_HASHTAG, 2, $this->funcaoOnClick($stringNomeDaFuncaoOnClickVoltarParaOCadastro));
        echo $this->botaoSubmit($traducaoDoBotao, ConstantesLancamento::$CLASS_BTN_DANGER_DARK);
        ?>                  
    </div>
</div>
<?php
echo $this->templateFormularioRodape();
echo $this->form()->closeTag();

/* Layout com javascript para tela de cadastro de celula */
echo $this->layoutJSCelulaValidacao;
