<?php

use Cadastro\Controller\Helper\ConstantesCadastro;
use Cadastro\Form\ConstantesForm;
use Login\Controller\Helper\Constantes;

/**
 * Nome: grupo.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com>
 * Descricao: Página de cadastro de grupos
 */
$form = $this->Form;
$form->prepare();
$form->setAttribute(ConstantesForm::$FORM_ACTION, 'cadastroGrupoFinalizar');
echo $this->form()->openTag($form);

$tituloDaPagina = 'Cadastro de <span class="text-primary">SubEquipe</span>';
echo $this->templateFormularioTopo($tituloDaPagina);
?>
<script type="text/javascript">
    /* Dados */
    var estadoCivil = 0;
    var responsavel0 = 0;
    var iconeTime = '<i class="fa fa-times" aria-hidden="true"></i>';
    var iconeCheck = '<i class="fa fa-check" aria-hidden="true"></i>';
    var hidden = 'hidden';
    var textDanger = 'text-danger';
    var textSuccess = 'text-success';
    var stringNBSP = '&nbsp;';
    var alertDanger = 'alert alert-danger text-center';

    function validarEstadoCivil() {
        var valorSelecionado = $('input[name=inputEstadoCivil]:checked').val();
        if (valorSelecionado !== undefined) {
            estadoCivil = parseInt(valorSelecionado);
            switch (estadoCivil) {
                case 1:
                    $('#blocoHomem').addClass('hidden');
                    $('#blocoMulher').addClass('hidden');
                    break;
                case 2:
                    $('#blocoResponsavel').addClass('hidden');
                    break;
                default:
                    break;
            }
            $('#divEstadoCivil').addClass('hidden');
            $('#divConfirmacao').removeClass('hidden');
        } else {
            alert('Selecione uma das opções!');
        }
    }

    function selecionarAluno(matricula, nome, dataNascimento, tipo) {
        var spanResponsavelMatricula, spanResponsavelNome, spanResponsavelDataNascimento;
        spanResponsavelMatricula = $('#spanResponsavelMatricula');
        spanResponsavelNome = $('#spanResponsavelNome');
        spanResponsavelDataNascimento = $('#spanResponsavelDataNascimento');
        spanResponsavelMatricula.html(matricula);
        spanResponsavelNome.html(nome);
        spanResponsavelDataNascimento.html(dataNascimento);
        $('#divResponsavel').removeClass('hidden');
        $('#divSelecionarAluno').addClass('hidden');
        var inputIdAlunoSelecionado;
        switch (tipo) {
            case 1:
                inputIdAlunoSelecionado = $('#idAlunoSelecionado1');
                break;
            case 2:
                inputIdAlunoSelecionado = $('#idAlunoSelecionado2');
                break;
            default:
                break;
        }
        $('#idAlunoSelecionado0').val(matricula);
        inputIdAlunoSelecionado.val(matricula);
        /* Limpar campos */
        $('#cpf').val('');
        $('#email').val('');
        $('#repetirEmail').val('');
        $('#hierarquia').val(0);
        $('#spanBuscaCPF').html('');
        $('#spanBuscaNome').html('');
        $('#spanBuscaDataNascimento').html('');
        $('#divResultadoBuscaCPF').addClass(hidden);
        $('#divDadosExtras').addClass(hidden);
        $('#spanEmailJaUtilizado').html('');
        $('#spanEmailJaUtilizado').removeClass('alert');
        $('#spanEmailNaoIgual').html('');
        $('#spanEmailNaoIgual').removeClass('alert');
        $('#divRepetirEmailEHierarquia').addClass(hidden);
    }

    function isNumber(n) {
        return !isNaN(parseFloat(n)) && isFinite(n);
    }

    function submitEnter(myfield, e) {
        var keycode;
        if (window.event)
            keycode = window.event.keyCode;
        else if (e)
            keycode = e.which;
        else
            return true;
        if (keycode == 13) {
            buscarCPF($('#cpf').val());
            return false;
        } else
            return true;
    }

    function buscarCPF(cpf, tipo, dataNascimento) {
        var loader = $('#loadercpf');
        var divResultadoBuscaCPF = $('#divResultadoBuscaCPF');
        var divDadosExtras = $('#divDadosExtras');
        var spanBuscaCPF = $('#spanBuscaCPF');
        var spanBuscaNome = $('#spanBuscaNome');
        var spanBuscaDataNascimento = $('#spanBuscaDataNascimento');
        var spanMensagemDeErro = $('#spanMensagemDeErro');
        var inputHiddenNome;
        var inputHiddenCPF;
        var inputHiddenDataNascimento;
        divResultadoBuscaCPF.addClass(hidden);
        divDadosExtras.addClass(hidden);
        spanBuscaCPF.html('');
        spanBuscaNome.html('');
        spanBuscaDataNascimento.html('');
        spanMensagemDeErro.addClass(hidden);

        loader.removeClass(hidden);

        if (cpf.length === 0) {
            loader.addClass(hidden);
            return false;
        }
        if (dataNascimento.length === 0 || dataNascimento.length !== 10) {
            loader.addClass(hidden);
            alert('Data de nascimento é invalida!');
            return false;
        }
        if (!isNumber(cpf) || cpf.length !== 11) {
            loader.addClass(hidden);
            alert('CPF é invalido!');
            return false;
        }
        $.post(
                "/cadastroBuscarCPF",
                {
                    cpf: cpf,
                    dataNascimento: dataNascimento
                },
        function (data) {
            if (parseInt(data.resposta) === 1) {
                divResultadoBuscaCPF.removeClass(hidden);
                spanBuscaCPF.html(data.cpf);
                spanBuscaNome.html(data.nome);
                spanBuscaDataNascimento.html(data.dataNascimento);
                var nomeDoAlunoSelecionado = $('#spanResponsavelNome').text();
                var splitNomeDoAluno = nomeDoAlunoSelecionado.split(" ");
                var splitNomeEncontradoNaBusca = data.nome.split(" ");

                if (splitNomeDoAluno[0] !== splitNomeEncontradoNaBusca[0]) {
                    spanMensagemDeErro
                            .text('Nome do CPF não confere com o do aluno')
                            .removeClass(hidden);
                } else {
                    if (splitNomeDoAluno[0] === splitNomeEncontradoNaBusca[0]) {
                        spanMensagemDeErro.addClass(hidden);
                        $('#divEmailResponsavel').removeClass(hidden);
                    }
                }

            }
            if (parseInt(data.resposta) === 2) {
                /* Não encontrou no PROCOB */
                spanMensagemDeErro
                        .removeClass(hidden)
                        .text(data.mensagem);
            }
            loader.addClass(hidden);
            divDadosExtras.removeClass(hidden);
        }
        , 'json');
    }

    function buscarEmail(email) {
        var loader = $('#loaderemail');
        var spanEmail = $('#spanemail');
        var divRepetirEmailEHierarquia = $('#divRepetirEmailEHierarquia');
        loader.removeClass(hidden);
        divRepetirEmailEHierarquia.addClass(hidden);
        if (email.length === 0) {
            loader.addClass(hidden);
            return false;
        }
        if (!validaEmail(email)) {
            loader.addClass(hidden);
            spanEmail.html(iconeTime);
            spanEmail.removeClass(textSuccess);
            spanEmail.addClass(textDanger);
            return false;
        } else {
            $.post(
                    "/cadastroBuscarEmail",
                    {email: email},
            function (data) {
                var spanEmailJaUtilizado = $('#spanEmailJaUtilizado');
                // liberado
                if (!data.resposta) {
                    spanEmailJaUtilizado.addClass(hidden);
                    divRepetirEmailEHierarquia.removeClass(hidden);
                    spanEmail.addClass(textSuccess);
                    spanEmail.removeClass(textDanger);
                    spanEmail.html(iconeCheck);
                }
                // não liberado
                if (data.resposta) {
                    spanEmailJaUtilizado.html('Email já utilizado por outra pessoa!');
                    spanEmailJaUtilizado.addClass(alertDanger);
                    divRepetirEmailEHierarquia.addClass(hidden);
                    spanEmail.addClass(textDanger);
                    spanEmail.removeClass(textSuccess);
                    spanEmail.html(iconeTime);
                }
                loader.addClass(hidden);
            }, 'json');
        }

    }

    function elementoBotaoInseririResponsavel() {
        return $('#botaoInserirResponsavel');
    }

    function validaEmail(email) {

        var er = RegExp(/^[A-Za-z0-9_\-\.]+@[A-Za-z0-9_\-\.]{2,}\.[A-Za-z0-9]{2,}(\.[A-Za-z0-9])?/);
        if (er.test(email) == false) {
            return false;
            var elemento = elementoBotaoInseririResponsavel();
            elemento.addClass(hidden);
        }
        return true;
    }

    function verificarEmailIgual(emailRepetido) {
        var elemento = elementoBotaoInseririResponsavel();
        var valorEmail = $('#email').val();
        var spanRepetirEmail = $('#spanrepetirEmail');
        var spanEmailNaoIgual = $('#spanEmailNaoIgual');
        if (emailRepetido != valorEmail) {
            spanRepetirEmail.html(iconeTime);
            spanRepetirEmail.removeClass(textSuccess);
            spanRepetirEmail.addClass(textDanger);
            elemento.addClass(hidden);
            spanEmailNaoIgual.removeClass(hidden);
            spanEmailNaoIgual.html('Emails não coferem!');
            spanEmailNaoIgual.addClass(alertDanger);
        } else {
            spanRepetirEmail.html(iconeCheck);
            spanRepetirEmail.addClass(textSuccess);
            spanRepetirEmail.removeClass(textDanger);
            spanEmailNaoIgual.addClass(hidden);
        }
    }

    function mostrarBotaoDeInserirResponsavel(valorDoSelectHierarquia) {
        var elemento = elementoBotaoInseririResponsavel();
        valorDoSelectHierarquia = parseInt(valorDoSelectHierarquia);
        if (valorDoSelectHierarquia !== 0) {
            if ($('#spanrepetirEmail').hasClass(textSuccess)) {
                elemento.removeClass(hidden);
            }
        }
        if (valorDoSelectHierarquia === 0) {
            elemento.addClass(hidden);
        }
    }

    function mostrarBotaoDeProsseguirDoEstadoCivil() {
        $('#divBotaoDeProsseguirDoEstadoCivil').removeClass(hidden);
    }

    function mostrarBotaoDeInserirDadosComplementares(valorDoSelectNumeracao) {
        valorDoSelectNumeracao = parseInt(valorDoSelectNumeracao);
        var divInserirAlterarDadosComplementares = $('#divInserirAlterarDadosComplementares');
        if (valorDoSelectNumeracao !== 0) {
            divInserirAlterarDadosComplementares.removeClass(hidden);
        }
        if (valorDoSelectNumeracao === 0) {
            divInserirAlterarDadosComplementares.addClass(hidden);
        }
    }

    function insereResponsavelNaTelaDeConfimacao(tipoResponsavel, mudarBarraDeProgresso) {
        var spanMatricula = '';
        var spanNome = '';
        var spanNomexs = '';
        var spanEmail = '';
        var spanEmailxs = '';
        var spanHierarquia = '';
        var spanCPF = '';
        var iconeResponavelMatricula = '<i class="fa fa-folder" aria-hidden="true"></i>' + stringNBSP;
        var iconeResponavelNomeInicial = '<i class="fa fa-user" aria-hidden="true"></i>' + stringNBSP + '<strong>';
        var iconeResponavelNomeFinal = '</strong>';
        var iconeResponavelCPF = '<i class="fa fa-info-circle" aria-hidden="true"></i>' + stringNBSP;
        var iconeResponavelEmail = '<i class="fa fa-envelope" aria-hidden="true"></i>' + stringNBSP;
        var iconeResponavelHierarquia = '<i class="fa fa-sitemap" aria-hidden="true"></i>' + stringNBSP;
        var inputHiddenEmail;
        var inputHiddenHierarquia;
        var valorBarraDeProgresso;
        var divCheckDadosResponsavelInseridos;
        var dibBotaoInserirResponsavel;
        var dibBotaoAlterarResponsavel;
        var inputHiddenNome;
        var inputHiddenCPF;
        var inputHiddenDataNascimento;

        switch (tipoResponsavel) {
            case 0:
                spanMatricula = $('#spanMatricula0');
                spanNome = $('#spanNome0');
                spanNomexs = $('#spanNome0xs');
                spanEmail = $('#spanEmail0');
                spanEmailxs = $('#spanEmail0xs');
                spanHierarquia = $('#spanHierarquia0');
                spanCPF = $('#spanCPF0');
                inputHiddenEmail = $('#email0');
                inputHiddenHierarquia = $('#hierarquia0');
                $('#spanInsiraOsDadosDoResponsavel').html('Dados do Respons&aacute;vel');
                valorBarraDeProgresso = 50;
                divCheckDadosResponsavelInseridos = $('#divCheckDadosResponsavelInseridos');
                dibBotaoInserirResponsavel = $('#dibBotaoInserirResponsavel');
                dibBotaoAlterarResponsavel = $('#dibBotaoAlterarResponsavel');
                inputHiddenNome = $('#nome0');
                inputHiddenCPF = $('#cpf0');
                inputHiddenDataNascimento = $('#dataNascimento0');
                break;
            case 1:
                spanMatricula = $('#spanMatricula1');
                spanNome = $('#spanNome1');
                spanNomexs = $('#spanNome1xs');
                spanEmail = $('#spanEmail1');
                spanEmailxs = $('#spanEmail1xs');
                spanHierarquia = $('#spanHierarquia1');
                spanCPF = $('#spanCPF1');
                inputHiddenEmail = $('#email1');
                inputHiddenHierarquia = $('#hierarquia1');
                $('#spanInsiraOsDadosDoResponsavel1').html('Dados do Homem');
                valorBarraDeProgresso = 25;
                divCheckDadosResponsavelInseridos = $('#divCheckDadosResponsavelInseridos1');
                dibBotaoInserirResponsavel = $('#dibBotaoInserirResponsavel1');
                dibBotaoAlterarResponsavel = $('#dibBotaoAlterarResponsavel1');
                inputHiddenNome = $('#nome1');
                inputHiddenCPF = $('#cpf1');
                inputHiddenDataNascimento = $('#dataNascimento1');
                break;
            case 2:
                spanMatricula = $('#spanMatricula2');
                spanNome = $('#spanNome2');
                spanNomexs = $('#spanNome2xs');
                spanEmail = $('#spanEmail2');
                spanEmailxs = $('#spanEmail2xs');
                spanHierarquia = $('#spanHierarquia2');
                spanCPF = $('#spanCPF2');
                inputHiddenEmail = $('#email2');
                inputHiddenHierarquia = $('#hierarquia2');
                $('#spanInsiraOsDadosDoResponsavel2').html('Dados da Mulher');
                valorBarraDeProgresso = 25;
                divCheckDadosResponsavelInseridos = $('#divCheckDadosResponsavelInseridos2');
                dibBotaoInserirResponsavel = $('#dibBotaoInserirResponsavel2');
                dibBotaoAlterarResponsavel = $('#dibBotaoAlterarResponsavel2');
                inputHiddenNome = $('#nome2');
                inputHiddenCPF = $('#cpf2');
                inputHiddenDataNascimento = $('#dataNascimento2');
                break;
            default:
                return false;
        }
        inputHiddenNome.val($('#spanBuscaNome').html());
        inputHiddenCPF.val($('#spanBuscaCPF').html());
        inputHiddenDataNascimento.val($('#spanBuscaDataNascimento').html());
        spanMatricula.html(iconeResponavelMatricula + $('#spanResponsavelMatricula').html());
        spanCPF.html(iconeResponavelCPF + $('#spanBuscaCPF').html());
        spanNomexs.html(iconeResponavelNomeInicial + ajustaStringTelaPequena($('#spanBuscaNome').html()) + iconeResponavelNomeFinal);
        spanEmailxs.html(iconeResponavelEmail + ajustaStringTelaPequena($('#email').val()));
        spanNome.html(iconeResponavelNomeInicial + $('#spanBuscaNome').html() + iconeResponavelNomeFinal);
        spanEmail.html(iconeResponavelEmail + $('#email').val());
        spanHierarquia.html(iconeResponavelHierarquia + $('#hierarquia option:selected').text());
        divCheckDadosResponsavelInseridos.removeClass(hidden);
        dibBotaoInserirResponsavel.addClass(hidden);
        dibBotaoAlterarResponsavel.removeClass(hidden);
        inputHiddenEmail.val($('#email').val());
        inputHiddenHierarquia.val($('#hierarquia option:selected').val());
        $('#email').val('');
        $('#hierarquia').val(0);
        $('#dataNascimento').val('');
        if (mudarBarraDeProgresso === 0) {
            atualizarBarraDeProgresso(valorBarraDeProgresso);
        }
    }

    function limparDadosPessoaSelecionada(tipoResponsavel) {
        var spanMatricula = '';
        var spanNome = '';
        var spanNomexs = '';
        var spanEmail = '';
        var spanEmailxs = '';
        var spanHierarquia = '';
        var spanCPF = '';
        switch (tipoResponsavel) {
            case 0:
                spanMatricula = $('#spanMatricula0');
                spanNome = $('#spanNome0');
                spanNomexs = $('#spanNome0xs');
                spanEmail = $('#spanEmail0');
                spanEmailxs = $('#spanEmail0xs');
                spanHierarquia = $('#spanHierarquia0');
                spanCPF = $('#spanCPF0');
                break;
            default:
                return false;
        }
        spanMatricula.html('');
        spanCPF.html('');
        spanNomexs.html('');
        spanEmailxs.html('');
        spanNome.html('');
        spanEmail.html('');
        spanHierarquia.html('');

        $('#spanInsiraOsDadosDoResponsavel').html('Insira os dados do Responsavel');
        $('#spanInsiraOsDadosDoResponsavel1').html('Insira os dados do Homem');
        $('#spanInsiraOsDadosDoResponsavel2').html('Insira os dados do Mulher');
        $('#cpf').val('');
        $('#email').val('');
        $('#repetirEmail').val('');
        $('#hierarquia').val(0);
        $('#spanBuscaCPF').html('');
        $('#spanBuscaNome').html('');
        $('#spanBuscaDataNascimento').html('');
        $('#divCheckDadosResponsavelInseridos').addClass(hidden);
        $('#dibBotaoInserirResponsavel').removeClass(hidden);
        $('#dibBotaoAlterarResponsavel').addClass(hidden);
        $('#divResultadoBuscaCPF').addClass(hidden);
        $('#divDadosExtras').addClass(hidden);
        $('#divEmailResponsavel').addClass(hidden);
        $('#divRepetirEmailEHierarquia').addClass(hidden);
        $('#botaoInserirResponsavel').addClass(hidden);
        atualizarBarraDeProgresso(-50);
    }

    function insereNumeracaoNaTelaDeConfimacao(mudarBarraDeProgresso) {
        var spanDadosComplementares = $('#spanDadosComplementares');
        var iconeNumeracao = '<i class="fa fa-info-circle" aria-hidden="true"></i>' + stringNBSP;
        spanDadosComplementares.html(iconeNumeracao + stringNBSP + 'Numeração:' + stringNBSP + $('#numeracao option:selected').text());
        $('#spanInsiraOsDadosComplementares').html('Dados Complementares');
        $('#divCheckDadosComplementaresInseridos').removeClass(hidden);
        $('#divBotaoInserirDadosComplementares').addClass(hidden);
        $('#divBotaoAlterarDadosComplementares').removeClass(hidden);
        if (mudarBarraDeProgresso === 0) {
            atualizarBarraDeProgresso(50);
        }
    }

    function pegaValorBarraDeProgresso() {
        return $('#divProgressBar').attr("aria-valuenow");
    }

    function atualizarBarraDeProgresso(valorParaSomar) {
        valorParaSomar = parseInt(valorParaSomar);
        var valorAtualDaBarraDeProgresso = pegaValorBarraDeProgresso();
        var valorAtualizadoDaBarraDeProgresso = parseInt(valorAtualDaBarraDeProgresso) + valorParaSomar;
        var stringPercentual = '%';
        $('#divProgressBar')
                .attr("aria-valuenow", valorAtualizadoDaBarraDeProgresso)
                .html(valorAtualizadoDaBarraDeProgresso + stringPercentual)
                .css('width', valorAtualizadoDaBarraDeProgresso + stringPercentual);

        var divBotaoSubmit = $('#divBotaoSubmit');
        if (valorAtualizadoDaBarraDeProgresso == 100) {
            divBotaoSubmit.removeClass(hidden);
        } else {
            divBotaoSubmit.addClass(hidden);
        }
    }

    function ajustaStringTelaPequena(string) {
        var stringAjustada = '';
        stringAjustada = string.substr(0, 20) + '...';
        return stringAjustada;
    }

    function abrirTelaDeAlunos(tipo) {
        $('#botaoInserirResponsavel0').addClass(hidden);
        $('#botaoInserirResponsavel1').addClass(hidden);
        $('#botaoInserirResponsavel2').addClass(hidden);
        $('.alunoM').addClass(hidden);
        $('.alunoF').addClass(hidden);
        switch (tipo) {
            case 0:
                $('.alunoM').removeClass(hidden);
                $('.alunoF').removeClass(hidden);
                $('#botaoInserirResponsavel0').removeClass(hidden);
                break;
            case 1:
                $('.alunoM').removeClass(hidden);
                $('#botaoInserirResponsavel1').removeClass(hidden);
                break;
            case 2:
                $('.alunoF').removeClass(hidden);
                $('#botaoInserirResponsavel2').removeClass(hidden);
                break;
        }
        $('#divConfirmacao').addClass(hidden);
        $('#divSelecionarAluno').removeClass(hidden);
    }
</script>
<style>
    .quebraDeLinhaDeSpan{
        display: block;
    }
    .checkDadosInseridos{
        float: right;
        position: absolute;
        top: 22px;
        right: 22px;
    }
</style>
<!-- Inicio panel-body -->
<!-- Estado Civil -->
<div id="divEstadoCivil" class="panel-body bg-light">
    <div class="section-divider mt40">
        <span>Selecione uma das opções abaixo</span>
    </div>
    Liderará:
    <div class="option-group field mb10">
        <?php
        echo $this->formRadio($form->get(ConstantesCadastro::$INPUT_ESTADO_CIVIL));
        ?>
    </div>
    <div id="divBotaoDeProsseguirDoEstadoCivil" class="text-right hidden">
        <?php
        $labelContinuar = ConstantesForm::$TRADUCAO_CONTINUAR;
        $extraContinuar = 'onclick="validarEstadoCivil()"';
        echo $this->botaoLink($labelContinuar, ConstantesForm::$STRING_HASHTAG, 0, $extraContinuar);
        ?>
    </div>
</div>

<!-- Confirmacao -->
<div id="divConfirmacao" class="panel-body bg-light hidden">
    <div class="section-divider mt40 mb50">
        <span>Insira o(s) Responsável(is) e os dados complementares</span>
    </div> 
    <!-- Primary Progress Bar -->
    <div class="col-xs-12">
        <div class="progress">
            <div id="divProgressBar" class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">0%</div>
        </div>
    </div>
    <!-- Bloco responsavel -->
    <div id="blocoResponsavel" class="well col-xs-12">
        <address>
            <span id="spanInsiraOsDadosDoResponsavel">Insira os dados do Responsavel</span>
            <span class="quebraDeLinhaDeSpan" id="spanMatricula0"></span>
            <span class="quebraDeLinhaDeSpan" id="spanCPF0"></span>
            <span class="quebraDeLinhaDeSpan hidden-xs" id="spanNome0"></span>
            <span class="quebraDeLinhaDeSpan quebraDeLinhaDeSpan hidden-xs" id="spanEmail0"></span>
            <span class="quebraDeLinhaDeSpan visible-xs" id="spanNome0xs"></span>
            <span class="quebraDeLinhaDeSpan visible-xs" id="spanEmail0xs"></span>
            <span class="quebraDeLinhaDeSpan" id="spanHierarquia0"></span>
        </address>
        <?php
        echo "<div id='dibBotaoInserirResponsavel'>";
        $labelInserirHomem = ConstantesCadastro::$TRADUCAO_INSERIR;
        $extraInserirHomem = 'onclick="abrirTelaDeAlunos(0);"';
        echo $this->botaoLink($labelInserirHomem, ConstantesForm::$STRING_HASHTAG, 5, $extraInserirHomem);
        echo "</div>";
        echo "<div id='dibBotaoAlterarResponsavel' class='hidden'>";
        $labelAlterarHomem = ConstantesCadastro::$TRADUCAO_ALTERAR;
        $extraAlterarHomem = 'onclick="
            $(\'#botaoInserirResponsavel\').addClass(\'hidden\');
            $(\'#botaoAlterarResponsavel\').removeClass(\'hidden\');
            $(\'#divConfirmacao\').addClass(\'hidden\');
            $(\'#divResponsavel\').removeClass(\'hidden\');
        "';
        echo $this->botaoLink($labelAlterarHomem, ConstantesForm::$STRING_HASHTAG, 6, $extraAlterarHomem);

        $labelLimparHomem = ConstantesCadastro::$TRADUCAO_LIMPAR;
        $extraLimparHomem = 'onclick="
            limparDadosPessoaSelecionada(0);
            $(\'#dibBotaoAlterarResponsavel\').addClass(\'hidden\');
            $(\'#dibBotaoInserirResponsavel\').removeClass(\'hidden\');
        "';
        echo $this->botaoLink($labelLimparHomem, ConstantesForm::$STRING_HASHTAG, 6, $extraLimparHomem);
        echo "</div>";
        ?>
        <div id="divCheckDadosResponsavelInseridos" class="checkDadosInseridos hidden">
            <span class="glyphicon glyphicon-ok text-success"></span>
        </div>
    </div>
    <!-- Bloco homem -->
    <div id="blocoHomem" class="well col-xs-12">
        <address>
            <span id="spanInsiraOsDadosDoResponsavel1">Insira os dados do Homem</span>
            <span class="quebraDeLinhaDeSpan" id="spanMatricula1"></span>
            <span class="quebraDeLinhaDeSpan" id="spanCPF1"></span>
            <span class="quebraDeLinhaDeSpan hidden-xs" id="spanNome1"></span>
            <span class="quebraDeLinhaDeSpan quebraDeLinhaDeSpan hidden-xs" id="spanEmail1"></span>
            <span class="quebraDeLinhaDeSpan visible-xs" id="spanNome1xs"></span>
            <span class="quebraDeLinhaDeSpan visible-xs" id="spanEmail1xs"></span>
            <span class="quebraDeLinhaDeSpan" id="spanHierarquia1"></span>
        </address>
        <?php
        echo "<div id='dibBotaoInserirResponsavel1'>";
        $labelInserirHomem = ConstantesCadastro::$TRADUCAO_INSERIR;
        $extraInserirHomem = 'onclick="abrirTelaDeAlunos(1);"';
        echo $this->botaoLink($labelInserirHomem, ConstantesForm::$STRING_HASHTAG, 5, $extraInserirHomem);
        echo "</div>";
        echo "<div id='dibBotaoAlterarResponsavel1' class='hidden'>";
        $labelAlterarHomem = ConstantesCadastro::$TRADUCAO_ALTERAR;
        $extraAlterarHomem = 'onclick="
            $(\'#divConfirmacao\').addClass(\'hidden\');
            $(\'#divResponsavel\').removeClass(\'hidden\');
        "';
        echo $this->botaoLink($labelAlterarHomem, ConstantesForm::$STRING_HASHTAG, 6, $extraAlterarHomem);

        $labelLimparHomem = ConstantesCadastro::$TRADUCAO_LIMPAR;
        $extraLimparHomem = 'onclick="
            $(\'#divConfirmacao\').addClass(\'hidden\');
            $(\'#divResponsavel\').removeClass(\'hidden\');
        "';
        echo $this->botaoLink($labelLimparHomem, ConstantesForm::$STRING_HASHTAG, 6, $extraLimparHomem);
        echo "</div>";
        ?>      
        <div id="divCheckDadosResponsavelInseridos1" class="checkDadosInseridos hidden">
            <span class="glyphicon glyphicon-ok text-success"></span>
        </div>
    </div>
    <!-- Bloco Mulher -->
    <div id="blocoMulher" class="well col-xs-12">
        <address>
            <span id="spanInsiraOsDadosDoResponsavel2">Insira os dados da Mulher</span>
            <span class="quebraDeLinhaDeSpan" id="spanMatricula2"></span>
            <span class="quebraDeLinhaDeSpan" id="spanCPF2"></span>
            <span class="quebraDeLinhaDeSpan hidden-xs" id="spanNome2"></span>
            <span class="quebraDeLinhaDeSpan quebraDeLinhaDeSpan hidden-xs" id="spanEmail2"></span>
            <span class="quebraDeLinhaDeSpan visible-xs" id="spanNome2xs"></span>
            <span class="quebraDeLinhaDeSpan visible-xs" id="spanEmail2xs"></span>
            <span class="quebraDeLinhaDeSpan" id="spanHierarquia2"></span>
        </address>
        <?php
        echo "<div id='dibBotaoInserirResponsavel2'>";
        $labelInserirMulher = ConstantesCadastro::$TRADUCAO_INSERIR;
        $extraInserirMulher = 'onclick="abrirTelaDeAlunos(2);"';
        echo $this->botaoLink($labelInserirMulher, ConstantesForm::$STRING_HASHTAG, 5, $extraInserirMulher);
        echo "</div>";
        echo "<div id='dibBotaoAlterarResponsavel2' class='hidden'>";
        $labelAlterarMulher = ConstantesCadastro::$TRADUCAO_ALTERAR;
        $extraAlterarMulher = 'onclick="
            $(\'#divConfirmacao\').addClass(\'hidden\');
            $(\'#divResponsavel\').removeClass(\'hidden\');
        "';
        echo $this->botaoLink($labelAlterarMulher, ConstantesForm::$STRING_HASHTAG, 6, $extraAlterarMulher);

        $labelLimparMulher = ConstantesCadastro::$TRADUCAO_LIMPAR;
        $extraLimparMulher = 'onclick="
            $(\'#divConfirmacao\').addClass(\'hidden\');
            $(\'#divResponsavel\').removeClass(\'hidden\');
        "';
        echo $this->botaoLink($labelLimparMulher, ConstantesForm::$STRING_HASHTAG, 6, $extraLimparMulher);
        echo "</div>";
        ?>       
        <div id="divCheckDadosResponsavelInseridos2" class="checkDadosInseridos hidden">
            <span class="glyphicon glyphicon-ok text-success"></span>
        </div>
    </div>
    <!-- Bloco Dados Complementares -->
    <div class="well col-xs-12 mb10">
        <address>
            <span id="spanInsiraOsDadosComplementares">Insira os Dados Complementares</span>
            <span class="quebraDeLinhaDeSpan" id="spanDadosComplementares"></span>
        </address>
        <?php
        echo "<div id='divBotaoInserirDadosComplementares'>";
        $labelInserirDadosComplementares = ConstantesCadastro::$TRADUCAO_INSERIR;
        $extraInserirDadosComplementares = 'onclick="
            $(\'#divConfirmacao\').addClass(\'hidden\');
            $(\'#divDadosComplementares\').removeClass(\'hidden\');
            $(\'#numeracao\').val(0);
        "';
        echo $this->botaoLink($labelInserirDadosComplementares, ConstantesForm::$STRING_HASHTAG, 5, $extraInserirDadosComplementares);
        echo "</div>";
        echo "<div id='divBotaoAlterarDadosComplementares' class='hidden'>";
        $labelAlterarDadosComplementares = ConstantesCadastro::$TRADUCAO_ALTERAR;
        $extraAlterarDadosComplementares = 'onclick="
            $(\'#divBotaoInserirSelectDadosComplementares\').addClass(\'hidden\');
            $(\'#divBotaoAlterarSelectDadosComplementares\').removeClass(\'hidden\');
            $(\'#divConfirmacao\').addClass(\'hidden\');
            $(\'#divDadosComplementares\').removeClass(\'hidden\');
        "';
        echo $this->botaoLink($labelAlterarDadosComplementares, ConstantesForm::$STRING_HASHTAG, 6, $extraAlterarDadosComplementares);
        echo "</div>";
        ?>
        <div id="divCheckDadosComplementaresInseridos" class="checkDadosInseridos hidden">
            <span class="glyphicon glyphicon-ok text-success"></span>
        </div>
    </div>
    <div id="divBotaoSubmit" class="hidden">
        <?php echo $this->botaoLink(ConstantesCadastro::$TRADUCAO_FINALIZAR, '#', 7, 'onclick="this.form.submit();"'); ?>
    </div>
</div>

<!-- Selecionar Aluno -->
<div id="divSelecionarAluno" class="panel-body bg-light hidden">
    <div class="section-divider mt40">
        <span>Selecione o Aluno que será utilizado para o cadastro</span>
    </div>  
    <div class="panel-menu">
        <input id="fooFilter" type="text" class="form-control" placeholder="Filtro">
    </div>
    <table class="table footable mb10" data-filter="#fooFilter">
        <thead>
            <tr>
                <th class = "hidden-xs">Matricula</th>
                <th>Name</th>
                <th class = "hidden-xs">Data Nascimento</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php
            if ($form->getAlunos()) {
                foreach ($form->getAlunos() as $ga) {
                    $tipoResponsavel = 0;
                    $turmaAluno = $ga->getTurmaAluno();
                    $aluno = $turmaAluno->getPessoa();
                    $aluno->setMatriculaAtual($turmaAluno->getMatricula());
                    if ($aluno->getSexo() === 'M') {
                        $classeAluno = 'alunoM';
                        $tipoResponsavel = 1;
                    }
                    if ($aluno->getSexo() === 'F') {
                        $classeAluno = 'alunoF';
                        $tipoResponsavel = 2;
                    }
                    $funcaoOnClick = 'onclick=\'selecionarAluno("' .
                            $aluno->getMatriculaAtual() . '", "' .
                            $aluno->getNome() . '", "' .
                            $aluno->getDataNascimentoFormatada() . '", ' .
                            $tipoResponsavel . ');\'';
                    echo '<tr class="' . $classeAluno . '">';
                    echo '<td class="hidden-xs">' . $aluno->getMatriculaAtual() . '</td>';
                    echo '<td><span class="hidden-xs">' . $aluno->getNome() . '</span><span class="visible-xs">' . $aluno->getNomePrimeiroPrimeiraSiglaUltimo() . '</span></td>';
                    echo '<td class="hidden-xs">' . $aluno->getDataNascimentoFormatada() . '</td>';
                    echo '<td><button type="button" class="btn btn-' . Constantes::$COR_BOTAO . ' btn-xs" ' . $funcaoOnClick . '>Selecionar</button></td>';
                    echo '</tr>';
                }
            } else {
                echo '<tr><td>Sem alunos cadastrados!</td></tr>';
            }
            ?>           
        </tbody>
    </table>
    <?php
    $labelVoltar = Constantes::$TRADUCAO_VOLTAR;
    $extraVoltar = 'onclick="
                    $(\'#divConfirmacao\').removeClass(\'hidden\');
            $(\'#divSelecionarAluno\').addClass(\'hidden\');
            "';
    echo $this->botaoLink($labelVoltar, ConstantesForm::$STRING_HASHTAG, 8, $extraVoltar);
    ?>
</div>

<!--Responsavel -->
<div id = "divResponsavel" class = "panel-body bg-light hidden">
    <div class="section-divider mt40">
        <span>Digite o CPF do Aluno selecionado</span>
    </div>
    <!-- HelperView aluno selecionado -->
    <div class = "well well-sm">
        <i class = "fa fa-folder" aria-hidden = "true"></i>&nbsp;
        <span id="spanResponsavelMatricula"></span>
        <br />
        <i class = "fa fa-user" aria-hidden = "true"></i>&nbsp;
        <strong><span id="spanResponsavelNome"></span></strong>
        <br />
        <i class = "fa fa-birthday-cake" aria-hidden = "true"></i>&nbsp;
        <span id="spanResponsavelDataNascimento"></span>
    </div>
    <!-- Fim HelperView -->
    <!-- Buscar CPF -->
    <span id="spanMensagemDeErro" class="quebraDeLinhaDeSpan mt10 alert alert-danger text-center hidden"></span>
    <?php
    echo $this->formInput($form->get(ConstantesForm::$FORM_DATA_NASCIMENTO));
    echo $this->inputAddon($form, ConstantesForm::$FORM_CPF);
    ?>
    <!-- FIM Buscar CPF -->

    <!-- HelperView Resultado Busca -->
    <div id="divResultadoBuscaCPF" class="well well-sm hidden">
        <i class = "fa fa-info-circle" aria-hidden = "true"></i>&nbsp;
        <span id="spanBuscaCPF"></span>
        <br /><i class = "fa fa-user" aria-hidden = "true"></i>&nbsp;
        <strong><span id="spanBuscaNome"></span></strong>
        <br /><i class = "fa fa-birthday-cake" aria-hidden = "true"></i>&nbsp;
        <span id="spanBuscaDataNascimento"></span>
    </div>
    <!-- Fim HelperView -->
    <div id="divDadosExtras" class="hidden">
        <span id="spanEmailJaUtilizado" class="quebraDeLinhaDeSpan"></span>
        <div id="divEmailResponsavel" class="hidden">            
            <label for="email" class="field-label">Digite o email</label>
            <!-- Buscar Email -->
            <?php echo $this->inputAddon($form, ConstantesForm::$FORM_EMAIL, 2); ?>
            <!-- FIM Buscar Email --> 
        </div>
        <div id="divRepetirEmailEHierarquia" class="hidden">
            <span id="spanEmailNaoIgual" class="quebraDeLinhaDeSpan"></span>
            <label for="repetirEmail" class="field-label">Repita o email</label>
            <!-- Buscar Repetir Email -->
            <?php echo $this->inputAddon($form, ConstantesForm::$FORM_REPETIR_EMAIL, 3); ?>
            <!-- FIM Buscar Repetir Email -->

            <!-- Selecionar Hierarquia -->
            <label class="field-label"><?php $this->translate(''); ?>Selecione a Hierarquia</label>
            <?php echo $this->formSelect($form->get(ConstantesForm::$FORM_HIERARQUIA)); ?>
            <!-- Fim Selecionar Hierarquia -->
        </div>
    </div>
    <div id="botaoInserirResponsavel" class="mt10 hidden">        
        <?php
        $labelInserirResponsavel = ConstantesCadastro::$TRADUCAO_INSERIR;
        $extraInserirResponsavel = ' id="botaoInserirResponsavel#numero" onclick="
            insereResponsavelNaTelaDeConfimacao(#numero, 0); 
            $(\'#divConfirmacao\').removeClass(\'hidden\');            
            $(\'#divResponsavel\').addClass(\'hidden\');
        "';
        $extraResponsavel0 = str_replace('#numero', 0, $extraInserirResponsavel);
        echo $this->botaoLink($labelInserirResponsavel, ConstantesForm::$STRING_HASHTAG, 7, $extraResponsavel0);

        $extraResponsavel1 = str_replace('#numero', 1, $extraInserirResponsavel);
        echo $this->botaoLink($labelInserirResponsavel, ConstantesForm::$STRING_HASHTAG, 7, $extraResponsavel1);

        $extraResponsavel2 = str_replace('#numero', 2, $extraInserirResponsavel);
        echo $this->botaoLink($labelInserirResponsavel, ConstantesForm::$STRING_HASHTAG, 7, $extraResponsavel2);
        ?>
    </div>
    <div id="botaoAlterarResponsavel" class="mt10 hidden">
        <?php
        $labelAlterarResponsavel = ConstantesCadastro::$TRADUCAO_ALTERAR;
        $extraAlterarResponsavel = 'onclick="
            insereResponsavelNaTelaDeConfimacao(0, 1); 
            $(\'#divConfirmacao\').removeClass(\'hidden\');            
            $(\'#divResponsavel\').addClass(\'hidden\');
        "';
        echo $this->botaoLink($labelAlterarResponsavel, ConstantesForm::$STRING_HASHTAG, 7, $extraAlterarResponsavel);
        ?>
    </div>
    <div class="mt10">
        <?php
        $extraVoltarDadosComplementares = 'onclick="
            $(\'#divSelecionarAluno\').removeClass(\'hidden\');
            $(\'#divResponsavel\').addClass(\'hidden\');
            "';
        echo $this->botaoLink($labelVoltar, ConstantesForm::$STRING_HASHTAG, 8, $extraVoltarDadosComplementares);
        ?>
    </div>
</div>

<!--Dados Complementares -->
<div id = "divDadosComplementares" class = "panel-body bg-light hidden">
    <!-- HelperView dados complementares -->

    <!-- Selecionar Numeracao -->
    <label class="field-label"><?php $this->translate(''); ?>Selecione a Numeracao da Sub Equipe</label>
    <?php echo $this->formSelect($form->get(ConstantesForm::$FORM_NUMERACAO)); ?>
    <!-- Fim Selecionar Numeracao -->

    <!-- Fim HelperView dados complementares -->
    <div class="mt10">
        <?php
        echo "<div id='divInserirAlterarDadosComplementares' class='hidden'>";
        echo "<div id='divBotaoInserirSelectDadosComplementares'>";
        $labelInserirDadosComplementares = ConstantesCadastro::$TRADUCAO_INSERIR;
        $extraInserirDadosComplementares = 'onclick="
            insereNumeracaoNaTelaDeConfimacao(0);
            $(\'#divDadosComplementares\').addClass(\'hidden\');
            $(\'#divConfirmacao\').removeClass(\'hidden\');
        "';
        echo $this->botaoLink($labelInserirDadosComplementares, ConstantesForm::$STRING_HASHTAG, 7, $extraInserirDadosComplementares);
        echo "</div>";

        echo "<div id='divBotaoAlterarSelectDadosComplementares' class='hidden'>";
        $labelInserirDadosComplementares = ConstantesCadastro::$TRADUCAO_ALTERAR;
        $extraInserirDadosComplementares = 'onclick="
            insereNumeracaoNaTelaDeConfimacao(1);
            $(\'#divDadosComplementares\').addClass(\'hidden\');
            $(\'#divConfirmacao\').removeClass(\'hidden\');
        "';
        echo $this->botaoLink($labelInserirDadosComplementares, ConstantesForm::$STRING_HASHTAG, 7, $extraInserirDadosComplementares);
        echo "</div>";
        echo "</div>";
        $extraVoltarDadosComplementares = 'onclick="
            $(\'#divConfirmacao\').removeClass(\'hidden\');
            $(\'#divDadosComplementares\').addClass(\'hidden\');
            "';
        echo $this->botaoLink($labelVoltar, ConstantesForm::$STRING_HASHTAG, 8, $extraVoltarDadosComplementares);
        ?>
    </div>
</div>

<?php
echo $this->formHidden($form->get(Constantes::$INPUT_CSRF));
echo $this->formHidden($form->get(ConstantesForm::$FORM_ID_ALUNO_SELECIONADO . '0'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_ID_ALUNO_SELECIONADO . '1'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_ID_ALUNO_SELECIONADO . '2'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_NOME . '0'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_NOME . '1'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_NOME . '2'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_EMAIL . '0'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_EMAIL . '1'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_EMAIL . '2'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_CPF . '0'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_CPF . '1'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_CPF . '2'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_HIERARQUIA . '0'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_HIERARQUIA . '1'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_HIERARQUIA . '2'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_DATA_NASCIMENTO . '0'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_DATA_NASCIMENTO . '1'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_DATA_NASCIMENTO . '2'));

echo $this->templateFormularioRodape();
echo $this->form()->closeTag();

/* Layout com javascript para tela de cadastro de grupo */
echo $this->layoutJSGrupo;
