<?php

use Cadastro\Controller\Helper\ConstantesCadastro;
use Login\Controller\Helper\Constantes;

/** Nome: grupo-atualizar.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com>
 * Descricao: Página para atualizar dados
 */
$form = $this->Form;
$form->prepare();
$form->setAttribute(Constantes::$ACTION, $this->url(ConstantesCadastro::$ROUTE_CADASTRO, array(ConstantesCadastro::$PAGINA => Constantes::$ACTION_ALTERAR_SENHA)));

echo $this->form()->openTag($form);
?>
<style>
    .quebraDeLinhaDeSpan{
        display: block;
    }
</style>
<div class="admin-form mw500">
    <!-- Login Logo -->
    <div class="row">
        <?php
        /* Logo com link para index */
        echo $this->linkLogo();
        ?>
    </div>
    <div class="row text-center">
        <h2 class="text-primary">
            Bem Vindo ao Circuito da Visão.
        </h2>
        <p>Para terminar preencha o seu número de Celular.</p>
        <p>O número deve ser válido e não pode pertencer ao seu líder, familiares ou terceiros.</p>
    </div>
    <div class="panel">
        <div class="panel-body bg-light p25 pb15">
            <div class="section">
                <span id="spanMensagemDeErro" class="alert text-center quebraDeLinhaDeSpan hidden"></span>
            </div>
            <div class="section">
                <div class="col-xs-5 col-sm-5 col-md-3">
                    <input id="ddd" type="tel" maxlength="2" class="form-control" placeholder="DDD"/>
                </div>
                <div class="col-xs-7 col-sm-7 col-md-9">
                    <input id="celular" type="tel" maxlength="9" class="form-control" placeholder="Celular"/>
                </div>
            </div>
        </div>
        <div class="panel-footer clearfix">
            <div id="divVerificarDados">
                <?php echo $this->botaoLink('Verificar', '#', 7, 'onclick="validarNumeroTelefoneCelular();"'); ?>     
            </div>
            <div id="divAtualizarDados" class="hidden">
                <?php echo $this->botaoLink('Atualizar', '#', 7); ?>     
            </div>
        </div>   
    </div>
</div>
<?php
echo $this->formHidden($form->get(Constantes::$ID));
echo $this->form()->closeTag();
?>
<script type="text/javascript">
    var hidden = 'hidden';
    var classAlertDanger = 'alert-danger';
    var classAlertSuccess = 'alert-success';

    function validarNumeroTelefoneCelular() {
        var valorDDD = $('#ddd').val();
        var valorCelular = $('#celular').val();
        var temErro = false;
        var mensagemDeErro;
        var spanMensagemDeErro = $('#spanMensagemDeErro');
        spanMensagemDeErro.html('').addClass(hidden);

        if (valorDDD.length === 0 || valorCelular.length === 0) {
            if (valorDDD.length === 0) {
                temErro = true;
                mensagemDeErro = 'Preencha DDD';
            }
            if (valorCelular.length === 0) {
                temErro = true;
                mensagemDeErro = 'Preencha Celular';
            }
            if (valorDDD.length === 0 && valorCelular.length === 0) {
                temErro = true;
                mensagemDeErro = 'Preencha DDD e Celular';
            }
        } else {
            if (valorDDD.length !== 2) {
                temErro = true;
                mensagemDeErro = 'DDD é invalido';
            } else {
                if (valorCelular.length < 8 || valorCelular.length > 9) {
                    temErro = true;
                    mensagemDeErro = 'Celular é invalido';
                }
            }
        }

        if (temErro) {
            spanMensagemDeErro
                    .removeClass(classAlertSuccess)
                    .addClass(classAlertDanger)
                    .html(mensagemDeErro);
        } else {
            spanMensagemDeErro
                    .removeClass(classAlertDanger)
                    .addClass(classAlertSuccess)
                    .html('<?php echo $this->translate(ConstantesCadastro::$TRADUCAO_DADOS_LIBERADOS); ?>');
            $('#divVerificarDados').addClass(hidden);
            $('#divAtualizarDados').removeClass(hidden);
        }
        spanMensagemDeErro
                .removeClass(hidden);
    }
</script>