<?php

use Cadastro\Controller\Helper\ConstantesCadastro;
use Login\Controller\Helper\Constantes;

/** Nome: grupo-atualizar.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com>
 * Descricao: Página para atualizar dados
 */
$form = $this->Form;
$form->prepare();
$form->setAttribute(Constantes::$ACTION, $this->url(ConstantesCadastro::$ROUTE_CADASTRO, array(ConstantesCadastro::$PAGINA => ConstantesCadastro::$PAGINA_GRUPO_ATUALIZAR)));

echo $this->form()->openTag($form);
?>
<style>
    .quebraDeLinhaDeSpan{
        display: block;
    }
</style>
<div class="admin-form mw800">
    <!-- Login Logo -->
    <div class="row">
        <?php
        /* Logo com link para index */
        echo $this->linkLogo();
        ?>
    </div>
    <div class="row text-center">
        <h1 class="text-primary">
            Bem Vindo ao Circuito da Visão.
        </h1>
        <h2>Para terminar atualize os dados abaixo.</h2>
        <div class="quebraDeLinhaDeSpan">
            <small>O número de célular deve ser válido e não pode pertencer ao seu líder, familiares ou terceiros.</small>
        </div>
    </div>
    <div class="panel mt10">
        <div class="panel-body bg-light p25 pb15">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="section">
                        <span id="spanMensagemDeErro" class="alert text-center quebraDeLinhaDeSpan hidden"></span>
                    </div>
                </div>
            </div>
            <?php
            /* Montar endereço */
            echo $this->montarEndereco($form);
            ?>
            <div class="row">
                <div class="section">
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <label class="field-label">Profissao</label>
                        <label class="field">
                            <?php echo $this->formSelect($form->get(ConstantesCadastro::$FORM_INPUT_PROFISSAO)); ?>
                        </label>
                    </div>                    
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <div class="col-xs-5 col-sm-5 col-md-3">
                            <label class="field-label">DDD</label>
                            <label class="field">
                                <input id="ddd" type="tel" maxlength="2" class="form-control" placeholder="DDD"/>
                            </label>
                        </div>
                        <div class="col-xs-7 col-sm-7 col-md-9">
                            <label class="field-label">Celular</label>
                            <label class="field">
                                <input id="celular" type="tel" maxlength="9" class="form-control" placeholder="Celular"/>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer clearfix">
            <div id="divVerificarDados">
                <?php echo $this->botaoLink('Verificar', '#', 7, 'onclick="validarFormulario();"'); ?>     
            </div>
            <div id="divAtualizarDados" class="hidden">
                <?php echo $this->botaoLink('Atualizar', '#', 7); ?>     
            </div>
        </div>   
    </div>
</div>
<?php
echo $this->formHidden($form->get(Constantes::$ID));
echo $this->form()->closeTag();
?>
<script type="text/javascript">
    var hidden = 'hidden';
    var classAlertDanger = 'alert-danger';
    var classAlertSuccess = 'alert-success';

    function validarFormulario() {
        var valorDDD = $('#ddd').val();
        var valorCelular = $('#celular').val();
        var valorCep = $('#cep_logradouro').val();
        var temErro = false;
        var mensagemDeErro;
        var spanMensagemDeErro = $('#spanMensagemDeErro');
        spanMensagemDeErro.html('').addClass(hidden);

        if (valorCelular.length === 0) {
            temErro = true;
            mensagemDeErro = 'Preencha o Celular';
        }
        if (valorDDD.length === 0) {
            temErro = true;
            mensagemDeErro = 'Preencha o DDD';
        }
        if (valorCep.length === 0) {
            temErro = true;
            mensagemDeErro = 'Preencha o CEP';
        }
        if (valorCelular.length !== 0 && (valorCelular.length < 8 || valorCelular.length > 9)) {
            temErro = true;
            mensagemDeErro = 'Celular é invalido';
        }
        if (valorDDD.length !== 0 && valorDDD.length !== 2) {
            temErro = true;
            mensagemDeErro = 'DDD é invalido';
        }
        if (valorCep.length !== 0 && valorCep.length !== 8) {
            temErro = true;
            mensagemDeErro = 'CEP é invalido';
        }

        if (temErro) {
            spanMensagemDeErro
                    .removeClass(classAlertSuccess)
                    .addClass(classAlertDanger)
                    .html(mensagemDeErro);
        } else {
            spanMensagemDeErro
                    .removeClass(classAlertDanger)
                    .addClass(classAlertSuccess)
                    .html('<?php echo $this->translate(ConstantesCadastro::$TRADUCAO_DADOS_LIBERADOS); ?>');
            $('#divVerificarDados').addClass(hidden);
            $('#divAtualizarDados').removeClass(hidden);
        }
        spanMensagemDeErro
                .removeClass(hidden);
    }
</script>
<?php
$versao = '?v=6.8';

echo $this
        ->headScript()
        ->prependFile($this->basePath() . '/js/circuito_da_visao/buscar-endereco.js' . $versao)
;
echo $this->inlineScript();
