<?php

use Cadastro\Controller\Helper\ConstantesCadastro;
use Cadastro\Form\ConstantesForm;
use Login\Controller\Helper\Constantes;

/**
 * Nome: grupo.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com>
 * Descricao: Página de cadastro de grupos
 */
$form = $this->Form;
$form->prepare();
$form->setAttribute(ConstantesForm::$FORM_ACTION, 'todo');
echo $this->form()->openTag($form);

$tituloDaPagina = 'Cadastro de <span class="text-danger">SubEquipe</span>';
echo $this->templateFormularioTopo($tituloDaPagina);
?>
<script type="text/javascript">
    /* Dados */
    var estadoCivil = 0;
    var responsavel0 = 0;
    function validarEstadoCivil() {
        var valorSelecionado = $('input[name=inputEstadoCivil]:checked').val();
        if (valorSelecionado !== undefined) {
            estadoCivil = parseInt(valorSelecionado);
            switch (estadoCivil) {
                case 1:
                    $('#blocoHomem').addClass('hidden');
                    $('#blocoMulher').addClass('hidden');
                    break;
                case 2:
                    $('#blocoResponsavel').addClass('hidden');
                    break;
                default:
                    break;
            }
            $('#divEstadoCivil').addClass('hidden');
            $('#divConfirmacao').removeClass('hidden');
        } else {
            alert('Selecione uma das opções!');
        }
    }

    function selecionarAluno(matricula, nome, dataNascimento, tipo) {

        var spanResponsavelMatricula, spanResponsavelNome, spanResponsavelDataNascimento;
        spanResponsavelMatricula = $('#spanResponsavelMatricula');
        spanResponsavelNome = $('#spanResponsavelNome');
        spanResponsavelDataNascimento = $('#spanResponsavelDataNascimento');
        spanResponsavelMatricula.html(matricula);
        spanResponsavelNome.html(nome);
        spanResponsavelDataNascimento.html(dataNascimento);
        $('#divResponsavel').removeClass('hidden');
        $('#divSelecionarAluno').addClass('hidden');
    }

    function isNumber(n) {
        return !isNaN(parseFloat(n)) && isFinite(n);
    }
    function submitEnter(myfield, e) {
        var keycode;
        if (window.event)
            keycode = window.event.keyCode;
        else if (e)
            keycode = e.which;
        else
            return true;
        if (keycode == 13) {
            buscarCPF($('#cpf').val());
            return false;
        } else
            return true;
    }

    function buscarCPF(cpf) {
        var loader = $('#loadercpf');
        var divResultadoBuscaCPF = $('#divResultadoBuscaCPF');
        var divDadosExtras = $('#divDadosExtras');
        var spanBuscaCPF = $('#spanBuscaCPF');
        var spanBuscaNome = $('#spanBuscaNome');
        var spanBuscaDataNascimento = $('#spanBuscaDataNascimento');
        var hidden = 'hidden';
        divResultadoBuscaCPF.addClass(hidden);
        spanBuscaCPF.html('');
        spanBuscaNome.html('');
        spanBuscaDataNascimento.html('');
        loader.removeClass(hidden);
        if (cpf.length === 0) {
            loader.addClass(hidden);
            return false;
        }
        if (!isNumber(cpf) || cpf.length !== 11) {
            loader.addClass(hidden);
            alert('CPF é invalido!');
            return false;
        }
        $.post(
                "/cadastroBuscarCPF",
                {
                    cpf: cpf
                },
        function (data) {
            divResultadoBuscaCPF.removeClass(hidden);
            divDadosExtras.removeClass(hidden);
            spanBuscaCPF.html(data.cpf);
            spanBuscaNome.html(data.nome);
            spanBuscaDataNascimento.html(data.dataNascimento);
            loader.addClass(hidden);
        },
                'json');
    }

    function buscarEmail(email) {
        var loader = $('#loaderemail');
        var span = $('#spanemail');
        var hidden = 'hidden';
        var iconeTime = '<i class="fa fa-times" aria-hidden="true"></i>';
        var iconeCheck = '<i class="fa fa-check" aria-hidden="true"></i>';
        var textDanger = 'text-danger';
        var textSuccess = 'text-success';
        loader.removeClass(hidden);
        if (email.length === 0) {
            loader.addClass(hidden);
            return false;
        }
        if (!validaEmail(email)) {
            loader.addClass(hidden);
            span.html(iconeTime);
            span.removeClass(textSuccess);
            span.addClass(textDanger);
            return false;
        } else {
            $.post(
                    "/cadastroBuscarEmail",
                    {email: email},
            function (data) {
                span.addClass(textSuccess);
                span.removeClass(textDanger);
                span.html(iconeCheck);
                loader.addClass(hidden);
            }, 'json');
        }

    }

    function repetirEmail(email) {
        var loader = $('#loaderemail');
        var span = $('#spanemail');
        var hidden = 'hidden';
        var iconeTime = '<i class="fa fa-times" aria-hidden="true"></i>';
        var iconeCheck = '<i class="fa fa-check" aria-hidden="true"></i>';
        var textDanger = 'text-danger';
        var textSuccess = 'text-success';
        loader.removeClass(hidden);
        if (email.length === 0) {
            loader.addClass(hidden);
            return false;
        }
        if (!validaEmail(email)) {
            loader.addClass(hidden);
            span.html(iconeTime);
            span.removeClass(textSuccess);
            span.addClass(textDanger);
            return false;
        } else {
            $.post(
                    "/cadastroBuscarEmail",
                    {email: email},
            function (data) {
                span.addClass(textSuccess);
                span.removeClass(textDanger);
                span.html(iconeCheck);
                loader.addClass(hidden);
            }, 'json');
        }

    }

    function validaEmail(email) {
        var er = RegExp(/^[A-Za-z0-9_\-\.]+@[A-Za-z0-9_\-\.]{2,}\.[A-Za-z0-9]{2,}(\.[A-Za-z0-9])?/);
                if (er.test(email) == false) {
            return false;
        }
        return true;
    }
</script>
<!-- Inicio panel-body -->
<!-- Estado Civil -->
<div id="divEstadoCivil" class="panel-body bg-light">
    <div class="section-divider mt40">
        <span>Selecione uma das opções abaixo</span>
    </div>
    Liderará:
    <div class="option-group field mb10">
        <?php
        echo $this->formRadio($form->get(ConstantesCadastro::$INPUT_ESTADO_CIVIL));
        ?>
    </div>
    <div class="text-right">
        <?php
        $labelContinuar = ConstantesForm::$TRADUCAO_CONTINUAR . ' ' . ConstantesForm::$STRING_ICONE_ARROW_RIGHT;
        $extraContinuar = 'onclick="validarEstadoCivil()"';
        echo $this->botaoLink($labelContinuar, ConstantesForm::$STRING_HASHTAG, 0, $extraContinuar);
        ?>
    </div>
</div>

<!-- Confirmacao -->
<div id="divConfirmacao" class="panel-body bg-light hidden">
    <div class="section-divider mt40 mb50">
        <span>Insira o(s) Responsável(is) e os dados complementares</span>
    </div> 
    <!-- Primary Progress Bar -->
    <div class="col-xs-12">
        <div class="progress">
            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="0" style="width: 0%;">0%</div>
        </div>
    </div>

    <!-- Bloco responsavel -->
    <div id="blocoResponsavel" class="well col-xs-12">
        <address>
            Insira os dados do Responsavel
<!--            <i class="fa fa-user" aria-hidden="true"></i>&nbsp;<strong>Leonardo Pereira Maga...</strong>
            <br><i class="fa fa-sitemap" aria-hidden="true"></i>&nbsp;Obreiro
            <br><i class="fa fa-envelope" aria-hidden="true"></i>&nbsp;falecomleonardope...-->
        </address>
        <?php
        $labelInserirHomem = ConstantesCadastro::$TRADUCAO_INSERIR;
        $extraInserirHomem = 'onclick="
            $(\'#divConfirmacao\').addClass(\'hidden\');
            $(\'#divSelecionarAluno\').removeClass(\'hidden\');
        "';
        echo $this->botaoLink($labelInserirHomem, ConstantesForm::$STRING_HASHTAG, 5, $extraInserirHomem);

//        $labelAlterarHomem = ConstantesCadastro::$TRADUCAO_ALTERAR;
//        $extraAlterarHomem = 'onclick="
//            $(\'#divConfirmacao\').addClass(\'hidden\');
//            $(\'#divResponsavel\').removeClass(\'hidden\');
//        "';
//        echo $this->botaoLink($labelAlterarHomem, ConstantesForm::$STRING_HASHTAG, 6, $extraAlterarHomem);
//
//        $labelLimparHomem = ConstantesCadastro::$TRADUCAO_LIMPAR;
//        $extraLimparHomem = 'onclick="
//            $(\'#divConfirmacao\').addClass(\'hidden\');
//            $(\'#divResponsavel\').removeClass(\'hidden\');
//        "';
//        echo $this->botaoLink($labelLimparHomem, ConstantesForm::$STRING_HASHTAG, 6, $extraLimparHomem);
        ?>
        <!--        <div style="
                     float: right;
                     position: absolute;
                     top: 22px;
                     right: 22px;
                     ">
                    <span class="glyphicon glyphicon-ok text-success"></span>
                </div>-->
    </div>
    <!-- Bloco homem -->
    <div id="blocoHomem" class="well col-xs-12">
        <address>
            Insira os dados do Homem
        </address>
        <?php
        $labelInserirHomem = ConstantesCadastro::$TRADUCAO_INSERIR;
        $extraInserirHomem = 'onclick="
            $(\'#divConfirmacao\').addClass(\'hidden\');
            $(\'#divSelecionarAluno\').removeClass(\'hidden\');
        "';
        echo $this->botaoLink($labelInserirHomem, ConstantesForm::$STRING_HASHTAG, 5, $extraInserirHomem);

        $labelAlterarHomem = ConstantesCadastro::$TRADUCAO_ALTERAR;
        $extraAlterarHomem = 'onclick="
            $(\'#divConfirmacao\').addClass(\'hidden\');
            $(\'#divResponsavel\').removeClass(\'hidden\');
        "';
        echo $this->botaoLink($labelAlterarHomem, ConstantesForm::$STRING_HASHTAG, 6, $extraAlterarHomem);

        $labelLimparHomem = ConstantesCadastro::$TRADUCAO_LIMPAR;
        $extraLimparHomem = 'onclick="
            $(\'#divConfirmacao\').addClass(\'hidden\');
            $(\'#divResponsavel\').removeClass(\'hidden\');
        "';
        echo $this->botaoLink($labelLimparHomem, ConstantesForm::$STRING_HASHTAG, 6, $extraLimparHomem);
        ?>
        <div style="
             float: right;
             position: absolute;
             top: 22px;
             right: 22px;
             ">
            <span class="glyphicon glyphicon-ok text-success"></span>
        </div>
    </div>
    <!-- Bloco Mulher -->
    <div id="blocoMulher" class="well col-xs-12">
        <address>
            Insira os dados do Mulher
        </address>
        <?php
        $labelInserirMulher = ConstantesCadastro::$TRADUCAO_INSERIR;
        $extraInserirMulher = 'onclick="
            $(\'#divConfirmacao\').addClass(\'hidden\');
            $(\'#divSelecionarAluno\').removeClass(\'hidden\');
        "';
        echo $this->botaoLink($labelInserirMulher, ConstantesForm::$STRING_HASHTAG, 5, $extraInserirMulher);

        $labelAlterarMulher = ConstantesCadastro::$TRADUCAO_ALTERAR;
        $extraAlterarMulher = 'onclick="
            $(\'#divConfirmacao\').addClass(\'hidden\');
            $(\'#divResponsavel\').removeClass(\'hidden\');
        "';
        echo $this->botaoLink($labelAlterarMulher, ConstantesForm::$STRING_HASHTAG, 6, $extraAlterarMulher);

        $labelLimparMulher = ConstantesCadastro::$TRADUCAO_LIMPAR;
        $extraLimparMulher = 'onclick="
            $(\'#divConfirmacao\').addClass(\'hidden\');
            $(\'#divResponsavel\').removeClass(\'hidden\');
        "';
        echo $this->botaoLink($labelLimparMulher, ConstantesForm::$STRING_HASHTAG, 6, $extraLimparMulher);
        ?>       
    </div>
    <!-- Bloco Dados Complementares -->
    <div class="well col-xs-12 mb10">
        <address>
            Insira os Dados Complementares
        </address>
        <?php
        $labelInserirDadosComplementares = ConstantesCadastro::$TRADUCAO_INSERIR;
        $extraInserirDadosComplementares = 'onclick="
            $(\'#divConfirmacao\').addClass(\'hidden\');
            $(\'#divDadosComplementares\').removeClass(\'hidden\');
        "';
        echo $this->botaoLink($labelInserirDadosComplementares, ConstantesForm::$STRING_HASHTAG, 5, $extraInserirDadosComplementares);
        ?>
    </div>
    <?php
    $labelFinalizar = ConstantesCadastro::$TRADUCAO_FINALIZAR;
    $extraFinalizar = 'onclick="
            $(\'#divConfirmacao\').addClass(\'hidden\');
            $(\'#divEmailEnviado\').removeClass(\'hidden\');
        "';
    echo $this->botaoLink($labelFinalizar, ConstantesForm::$STRING_HASHTAG, 7, $extraFinalizar);
    ?>
</div>

<!-- Selecionar Aluno -->
<div id="divSelecionarAluno" class="panel-body bg-light hidden">
    <div class="section-divider mt40">
        <span>Selecione o Aluno que será utilizado para o cadastro</span>
    </div>  
    <div class="panel-menu">
        <input id="fooFilter" type="text" class="form-control" placeholder="Filtro">
    </div>
    <table class="table footable mb10" data-filter="#fooFilter">
        <thead>
            <tr>
                <th class = "hidden-xs">Matricula</th>
                <th>Name</th>
                <th class = "hidden-xs">Data Nascimento</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php
            if ($form->getAlunos()) {
                foreach ($form->getAlunos() as $ga) {
                    $turmaAluno = $ga->getTurmaAluno();
                    $aluno = $turmaAluno->getPessoa();
                    $funcaoOnClick = 'onclick=\'selecionarAluno("' .
                            $turmaAluno->getMatricula() . '", "' .
                            $aluno->getNome() . '", "' .
                            $aluno->getDataNascimentoFormatada() . '", 0);\'';
                    echo '<tr>';
                    echo '<td class="hidden-xs">' . $turmaAluno->getMatricula() . '</td>';
                    echo '<td><span class="hidden-xs">' . $aluno->getNome() . '</span><span class="visible-xs">' . $aluno->getNomePrimeiroPrimeiraSiglaUltimo() . '</span></td>';
                    echo '<td class="hidden-xs">' . $aluno->getDataNascimentoFormatada() . '</td>';
                    echo '<td><button type="button" class="btn btn-danger btn-xs" ' . $funcaoOnClick . '>Selecionar</button></td>';
                    echo '</tr>';
                }
            } else {
                echo '<tr><td>Sem alunos incircuciso</td></tr>';
            }
            ?>           
        </tbody>
    </table>
    <?php
    $labelVoltar = ConstantesForm::$STRING_ICONE_ARROW_LEFT . ' ' . Constantes::$TRADUCAO_VOLTAR;
    $extraVoltar = 'onclick="
                    $(\'#divConfirmacao\').removeClass(\'hidden\');
            $(\'#divSelecionarAluno\').addClass(\'hidden\');
            "';
    echo $this->botaoLink($labelVoltar, ConstantesForm::$STRING_HASHTAG, 8, $extraVoltar);
    ?>
</div>

<!--Responsavel -->
<div id = "divResponsavel" class = "panel-body bg-light hidden">
    <div class = "section-divider mt40">
        <span>Digite o CPF do Aluno selecionado</span>
    </div>
    <!-- HelperView aluno selecionado -->
    <div class = "well well-sm">
        <i class = "fa fa-folder" aria-hidden = "true"></i>&nbsp;
        <span id="spanResponsavelMatricula"></span>
        <br />
        <i class = "fa fa-user" aria-hidden = "true"></i>&nbsp;
        <strong><span id="spanResponsavelNome"></span></strong>
        <br />
        <i class = "fa fa-birthday-cake" aria-hidden = "true"></i>&nbsp;
        <span id="spanResponsavelDataNascimento"></span>
    </div>
    <!-- Fim HelperView -->
    <!-- Buscar CPF -->
    <?php echo $this->inputAddon($form, ConstantesForm::$FORM_CPF); ?>
    <!-- FIM Buscar CPF -->    
    <!-- HelperView Resultado Busca -->
    <div id="divResultadoBuscaCPF" class="well well-sm hidden">
        <i class = "fa fa-info-circle" aria-hidden = "true"></i>&nbsp;
        <span id="spanBuscaCPF"></span>
        <br /><i class = "fa fa-user" aria-hidden = "true"></i>&nbsp;
        <strong><span id="spanBuscaNome"></span></strong>
        <br /><i class = "fa fa-birthday-cake" aria-hidden = "true"></i>&nbsp;
        <span id="spanBuscaDataNascimento"></span>
    </div>
    <!-- Fim HelperView -->
    <div id="divDadosExtras" class="hidden">

        <label for = "email" class = "field-label">Digite o email</label>
        <!-- Buscar Email -->
        <?php echo $this->inputAddon($form, ConstantesForm::$FORM_EMAIL, 2); ?>
        <!-- FIM Buscar Email -->    
        <label for = "repetirEmail" class = "field-label">Repita o email</label>
        <!-- Buscar Repetir Email -->
        <?php echo $this->inputAddon($form, ConstantesForm::$FORM_EMAIL, 3); ?>
        <!-- FIM Buscar Repetir Email -->

        <!--        <label for = "" class = "field-label">Selecione a Hierarquia</label>
                <div class = "sm-right">
                    <select class = "form-control">
                        <option value = "0">Selecione</option>
                        <option value = "1">Obreiro</option>
                    </select>
                </div>-->
    </div>
    <?php
    $labelInserirResponsavel = ConstantesCadastro::$TRADUCAO_INSERIR;
    $extraInserirResponsavel = 'onclick="
            $(\'#divResponsavel\').addClass(\'hidden\');
            $(\'#divConfirmacao\').removeClass(\'hidden\');
        "';
//    echo $this->botaoLink($labelInserirResponsavel, ConstantesForm::$STRING_HASHTAG, 7, $extraInserirResponsavel);
    ?>
</div>

<!--Dados Complementares -->
<div id = "divDadosComplementares" class = "panel-body bg-light hidden">
    <label for = "numeroSubEquipe" class = "field-label">Selecione a SubEquipe</label>
    <div class = "sm-right mb10">
        <select class = "form-control">
            <option value = "0">Selecione</option>
            <option value = "1">01</option>
            <option value = "5">05</option>
            <option value = "9">09</option>
        </select>
    </div>
    <?php
    $labelInserirDadosComplementares = ConstantesCadastro::$TRADUCAO_INSERIR;
    $extraInserirDadosComplementares = 'onclick="
            $(\'#divDadosComplementares\').addClass(\'hidden\');
            $(\'#divConfirmacao\').removeClass(\'hidden\');
        "';
    echo $this->botaoLink($labelInserirDadosComplementares, ConstantesForm::$STRING_HASHTAG, 7, $extraInserirDadosComplementares);

    $extraVoltarDadosComplementares = 'onclick="
            $(\'#divConfirmacao\').removeClass(\'hidden\');
            $(\'#divDadosComplementares\').addClass(\'hidden\');
            "';
    echo $this->botaoLink($labelVoltar, ConstantesForm::$STRING_HASHTAG, 8, $extraVoltarDadosComplementares);
    ?>
</div>

<!--Email Enviado -->
<div id = "divEmailEnviado" class = "panel-body bg-light hidden">
    <div id = "divTextoCadastroConcluido" class = "text-center">
        <h1><span class = "text-success">Cadastro concluido com Sucesso!</span></h1>
        <small>Porém ainda <strong>NÃO ESTÁ ATIVADO</strong>
            em poucos minutos os usuários receberão
            um email com as instruções para ativação.
        </small>

        <div class = "col-xs-12">
            <h2 class = "text-default mbn confirmation-header"><i class = "fa fa-check text-success"></i></h2>
        </div>
        <div class = "col-xs-12 mt10">
            <button data-style = "zoom-in" onclick = "location.href = '/pri
                        ncipal
                        ';" type = "button" class = "btn ladda-button btn-danger"><span class = "ladda-label">Pronto!</span></button>
        </div>
    </div>
</div>
<?php
echo $this->templateFormularioRodape();
echo $this->form()->closeTag();
