<div class="panel-body bg-light text-center">
    <h1><span class = "text-success">Cadastro concluido com Sucesso!</span></h1>
    <small>Porém ainda <strong>NÃO ESTÁ ATIVADO</strong>
        em poucos minutos os usuários receberão
        um email com as instruções para ativação.
    </small>

    <div class = "col-xs-12">
        <h2 class = "text-default mbn confirmation-header"><i class = "fa fa-check text-success"></i></h2>
    </div>
    <div class = "col-xs-12 mt10">
        <button data-style = "zoom-in" onclick="location.href = '/principal';" type = "button" class = "btn ladda-button btn-danger"><span class = "ladda-label">Pronto!</span></button>
    </div>
</div>