<style>
    .stepwizard-step p {
        margin-top: 10px;    
        font-size: smaller;
    }

    .stepwizard-row {
        display: table-row;
    }

    .stepwizard {
        display: table;     
        width: 100%;
        position: relative;
    }

    .stepwizard-step button[disabled] {
        opacity: 1 !important;
        filter: alpha(opacity=100) !important;
    }

    .stepwizard-row:before {
        top: 14px;
        bottom: 0;
        position: absolute;
        content: " ";
        width: 100%;
        height: 1px;
        background-color: #ccc;
    }

    .stepwizard-step {   
        width: 25%;
        display: table-cell;
        text-align: center;
        position: relative;
    }

    .btn-circle {
        width: 30px;
        height: 30px;
        text-align: center;
        padding: 6px 0;
        font-size: 12px;
        line-height: 1.428571429;
        border-radius: 15px;
    }
</style>
<div class="mw600 center-block p10">
    <form class="admin-form">
        <div class="panel">
            <div class="panel-body text-center" style="background-color: #FFFFFF;">
                <h1 class="text-primary">
                    Bem Vindo ao Circuito da Visão.
                </h1>
                <!-- Primary Progress Bar -->
                <div class="col-xs-12 mt10">
                    <center>
                        <div class="stepwizard">
                            <div class="stepwizard-row">
                                <div class="stepwizard-step">
                                    <button type="button" class="btn btn-primary btn-circle" disabled="disabled">1</button>
                                    <p>Cadastro</p>
                                </div>
                                <div class="stepwizard-step">
                                    <button type="button" class="btn btn-primary btn-circle" disabled="disabled">2</button>
                                    <p>Atualizar</p>
                                </div>
                                <div class="stepwizard-step">
                                    <button id="botaoPasso3" type="button" class="btn btn-default btn-circle" disabled="disabled">3</button>
                                    <p>Verificar</p>
                                </div> 
                                <div class="stepwizard-step">
                                    <button id="botaoPasso4" type="button" class="btn btn-default btn-circle" disabled="disabled">4</button>
                                    <p>Concluído</p>
                                </div> 
                            </div>
                        </div>
                    </center>
                </div>
                <div id="divInsiraOCelular">
                    <div class="col-xs-12 mt10">
                        <p>Para terminar preencha o seu número de Celular, um código de verificação será enviado via SMS.</p>
                         <p></p>
                    </div>
                    <div class="col-xs-12 mt10">
                        <input type="tel" maxlength="11" class="gui-input phone" placeholder="DDD + Celular"/>
                    </div> 
                    <div class="col-xs-12 mt10">
                        <p>O número deve ser válido e não pode pertencer ao seu líder, familiares ou terceiros.</p>
                    </div>
                    <div class="col-xs-12 mt10">
                        <button data-style="zoom-in" type="button" class="btn ladda-button btn-primary" onclick="mostrarInputParaCodigoDeConfirmacao();"><span class = "ladda-label">Inserir</span></button>
                    </div> 
                </div> 
                <div id="divCodigoConfirmacao" class="hidden">
                    <p>Insira o codigo de ativacao. enviado para o número: (61) 99851-0703</p>
                    <div class="col-xs-12 mt10">
                        <input type="number" class="gui-input" placeholder="Código"/>
                    </div> 
                    <div class="col-xs-12 mt10">
                        <button data-style="zoom-in" type="button" class="btn ladda-button btn-default" onclick="mostrarInputParaCelular();" ><span class = "ladda-label">Editar Número</span></button>
                        <button data-style="zoom-in" type="button" class="btn ladda-button btn-primary" onclick="ajustarProgressBar();" ><span class = "ladda-label">Verificar</span></button>
                    </div> 
                </div> 
                <div id="divFinalizado" class="col-xs-12 hidden">
                    <h1><span class="text-success">Cadastro atualizado com Sucesso!</span></h1>
                    <div class="col-xs-12 mt10">
                        <h2 class="text-default mbn confirmation-header"><i class="fa fa-check text-success"></i></h2>
                    </div>
                    <div class="col-xs-12 mt10">
                        <button data-style="zoom-in" onclick="location.href = '/principal';" type = "button" class = "btn ladda-button btn-primary"><span class = "ladda-label">Pronto!</span></button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    window.onload = initPage;
    function initPage() {
        // Init jQuery Masked inputs
        $('.phone').mask('(99) 99999-9999');
    }
    var hidden = 'hidden';
    function mostrarInputParaCelular() {
        $('#divCodigoConfirmacao').addClass(hidden);
        $('#botaoPasso3')
                .removeClass('btn-primary');
        $('#divInsiraOCelular').removeClass(hidden);
    }
    function mostrarInputParaCodigoDeConfirmacao() {
        $('#divCodigoConfirmacao').removeClass(hidden);
        $('#botaoPasso3')
                .addClass('btn-primary');
        $('#divInsiraOCelular').addClass(hidden);
    }
    function ajustarProgressBar() {
        $('#botaoPasso4')
                .addClass('btn-primary');
        $('#divCodigoConfirmacao').addClass(hidden);
        $('#divFinalizado').removeClass(hidden);
    }
</script>