<?php

use Cadastro\Controller\Helper\ConstantesCadastro;
use Cadastro\Form\ConstantesForm;
use Login\Controller\Helper\Constantes;

/**
 * Nome: grupo.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com>
 * Descricao: Página de cadastro de grupos
 */
$form = $this->Form;
$form->prepare();
$form->setAttribute(ConstantesForm::$FORM_ACTION, 'cadastroGrupoFinalizar');
echo $this->form()->openTag($form);

$tituloDaPagina = 'Cadastro de <span class="text-primary">SubEquipe</span>';
echo $this->templateFormularioTopo($tituloDaPagina);
?>
<style>
    .quebraDeLinhaDeSpan{
        display: block;
    }

    .checkDadosInseridos{
        float: right;
        position: absolute;
        top: 22px;
        right: 22px;
    }

    /* Passo a passo */
    .stepwizard-step p {
        margin-top: 10px;    
        font-size: smaller;
    }

    .stepwizard-row {
        display: table-row;
    }

    .stepwizard {
        display: table;     
        width: 100%;
        position: relative;
        text-align: center;
    }

    .stepwizard-step button[disabled] {
        opacity: 1 !important;
        filter: alpha(opacity=100) !important;
    }

    .stepwizard-row:before {
        top: 14px;
        bottom: 0;
        position: absolute;
        content: " ";
        width: 100%;
        height: 1px;
        background-color: #ccc;
    }

    .stepwizard-step {   
        width: 25%;
        display: table-cell;
        text-align: center;
        position: relative;
    }

    .btn-circle {
        width: 30px;
        height: 30px;
        text-align: center;
        padding: 6px 0;
        font-size: 12px;
        line-height: 1.428571429;
        border-radius: 15px;
    }
</style>
<!-- Inicio panel-body -->
<div class="panel-body bg-light">

    <!-- Estado Civil -->
    <?php echo $this->grupoEstadoCivil($form); ?>

    <!-- Confirmacao -->
    <div id="divConfirmacao" class="hidden">
        <div class="section-divider mt40 mb50">
            <span>Insira o(s) Responsável(is) e os dados complementares</span>
        </div> 
        <!-- Primary Progress Bar -->
        <div class="col-xs-12">
            <div class="progress">
                <div id="divProgressBar" class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">0%</div>
            </div>
        </div>
        <!-- Bloco responsavel -->
        <div id="blocoResponsavel" class="well col-xs-12">
            <address>
                <span id="spanInsiraOsDadosDoResponsavel">Insira os dados do Responsavel</span>
                <span class="quebraDeLinhaDeSpan" id="spanMatricula0"></span>
                <span class="quebraDeLinhaDeSpan" id="spanCPF0"></span>
                <span class="quebraDeLinhaDeSpan hidden-xs" id="spanNome0"></span>
                <span class="quebraDeLinhaDeSpan quebraDeLinhaDeSpan hidden-xs" id="spanEmail0"></span>
                <span class="quebraDeLinhaDeSpan visible-xs" id="spanNome0xs"></span>
                <span class="quebraDeLinhaDeSpan visible-xs" id="spanEmail0xs"></span>
                <span class="quebraDeLinhaDeSpan" id="spanHierarquia0"></span>
            </address>
            <?php
            echo "<div id='divBotaoInserirResponsavel'>";
            $labelInserirHomem = ConstantesCadastro::$TRADUCAO_INSERIR;
            echo $this->botaoLink($labelInserirHomem, ConstantesForm::$STRING_HASHTAG, 5, $this->funcaoOnClick('abrirTelaDeAlunos(0)'));
            echo "</div>";
            echo "<div id='divBotaoLimparResponsavel' class='hidden'>";
            $labelLimparHomem = ConstantesCadastro::$TRADUCAO_LIMPAR;
            echo $this->botaoLink($labelLimparHomem, ConstantesForm::$STRING_HASHTAG, 6, $this->funcaoOnClick('limparDadosPessoaSelecionada(0)'));
            echo "</div>";
            ?>
            <div id="divCheckDadosResponsavelInseridos" class="checkDadosInseridos hidden">
                <span class="glyphicon glyphicon-ok text-success"></span>
            </div>
        </div>
        <!-- Bloco homem -->
        <div id="blocoHomem" class="well col-xs-12">
            <address>
                <span id="spanInsiraOsDadosDoResponsavel1">Insira os dados do Homem</span>
                <span class="quebraDeLinhaDeSpan" id="spanMatricula1"></span>
                <span class="quebraDeLinhaDeSpan" id="spanCPF1"></span>
                <span class="quebraDeLinhaDeSpan hidden-xs" id="spanNome1"></span>
                <span class="quebraDeLinhaDeSpan quebraDeLinhaDeSpan hidden-xs" id="spanEmail1"></span>
                <span class="quebraDeLinhaDeSpan visible-xs" id="spanNome1xs"></span>
                <span class="quebraDeLinhaDeSpan visible-xs" id="spanEmail1xs"></span>
                <span class="quebraDeLinhaDeSpan" id="spanHierarquia1"></span>
            </address>
            <?php
            echo "<div id='divBotaoInserirResponsavel1'>";
            $labelInserirHomem = ConstantesCadastro::$TRADUCAO_INSERIR;
            echo $this->botaoLink($labelInserirHomem, ConstantesForm::$STRING_HASHTAG, 5, $this->funcaoOnClick('abrirTelaDeAlunos(1)'));
            echo "</div>";

            echo "<div id='divBotaoLimparResponsavel1' class='hidden'>";
            $labelLimparHomem = ConstantesCadastro::$TRADUCAO_LIMPAR;
            echo $this->botaoLink($labelLimparHomem, ConstantesForm::$STRING_HASHTAG, 6, $this->funcaoOnClick('limparDadosPessoaSelecionada(1)'));
            echo "</div>";
            ?>      
            <div id="divCheckDadosResponsavelInseridos1" class="checkDadosInseridos hidden">
                <span class="glyphicon glyphicon-ok text-success"></span>
            </div>
        </div>
        <!-- Bloco Mulher -->
        <div id="blocoMulher" class="well col-xs-12">
            <address>
                <span id="spanInsiraOsDadosDoResponsavel2">Insira os dados da Mulher</span>
                <span class="quebraDeLinhaDeSpan" id="spanMatricula2"></span>
                <span class="quebraDeLinhaDeSpan" id="spanCPF2"></span>
                <span class="quebraDeLinhaDeSpan hidden-xs" id="spanNome2"></span>
                <span class="quebraDeLinhaDeSpan quebraDeLinhaDeSpan hidden-xs" id="spanEmail2"></span>
                <span class="quebraDeLinhaDeSpan visible-xs" id="spanNome2xs"></span>
                <span class="quebraDeLinhaDeSpan visible-xs" id="spanEmail2xs"></span>
                <span class="quebraDeLinhaDeSpan" id="spanHierarquia2"></span>
            </address>
            <?php
            echo "<div id='divBotaoInserirResponsavel2'>";
            $labelInserirMulher = ConstantesCadastro::$TRADUCAO_INSERIR;
            echo $this->botaoLink($labelInserirMulher, ConstantesForm::$STRING_HASHTAG, 5, $this->funcaoOnClick('abrirTelaDeAlunos(2)'));
            echo "</div>";

            echo "<div id='divBotaoLimparResponsavel2' class='hidden'>";
            $labelLimparMulher = ConstantesCadastro::$TRADUCAO_LIMPAR;
            echo $this->botaoLink($labelLimparMulher, ConstantesForm::$STRING_HASHTAG, 6, $this->funcaoOnClick('limparDadosPessoaSelecionada(2)'));
            echo "</div>";
            ?>       
            <div id="divCheckDadosResponsavelInseridos2" class="checkDadosInseridos hidden">
                <span class="glyphicon glyphicon-ok text-success"></span>
            </div>
        </div>
        <!-- Bloco Dados Complementares -->
        <div class="well col-xs-12 mb10">
            <address>
                <span id="spanInsiraOsDadosComplementares">Insira os Dados Complementares</span>
                <span class="quebraDeLinhaDeSpan" id="spanDadosComplementares"></span>
            </address>
            <?php
            echo "<div id='divBotaoInserirDadosComplementares'>";
            $labelInserirDadosComplementares = ConstantesCadastro::$TRADUCAO_INSERIR;
            $extraInserirDadosComplementares = 'onclick="
            $(\'#divConfirmacao\').addClass(\'hidden\');
            $(\'#divDadosComplementares\').removeClass(\'hidden\');
            $(\'#numeracao\').val(0);
        "';
            echo $this->botaoLink($labelInserirDadosComplementares, ConstantesForm::$STRING_HASHTAG, 5, $extraInserirDadosComplementares);
            echo "</div>";
            echo "<div id='divBotaoAlterarDadosComplementares' class='hidden'>";
            $labelAlterarDadosComplementares = ConstantesCadastro::$TRADUCAO_ALTERAR;
            $extraAlterarDadosComplementares = 'onclick="
            $(\'#divBotaoInserirSelectDadosComplementares\').addClass(\'hidden\');
            $(\'#divBotaoAlterarSelectDadosComplementares\').removeClass(\'hidden\');
            $(\'#divConfirmacao\').addClass(\'hidden\');
            $(\'#divDadosComplementares\').removeClass(\'hidden\');
        "';
            echo $this->botaoLink($labelAlterarDadosComplementares, ConstantesForm::$STRING_HASHTAG, 6, $extraAlterarDadosComplementares);
            echo "</div>";
            ?>
            <div id="divCheckDadosComplementaresInseridos" class="checkDadosInseridos hidden">
                <span class="glyphicon glyphicon-ok text-success"></span>
            </div>
        </div>
        <div id="divBotaoSubmit" class="hidden">
            <?php echo $this->botaoLink(ConstantesCadastro::$TRADUCAO_FINALIZAR, '#', 7, 'onclick="this.form.submit();"'); ?>
        </div>
    </div>

    <!-- Incluir Responsavel -->
    <div id="divIncluirResponsavel" class="hidden">
        <!-- Passo a Passo -->
        <div id="divPassoAPasso" class="hidden">           
            <div class="stepwizard">
                <div class="stepwizard-row">
                    <div class="stepwizard-step">
                        <button type="button" class="btn btn-primary btn-circle" disabled="disabled">1</button>
                        <p>Selecione o Aluno</p>
                    </div>
                    <div class="stepwizard-step">
                        <button id="botaoPasso2" type="button" class="btn btn-default btn-circle" disabled="disabled">2</button>
                        <p>Dados Pessoais</p>
                    </div>
                    <div class="stepwizard-step">
                        <button id="botaoPasso3" type="button" class="btn btn-default btn-circle" disabled="disabled">3</button>
                        <p>Email</p>
                    </div> 
                    <div class="stepwizard-step">
                        <button id="botaoPasso4" type="button" class="btn btn-default btn-circle" disabled="disabled">4</button>
                        <p>Hierarquia</p>
                    </div> 
                </div>
            </div>
            <!-- HelperView Dados -->
            <div id="divDadosSelecionados" class="alert alert-info hidden">
                <div class="quebraDeLinhaDeSpan">
                    <i class="fa fa-user" aria-hidden="true"></i>&nbsp;
                    <span id="spanResponsavelMatricula"></span>
                </div>

                <div class="quebraDeLinhaDeSpan">
                    <i class="fa fa-user" aria-hidden="true"></i>&nbsp;
                    <span id="spanResponsavelNome"></span>
                </div>

                <div class="quebraDeLinhaDeSpan">
                    <i class="fa fa-birthday-cake" aria-hidden="true"></i>&nbsp;
                    <span id="spanResponsavelDataNascimento"></span>
                </div>

                <div id="divSpanResponsavelCPF" class="quebraDeLinhaDeSpan hidden">
                    <i class="fa fa-info-circle" aria-hidden="true"></i>&nbsp;
                    <span id="spanResponsavelCPF"></span>
                </div>

                <div id="divSpanResponsavelEmail" class="quebraDeLinhaDeSpan hidden">
                    <i class="fa fa-envelope-o" aria-hidden="true"></i>&nbsp;
                    <span id="spanResponsavelEmail"></span>
                </div>
            </div>
            <!-- Fim HelperView -->
            <span id="spanMensagens" class="quebraDeLinhaDeSpan mt10 alert text-center hidden"></span>
        </div>

        <!-- Selecionar Aluno -->
        <div id="divSelecionarAluno" class="">
            <div class="section-divider mt40">
                <span>Selecione o Aluno que será utilizado para o cadastro</span>
            </div> 
            <div class="panel-menu">
                <input id="fooFilter" type="text" class="form-control" placeholder="Filtro">
            </div>
            <table class="table footable" data-filter="#fooFilter">
                <thead>
                    <tr>
                        <th class = "hidden-xs">Matricula</th>
                        <th>Name</th>
                        <th class = "hidden-xs">Data Nascimento</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if ($form->getAlunos()) {
                        foreach ($form->getAlunos() as $ga) {
                            $tipoResponsavel = 0;
                            $turmaAluno = $ga->getTurmaAluno();
                            $aluno = $turmaAluno->getPessoa();
                            $aluno->setMatriculaAtual($turmaAluno->getMatricula());
                            if ($aluno->getSexo() === 'M') {
                                $classeAluno = 'alunoM';
                                $tipoResponsavel = 1;
                            }
                            if ($aluno->getSexo() === 'F') {
                                $classeAluno = 'alunoF';
                                $tipoResponsavel = 2;
                            }

                            $valorRadio = $aluno->getMatriculaAtual() . '#' .
                                    $aluno->getNome() . '#' .
                                    $aluno->getDataNascimentoFormatada() . '#' .
                                    $tipoResponsavel;
                            echo '<tr class="' . $classeAluno . '">';
                            echo '<td class="hidden-xs">' . $aluno->getMatriculaAtual() . '</td>';
                            echo '<td><span class="hidden-xs">' . $aluno->getNome() . '</span><span class="visible-xs">' . $aluno->getNomePrimeiroPrimeiraSiglaUltimo() . '</span></td>';
                            echo '<td class="hidden-xs">' . $aluno->getDataNascimentoFormatada() . '</td>';
                            echo '<td>';
                            echo '<input type="radio" name="radioAlunoSelecionado" value="' . $valorRadio . '" onclick="mostrarBotaoDeSelecionarAluno();"  />';
                            echo '</td>';
                            echo '</tr>';
                        }
                    } else {
                        echo '<tr><td>Sem alunos cadastrados!</td></tr>';
                    }
                    ?>           
                </tbody>
            </table>
            <div class="mt10">
                <?php
                echo '<div id="divBotaoDeSelecionarAluno" class="hidden">';
                $labelBotaoContinuar = Constantes::$TRADUCAO_CONTINUAR;
                $extraBotaoContinuar = $this->funcaoOnClick('selecionarAluno()');
                echo $this->botaoLink($labelBotaoContinuar, ConstantesForm::$STRING_HASHTAG, 7, $extraBotaoContinuar);
                echo '</div>';

                /* Botao Voltar Confirmação */
                $labelVoltar = Constantes::$TRADUCAO_VOLTAR;
                echo $this->botaoLink($labelVoltar, ConstantesForm::$STRING_HASHTAG, 8, $this->FuncaoOnClick('botaoVoltarSelecionarAluno()'));
                ?>
            </div>
        </div>

        <!-- Div Dados Pessoais -->
        <div id="divCPFDataNascimento" class="hidden">            
            <div class="section-divider mt40">
                <span>Informe Data de Nascimento e CPF</span>
            </div>
            <!-- Buscar CPF -->
            <?php
            echo '<div class="row">';
            echo '<div class="col-xs-4">';
            echo $this->formSelect($form->get('Dia'));
            echo '</div>';
            echo '<div class="col-xs-4">';
            echo $this->formSelect($form->get('Mes'));
            echo '</div>';
            echo '<div class="col-xs-4">';
            echo $this->formSelect($form->get('Ano'));
            echo '</div>';
            echo '</div>';
            echo $this->inputAddon($form, ConstantesForm::$FORM_CPF, 1, ConstantesForm::$FORM_FUNCAO_BUSCAR_CPF);
            ?>
            <!-- FIM Buscar CPF --> 
            <div id="divBotoesBuscaCPF" class="mt10">
                <?php
                echo '<div id="botaoCPFLiberado" class="quebraDeLinhaDeSpan hidden">';
                $extraBotaoContinuar = $this->funcaoOnClick('mostrarDivEmail()');
                echo $this->botaoLink($labelBotaoContinuar, ConstantesForm::$STRING_HASHTAG, 7, $extraBotaoContinuar);
                echo '</div>';
                ?>      
                <!-- Botao Voltar Selecionar Aluno -->
                <?php echo $this->botaoLink($labelVoltar, ConstantesForm::$STRING_HASHTAG, 8, $this->funcaoOnClick('botaoVoltarDataNascimentoCPF()')); ?>
            </div>
        </div>

        <!-- Div Email -->
        <div id="divEmail" class="hidden">
            <!-- Email -->
            <?php echo $this->formInput($form->get(ConstantesForm::$FORM_EMAIL)); ?>
            <!-- FIM Email --> 
            <!-- Repetir Email -->
            <?php echo $this->inputAddon($form, ConstantesForm::$FORM_REPETIR_EMAIL, 1, ConstantesForm::$FORM_FUNCAO_BUSCAR_EMAIL); ?>
            <!-- FIM Repetir Email -->
            <div class="mt10">
                <?php
                echo '<div id="botaoEmailLiberado" class="quebraDeLinhaDeSpan hidden">';
                $extraBotaoContinuar = $this->funcaoOnClick('mostrarDivHierarquia()');
                echo $this->botaoLink($labelBotaoContinuar, ConstantesForm::$STRING_HASHTAG, 7, $extraBotaoContinuar);
                echo '</div>';

                /* Botao Voltar Data de Nascimento e CPF */
                echo $this->botaoLink($labelVoltar, ConstantesForm::$STRING_HASHTAG, 8, $this->funcaoOnClick('botaoVoltarEmail()'));
                ?>
            </div>
        </div>

        <!-- Div Hierarquia -->
        <div id="divHierarquia" class="hidden">
            <!-- Selecionar Hierarquia -->
            <?php echo $this->formSelect($form->get(ConstantesForm::$FORM_HIERARQUIA)); ?>
            <!-- Fim Selecionar Hierarquia -->
            <div class="mt10">
                <?php
                echo '<div id="botaoHierarquiaSelecionada" class="quebraDeLinhaDeSpan hidden">';

                echo '<div id="botaoInserirResponsavel" class="">';
                $labelInserirResponsavel = ConstantesCadastro::$TRADUCAO_INSERIR;
                $extraInserirResponsavel = ' id="botaoInserirResponsavel#numero" onclick="
                insereResponsavelNaTelaDeConfimacao(#numero, 0); 
                    $(\'#divConfirmacao\').removeClass(\'hidden\');            
                    $(\'#divResponsavel\').addClass(\'hidden\');
                "';
                $extraResponsavel0 = str_replace('#numero', 0, $extraInserirResponsavel);
                echo $this->botaoLink($labelInserirResponsavel, ConstantesForm::$STRING_HASHTAG, 7, $extraResponsavel0);

                $extraResponsavel1 = str_replace('#numero', 1, $extraInserirResponsavel);
                echo $this->botaoLink($labelInserirResponsavel, ConstantesForm::$STRING_HASHTAG, 7, $extraResponsavel1);

                $extraResponsavel2 = str_replace('#numero', 2, $extraInserirResponsavel);
                echo $this->botaoLink($labelInserirResponsavel, ConstantesForm::$STRING_HASHTAG, 7, $extraResponsavel2);
                echo '</div>';

                echo '</div>';

                /* Botao Voltar Email */
                echo $this->botaoLink($labelVoltar, ConstantesForm::$STRING_HASHTAG, 8, $this->funcaoOnClick('botaoVoltarHierarquia()'));
                ?>
            </div>
        </div>          
    </div>

    <!--Dados Complementares -->
    <div id = "divDadosComplementares" class="hidden">
        <!-- HelperView dados complementares -->

        <!-- Selecionar Numeracao -->
        <label class="field-label"><?php $this->translate(''); ?>Selecione a Numeracao da Sub Equipe</label>
        <?php echo $this->formSelect($form->get(ConstantesForm::$FORM_NUMERACAO)); ?>
        <!-- Fim Selecionar Numeracao -->

        <!-- Fim HelperView dados complementares -->
        <div class="mt10">
            <?php
            echo "<div id='divInserirAlterarDadosComplementares' class='hidden'>";
            echo "<div id='divBotaoInserirSelectDadosComplementares'>";
            $labelInserirDadosComplementares = ConstantesCadastro::$TRADUCAO_INSERIR;
            $extraInserirDadosComplementares = 'onclick="
            insereNumeracaoNaTelaDeConfimacao(0);
            $(\'#divDadosComplementares\').addClass(\'hidden\');
            $(\'#divConfirmacao\').removeClass(\'hidden\');
        "';
            echo $this->botaoLink($labelInserirDadosComplementares, ConstantesForm::$STRING_HASHTAG, 7, $extraInserirDadosComplementares);
            echo "</div>";

            echo "<div id='divBotaoAlterarSelectDadosComplementares' class='hidden'>";
            $labelInserirDadosComplementares = ConstantesCadastro::$TRADUCAO_ALTERAR;
            $extraInserirDadosComplementares = 'onclick="
            insereNumeracaoNaTelaDeConfimacao(1);
            $(\'#divDadosComplementares\').addClass(\'hidden\');
            $(\'#divConfirmacao\').removeClass(\'hidden\');
        "';
            echo $this->botaoLink($labelInserirDadosComplementares, ConstantesForm::$STRING_HASHTAG, 7, $extraInserirDadosComplementares);
            echo "</div>";
            echo "</div>";
            $extraVoltarDadosComplementares = 'onclick="
            $(\'#divConfirmacao\').removeClass(\'hidden\');
            $(\'#divDadosComplementares\').addClass(\'hidden\');
            "';
            echo $this->botaoLink($labelVoltar, ConstantesForm::$STRING_HASHTAG, 8, $extraVoltarDadosComplementares);
            ?>
        </div>
    </div>

</div>
<?php
echo $this->formHidden($form->get(Constantes::$INPUT_CSRF));
echo $this->formHidden($form->get(ConstantesForm::$FORM_ID_ALUNO_SELECIONADO . '0'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_ID_ALUNO_SELECIONADO . '1'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_ID_ALUNO_SELECIONADO . '2'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_NOME . '0'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_NOME . '1'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_NOME . '2'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_EMAIL . '0'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_EMAIL . '1'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_EMAIL . '2'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_CPF . '0'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_CPF . '1'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_CPF . '2'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_HIERARQUIA . '0'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_HIERARQUIA . '1'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_HIERARQUIA . '2'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_DATA_NASCIMENTO . '0'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_DATA_NASCIMENTO . '1'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_DATA_NASCIMENTO . '2'));
echo $this->formHidden($form->get(ConstantesForm::$FORM_NOME_ALUNO));

echo $this->templateFormularioRodape();
echo $this->form()->closeTag();
