<script type="text/javascript">
    window.onload = initPage;
    function initPage() {
        // Init jQuery Masked inputs
        $('.date').mask('99/99/9999');
    }

    /* Dados */
    var estadoCivil = 0;
    var responsavel0 = 0;
    var iconeTime = '<i class="fa fa-times" aria-hidden="true"></i>';
    var iconeCheck = '<i class="fa fa-check" aria-hidden="true"></i>';
    var hidden = 'hidden';
    var textDanger = 'text-danger';
    var textSuccess = 'text-success';
    var stringNBSP = '&nbsp;';
    var alertDanger = 'alert alert-danger text-center';

    function validarEstadoCivil() {
        var valorSelecionado = $('input[name=inputEstadoCivil]:checked').val();
        if (valorSelecionado !== undefined) {
            estadoCivil = parseInt(valorSelecionado);
            switch (estadoCivil) {
                case 1:
                    $('#blocoHomem').addClass('hidden');
                    $('#blocoMulher').addClass('hidden');
                    break;
                case 2:
                    $('#blocoResponsavel').addClass('hidden');
                    break;
                default:
                    break;
            }
            $('#divEstadoCivil').addClass('hidden');
            $('#divConfirmacao').removeClass('hidden');
        } else {
            alert('Selecione uma das opções!');
        }
    }

    function selecionarAluno(matricula, nome, dataNascimento, tipo) {
        var spanResponsavelMatricula, spanResponsavelNome, spanResponsavelDataNascimento;
        spanResponsavelMatricula = $('#spanResponsavelMatricula');
        spanResponsavelNome = $('#spanResponsavelNome');
        spanResponsavelDataNascimento = $('#spanResponsavelDataNascimento');
        spanResponsavelMatricula.html(matricula);
        spanResponsavelNome.html(nome);
        spanResponsavelDataNascimento.html(dataNascimento);
        $('#divResponsavel').removeClass('hidden');
        $('#divSelecionarAluno').addClass('hidden');
        var inputIdAlunoSelecionado;
        switch (tipo) {
            case 1:
                inputIdAlunoSelecionado = $('#idAlunoSelecionado1');
                break;
            case 2:
                inputIdAlunoSelecionado = $('#idAlunoSelecionado2');
                break;
            default:
                break;
        }
        $('#idAlunoSelecionado0').val(matricula);
        inputIdAlunoSelecionado.val(matricula);
        /* Limpar campos */
        $('#cpf').val('');
        $('#email').val('');
        $('#repetirEmail').val('');
        $('#hierarquia').val(0);
        $('#spanBuscaCPF').html('');
        $('#spanBuscaNome').html('');
        $('#spanBuscaDataNascimento').html('');
        $('#divResultadoBuscaCPF').addClass(hidden);
        $('#divDadosExtras').addClass(hidden);
        $('#spanEmailJaUtilizado').html('');
        $('#spanEmailJaUtilizado').removeClass('alert');
        $('#spanEmailNaoIgual').html('');
        $('#spanEmailNaoIgual').removeClass('alert');
        $('#divRepetirEmailEHierarquia').addClass(hidden);
    }

    function isNumber(n) {
        return !isNaN(parseFloat(n)) && isFinite(n);
    }

    function buscarCPF() {
        var cpf = $("#cpf").val();
        var dataNascimento = $("#dataNascimento").val();
        var loader = $('#loadercpf');
        loader.removeClass(hidden);
        var divResultadoBuscaCPF = $('#divResultadoBuscaCPF');
        var divDadosExtras = $('#divDadosExtras');
        var spanBuscaCPF = $('#spanBuscaCPF');
        var spanBuscaNome = $('#spanBuscaNome');
        var spanBuscaDataNascimento = $('#spanBuscaDataNascimento');
        var spanMensagemDeErroCPF = $('#spanMensagemDeErroCPF');
        divResultadoBuscaCPF.addClass(hidden);
        divDadosExtras.addClass(hidden);
        spanBuscaCPF.html('');
        spanBuscaNome.html('');
        spanBuscaDataNascimento.html('');
        spanMensagemDeErroCPF.addClass(hidden);

        var temErro = false;
        if (cpf.length === 0 && dataNascimento.length === 0) {
            spanMensagemDeErroCPF
                    .text('Preenchar a Data de Nascimento e o CPF!');
            temErro = true;
        } else {
            if (cpf.length === 0 || dataNascimento.length === 0) {
                if (cpf.length === 0) {
                    spanMensagemDeErroCPF
                            .text('Preenchar o CPF!');
                    temErro = true;
                }
                if (dataNascimento.length === 0) {
                    spanMensagemDeErroCPF
                            .text('Preenchar a data de nascimento!');
                    temErro = true;
                }
            } else {
                if (dataNascimento.length !== 10) {
                    spanMensagemDeErroCPF
                            .text('Data de nascimento é invalida!');
                    temErro = true;

                } else {
                    if (!isNumber(cpf) || cpf.length !== 11) {
                        spanMensagemDeErroCPF
                                .text('CPF é invalido!');
                        temErro = true;
                    }
                }
            }

        }

        if (!temErro) {
            $.post(
                    "/cadastroBuscarCPF",
                    {
                        cpf: cpf,
                        dataNascimento: dataNascimento
                    },
            function (data) {
                if (parseInt(data.resposta) === 1) {
                    $('#spanBuscaMensagem').html('CPF liberado');
                    divResultadoBuscaCPF.removeClass(hidden);
                    spanBuscaCPF.html(data.cpf);
                    spanBuscaNome.html(data.nome);
                    spanBuscaDataNascimento.html(data.dataNascimento);
                    var nomeDoAlunoSelecionado = $('#spanResponsavelNome').text();
                    var splitNomeDoAluno = nomeDoAlunoSelecionado.split(" ");
                    var splitNomeEncontradoNaBusca = data.nome.split(" ");

                    if (splitNomeDoAluno[0] !== splitNomeEncontradoNaBusca[0]) {
                        spanMensagemDeErroCPF
                                .text('Nome do CPF não confere com o do aluno')
                                .removeClass(hidden);
                    } else {
                        if (splitNomeDoAluno[0] === splitNomeEncontradoNaBusca[0]) {
                            spanMensagemDeErroCPF.addClass(hidden);
                            $('#divEmailResponsavel').removeClass(hidden);
                        }
                    }

                }
                if (parseInt(data.resposta) === 2) {
                    /* Não encontrou no PROCOB */
                    spanMensagemDeErroCPF
                            .removeClass(hidden)
                            .text(data.mensagem);
                }
                divDadosExtras.removeClass(hidden);
                loader.addClass(hidden);
            }
            , 'json');
        } else {
            spanMensagemDeErroCPF
                    .removeClass(hidden);
            loader.addClass(hidden);
        }
    }

    function buscarEmail(email) {
        var loader = $('#loaderemail');
        var spanEmail = $('#spanemail');
        var divRepetirEmailEHierarquia = $('#divRepetirEmailEHierarquia');
        loader.removeClass(hidden);
        divRepetirEmailEHierarquia.addClass(hidden);
        if (email.length === 0) {
            loader.addClass(hidden);
            return false;
        }
        if (!validaEmail(email)) {
            loader.addClass(hidden);
            spanEmail.html(iconeTime);
            spanEmail.removeClass(textSuccess);
            spanEmail.addClass(textDanger);
            return false;
        } else {
            $.post(
                    "/cadastroBuscarEmail",
                    {email: email},
            function (data) {
                var spanEmailJaUtilizado = $('#spanEmailJaUtilizado');
                // liberado
                if (!data.resposta) {
                    spanEmailJaUtilizado.addClass(hidden);
                    divRepetirEmailEHierarquia.removeClass(hidden);
                    spanEmail.addClass(textSuccess);
                    spanEmail.removeClass(textDanger);
                    spanEmail.html(iconeCheck);
                }
                // não liberado
                if (data.resposta) {
                    spanEmailJaUtilizado.html('Email já utilizado por outra pessoa!');
                    spanEmailJaUtilizado.addClass(alertDanger);
                    divRepetirEmailEHierarquia.addClass(hidden);
                    spanEmail.addClass(textDanger);
                    spanEmail.removeClass(textSuccess);
                    spanEmail.html(iconeTime);
                }
                loader.addClass(hidden);
            }, 'json');
        }

    }

    function elementoBotaoInseririResponsavel() {
        return $('#botaoInserirResponsavel');
    }

    function validaEmail(email) {

        var er = RegExp(/^[A-Za-z0-9_\-\.]+@[A-Za-z0-9_\-\.]{2,}\.[A-Za-z0-9]{2,}(\.[A-Za-z0-9])?/);
        if (er.test(email) == false) {
            return false;
            var elemento = elementoBotaoInseririResponsavel();
            elemento.addClass(hidden);
        }
        return true;
    }

    function verificarEmailIgual(emailRepetido) {
        var elemento = elementoBotaoInseririResponsavel();
        var valorEmail = $('#email').val();
        var spanRepetirEmail = $('#spanrepetirEmail');
        var spanEmailNaoIgual = $('#spanEmailNaoIgual');
        if (emailRepetido != valorEmail) {
            spanRepetirEmail.html(iconeTime);
            spanRepetirEmail.removeClass(textSuccess);
            spanRepetirEmail.addClass(textDanger);
            elemento.addClass(hidden);
            spanEmailNaoIgual.removeClass(hidden);
            spanEmailNaoIgual.html('Emails não coferem!');
            spanEmailNaoIgual.addClass(alertDanger);
        } else {
            spanRepetirEmail.html(iconeCheck);
            spanRepetirEmail.addClass(textSuccess);
            spanRepetirEmail.removeClass(textDanger);
            spanEmailNaoIgual.addClass(hidden);
        }
    }

    function mostrarBotaoDeInserirResponsavel(valorDoSelectHierarquia) {
        var elemento = elementoBotaoInseririResponsavel();
        valorDoSelectHierarquia = parseInt(valorDoSelectHierarquia);
        if (valorDoSelectHierarquia !== 0) {
            if ($('#spanrepetirEmail').hasClass(textSuccess)) {
                elemento.removeClass(hidden);
            }
        }
        if (valorDoSelectHierarquia === 0) {
            elemento.addClass(hidden);
        }
    }

    function mostrarBotaoDeProsseguirDoEstadoCivil() {
        $('#divBotaoDeProsseguirDoEstadoCivil').removeClass(hidden);
    }

    function mostrarBotaoDeInserirDadosComplementares(valorDoSelectNumeracao) {
        valorDoSelectNumeracao = parseInt(valorDoSelectNumeracao);
        var divInserirAlterarDadosComplementares = $('#divInserirAlterarDadosComplementares');
        if (valorDoSelectNumeracao !== 0) {
            divInserirAlterarDadosComplementares.removeClass(hidden);
        }
        if (valorDoSelectNumeracao === 0) {
            divInserirAlterarDadosComplementares.addClass(hidden);
        }
    }

    function insereResponsavelNaTelaDeConfimacao(tipoResponsavel, mudarBarraDeProgresso) {
        var spanMatricula = '';
        var spanNome = '';
        var spanNomexs = '';
        var spanEmail = '';
        var spanEmailxs = '';
        var spanHierarquia = '';
        var spanCPF = '';
        var iconeResponavelMatricula = '<i class="fa fa-folder" aria-hidden="true"></i>' + stringNBSP;
        var iconeResponavelNomeInicial = '<i class="fa fa-user" aria-hidden="true"></i>' + stringNBSP + '<strong>';
        var iconeResponavelNomeFinal = '</strong>';
        var iconeResponavelCPF = '<i class="fa fa-info-circle" aria-hidden="true"></i>' + stringNBSP;
        var iconeResponavelEmail = '<i class="fa fa-envelope" aria-hidden="true"></i>' + stringNBSP;
        var iconeResponavelHierarquia = '<i class="fa fa-sitemap" aria-hidden="true"></i>' + stringNBSP;
        var inputHiddenEmail;
        var inputHiddenHierarquia;
        var valorBarraDeProgresso;
        var divCheckDadosResponsavelInseridos;
        var dibBotaoInserirResponsavel;
        var dibBotaoAlterarResponsavel;
        var inputHiddenNome;
        var inputHiddenCPF;
        var inputHiddenDataNascimento;

        switch (tipoResponsavel) {
            case 0:
                spanMatricula = $('#spanMatricula0');
                spanNome = $('#spanNome0');
                spanNomexs = $('#spanNome0xs');
                spanEmail = $('#spanEmail0');
                spanEmailxs = $('#spanEmail0xs');
                spanHierarquia = $('#spanHierarquia0');
                spanCPF = $('#spanCPF0');
                inputHiddenEmail = $('#email0');
                inputHiddenHierarquia = $('#hierarquia0');
                $('#spanInsiraOsDadosDoResponsavel').html('Dados do Respons&aacute;vel');
                valorBarraDeProgresso = 50;
                divCheckDadosResponsavelInseridos = $('#divCheckDadosResponsavelInseridos');
                dibBotaoInserirResponsavel = $('#dibBotaoInserirResponsavel');
                dibBotaoAlterarResponsavel = $('#dibBotaoAlterarResponsavel');
                inputHiddenNome = $('#nome0');
                inputHiddenCPF = $('#cpf0');
                inputHiddenDataNascimento = $('#dataNascimento0');
                break;
            case 1:
                spanMatricula = $('#spanMatricula1');
                spanNome = $('#spanNome1');
                spanNomexs = $('#spanNome1xs');
                spanEmail = $('#spanEmail1');
                spanEmailxs = $('#spanEmail1xs');
                spanHierarquia = $('#spanHierarquia1');
                spanCPF = $('#spanCPF1');
                inputHiddenEmail = $('#email1');
                inputHiddenHierarquia = $('#hierarquia1');
                $('#spanInsiraOsDadosDoResponsavel1').html('Dados do Homem');
                valorBarraDeProgresso = 25;
                divCheckDadosResponsavelInseridos = $('#divCheckDadosResponsavelInseridos1');
                dibBotaoInserirResponsavel = $('#dibBotaoInserirResponsavel1');
                dibBotaoAlterarResponsavel = $('#dibBotaoAlterarResponsavel1');
                inputHiddenNome = $('#nome1');
                inputHiddenCPF = $('#cpf1');
                inputHiddenDataNascimento = $('#dataNascimento1');
                break;
            case 2:
                spanMatricula = $('#spanMatricula2');
                spanNome = $('#spanNome2');
                spanNomexs = $('#spanNome2xs');
                spanEmail = $('#spanEmail2');
                spanEmailxs = $('#spanEmail2xs');
                spanHierarquia = $('#spanHierarquia2');
                spanCPF = $('#spanCPF2');
                inputHiddenEmail = $('#email2');
                inputHiddenHierarquia = $('#hierarquia2');
                $('#spanInsiraOsDadosDoResponsavel2').html('Dados da Mulher');
                valorBarraDeProgresso = 25;
                divCheckDadosResponsavelInseridos = $('#divCheckDadosResponsavelInseridos2');
                dibBotaoInserirResponsavel = $('#dibBotaoInserirResponsavel2');
                dibBotaoAlterarResponsavel = $('#dibBotaoAlterarResponsavel2');
                inputHiddenNome = $('#nome2');
                inputHiddenCPF = $('#cpf2');
                inputHiddenDataNascimento = $('#dataNascimento2');
                break;
            default:
                return false;
        }
        inputHiddenNome.val($('#spanBuscaNome').html());
        inputHiddenCPF.val($('#spanBuscaCPF').html());
        inputHiddenDataNascimento.val($('#spanBuscaDataNascimento').html());
        spanMatricula.html(iconeResponavelMatricula + $('#spanResponsavelMatricula').html());
        spanCPF.html(iconeResponavelCPF + $('#spanBuscaCPF').html());
        spanNomexs.html(iconeResponavelNomeInicial + ajustaStringTelaPequena($('#spanBuscaNome').html()) + iconeResponavelNomeFinal);
        spanEmailxs.html(iconeResponavelEmail + ajustaStringTelaPequena($('#email').val()));
        spanNome.html(iconeResponavelNomeInicial + $('#spanBuscaNome').html() + iconeResponavelNomeFinal);
        spanEmail.html(iconeResponavelEmail + $('#email').val());
        spanHierarquia.html(iconeResponavelHierarquia + $('#hierarquia option:selected').text());
        divCheckDadosResponsavelInseridos.removeClass(hidden);
        dibBotaoInserirResponsavel.addClass(hidden);
        dibBotaoAlterarResponsavel.removeClass(hidden);
        inputHiddenEmail.val($('#email').val());
        inputHiddenHierarquia.val($('#hierarquia option:selected').val());
        $('#email').val('');
        $('#hierarquia').val(0);
        $('#dataNascimento').val('');
        if (mudarBarraDeProgresso === 0) {
            atualizarBarraDeProgresso(valorBarraDeProgresso);
        }
    }

    function limparDadosPessoaSelecionada(tipoResponsavel) {
        var spanMatricula = '';
        var spanNome = '';
        var spanNomexs = '';
        var spanEmail = '';
        var spanEmailxs = '';
        var spanHierarquia = '';
        var spanCPF = '';
        switch (tipoResponsavel) {
            case 0:
                spanMatricula = $('#spanMatricula0');
                spanNome = $('#spanNome0');
                spanNomexs = $('#spanNome0xs');
                spanEmail = $('#spanEmail0');
                spanEmailxs = $('#spanEmail0xs');
                spanHierarquia = $('#spanHierarquia0');
                spanCPF = $('#spanCPF0');
                break;
            default:
                return false;
        }
        spanMatricula.html('');
        spanCPF.html('');
        spanNomexs.html('');
        spanEmailxs.html('');
        spanNome.html('');
        spanEmail.html('');
        spanHierarquia.html('');

        $('#spanInsiraOsDadosDoResponsavel').html('Insira os dados do Responsavel');
        $('#spanInsiraOsDadosDoResponsavel1').html('Insira os dados do Homem');
        $('#spanInsiraOsDadosDoResponsavel2').html('Insira os dados do Mulher');
        $('#cpf').val('');
        $('#email').val('');
        $('#repetirEmail').val('');
        $('#hierarquia').val(0);
        $('#spanBuscaCPF').html('');
        $('#spanBuscaNome').html('');
        $('#spanBuscaDataNascimento').html('');
        $('#divCheckDadosResponsavelInseridos').addClass(hidden);
        $('#dibBotaoInserirResponsavel').removeClass(hidden);
        $('#dibBotaoAlterarResponsavel').addClass(hidden);
        $('#divResultadoBuscaCPF').addClass(hidden);
        $('#divDadosExtras').addClass(hidden);
        $('#divEmailResponsavel').addClass(hidden);
        $('#divRepetirEmailEHierarquia').addClass(hidden);
        $('#botaoInserirResponsavel').addClass(hidden);
        atualizarBarraDeProgresso(-50);
    }

    function insereNumeracaoNaTelaDeConfimacao(mudarBarraDeProgresso) {
        var spanDadosComplementares = $('#spanDadosComplementares');
        var iconeNumeracao = '<i class="fa fa-info-circle" aria-hidden="true"></i>' + stringNBSP;
        spanDadosComplementares.html(iconeNumeracao + stringNBSP + 'Numeração:' + stringNBSP + $('#numeracao option:selected').text());
        $('#spanInsiraOsDadosComplementares').html('Dados Complementares');
        $('#divCheckDadosComplementaresInseridos').removeClass(hidden);
        $('#divBotaoInserirDadosComplementares').addClass(hidden);
        $('#divBotaoAlterarDadosComplementares').removeClass(hidden);
        if (mudarBarraDeProgresso === 0) {
            atualizarBarraDeProgresso(50);
        }
    }

    function pegaValorBarraDeProgresso() {
        return $('#divProgressBar').attr("aria-valuenow");
    }

    function atualizarBarraDeProgresso(valorParaSomar) {
        valorParaSomar = parseInt(valorParaSomar);
        var valorAtualDaBarraDeProgresso = pegaValorBarraDeProgresso();
        var valorAtualizadoDaBarraDeProgresso = parseInt(valorAtualDaBarraDeProgresso) + valorParaSomar;
        var stringPercentual = '%';
        $('#divProgressBar')
                .attr("aria-valuenow", valorAtualizadoDaBarraDeProgresso)
                .html(valorAtualizadoDaBarraDeProgresso + stringPercentual)
                .css('width', valorAtualizadoDaBarraDeProgresso + stringPercentual);

        var divBotaoSubmit = $('#divBotaoSubmit');
        if (valorAtualizadoDaBarraDeProgresso == 100) {
            divBotaoSubmit.removeClass(hidden);
        } else {
            divBotaoSubmit.addClass(hidden);
        }
    }

    function ajustaStringTelaPequena(string) {
        var stringAjustada = '';
        stringAjustada = string.substr(0, 20) + '...';
        return stringAjustada;
    }

    function abrirTelaDeAlunos(tipo) {
        $('#botaoInserirResponsavel0').addClass(hidden);
        $('#botaoInserirResponsavel1').addClass(hidden);
        $('#botaoInserirResponsavel2').addClass(hidden);
        $('.alunoM').addClass(hidden);
        $('.alunoF').addClass(hidden);
        switch (tipo) {
            case 0:
                $('.alunoM').removeClass(hidden);
                $('.alunoF').removeClass(hidden);
                $('#botaoInserirResponsavel0').removeClass(hidden);
                break;
            case 1:
                $('.alunoM').removeClass(hidden);
                $('#botaoInserirResponsavel1').removeClass(hidden);
                break;
            case 2:
                $('.alunoF').removeClass(hidden);
                $('#botaoInserirResponsavel2').removeClass(hidden);
                break;
        }
        $('#divConfirmacao').addClass(hidden);
        $('#divSelecionarAluno').removeClass(hidden);
    }
</script>