<?php

use Cadastro\Controller\Helper\ConstantesCadastro;
use Login\Controller\Helper\Constantes;
use Zend\Session\Container;

$sessao = new Container(Constantes::$NOME_APLICACAO);

$titulo = '';
$texto = '';
$mostrar = false;

if($sessao->tipoMensagem) {
    $mostrar = true;
    switch ($sessao->tipoMensagem) {
        case 1:
            $titulo = ConstantesCadastro::$TRADUCAO_CELULA_ . ConstantesCadastro::$TRADUCAO_CADASTRADO;
            $texto = ConstantesCadastro::$TRADUCAO_CELULA_TEXTO . $sessao->textoMensagem;
            break;
        case 2:
            $titulo = ConstantesCadastro::$TRADUCAO_CELULA_ . ConstantesCadastro::$TRADUCAO_ALTERADO;
            $texto = ConstantesCadastro::$TRADUCAO_CELULA_TEXTO . $sessao->textoMensagem;
            break;
        case 3:
            $titulo = ConstantesCadastro::$TRADUCAO_CELULA_ . ConstantesCadastro::$TRADUCAO_EXCLUIDO;
            $texto = ConstantesCadastro::$TRADUCAO_CELULA_TEXTO . $sessao->textoMensagem;
            break;
        case 4:
            $titulo = ConstantesCadastro::$TRADUCAO_CULTO_ . ConstantesCadastro::$TRADUCAO_CADASTRADO;
            $texto = ConstantesCadastro::$TRADUCAO_CULTO_TEXTO . $sessao->textoMensagem;
            break;
        case 5:
            $titulo = ConstantesCadastro::$TRADUCAO_CULTO_ . ConstantesCadastro::$TRADUCAO_ALTERADO;
            $texto = ConstantesCadastro::$TRADUCAO_CULTO_TEXTO . $sessao->textoMensagem;
            break;
        case 6:
            $titulo = ConstantesCadastro::$TRADUCAO_CULTO_ . ConstantesCadastro::$TRADUCAO_EXCLUIDO;
            $texto = ConstantesCadastro::$TRADUCAO_CULTO_TEXTO . $sessao->textoMensagem;
            break;
    }
    $sessao->tipoMensagem = '';
    $sessao->textoMensagem = '';
}
?>
<script type="text/javascript">
    var stack_bar_bottom = {
        "dir1": "up",
        "dir2": "right",
        "spacing1": 0,
        "spacing2": 0
    };

    var noteStyle = 'success';
    var noteShadow = true;
    var noteOpacity = 1;
    var addClass = 'stack_bar_bottom';
    var width = '70%';
    var titulo = '<?php echo $titulo; ?>';
    var texto = '<?php echo $texto; ?>';

<?php
if ($mostrar) {
    echo 'window.onload = initPage;';
}
?>

    function initPage() {

        new PNotify({
            title: titulo,
            text: texto,
            shadow: noteShadow,
            opacity: noteOpacity,
            addclass: addClass,
            type: noteStyle,
            stack: stack_bar_bottom,
            width: width,
            delay: 10000
        });

    }
</script>