<?php

use Application\Controller\Helper\Constantes;

$formulario = $this->formulario;
$formulario->prepare();
$formulario->setAttribute(Constantes::$ACTION, $this->url(Constantes::$ROUTE_LOGIN, array(Constantes::$ACTION => Constantes::$ACTION_SUPORTE)));
echo $this->form()->openTag($formulario);
?>
<div class="panel mt30 center-block" style="width: 300px;">
    <div class="panel-body bg-light pl10 pr10">
        <?php
        echo $this->inputFormularioSimples(Constantes::$TRADUCAO_USUARIO, $formulario->get(Constantes::$INPUT_USUARIO));
        ?>
    </div>
    <div class="panel-footer">
        <?php
        echo $this->formHidden($formulario->get(Constantes::$INPUT_CSRF));
        $funcaoVerificarLogin = $this->funcaoOnClick('this.form.submit()');
        echo $this->botaoSimples(Constantes::$TRADUCAO_ENTRAR, $funcaoVerificarLogin . ' id="botaoLogar"');
        ?>   
    </div>
</div>
<?php
echo $this->form()->closeTag();
