<?php

use Application\Controller\Helper\Constantes;
use Zend\View\Helper\AbstractHelper;
use Application\Model\Entity\MetasOrdenacaoCriterio;

/**
 * Nome: consultar-ordenacao.phtml
 * @author Ivan Tavares <ivanlsjt@gmail.com>
 * Descricao: Página para consultar ordenação de pessoas.
 */
$cpf = '';
if($this->cpf){
    $cpf = $this->cpf;
}
$html = '';
$label = 'Consultar <b class="text-danger">Ordenação</b>';
$html .= $this->templateFormularioTopo($label, 0, 'style="max-width:100%; margin-top:0%;');
// inicio div panel-body
$html .= '<div class="panel-body bg-light pbn">';
$html .= '<span id="spanMensagens" class="quebraDeLinhaDeSpan mt10 alert text-center alert-danger hidden"></span>';
$html .= '<form id="formConsultarOrdenacao" action="/consultarOrdenacao" method="post">';

//inicio row 1
$html .= '<div class="row">';

$html .= '<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">';
$html .= '<div class="form-group">';
$html .= '<input type="number" name="cpf" class="form-control" id="cpf" placeholder="CPF" pattern="\d*" value="'. $cpf .'">';
$html .= '</div>';
$html .= '</div>';


$html .= '<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">';
$html .= '<div class="option-group field text-center mb15">';

for($indiceRadio = 1; $indiceRadio < 3; $indiceRadio++){
    $checked = '';
    if($this->nivelDeDificuldade && $this->nivelDeDificuldade == $indiceRadio){
        $checked = 'checked';
    } 
    if(!$this->nivelDeDificuldade){
        if($indiceRadio == 1){
            $checked = 'checked';
        }
    }
    switch($indiceRadio){
        case 1:             
            $label = 'Jovem';
            break;
        case 2:                                                            
            $label = 'Adulto';
            break;
    }
    $html .= '<label class="option option-primary">';
    $html .= '<input type="radio" name="nivelDeDificuldade" value="'.$indiceRadio.'" '.$checked.'>';
    $html .= '<span class="radio"></span>'.$label.'</label>';
}
$html .= '</div>';
$html .= '</div>';


$html .= '<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">';
$html .= '<button type="button" onclick="validarDados();" class="btn ladda-button btn-primary btn-block mb15" data-style="zoom-in">';
$html .= '<span class="ladda-label">Filtrar</span>';
$html .= '<span class="ladda-spinner"></span></button>';
$html .= '</div>';

// fim row 1
$html .= '</div>';
$html .= '</form>';

if($this->filtrado && $this->ordenacaoMetas && $this->situacaoPessoa == 'ativa'){
    //inicio row 2
    $html .= '<div class="row">';
    $html .= '<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">';
    $html .= '<div class="alert alert-default text-center">'. $this->nome .'</div>';
    $html .= '</div>';
    // fim row 2
    $html .= '</div>';

    // row numeros grandes
    $html .= '<div class="row mb10">';
    $totalDeIndices = 4;
    if(!$this->lideres){
        $this->lideres = 0;
    }
    if(!$this->membresia){
        $this->membresia = 0;
    }
    if(!$this->parceiroDeDeus){
        $this->parceiroDeDeus = 0;
    }
    if(!$this->mediaPessoasFrequentes){
        $this->mediaPessoasFrequentes = 0;
    }
    for($indiceNumeroGrandes = 1; $indiceNumeroGrandes <= $totalDeIndices; $indiceNumeroGrandes++){
        switch($indiceNumeroGrandes){
            case 1: 
                $valor = number_format($this->membresia);
                $label = 'Membresia';
                break;
            case 2:                 
                $valor = $this->lideres;                                
                $label = 'Lider(es)';
                break;
            case 3: 
                $valor = 'R$ ' . number_format($this->parceiroDeDeus, 2);
                $label = 'Parceiro de Deus';
                break;
            case 4: 
                $valor = number_format($this->mediaPessoasFrequentes);
                $label = 'Pessoas em Célula';
                break; 
        }
        $html .= '<div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">';
        $html .= '<div class="panel text-center br-a br-grey">';
        $html .= '<div class="panel-body">';
        $html .= '<h1 class="fs16 mt5 mbn">'. $valor .'</h1>';
        $html .= '<h6 class="text-info">'.$label.'</h6>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
    }    
    //fim  row numeros grandes
    $html .= '</div>';
    
    if($this->quantidadeDeIgrejas){
        //row igrejas
        $html .= '<div class="row mb10">';
        $html .= '<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">';
        $html .= '<div class="panel text-center br-a br-grey">';
        $html .= '<div class="panel-body">';
        $html .= '<h1 class="fs16 mt5 mbn">'.$this->quantidadeDeIgrejas.'</h1>';
        $html .= '<h6 class="text-info">Igrejas</h6>';        
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
        //fim  row igrejas
        $html .= '</div>';
    }
    
    foreach ($this->tiposDeMetasOrdenacao as $ordenacaoTipo) {               
        $pontosOrdenado = 0;                        
        foreach ($this->ordenacaoMetas as $metas) {          
            if($metas->getMetas_ordenacao_tipo_id() === $ordenacaoTipo->getId()){
                $ordenacaoCriterio = $metas->getMetas_ordenacao_criterio_id();               
                $meta = $metas->metaPorDificuldade($this->nivelDeDificuldade);                                    
                switch($ordenacaoCriterio){
                    case MetasOrdenacaoCriterio::lideres:                                                                              
                        if($this->lideres >= $meta){                                   
                            $pontosOrdenado++;
                        }
                        break;
                    case MetasOrdenacaoCriterio::membresia:                                                                                                              
                        if($this->membresia >= $meta){                            
                            $pontosOrdenado++;
                        }
                        break;
                    case MetasOrdenacaoCriterio::pessoasEmCelula:                                                                                         
                        if($this->mediaPessoasFrequentes >= $meta){                            
                            $pontosOrdenado++;
                        }
                        break;                        
                    case MetasOrdenacaoCriterio::parceiroDeDeus:     
                        if(!$this->parceiroDeDeus){
                            $this->parceiroDeDeus = 0;
                        }                                                                                             
                        if($this->parceiroDeDeus >= $meta){                            
                            $pontosOrdenado++;
                        }
                        break;                         
                    case MetasOrdenacaoCriterio::igrejas:    
                        if(!$this->quantidadeDeIgrejas){
                            $this->quantidadeDeIgrejas = 0;
                        }                                                                                 
                        if($this->quantidadeDeIgrejas >= $meta){                            
                            $pontosOrdenado++;
                        }
                        break;                         
                }
            }        
        }
        // row aprovação dos critérios
        $html .= '<div class="row">'; 

        $ordenacaoId = $ordenacaoTipo->getId();
        $html .= '<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">';
        $html .= '<div style="cursor: pointer;" class="alert alert-default text-center"  onclick="mostrarMeta('.$ordenacaoId.');">'. $ordenacaoTipo->getNome() .'  <i class="fa fa-info-circle text-info"></i></div>';
        $html .= '</div>';

        $tipoBispo = 5;
        $pontosParaAprovar = 4;
        if($ordenacaoTipo->getId() == $tipoBispo){
            $pontosParaAprovar = 2;
        } 

        if($pontosOrdenado >= $pontosParaAprovar){
            $html .= '<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 ptn">';
            $html .= '<div class="alert alert-success text-center">APROVADO</div>';
            $html .= '</div>';
        }

        if($pontosOrdenado < $pontosParaAprovar){
            $html .= '<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 ptn">';
            $html .= '<div class="alert alert-danger text-center">REPROVADO</div>';
            $html .= '</div>';
        }
        // fim da row aprovação dos critérios
        $html .= '</div>';
        
         // row para mostrar as metas da ordenação tipo         
         $html .= '<div id="meta'.$ordenacaoId.'" class="row hidden mb20">'; 
         $html .= '<div class="section-divider mt20 mb30" id="spy5"><span style="color: red;">METAS '.$ordenacaoTipo->getNome().'</span></div>';
         foreach($ordenacaoTipo->getGrupoMetasOrdenacao() as $meta){
             if($meta->verificarSeEstaAtivo()){
                $valor = $meta->metaPorDificuldade($this->nivelDeDificuldade); 
                $html .= '<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 ptn">';
                $html .= '<div class="alert alert-dark text-center">'.$meta->getMetasOrdenacaoCriterio()->getNome().': '.$valor.'</div>';
                $html .= '</div>';
             }           
         }
          // fim da row para mostrar as metas da ordenação tipo
        $html .= '</div>';
    }    
}

if($this->filtrado && $this->situacaoPessoa == 'inativada'){
    //inicio row pessoa inativada
    $html .= '<div class="row">';
    $html .= '<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">';
    $html .= '<div class="alert alert-danger text-center">'. $this->nome .' - PESSOA INATIVADA</div>';
    $html .= '</div>';
    // fim row pessoa inativada
    $html .= '</div>';
}  

if($this->filtrado && $this->situacaoPessoa == 'naoEncontrada'){
    //inicio row pessoa inativada
    $html .= '<div class="row">';
    $html .= '<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">';
    $html .= '<div class="alert alert-danger text-center">CPF NÃO ENCONTRADO</div>';
    $html .= '</div>';
    // fim row pessoa inativada
    $html .= '</div>';
}

if($this->filtrado && !$this->ordenacaoMetas){
    //inicio row pessoa inativada
    $html .= '<div class="row">';
    $html .= '<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">';
    $html .= '<div class="alert alert-danger text-center">SEM METAS CADASTRADAS</div>';
    $html .= '</div>';
    // fim row pessoa inativada
    $html .= '</div>';
}



//fim div panel-body
$html .= '</div>';

$html .= $this->templateFormularioRodape();
echo $html;   
        
?>

<script>
    function isNumber(n) {
        return !isNaN(parseFloat(n)) && isFinite(n);
    }
    function validarDados(){
        var temErro = false;
        var hidden = 'hidden';
        var spanMensagens = $('#spanMensagens');
        var inputCPF = $("#cpf");        
        var formConsultarOrdenacao = $("#formConsultarOrdenacao");
        var cpf = inputCPF.val();
        if (cpf.length === 0 || !isNumber(cpf) || cpf.length !== 11) {
            spanMensagens.removeClass(hidden);
            spanMensagens.text('<?php echo $this->translate(Constantes::$TRADUCAO_CPF_INVALIDO); ?>');            
            temErro = true;
        }
        if(!temErro){
            formConsultarOrdenacao.submit();
        }
    }
    function mostrarMeta(ordenacaoId){                
        var divMeta = $('#meta'+ordenacaoId);        
        divMeta.toggleClass('hidden');
    }
</script>
