<div id="topo" class='panel text-center'>
<div class='alert alert-primary'>Espaço do Aluno</div>
<div id='divConsultarMatricula' class='panel text-center p20'>
<p>Informe a matrícula do aluno</p>
<input type='number' id='matricula' class='form-control' />
<br />
<button type='button' onClick='mostrarMensagem()' class='btn btn-sm btn-primary'>
Consultar
</button>
</div>
<div id='divMensagemDeErro'></div>
<div id="divMensagem" class="hidden">
<div class="alert alert-success">
	Seja muito bem vindo ao Espaço do Aluno. Esse espaço é destinado a reposição de aulas.
	<br />
	<br />
	É necessário que você assista a aula até o final, em seguida responda ao questionário. 
	<br />
	<br />
	Cada aula tem um questionário específico e é necessário que você acerte pelo menos 70% das questões para ser efetivada a sua reposição.
	<br />
	<br />
	Uma vez respondido o questionário, a sua reposição será efetivada e o visto pedagógico daquela aula também.
	<br />
	<br />
	Boa reposição.
	<br />
	<br />
	<button type="button" class="btn btn-sm btn-primary mb10" onClick="consultarMatricula()">Prosseguir</button>
</div>
</div>
<div id='divRetorno'></div>
<div id='divBotaoVoltar' class='hidden'></div>
</div>

<script type='text/javascript'>

let estado = {
	respostas: [],
}

function mostrarMensagem(){
	document.getElementById('divConsultarMatricula').classList.add('hidden')
	document.getElementById('divMensagem').classList.remove('hidden')
}

function consultarMatricula(item = null){
		let matricula = null
		if(item === null){
			matricula = document.getElementById('matricula').value;
		}else{
			matricula = item
		}
		document.getElementById('divMensagemDeErro').classList.add('hidden')
		if(isNaN(matricula) || matricula === ''){
			return false
		}
		mostrarSplash();
		const url = '/consultarMatricula'
		fetch(
			url,
			{
				method: 'POST',	
				body: JSON.stringify({
					matricula,
				}),
			},
		)
		.then(retorno => {
			esconderSplash()
			if(!retorno.ok){
				const divMensagemDeErro = document.getElementById('divMensagemDeErro')	
				divMensagemDeErro.classList.remove('hidden')
				divMensagemDeErro.inerHTML = '<div class="alert alert-warning">Matrícula não encontrada!</div>'
			}
			return retorno.json()
		})
		.then(json => {
			document.getElementById('divMensagem').classList.add('hidden')
			if(json.html !== undefined){
				document.getElementById('divRetorno').innerHTML = json.html
			}else{
				document.getElementById('divMensagemDeErro').classList.remove('hidden')
				document.getElementById('divMensagemDeErro').innerHTML = '<div class="alert alert-danger">Matrícula não Encontrada</div>'
				document.getElementById('matricula').value = ''
			}
		})
}

function mostrarDados(){
	document.getElementById('divEspacoAluno').classList.add('hidden')
}

function mostrarAulaAberta(){
	document.getElementById('divDados').classList.add('hidden')
	document.getElementById('divAulaAberta').classList.remove('hidden')
}

function verReposicao(idFalta){
	document.getElementById('divDados').classList.add('hidden')
	document.getElementById('divFaltas').classList.remove('hidden')
	document.getElementById('divFalta'+idFalta).classList.remove('hidden')
}

function mostrarSituacaoFinanceira(){
	document.getElementById('divDados').classList.add('hidden')
	document.getElementById('divSituacaoFinanceira').classList.remove('hidden')
	document.getElementById('divPagamentos').classList.add('hidden')
}

function mostrarPagamentos(){
	document.getElementById('divSituacaoFinanceira').classList.add('hidden')
	document.getElementById('divPagamentos').classList.remove('hidden')
}

function mostrarCadastrarEmail(){
	document.getElementById('divDados').classList.add('hidden')
	document.getElementById('divEmail').classList.remove('hidden')
	document.getElementById('divCadastrarEmail').classList.remove('hidden')
}

function voltarAosDados(){
	document.getElementById('divDados').classList.remove('hidden')
	let divAulaAberta = null
	let divFaltas = null
	let divPagamentos = null
	let divSituacaoFinanceira = null
	if(divAulaAberta = document.getElementById('divAulaAberta')){
		divAulaAberta.classList.add('hidden')
	}
	if(divFaltas = document.getElementById('divFaltas')){
		divFaltas.classList.add('hidden')
	}
	if(divPagamentos = document.getElementById('divPagamentos')){
		divPagamentos.classList.add('hidden')
	}
	if(divSituacaoFinanceira = document.getElementById('divSituacaoFinanceira')){
		divSituacaoFinanceira.classList.add('hidden')
	}
	const elementosFaltas = document.getElementsByClassName('falta')
	for(let i = 0; i < elementosFaltas.length; i++){
		elementosFaltas[i].classList.add('hidden')
	}
	location.href='#topo'
}

function enviarRespostas(aula_id, tipo = 0){
		const { respostas, } = estado
		matricula = document.getElementById('matricula').value;

		mostrarSplash();
		const url = '/enviarRespostas'
		fetch(
			url,
			{
				method: 'POST',	
				body: JSON.stringify({
					aula_id,
					respostas,
					matricula,
					tipo,
				}),
			},
		)
		.then(retorno => {
			esconderSplash()
			if(!retorno.ok){
				const divMensagemDeErro = document.getElementById('divMensagemDeErro')	
				divMensagemDeErro.classList.remove('hidden')
				divMensagemDeErro.inerHTML = '<div class="alert alert-warning">Relatório não enviado tente novamente!</div>'
				return false
			}
			return retorno.json()
		})
		.then(json => {
			if(json.ok){
				location.href='#topo'
				let mensagem = 'Parabéns a aula foi reposta!'
				if(tipo === 1){
					mensagem = 'Parabéns você recebeu presença na Aula!'
				}
				alert(mensagem)
				consultarMatricula(matricula)
			}else{
				alert('Você não acertou 70% do exercícios refaça o questionário')
			}
		})
}

function salvarEmail(){
		email = document.getElementById('email').value;
		matricula = document.getElementById('matricula').value;

		mostrarSplash();
		const url = '/salvarEmail'
		fetch(
			url,
			{
				method: 'POST',	
				body: JSON.stringify({
					matricula,
					email,
				}),
			},
		)
		.then(retorno => {
			esconderSplash()
			if(!retorno.ok){
				const divMensagemDeErro = document.getElementById('divMensagemDeErro')	
				divMensagemDeErro.classList.remove('hidden')
				divMensagemDeErro.inerHTML = '<div class="alert alert-warning">Erro ao salvar email tente novamente</div>'
				return false
			}
			return retorno.json()
		})
		.then(json => {
			if(json.ok){
				alert('Email salvo com sucesso!')
				document.getElementById('divPagamentos').innerHTML = json.html	
			}else{
				alert('Email inválido ou já utilizado!')
			}
		})
}

function sair(){
	document.getElementById('divConsultarMatricula').classList.remove('hidden')
	document.getElementById('divRetorno').innerHTML = ''
	document.getElementById('matricula').value = ''
}
</script>
