<div id="topo" class='panel text-center'>
<div class='alert alert-info'>Espaço do Aluno</div>
<div id='divConsultarMatricula' class='panel text-center p20'>
<p>Informe a matrícula do aluno</p>
<input type='number' id='matricula' class='form-control' />
<br />
<button type='button' onClick='consultarMatricula()' class='btn btn-sm btn-primary'>
Consultar
</button>
</div>
<div id='divMensagemDeErro'></div>
<div id='divRetorno'></div>
<div id='divBotaoVoltar' class='hidden'></div>
</div>

<script type='text/javascript'>

let estado = {
	respostas: [],
}

function consultarMatricula(item = null){
		let matricula = null
		if(item === null){
			matricula = document.getElementById('matricula').value;
		}else{
			matricula = item
		}
		document.getElementById('divMensagemDeErro').classList.add('hidden')
		if(isNaN(matricula) || matricula === ''){
			return false
		}
		mostrarSplash();
		const url = '/consultarMatricula'
		fetch(
			url,
			{
				method: 'POST',	
				body: JSON.stringify({
					matricula,
				}),
			},
		)
		.then(retorno => {
			esconderSplash()
			if(!retorno.ok){
				const divMensagemDeErro = document.getElementById('divMensagemDeErro')	
				divMensagemDeErro.classList.remove('hidden')
				divMensagemDeErro.inerHTML = '<div class="alert alert-warning">Matrícula não encontrada!</div>'
			}
			return retorno.json()
		})
		.then(json => {
			if(json.html !== undefined){
				document.getElementById('divConsultarMatricula').classList.add('hidden')
				document.getElementById('divRetorno').innerHTML = json.html
			}else{
				document.getElementById('divMensagemDeErro').classList.remove('hidden')
				document.getElementById('divMensagemDeErro').innerHTML = '<div class="alert alert-danger">Matrícula não Encontrada</div>'
				document.getElementById('matricula').value = ''
			}

		})
}

function mostrarFaltas(){
	document.getElementById('divEspacoAluno').classList.add('hidden')
	document.getElementById('divFaltas').classList.remove('hidden')
}

function enviarRespostas(aula_id){
		const { respostas, } = estado
		matricula = document.getElementById('matricula').value;

		mostrarSplash();
		const url = '/enviarRespostas'
		fetch(
			url,
			{
				method: 'POST',	
				body: JSON.stringify({
					aula_id,
					respostas,
					matricula,
				}),
			},
		)
		.then(retorno => {
			esconderSplash()
			if(!retorno.ok){
				const divMensagemDeErro = document.getElementById('divMensagemDeErro')	
				divMensagemDeErro.classList.remove('hidden')
				divMensagemDeErro.inerHTML = '<div class="alert alert-warning">Relatório não enviado tente novamente!</div>'
				return false
			}
			return retorno.json()
		})
		.then(json => {
			if(json.ok){
				document.location.href='#topo'
				alert('Parabéns a aula foi reposta!')
				consultarMatricula(matricula)
			}else{
				alert('Você não acertou 70% do exercícios refaça o questionário')
			}
		})
}

function sair(){
	document.getElementById('divConsultarMatricula').classList.remove('hidden')
	document.getElementById('divRetorno').innerHTML = ''
	document.getElementById('matricula').value = ''
}
</script>
