<?php

use Application\Controller\Helper\Constantes;

/**
 * Nome: index.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com> e Sergio Bezerra da Silva <sergio.silva.unb@gmail.com>
 * Descricao: Página de login
 */
$formLogin = $this->formLogin;
$formLogin->prepare();
$formLogin->setAttribute(Constantes::$ACTION, $this->url(Constantes::$ROUTE_LOGIN, array(Constantes::$ACTION => Constantes::$ACTION_LOGAR)));

$classMensagem = $this->hidden;
?> 
<?php
/* Layout com botton para telas de acesso */
echo $this->layoutLoginTop;
?>
<!-- Login Panel/Form -->
<?php echo $this->form()->openTag($formLogin); ?>
<div class="panel mt30">
	<div class="panel-body bg-light pl10 pr10">
<div class='alert alert-info'>Sistema em manutenção</div>
   </div>
</div>
<?php echo $this->form()->closeTag() ?>
<?php
/* Layout com botton para telas de acesso */
echo $this->layoutLoginBotton;
