<?php

use Application\Controller\Helper\Constantes;
?>
<div class="panel-body bg-light text-center">
    <h1><span class = "text-success">Estamos processando seu pagamento em breve receberá um email de confirmação</span></h1>
    <div class = "col-xs-12">
        <h2 class = "text-default mbn confirmation-header"><i class="fa fa-check text-success"></i></h2>
    </div>
    <div class = "col-xs-12 mt10">
		<button type="button" class="btn btn-primary btn-sm" onClick="window.open('location', '_self', '');
window.close();">Ok</button>
    </div>
</div>
