<?php

use Application\Controller\Helper\Constantes;
use Application\Model\Helper\FuncoesEntidade;

$pessoa = $this->pessoa;
$imagem = FuncoesEntidade::tagImgComFotoDaPessoa($pessoa, $tamanho = 256, $tipoTamanho = 'px', $id = 'inputFoto');
$tituloDaPagina = 'Meu Perfil';
$html .= $this->templateFormularioTopo($tituloDaPagina);

$formulario = $this->formulario;
$formulario->prepare();
$formulario->setAttribute(Constantes::$ACTION, $this->url(Constantes::$ROUTE_CADASTRO, array(Constantes::$PAGINA => Constantes::$PAGINA_SALVAR_REVISAO)));

$html .= $this->form()->openTag($formulario);
$html .= '<div class="panel-body bg-light p25 mt30">';

$html .= $this->inputFormularioSimples(Constantes::$TRADUCAO_NOME, $formulario->get(Constantes::$INPUT_NOME), 12);
$html .= $this->inputFormularioSimples(Constantes::$TRADUCAO_DDD, $formulario->get(Constantes::$INPUT_DDD), 3);
$html .= $this->inputFormularioSimples(Constantes::$TRADUCAO_TELEFONE, $formulario->get(Constantes::$INPUT_TELEFONE), 9);
$html .= $this->inputFormularioSimples(Constantes::$TRADUCAO_CPF, $formulario->get(Constantes::$INPUT_CPF), 12);
$html .= $this->inputFormularioSimples(Constantes::$TRADUCAO_EMAIL, $formulario->get(Constantes::$INPUT_EMAIL), 12);
$html .= '</div>';

$html .= '<div class="panel-footer text-right">';
$html .= $this->formHidden($formulario->get(Constantes::$FORM_ID));
$html .= $this->formHidden($formulario->get(Constantes::$INPUT_CSRF));
$funcaoVerificarPerfil = $this->funcaoOnClick('validarPerfil(this.form)');
$html .= $this->botaoLink($this->translate('Salvar'), Constantes::$STRING_HASHTAG, 1, $this->funcaoOnClick($funcaoVerificarPerfil));
$html .= '</div>';

$html .= $this->form()->closeTag();

$html .= $this->templateFormularioRodape();
echo $html;
