<?php
echo $this->templateFormularioTopo($this->tituloDaPagina);
echo $this->perfil($this->pessoa, $this->formulario);
echo $this->templateFormularioRodape();
?>
<script type="text/javascript">
    function salvarFoto(result) {
        mostrarSplash();
        $('.alterarFoto').addClass('hidden');
        var id = $('#id').val();
        var canvas = result.toDataURL("image/jpeg");
        $.post(
                "/salvarFoto",
                {
                    canvas: canvas,
                    id: id,
                },
                function (data) {
                    if (data.response) {
                        alert('Foto Salva');
                        location.reload();
                    } else {
                        alert('Foto não salva');
                    }
                }, 'json');
    }

    function removerFoto(){
      var formulario = document.getElementById('formulario');
      formulario.method = 'post';
      formulario.action = 'removerFoto';
      formulario.submit();
    }

    function validarPerfil(formulario) {
        var ddd = $('#ddd').val();
        var telefone = $('#telefone').val();
        var email = $('#email').val();

        var temErro = false;
        var divMensagens = $('#divMensagens');
        var mensagem = '';

        if (telefone.length !== 8 && telefone.length !== 9) {
            temErro = true;
            mensagem = 'Telefone inválido';
        }

        if (ddd.length !== 2) {
            temErro = true;
            mensagem = 'DDD inválido';
        }

        if (temErro) {
            divMensagens
                    .html(mensagem)
                    .removeClass('alert-success')
                    .removeClass('hidden')
                    .addClass('alert-danger');
        } else {
            divMensagens
                    .addClass('hidden');
            mostrarSplash();
            formulario.submit();
        }
    }

</script>
