<?php

use Application\Controller\Helper\Constantes;

/** Nome: recuperar-senha.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com> e Sergio Bezerra da Silva <sergio.silva.unb@gmail.com>
 * Descricao: Página para redefinição de senha
 */
$formRecuperarSenha = $this->formRecuperarSenha;
$formRecuperarSenha->prepare();
$formRecuperarSenha->setAttribute(Constantes::$ACTION, $this->url(Constantes::$ROUTE_LOGIN, array(Constantes::$ACTION => Constantes::$ACTION_ALTERAR_SENHA)));

echo $this->form()->openTag($formRecuperarSenha);
?>
<?php
/* Layout com top para telas de acesso */
echo $this->layoutLoginTop;
?>
<div class="panel-body bg-light p25 pb15">
    <ul class="fa-ul">
        <li id="mensagem1">
            <i class="fa-li fa fa-check-square"></i><?php echo $this->translate(Constantes::$FORM_RECUPERAR_SENHA_6_CARACTERES); ?></li>
        <li id="mensagem2">
            <i class="fa-li fa fa-check-square"></i><?php echo $this->translate(Constantes::$FORM_RECUPERAR_SENHA_LETRA_NUMERO); ?></li>
    </ul>
    <?php
    /* Mensagem Estatica */
    echo $this->divJavaScript();
    ?>
    <!-- Username Input -->
    <div class="section">
        <label for="<?php echo $this->translate(Constantes::$INPUT_SENHA); ?>" class="field-label text-muted fs18 mb10"><?php echo $this->translate(Constantes::$TRADUCAO_NOVA_SENHA_PLACEHOLDER); ?></label>
        <label for="<?php echo $this->translate(Constantes::$INPUT_SENHA); ?>" class="field prepend-icon">
            <?php echo $this->formInput($formRecuperarSenha->get(Constantes::$INPUT_SENHA)); ?>
            <label for="<?php echo $this->translate(Constantes::$INPUT_SENHA); ?>" class="field-icon">
                <i class="fa fa-user"></i>
            </label>
            <label for="firstname" class="field-icon">
                <i id="iconeSenha" class="hidden"></i>
            </label>
        </label>
    </div>

    <!-- Password Input -->
    <div class="section">
        <label for="<?php echo $this->translate(Constantes::$INPUT_REPETIR_SENHA); ?>" class="field-label text-muted fs18 mb10"><?php echo $this->translate(Constantes::$TRADUCAO_REPETIR_SENHA_PLACEHOLDER); ?></label>
        <label for="<?php echo $this->translate(Constantes::$INPUT_REPETIR_SENHA); ?>" class="field prepend-icon">
            <?php echo $this->formInput($formRecuperarSenha->get(Constantes::$INPUT_REPETIR_SENHA)); ?>
            <label for="<?php echo $this->translate(Constantes::$INPUT_REPETIR_SENHA); ?>" class="field-icon">
                <i class="fa fa-lock"></i>
            </label>
            <label for="firstname" class="field-icon">
                <i id="iconeRecuperaSenha" class="hidden"></i>
            </label>
        </label>
    </div>
</div>

<div class="panel-footer clearfix">
    <?php echo $this->formHidden($formRecuperarSenha->get(Constantes::$INPUT_CSRF)); ?>
    <?php echo $this->formHidden($formRecuperarSenha->get(Constantes::$INPUT_ID_PESSOA)); ?>
    <?php echo $this->botaoSubmitDesabilitado(Constantes::$TRADUCAO_ALTERAR, Constantes::$INPUT_ALTERAR); ?>
</div> 
<?php
/* Layout com botton para telas de acesso */
echo $this->layoutLoginBotton;
?>
<?php
/* Layout com javascript para telas de recuperação de acessos */
echo $this->layoutJSRecuperarAcesso;
