<?php

use Application\Controller\Helper\Constantes;

/** Nome: selecionar-perfil.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com>
 * Descricao: Página para selecionar perfil
 */
?>
<!-- Start: Main -->
<div id="main" class="animated fadeIn">
    <!-- Start: Header -->
    <header class="navbar-fixed-top barra-translucida">
        <a href="<?php echo Constantes::$INDEX; ?>">
            <img src="<?php echo Constantes::$IMAGEM_LOGO_PEQUENA; ?>" title="<?php echo $this->translate(Constantes::$TRADUCAO_NOME_APLICACAO) ?>" class="img-responsive" style="max-width: 275px;">
        </a>
    </header>
    <!-- End: Header -->
    <!-- Start: Content-Wrapper -->
    <section id="content_wrapper">
        <h1 class="mtn mt70" style="text-align: center;"><?php echo $this->translate(Constantes::$TRADUCAO_QUAL_PERFIL); ?>
            <br>
            <small><?php echo $this->translate(Constantes::$TRADUCAO_SELECIONE_PERFIL); ?></small>
        </h1>

        <!-- Begin: Content -->
        <section id="content" class="table-layout animated fadeIn">

            <!-- begin: .tray-left -->
            <!-- end: .tray-left -->
            <div class="tray tray-center">
                <div class="row mb10">
                    <?php
                    /* Laço para mostrar as responsabilidades ativas */
                    foreach ($this->responsabilidades as $responsabilidade) {
						if($responsabilidade->verificarSeEstaAtivo()){
							/* Grupo da responsabilidades */
							$grupo = $responsabilidade->getGrupo();
							if ($grupo->getGrupoPaiFilhoPaiAtivo()) {
								$grupoPais = $grupo->getGrupoPaiFilhoPai();

								$arrayPais = array();
								foreach ($grupoPais as $gpfPai) {
									$arrayPais[] = $gpfPai;
								}
								uksort($arrayPais, function ($a, $b) use ($arrayPais) {
									return ($arrayPais[$a]->getId() > $arrayPais[$b]->getId()) ? -1 : 1;
								});

								foreach ($arrayPais as $gpfPai) {
									$mostrar = false;
									$ativo = true;
									$entidadeSelecionada = $grupo->getEntidadeAtiva();
									if (!$gpfPai->verificarSeEstaAtivo()) {
										$ativo = false;
										if($entidadeSelecionada = $grupo->getEntidadeInativaPorDataInativacao($gpfPai->getData_inativacaoStringPadraoBanco())){
											$mostrar = true;	
										}
									}else{
										$mostrar = true;
									}
									$grupoPai = $gpfPai->getGrupoPaiFilhoPai();
									if($mostrar){
										echo $this->perfilIcone($entidadeSelecionada, count($this->responsabilidades), $ativo, $grupoPai);
									}
								}
							} else {
								$entidadeSelecionada = $grupo->getEntidadeAtiva();
								echo $this->perfilIcone($entidadeSelecionada, count($this->responsabilidades));
							}
						}else{
							$grupo = $responsabilidade->getGrupo();
							$entidadeSelecionada = $grupo->getEntidadeAtiva();
							echo $this->perfilIcone($entidadeSelecionada, count($this->responsabilidades));
						}
                    }
                    ?>
                </div>
            </div>
        </section>
        <!-- End: Content -->
    </section>
    <!-- End: Content-Wrapper -->
</div>
<!-- End: Main -->
