<?php

use Application\Controller\Helper\Constantes;

/** Nome: selecionar-perfil.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com>
 * Descricao: Página para selecionar perfil
 */
?>
<!-- Start: Main -->
<div id="main" class="animated fadeIn">   
    <!-- Start: Content-Wrapper -->
    <section id="content_wrapper">
        <h1 style="text-align: center; margin-top: 50px;"><?php echo $this->translate(Constantes::$TRADUCAO_QUAL_PERFIL); ?>
            <br>
            <small><?php echo $this->translate(Constantes::$TRADUCAO_SELECIONE_PERFIL); ?></small>
        </h1>

        <!-- Begin: Content -->
        <section id="content" class="table-layout animated fadeIn">
            <!-- begin: .tray-left -->
            <!-- end: .tray-left -->
            <div class="tray tray-center">
                <div class="row mb10">
                    <?php
                    /* Laço para mostrar as responsabilidades ativas */
                    foreach ($this->responsabilidades as $responsabilidade) {
						$grupo = $responsabilidade->getGrupo();
						if($responsabilidade->verificarSeEstaAtivo()){
							/* Grupo da responsabilidades */
							if ($grupo->getGrupoPaiFilhoPaiAtivo()) {
								$grupoPais = $grupo->getGrupoPaiFilhoPai();

								$arrayPais = array();
								foreach ($grupoPais as $gpfPai) {
									$arrayPais[] = $gpfPai;
								}
								uksort($arrayPais, function ($a, $b) use ($arrayPais) {
									return ($arrayPais[$a]->getId() > $arrayPais[$b]->getId()) ? -1 : 1;
								});

								foreach ($arrayPais as $gpfPai) {
									$mostrar = false;
									$ativo = true;
									$entidadeSelecionada = $grupo->getEntidadeAtiva();
									if (!$gpfPai->verificarSeEstaAtivo() && $gpfPai->getData_inativacaoStringPadraoBanco()) {
										$ativo = false;
										if($entidadeSelecionada = $grupo->getEntidadeInativaPorDataInativacao($gpfPai->getData_inativacaoStringPadraoBanco())){
											$mostrar = true;	
										}
									}else{
										$mostrar = true;
									}
									$grupoPai = $gpfPai->getGrupoPaiFilhoPai();
									if($mostrar){
										echo $this->perfilIcone($entidadeSelecionada, count($this->responsabilidades), $ativo, $grupoPai);
									}
								}
							} else {
								$entidadeSelecionada = $grupo->getEntidadeAtiva();
								echo $this->perfilIcone($entidadeSelecionada, count($this->responsabilidades));
							}
						}else{
							$entidadeSelecionada = $grupo->getUltimaEntidadeInativa();
							$mostrar = true;
							$perfilSecretario = 8;
							if(!$entidadeSelecionada || $entidadeSelecionada->getTipo_id() == $perfilSecretario){
								$mostrar = false;
							}
							if($mostrar){
								if($grupo->getGrupoPaiFilhoPai()){
									$grupoPai = $grupo->getGrupoPaiFilhoPai()[0]->getGrupoPaiFilhoPai();
									echo $this->perfilIcone($entidadeSelecionada, count($this->responsabilidades), $ativo = false, $grupoPai);
								}
							}							
						}
                    }
                    ?>
                </div>
            </div>
        </section>
        <!-- End: Content -->
    </section>
    <!-- End: Content-Wrapper -->
</div>
<!-- End: Main -->
