<div class="mw1000 center-block mt50">
    <div class="panel">      
        <div class="panel-body center-block">
            <?php
            $html = '';
            $html .= '<table class="text-center table table-condensed table-hover bg-light mt15">';
            $html .= '<thead>';
            $html .= '<tr class="info">';
            $html .= '<th colspan="3" class="text-center">Relat&oacute;rio de C&eacute;lulas de Elite</th>';
            $html .= '</tr>';
            $html .= '<tr class="info">';
            $html .= '<th colspan="3" class="text-center">Per&iacute;odo ' . Application\Controller\Helper\Funcoes::montaPeriodo($this->periodo)[0] . '</th>';
            $html .= '</tr>';
            $html .= '<tr class="info">';
            $html .= '<th>Time</th>';
            $html .= '<th>Células</th>';
            $html .= '<th>Elite</th>';
            $html .= '</tr>';
            $html .= '</thead>';
            $html .= '<tbody>';
            foreach ($this->relatorioCelulas as $relatorio) {
                $corLinha = '';
                if ($relatorio['time'] === 'TOTAL') {
                    $corLinha = 'dark';
                }
                $html .= '<tr class="' . $corLinha . '">';
                $html .= '<th>' . $relatorio['time'] . '</th>';
                $html .= '<th>' . $relatorio['celulas'] . '</th>';
                $html .= '<th>' . $relatorio['elite'] . '</th>';
                $html .= '</tr>';
            }
            $html .= '</tbody>';
            $html .= '</table>';

            echo $html;
            ?>
        </div>
    </div>
</div>