<?php

use Application\Controller\Helper\Constantes;
use Application\Controller\Helper\Funcoes;

?>
<style type="text/css">
	th, p {
		text-align: center;
	}
	table {
		font-size: 10px;
	}
</style>
<div class="center-block mw600">
	<div class="panel">
	<div class="panel-heading text-center">Células não realizadas - <?php echo count($this->relatorio); ?></div>
		<div class="panel-body pn p10">
			<p>Período <?php echo Funcoes::montaPeriodo($this->periodo)[0]; ?></p>	
<?php
echo '<table class="text-center table table-bordered table-condensed table-hover bg-light mt15" >';
echo '<thead>';
echo '<tr class="dark">';
echo '<th>Time</th>';
echo '<th>Quem</th>';
echo '<th></th>';
echo '<th class="hidden-xs">Célula</th>';
echo '</tr>';
echo '</thead>';
echo '<tbody>';
if($this->relatorio){
	foreach($this->relatorio as $relatorio){
		$eventoCelula = $this->repositorio->getEventoCelulaORM()->encontrarPorId($relatorio['evento_celula_id']);
		$grupo = $this->repositorio->getGrupoORM()->encontrarPorId(substr($relatorio['numero_identificador'], (count($relatorio['numero_identificador'])-8)));

		$infoEntidade = $grupo->getEntidadeAtiva()->infoEntidade($somenteNumeros = true);
		$lideres = $grupo->getNomeLideresAtivos();
		$linkWhatsapp = $grupo->getLinksWhatsapp();
		$celulaDia = $this->translate(Funcoes::diaDaSemanaPorDia($eventoCelula->getEvento()->getDia())).' - ' . substr($eventoCelula->getEvento()->getHora(),0,5);

		echo '<tr>';
		echo '<td>'.$infoEntidade.'</td>';
		echo '<td>'.$lideres.'</td>';
		echo '<td>'.$linkWhatsapp.'</td>';
		echo '<td class="hidden-xs">'.$celulaDia.'</td>';
		echo '</tr>';
	}
}
echo '</tbody>';
echo '</table>';
