<?php

use Application\Controller\Helper\Constantes;
use Application\Controller\RelatorioController;
use Application\Controller\Helper\Funcoes;
use Application\Model\Entity\EventoTipo;
?>
<div class="center-block mw600">
	<div class="panel">
		<div class="panel-heading text-center">Discipulado</div>
		<div class="panel-body p5">
<?php
echo '<form action="/relatorioDiscipulado" method="post">';
echo $this->cabecalhoDeMeses();
echo '</form>';
if($this->filtrado){
	if($this->grupoPaiFilhoFlhos){
		foreach($this->grupoPaiFilhoFlhos as $grupoPaiFilhoFilho){
			$relatorio = array();
			$grupoFilho = $grupoPaiFilhoFilho->getGrupoPaiFilhoFilho();
			echo '<div class="panel">';
			echo '<div class="panel-body pn">';

			echo '<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 p10 text-center">';
			echo '<div>';
			echo $grupoFilho->getEntidadeAtiva()->infoEntidade();
			echo '</div>';
			foreach($grupoFilho->getPessoasAtivas() as $pessoa){
				echo '<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 p10 text-center">';
				echo '<img src="/img/fotos/'.$pessoa->getFoto().'" class="user-avatar" width="56px" height="56px" style="margin:auto;">';
				echo '</div>';
			}
			echo '</div>';// fim 6 fotos

			echo '<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 p10 text-center">';
			if($grupoEventoDiscipulado = $grupoFilho->getGrupoEventoPorTipoEAtivo(EventoTipo::tipoDiscipulado)){
				$relatorio = RelatorioController::relatorioDiscipulado($this->repositorio, $grupoFilho, $this->mes, $this->ano, $this->tradutor);
				$estrelas = '';
				if($relatorio['media']){
					for($i = 1; $i <= 5; $i++){
						if($relatorio['media'] >= $i){
							$estrelas .= '<i class="fa fa-star"></i>';
						}else{
							$estrelas .= '<i class="fa fa-star-o"></i>';
						}
					}
				}
				echo '<div class="alert alert-default" onClick="$(\'#grupo_'.$grupoFilho->getId().'\').toggleClass(\'hidden\');">Pontuação<br />'.$estrelas.'</div>';
			}else{
				echo '<span class="label label-warning">Sem discipulado</span>';
			}
			echo '</div>';// fim 6 dados

			echo '<div id="grupo_'.$grupoFilho->getId().'" class="hidden" >';
			if($discipulados = $relatorio['discipulados']){
				echo '<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 p10 text-center">';
				echo '<div class="panel">';
				echo '<div class="panel-heading text-center">Discipulados</div>';
				echo '<div class="panel-body pn">';
				foreach($discipulados as $discipulado){
					echo '<div class="alert alert-default">'.$discipulado['info'].'</div>';

					echo '<div class="row">';
					for ($indiceInputs = 1; $indiceInputs <= 6; $indiceInputs++) {
						$input = '';
						$label = '';
						switch ($indiceInputs) {
						case 1:$input = 'lanche'; $label = 'Lanche';break;
						case 2:$input = 'administrativo'; $label = 'Circuito';break;
						case 3:$input = 'oracao'; $label = 'Oração';break;
						case 4:$input = 'palavra'; $label = 'Palavra';break;
						case 5:$input = 'pontualidade'; $label = 'Pontualidade';break;
						case 6:$input = 'assiduidade'; $label = 'Assiduidade';break;
						}
						$estrelas = '';
						echo '<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 p10 text-center">';
						for($i = 1; $i <= 5; $i++){
							if($discipulado[$input] >= $i){
								$estrelas .= '<i class="fa fa-star"></i>';
							}else{
								$estrelas .= '<i class="fa fa-star-o"></i>';
							}
						}
					echo $label.'<br />';
						echo $estrelas;
						echo '</div>';
					}
					echo '</div>';
				}
				echo '</div>';
				echo '</div>';
				echo '</div>';
			}

			if($observacoes = $relatorio['observacoes']){
				echo '<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 p10 text-center">';
				echo '<div class="panel">';
				echo '<div class="panel-heading text-center">Observações</div>';
				echo '<div class="panel-body pn">';
				foreach($observacoes as $observacao){
					echo '<div class="alert alert-default">'.$observacao.'</div>';
				}
				echo '</div>';
				echo '</div>';
				echo '</div>';
			}
			echo '</div>';

			echo '</div>';
			echo '</div>';
		}
	}
}
echo '</div>';
echo '</div>';
echo '</div>';
