<?php
use Application\Controller\Helper\Funcoes;
use Application\Controller\RelatorioController;
use Application\Model\Entity\EntidadeTipo;
use Application\View\Helper\BotaoSimples;

?>
 <style type="text/css">
 th {
   text-align: center;
 }
 .table-condensed>tbody>tr>td, .table-condensed>tbody>tr>th, .table-condensed>tfoot>tr>td, .table-condensed>tfoot>tr>th, .table-condensed>thead>tr>td, .table-condensed>thead>tr>th {
   padding: 0px;
 }
 .table-condensed>tbody>tr:hover{
   font-weight: bold;
 }
 </style>
<?php
  $label = 'Gerador de Metas';
  echo $this->templateFormularioTopo($label);
?>

 <div class="panel-body bg-light" style="padding: 15px 5px 5px 5px;">
   <?php
   // echo '<form action="/relatorioExclusaoCelulas" method="post">';
   // echo $this->cabecalhoDeMeses();
   // echo '</form>';
   for ($indiceDeArrays = $this->periodoInicial; $indiceDeArrays <= $this->periodoFinal; $indiceDeArrays++) {
     $classeBase = 'periodo' . $indiceDeArrays . ' ';
     if ($indiceDeArrays != -1) {
       $classeBase .= 'hidden-xs';
     }
     $mostrarBotaoEsquerdo = true;
     if ($indiceDeArrays == $this->periodoInicial) {
       $mostrarBotaoEsquerdo = false;
     }
     $mostrarBotaoDireito = true;
     if ($indiceDeArrays == $this->periodoFinal) {
       $mostrarBotaoDireito = false;
     }
     $funcaoEsquerda = $this->funcaoOnClick('$(".periodo' . ($indiceDeArrays - 1) . '").removeClass("hidden-xs");$(".periodo' . $indiceDeArrays . '").addClass("hidden-xs");');
     $funcaoDireita = $this->funcaoOnClick('$(".periodo' . ($indiceDeArrays + 1) . '").removeClass("hidden-xs");$(".periodo' . $indiceDeArrays . '").addClass("hidden-xs");');
     $botaoEsquerda = $this->botaoSimples('<i class="fa fa-angle-double-left"></i>', $funcaoEsquerda, BotaoSimples::botaoPequenoImportante, BotaoSimples::posicaoAEsquerda);
     $botaoDireita = $this->botaoSimples('<i class="fa fa-angle-double-right"></i>', $funcaoDireita, BotaoSimples::botaoPequenoImportante, BotaoSimples::posicaoADireita);
     echo '<div class="p5 hidden-lg hidden-md hidden-sm center-block text-center ' . $classeBase . '" style="margin-bottom: 17px;"> ';
     if ($mostrarBotaoEsquerdo) {
       echo '<span class="hidden-lg hidden-md hidden-sm">' . $botaoEsquerda . '</span>';
     }
     echo Funcoes::montaPeriodo($indiceDeArrays)[0];
     if ($mostrarBotaoDireito) {
       echo '<span class="hidden-lg hidden-md hidden-sm">' . $botaoDireita . '</span>';
     }
     echo '</div>';
   }
   ?>
   <div class="p5">
     <table class="text-center table table-condensed table-hover bg-light" style="font-size:8px;">
       <thead>
         <tr class="dark hidden-xs">
           <?php
           echo '<th>Periodos</th>';
           for ($indiceDeArrays = $this->periodoInicial; $indiceDeArrays <= $this->periodoFinal; $indiceDeArrays++) {
             $classePeriodoAtual = '';
             if ($indiceDeArrays == -1) {
               $classePeriodoAtual = 'bg-info';
             }
             $colspan = 1;
             echo '<th colspan="4" class="' . $classePeriodoAtual . '">';
             echo Funcoes::montaPeriodo($indiceDeArrays)[0];
             echo '</th>';
           }
           echo '<th></th>';
           ?>
         </tr>
         <tr class="dark">
           <?php
           echo '<th>TIMES</th>';
           for ($indiceDeArrays = $this->periodoInicial; $indiceDeArrays <= $this->periodoFinal; $indiceDeArrays++) {
             $classeBase = 'periodo' . $indiceDeArrays . ' ';
             if ($indiceDeArrays != -1) {
               $classeBase .= 'hidden-xs';
             }
             $classePeriodoAtual = '';
             if ($indiceDeArrays == -1) {
               $classePeriodoAtual = 'bg-info';
             }
             echo '<th>CÉLULAS</th>';
           }
           echo '<th>ALUNOS</th>';
           echo '<th>META</th>';
           ?>
         </tr>
       </thead>
       <tbody>
         <?php
           $dadosCelulasExcluidas = $this->relatorioCelulasExcluidas;
           $dadosTeste = $this->teste;
           $contador = 0;
           $corLinha = '';
           foreach ($dadosTeste as $teste) {
             if($teste['tipo'] == 'titulo'){
               echo '<tr class="primary">';
                 echo '<td colspan="4" class="text-left text-center" style="font-size:16px;padding-left:6 px;">' . $teste['nome'] . '</span>';
                 echo '</td>';
              echo '</tr>';
            } else {
              $labelTD = '';
              $contador++;
              $totalDeCelulas = 0;
              if ($equipes == 'TOTAL') {
                $labelTD = '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
                $padding = '6';
                $corLinha = 'dark';
              }
              if ($equipes != 'TOTAL') {
                $padding = '5';
                $labelTD .= $contador;
                $labelTD .= '-';
              }
              echo '<tr class="'.$corLinha.'">';
                echo '<td class="text-left" style="font-size:8px;padding-left:6px;">' . $teste['nome'] . '</span>';
                echo $equipes;
                echo '</td>';
                for ($indiceDeArrays = $this->periodoInicial; $indiceDeArrays <= $this->periodoFinal; $indiceDeArrays++) {
                  $classeBase = 'periodo' . $indiceDeArrays . ' ';
                  if ($indiceDeArrays != -1) {
                    $classeBase .= 'hidden-xs';
                  }
                  echo '<td>';
                  echo $teste['celulas'];
                  echo '</td>';
                }
                echo '<td>'. $teste['alunos'] .'</td>';
                echo '<td>'. $teste['meta'] .'</td>';
              echo '</tr>';
            }
           }
         ?>
       </tbody>
     </table>
   </div>
 </div>
 <?php
   echo $this->templateFormularioRodape();
 ?>
