 <style type="text/css">
 th {
   text-align: center;
 }
 .table-condensed>tbody>tr>td, .table-condensed>tbody>tr>th, .table-condensed>tfoot>tr>td, .table-condensed>tfoot>tr>th, .table-condensed>thead>tr>td, .table-condensed>thead>tr>th {
   padding: 0px;
 }
 .table-condensed>tbody>tr:hover{
   font-weight: bold;
 }
 </style>
<?php

use Application\Controller\Helper\Funcoes;

$mesInicial = 1;
$mesFinal = 12;
$anoInicial = 2017;
$anoFinal = date('Y');

$html = '';
$label = 'Gerador de Metas';
$html .= $this->templateFormularioTopo($label);
$html .= '<div class="panel-body bg-light" style="padding: 15px 5px 5px 5px;">';

$html .= '<form id="formulario" method="POST" action="/relatorioGeradorDeMeta" >';

//$html .= '<div class="row p5">';
//$html .= '<div class="col-xs-12 col-sm-3 col-md-3 col-lg-1">';
//$html .= 'Nome';
//$html .= '</div>';
//$html .= '<div class="col-xs-12 col-sm-11 col-md-11 col-lg-11">';
//$html .= '<input type="text" name="nome" class="form-control" />';
//$html .= '</div>';
//$html .= '</div>';

$html .= '<div class="row p5">';
$html .= '<div class="col-lg-1 col-md-3 col-sm-3 col-xs-12 pb10 pt10">';
$html .= 'Quem';
$html .= '</div>';
$html .= '<div class="col-lg-11 col-md-9 col-sm-9 col-xs-12">';
$html .= '<select name="quem" id="quem" class="form-control">';
$html .= '<option value="0" selected>TODOS</option>';
if($this->quems){
	foreach($this->quems as $quem){
		$selected = '';
		if ($this->quem == $quem['id']) {
			$selected = 'selected';
		}
		$html .= '<option value="' . $quem['id'] . '" ' . $selected . '>' . $quem['info'] . '</option>';
	}
}
$html .= '</select>';
$html .= '</div>';
$html .= '</div>';


// div mes ano
$html .= '<div class="row p5">';
$html .= '<div class="col-lg-1 col-md-3 col-sm-3 col-xs-12 pb10 pt10">';
$html .= 'Mês';
$html .= '</div>';
$html .= '<div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">';
$html .= '<select name="mes" id="mes" class="form-control">';
for ($indice = $mesInicial; $indice <= $mesFinal; $indice++) {
	$selected = '';
	if ($this->mes == $indice) {
		$selected = 'selected';
	}

	$html .= '<option value="' . $indice . '" ' . $selected . '>' . Funcoes::mesPorExtenso($indice, 1) . '</option>';
}
$html .= '</select>';
$html .= '</div>';
$html .= '<div class="col-lg-1 col-md-3 col-sm-3 col-xs-12 pb10 pt10"">';
$html .= 'Ano';
$html .= '</div>';
$html .= '<div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">';
$html .= '<select name="ano" id="ano" class="form-control">';
for ($indice = $anoFinal; $indice >= $anoInicial; $indice--) {
	$selected = '';
	if ($this->ano == $indice) {
		$selected = 'selected';
	}
	$html .= '<option value="' . $indice . '" ' . $selected . '>' . $indice . '</option>';
}
$html .= '</select>';
$html .= '</div>';
$html .= '</div>';
// fim div mes ano

$html .= '<div class="row p15 text-center">';
$html .= '<div class="alert alert-default">';
$html .= 'Percentuais líderes e células';
$html .= '</div>';
$html .= '</div>';

// div percentual liderres e celulas
$html .= '<div class="row p5">';
$html .= '<div class="col-xs-12 col-sm-3 col-md-3 col-lg-1 pt10">';
$html .= 'Líderes';
$html .= '</div>';
$html .= '<div class="col-xs-12 col-sm-3 col-md-11 col-lg-3 mb15">';
$html .= '<input value="'.$this->lideres.'" maxlength="3" type="number" name="lideres" class="form-control" placeholder="0%" />';
$html .= '</div>';

//$html .= '<div class="col-xs-12 col-sm-3 col-md-3 col-lg-1 pt10">';
//$html .= 'Líderes Beta';
//$html .= '</div>';
//$html .= '<div class="col-xs-12 col-sm-3 col-md-11 col-lg-3 mb15">';
//$html .= '<input value="'.$this->lideresBeta.'" maxlength="3" type="number" name="lideresBeta" class="form-control" placeholder="0%" />';
//$html .= '</div>';

$html .= '<div class="col-xs-12 col-sm-3 col-md-3 col-lg-1 pt10">';
$html .= 'Células';
$html .= '</div>';
$html .= '<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 mb15">';
$html .= '<input value="'.$this->celulas.'" maxlength="3" type="number" name="celulas" class="form-control" placeholder="0%"  />';
$html .= '</div>';

$html .= '<div class="col-xs-12 col-sm-3 col-md-3 col-lg-1 pt10">';
$html .= 'Células Beta';
$html .= '</div>';
$html .= '<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 mb15">';
$html .= '<input value="'.$this->celulasBeta.'" maxlength="3" type="number" name="celulasBeta" class="form-control" placeholder="0%"  />';
$html .= '</div>';
$html .= '</div>';
// fim div percentual liderres e celulas

$html .= '<div class="row p15 text-center">';
$html .= '<div class="alert alert-default">';
$html .= 'Percentuais dos Alunos';
$html .= '</div>';
$html .= '</div>';

$html .= '<div class="row p5">';
$html .= '<div class="col-xs-12 col-sm-3 col-md-3 col-lg-1">';
$html .= '1° M';
$html .= '</div>';
$html .= '<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">';
$html .= '<input value="'.$this->alunos1m.'" maxlength="3" type="number" name="alunos1m" class="form-control" placeholder="0%"  />';
$html .= '</div>';

$html .= '<div class="col-xs-12 col-sm-3 col-md-3 col-lg-1">';
$html .= '2° M';
$html .= '</div>';
$html .= '<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">';
$html .= '<input value="'.$this->alunos2m.'" maxlength="3" type="number" name="alunos2m" class="form-control" placeholder="0%"  />';
$html .= '</div>';

$html .= '<div class="col-xs-12 col-sm-3 col-md-3 col-lg-1">';
$html .= '3° M';
$html .= '</div>';
$html .= '<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">';
$html .= '<input value="'.$this->alunos3m.'" maxlength="3" type="number" name="alunos3m" class="form-control" placeholder="0%"  />';
$html .= '</div>';
$html .= '</div>';

$html .= '<div class="row p15 text-center">';
$html .= '<div class="alert alert-default">';
$html .= 'Percentuais dos Gêneros';
$html .= '</div>';
$html .= '</div>';

$html .= '<div class="row p5">';
$html .= '<div class="col-xs-12 col-sm-3 col-md-3 col-lg-1">';
$html .= 'Homens';
$html .= '</div>';
$html .= '<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">';
$html .= '<input value="'.$this->homens.'" maxlength="3" type="number" name="homens" class="form-control" placeholder="0%"  />';
$html .= '</div>';

$html .= '<div class="col-xs-12 col-sm-3 col-md-3 col-lg-1">';
$html .= 'Mulheres';
$html .= '</div>';
$html .= '<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">';
$html .= '<input value="'.$this->mulheres.'" maxlength="3" type="number" name="mulheres" class="form-control" placeholder="0%"  />';
$html .= '</div>';

$html .= '<div class="col-xs-12 col-sm-3 col-md-3 col-lg-1">';
$html .= 'Casais';
$html .= '</div>';
$html .= '<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">';
$html .= '<input value="'.$this->casais.'" maxlength="3" type="number" name="casais" class="form-control" placeholder="0%"  />';
$html .= '</div>';
$html .= '</div>';

$html .= '<div id="divMensagemDeErro" class="row p15 hidden">';
$html .= '<div class="alert alert-danger">';
$html .= 'Campo(s) com erro(s): <span id="spanCamposComErro"></span>';
$html .= '</div>';
$html .= '</div>';

$html .= '<div class="row p10">';
$html .= '<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 pb10 pt10">';
$html .= '<button type="button" class="btn btn-primary form-control" onClick="ajudadorDeSubmissao()" >Mostrar</button>';
$html .= '</div>';
$html .= '</div>';

$html .= '</form>';
if($this->postado){
	$html .= '<table class="table table-condesend table-bordered">';
	$html .= '<tbody>';
	if($this->filhos){
		foreach($this->filhos as $filho){
			$corLinha = 'primary';
			$colSpan = 11;
			$colSpan = 9;
			if($filho['informacao'] === 'TOTAL'){
				$corLinha = 'dark';
				$colSpan = 0;
				$html .= '<tr class="dark">'; 
				$html .= '<td></td>';
				$html .= '<td>LÍDERES / META</td>';
				//$html .= '<td>LÍDERES BETA / META</td>';
				$html .= '<td>CÉLULAS / META</td>';
				$html .= '<td>CÉLULAS BETAS / META</td>';
				if($this->alunos1m > 0 || $this->alunos2m > 0 || $this->alunos3m){
					$html .= '<td>ALUNOS 1°M / META</td>';
					$html .= '<td>ALUNOS 2°M / META</td>';
					$html .= '<td>ALUNOS 3°M / META</td>';
				}
				if($this->homens > 0 || $this->mulheres > 0 || $this->casais){
					$html .= '<td>HOMENS</td>';
					$html .= '<td>MULHERES</td>';
					$html .= '<td>CASAIS</td>';
				}
				$html .= '<td>TOTAL</td>';
				$html .= '</tr>';
			}
			$html .= '<tr class="'.$corLinha.'">'; 
			$html .= '<td colspan="'.$colSpan.'">'.$filho['informacao'].'</td>';
			if($filho['informacao'] === 'TOTAL'){
				$total = 
					$filho['lideresMeta']
					+ $filho['lideresBetaMeta']
					+ $filho['celulasMeta']
					+ $filho['celulasBetaMeta']
					+ $filho['alunos1Meta']
					+ $filho['alunos2Meta']
					+ $filho['alunos3Meta']
					+ $filho['homensMeta']
					+ $filho['mulheresMeta']
					+ $filho['casaisMeta']
					;
				$html .= '<td>'.$filho['lideres'].' / '.number_format($filho['lideresMeta']).'</td>';
				//$html .= '<td>'.$filho['lideresBeta'].' / '.number_format($filho['lideresBetaMeta']).'</td>';
				$html .= '<td>'.$filho['celulas'].' / '.number_format($filho['celulasMeta']).'</td>';
				$html .= '<td>'.$filho['celulasBeta'].' / '.number_format($filho['celulasBetaMeta']).'</td>';
				if($this->alunos1m > 0 || $this->alunos2m > 0 || $this->alunos3m){
					$html .= '<td>'.$filho['alunos1'].' / '.number_format($filho['alunos1Meta']).'</td>';
					$html .= '<td>'.$filho['alunos2'].' / '.number_format($filho['alunos2Meta']).'</td>';
					$html .= '<td>'.$filho['alunos3'].' / '.number_format($filho['alunos3Meta']).'</td>';
				}
				if($this->homens > 0 || $this->mulheres > 0 || $this->casais){
					$html .= '<td>'.$filho['homens'].' / '.number_format($filho['homensMeta']).'</td>';
					$html .= '<td>'.$filho['mulheres'].' / '.number_format($filho['mulheresMeta']).'</td>';
					$html .= '<td>'.$filho['casais'].' / '.number_format($filho['casaisMeta']).'</td>';
				}
				$html .= '<td>'.number_format($total).'</td>';
			}
			$html .= '</tr>';

			if($filho['informacao'] !== 'TOTAL'){
				$html .= '<tr class="primary">'; 
				$html .= '<td>TIMES</td>';
				$html .= '<td>LÍDERES / META</td>';
				//$html .= '<td>LÍDERES BETA / META</td>';
				$html .= '<td>CÉLULAS / META</td>';
				$html .= '<td>CÉLULAS BETAS / META</td>';
				if($this->alunos1m > 0 || $this->alunos2m > 0 || $this->alunos3m){
					$html .= '<td>ALUNOS 1°M / META</td>';
					$html .= '<td>ALUNOS 2°M / META</td>';
					$html .= '<td>ALUNOS 3°M / META</td>';
				}
				if($this->homens > 0 || $this->mulheres > 0 || $this->casais){
					$html .= '<td>HOMENS</td>';
					$html .= '<td>MULHERES</td>';
					$html .= '<td>CASAIS</td>';
				}
				$html .= '<td>TOTAL</td>';
				$html .= '</tr>';
			}
			if($filho['filhos']){
				foreach($filho['filhos'] as $filho144){
					$corLinha144 = '';
					if($filho144['informacao'] === 'TOTAL PARCIAL'){
						$corLinha144 = 'info';
					}
					$total = 
						$filho144['lideresMeta']
						+ $filho144['lideresBetaMeta']
						+ $filho144['celulasMeta']
						+ $filho144['celulasBetaMeta']
						+ $filho144['alunos1Meta']
						+ $filho144['alunos2Meta']
						+ $filho144['alunos3Meta']
						+ $filho144['homensMeta']
						+ $filho144['mulheresMeta']
						+ $filho144['casaisMeta']
						;

					$html .= '<tr class="'.$corLinha144.'">'; 
					$html .= '<td>---- '.$filho144['informacao'].'</td>';
					$html .= '<td>'.$filho144['lideres'].' / '.number_format($filho144['lideresMeta']).'</td>';
					//$html .= '<td>'.$filho144['lideresBeta'].' / '.number_format($filho144['lideresBetaMeta']).'</td>';
					$html .= '<td>'.$filho144['celulas'].' / '.number_format($filho144['celulasMeta']).'</td>';
					$html .= '<td>'.$filho144['celulasBeta'].' / '.number_format($filho144['celulasBetaMeta']).'</td>';
					if($this->alunos1m > 0 || $this->alunos2m > 0 || $this->alunos3m){
						$html .= '<td>'.$filho144['alunos1'].' / '.number_format($filho144['alunos1Meta']).'</td>';
						$html .= '<td>'.$filho144['alunos2'].' / '.number_format($filho144['alunos2Meta']).'</td>';
						$html .= '<td>'.$filho144['alunos3'].' / '.number_format($filho144['alunos3Meta']).'</td>';
					}
					if($this->homens > 0 || $this->mulheres > 0 || $this->casais){
						$html .= '<td>'.$filho144['homens'].' / '.number_format($filho144['homensMeta']).'</td>';
						$html .= '<td>'.$filho144['mulheres'].' / '.number_format($filho144['mulheresMeta']).'</td>';
						$html .= '<td>'.$filho144['casais'].' / '.number_format($filho144['casaisMeta']).'</td>';
					}
					$html .= '<td>'.number_format($total).'</td>';
					$html .= '</tr>';

					if($filho144['informacao'] === 'TOTAL PARCIAL'){
						$html .= '<tr style="height: 10px;">'; 
						$html .= '<td>&nbsp;</td>';
						$html .= '</tr>';
					}
				}
			}
		}
	}
	$html .= '</tbody>';
	$html .= '</table>';
}
$html .= $this->templateFormularioRodape();

echo $html;
?>
<script type='text/javascript'>
function ajudadorDeSubmissao(){
	const hidden = 'hidden'
	const formulario = document.getElementById('formulario')
	let mostrarMensagemDeErro = false
	let camposComErro = []
	const divMensagemDeErro = document.getElementById('divMensagemDeErro')
	const spanCamposComErro = document.getElementById('spanCamposComErro')

//	if(formulario.nome.value === ''){
//		mostrarMensagemDeErro = true
//		camposComErro.push('Nome')
//	}
	if(parseInt(formulario.mes.value) === 0){
		mostrarMensagemDeErro = true
		camposComErro.push('Mês')
	}
	if(parseInt(formulario.ano.value) === 0){
		mostrarMensagemDeErro = true
		camposComErro.push('Ano')
	}
	if(formulario.lideres.value === ''){
		mostrarMensagemDeErro = true
		camposComErro.push('Líderes')
	}
	if(formulario.celulas.value === ''){
		mostrarMensagemDeErro = true
		camposComErro.push('Células')
	}
	if(formulario.celulasBeta.value === ''){
		mostrarMensagemDeErro = true
		camposComErro.push('Células Beta')
	}
	if(formulario.alunos1m.value === ''){
		mostrarMensagemDeErro = true
		camposComErro.push('Alunos 1° módulo')
	}
	if(formulario.alunos2m.value === ''){
		mostrarMensagemDeErro = true
		camposComErro.push('Alunos 2° módulo')
	}
	if(formulario.alunos3m.value === ''){
		mostrarMensagemDeErro = true
		camposComErro.push('Alunos 3° módulo')
	}
	if(formulario.homens.value === ''){
		mostrarMensagemDeErro = true
		camposComErro.push('Homens')
	}
	if(formulario.mulheres.value === ''){
		mostrarMensagemDeErro = true
		camposComErro.push('Mulheres')
	}
	if(formulario.casais.value === ''){
		mostrarMensagemDeErro = true
		camposComErro.push('Casais')
	}

	if(mostrarMensagemDeErro){
		divMensagemDeErro.classList.remove(hidden)
		
		let texto = ''
		camposComErro.forEach(campo => {
			if(texto === ''){
				texto += campo
			}else{
				texto += `, ${campo}`
			}
		})
		spanCamposComErro.innerHTML = texto
	}else{
		divMensagemDeErro.classList.add(hidden)
		mostrarSplash()
		formulario.submit()
	}

}
</script>
