<h1> Relatório Membresia</h1>
<div class="panel">
    <div class="panel-heading">
        <ul class="nav panel-tabs-border panel-tabs panel-tabs-left">
            <li class="active">
                <a href="#tab8_1" data-toggle="tab">PERIODO ATUAL</a>
            </li>
            <li>
                <a href="#tab8_2" data-toggle="tab">PERIODO ANTERIOR</a>
            </li>
        </ul>
    </div>
    <div class="panel-body pn">    
        <div class="tab-content br-n pn">
            <div id="tab18_1" class="tab-pane active">
                <table class="text-center table table-condensed bg-light">
                    <thead>
                        <tr>                   
                            <th colspan="6" class="text-center">
                                27/02 a 05/03
                            </th>                    
                        </tr>
                        <tr>
                            <th>#</th>
                            <th>TIMES</th>
                            <th>META</th>
                            <th>LIDERES</th>
                            <th>VALOR</th>
                            <th>%</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="success">
                            <td>1</td>
                            <td>BKB</td>
                            <td>6</td>
                            <td>1</td>
                            <td>3</td>
                            <td>50,00%</td>
                        </tr> 
                        <tr class="warning">
                            <td>2</td>
                            <td>FALCONS</td>
                            <td>6</td>
                            <td>1</td>
                            <td>3</td>
                            <td>50,00%</td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr>  
                            <td></td>
                            <td>TOTAL</td>
                            <td>12</td>
                            <td>2</td>
                            <td>6</td>
                            <td>50,00%</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>

    </div>
</div>