<?php
use Application\Controller\Helper\Funcoes;
use Application\Controller\RelatorioController;
?>
<style type="text/css">
	th {
		text-align: center;
	}
	.colunaEspacamento {
		width: 5px;
		background-color: #fff;
	}
</style>
<div class="center-block mt50">
    <div class="panel">
        <div class="panel-heading text-center">Aproveitamento Instituto de vencedores</div>
        <div class="panel-body pn">
            <div class="p10">
                <table class="text-center table table-condensed table-hover bg-light mt15" style="font-size:8px;">
                    <thead>
                        <tr class="dark">
							<th>Times</th>
							<?php
							echo '<th class="hidden-xs colunaEspacamento">&nbsp;</th>';
							foreach($this->turmas as $turma){
								echo '<th class="hidden-xs" colspan="5">'.$turma->getTurmaAulaAtiva()->getAula()->getDisciplina()->getNome() . ' - ' . Funcoes::mesPorExtenso($turma->getMes(), 1).'/'.$turma->getAno() . '</th>';
							echo '<th class="hidden-xs colunaEspacamento">&nbsp;</th>';
							}
							echo '<th colspan="4">TOTAL</th>';
							?>
						</tr>
						<tr>
							<th></th>
							<?php
							echo '<th class="hidden-xs colunaEspacamento">&nbsp;</th>';
							foreach($this->turmas as $turma){
							echo '<th class="hidden-xs">TOTAL</th>';
							echo '<th class="hidden-xs">OUTROS</th>';
							echo '<th class="hidden-xs">META</th>';
							echo '<th class="hidden-xs">ATIVOS</th>';
							echo '<th class="hidden-xs">%</th>';
							echo '<th class="hidden-xs colunaEspacamento">&nbsp;</th>';
							}
							echo '<th>TOTAL</th>';
							echo '<th>OUTROS</th>';
							echo '<th>ATIVOS</th>';
							echo '<th>%</th>';
							?>
						</tr>
					</thead>
					<tbody>
					<?php
							$relatorioPronto = array();
							$chaves = array();
					foreach($this->relatorio as $chave => $relatorio){
						$chaves[] = $chave;
						$soma = array();
						$relatorioTime = array();
						foreach($this->turmas as $turma){
							$total = $relatorio[$turma->getId()]['ATIVO'] + $relatorio[$turma->getId()]['DESISTENTE'] + $relatorio[$turma->getId()]['REPROVADO POR FALTAS'] + $relatorio[$turma->getId()]['ESPECIAL'];
							$outros = $relatorio[$turma->getId()]['DESISTENTE'] + $relatorio[$turma->getId()]['REPROVADO POR FALTAS'];
							$meta = 0;
							switch($turma->getTurmaAulaAtiva()->getAula()->getDisciplina()->getId()){
							case 5: $meta = 70; break;
							case 6: $meta = 70; break;
							case 7: $meta = 50; break;
							case 8: $meta = 30; break;
							}
							$metaCalculada = number_format($meta / 100 * $total);
							$ativos = $relatorio[$turma->getId()]['ATIVO'] + $relatorio[$turma->getId()]['ESPECIAL'];
							$performance = $ativos / $metaCalculada * 100;

							$soma['total'] += $total;
							$soma['outros'] += $outros;
							$soma['ativos'] += $ativos;
							$soma['performances'] += $performance;

							$relatorioTime[$turma->getId()]['total'] = $total;
							$relatorioTime[$turma->getId()]['outros'] = $outros;
							$relatorioTime[$turma->getId()]['metaCalCulada'] = $metaCalculada;
							$relatorioTime[$turma->getId()]['ativos'] = $ativos;
							$relatorioTime[$turma->getId()]['performance'] = $performance;

							$relatorioFinal[$turma->getId()]['total'] += $total;
							$relatorioFinal[$turma->getId()]['outros'] += $outros;
							$relatorioFinal[$turma->getId()]['metaCalCulada'] += $metaCalculada;
							$relatorioFinal[$turma->getId()]['ativos'] += $ativos;
						}

						$performanceFinal = $soma['performances'] / count($this->turmas);
						$relatorioTime['total'] = $soma['total'];
						$relatorioTime['outros'] = $soma['outros'];
						$relatorioTime['ativos'] = $soma['ativos'];
						$relatorioTime['performanceFinal'] = $performanceFinal;
						$relatorioPronto[$chave] = $relatorioTime;

						$relatorioFinal['total'] += $soma['total'];
						$relatorioFinal['outros'] += $soma['outros'];
						$relatorioFinal['ativos'] += $soma['ativos'];
				}


							$tamanhoArray = count($chaves);

							for ($i = 0; $i < $tamanhoArray; $i++) {
								for ($j = 0; $j < $tamanhoArray; $j++) {

									$chave1 = $chaves[$i];
									$chave2 = $chaves[$j];

									if ($relatorioPronto[$chave1]['performanceFinal'] > $relatorioPronto[$chave2]['performanceFinal']){
										$aux = $chave1;
										$chaves[$i] = $chave2;
										$chaves[$j] = $aux;
									}
								}
							}
	
							
						$htmlTime = '';
					foreach($chaves as $chave){
						$relatorioTime = $relatorioPronto[$chave];						
						$corPerformanceGeral = RelatorioController::corDaLinhaPelaPerformance($relatorioTime['performanceFinal']);
						$htmlTime .= '<tr>';
						$htmlTime .= '<td class="'.$corPerformanceGeral.'">' . $chave . '</td>';
						$htmlTime .= '<td class="hidden-xs colunaEspacamento">&nbsp;</td>';

						foreach($this->turmas as $turma){
							$corPerformance = RelatorioController::corDaLinhaPelaPerformance($relatorioTime[$turma->getId()]['performance']);
							$htmlTime .= '<td class="hidden-xs '.$corPerformance.'">' . $relatorioTime[$turma->getId()]['total'] . '</td>';
							$htmlTime .= '<td class="hidden-xs '.$corPerformance.'">' . $relatorioTime[$turma->getId()]['outros'] . '</td>';
							$htmlTime .= '<td class="hidden-xs '.$corPerformance.'">' . $relatorioTime[$turma->getId()]['metaCalCulada'] . '</td>';
							$htmlTime .= '<td class="hidden-xs '.$corPerformance.'">' . $relatorioTime[$turma->getId()]['ativos'] . '</td>';
							$htmlTime .= '<td class="hidden-xs '.$corPerformance.'">' . RelatorioController::formataNumeroRelatorio($relatorioTime[$turma->getId()]['performance']) . '%</td>';
							$htmlTime .= '<td class="hidden-xs colunaEspacamento">&nbsp;</td>';
						}

						$htmlTime .= '<td class="'.$corPerformanceGeral.'">' . $relatorioTime['total'] . '</td>';
						$htmlTime .= '<td class="'.$corPerformanceGeral.'">' . $relatorioTime['outros'] . '</td>';
						$htmlTime .= '<td class="'.$corPerformanceGeral.'">' . $relatorioTime['ativos'] . '</td>';
						$htmlTime .= '<td class="'.$corPerformanceGeral.'">' . RelatorioController::formataNumeroRelatorio($relatorioTime['performanceFinal']) . '%</td>';
						$htmlTime .= '</tr>';

						}

						$htmlTime .= '<tr>';
						$htmlTime .= '<td>TOTAL</td>';
						$htmlTime .= '<td class="hidden-xs colunaEspacamento">&nbsp;</td>';

						$somaPerformancesFinal = 0;
						foreach($this->turmas as $turma){
							$meta = 0;
							switch($turma->getTurmaAulaAtiva()->getAula()->getDisciplina()->getId()){
							case 5: $meta = 70; break;
							case 6: $meta = 70; break;
							case 7: $meta = 50; break;
							case 8: $meta = 30; break;
							}
							$metaCalculada = number_format($meta / 100 * $relatorioFinal[$turma->getId()]['total']);
							$performance = $relatorioFinal[$turma->getId()]['ativos'] / $metaCalculada * 100;
							$htmlTime .= '<td class="hidden-xs">' . $relatorioFinal[$turma->getId()]['total'] . '</td>';
							$htmlTime .= '<td class="hidden-xs">' . $relatorioFinal[$turma->getId()]['outros'] . '</td>';
							$htmlTime .= '<td class="hidden-xs">' . $relatorioFinal[$turma->getId()]['metaCalCulada'] . '</td>';
							$htmlTime .= '<td class="hidden-xs">' . $relatorioFinal[$turma->getId()]['ativos'] . '</td>';
							$htmlTime .= '<td class="hidden-xs">' . RelatorioController::formataNumeroRelatorio($performance) . '%</td>';
							$htmlTime .= '<td class="hidden-xs colunaEspacamento">&nbsp;</td>';

							$somaPerformancesFinal += $performance;
						}

						$htmlTime .= '<td>' . $relatorioFinal['total'] . '</td>';
						$htmlTime .= '<td>' . $relatorioFinal['outros'] . '</td>';
						$htmlTime .= '<td>' . $relatorioFinal['ativos'] . '</td>';
						$htmlTime .= '<td>' . RelatorioController::formataNumeroRelatorio($somaPerformancesFinal / count($turmas)) . '%</td>';
						$htmlTime .= '</tr>';

						echo $htmlTime;
					?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
 
