<?php

use Application\Controller\Helper\Constantes;
use Application\Controller\RelatorioController;

$dimensaoTipoCulto = 2;
$dimensaoTipoArena = 3;
$dimensaoTipoDomingo = 4;

$somaGeral[1] = 0;
$somaGeral[2] = 0;
$somaGeral[3] = 0;
$somaGeral[4] = 0;
$somaGeralLideres = 0;
$somaQuantidadeCelulas = 0;
$somaQuantidadeCelulasRealizadas = 0;

$urlBase = $this->url(Constantes::$ROUTE_RELATORIO) . 'Membresia';
$urlBase2 = $urlBase . '/2';
?>
<div class="mw600 center-block">
    <div class="panel-body bg-light">  
        <div class="panel">
            <div class="panel-heading">
                <ul class="nav panel-tabs-border panel-tabs panel-tabs-left">
                    <li <?php echo $this->abaSelecionada($this->abaSelecionada, 1); ?>>
                        <?php echo '<a href="' . $urlBase . '">Período Atual</a>'; ?>
                    </li>
                    <li <?php echo $this->abaSelecionada($this->abaSelecionada, 2); ?>>
                        <?php echo '<a href="' . $urlBase2 . '">Período Anterior</a>'; ?>
                    </li>
                </ul>
            </div>
            <div class="panel-body pn">
                <table class="text-center table table-condensed bg-light" style="font-size:10px;">
                    <thead>
                        <tr>                   
                            <th colspan="9" class="text-center"  style="font-size:12px;">
                                Membresia
                            </th>                    
                        </tr>
                        <tr>                   
                            <th colspan="9" class="text-center"  style="font-size:12px;">
                                Período <?php echo $this->periodoSelecionado ?>
                            </th>                    
                        </tr>
                        <tr>
                            <th class="hidden-xs">#</th>
                            <th>TIMES</th>
                            <th class="hidden-xs">LID</th>
                            <th>MET</th>                                   
                            <th>CUL</th>
                            <th>ARE</th>
                            <th>DOM</th>
                            <th>MEM</th>
                            <th>%</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $somaGeralLideres = $this->relatorio['quantidadeLideres'];
                        $somaGeral[$dimensaoTipoCulto] = $this->relatorio['membresiaCulto'];
                        $somaGeral[$dimensaoTipoArena] = $this->relatorio['membresiaArena'];
                        $somaGeral[$dimensaoTipoDomingo] = $this->relatorio['membresiaDomingo'];

                        echo '<tr>';
                        echo '<td class="hidden-xs"></td>';
                        echo '<td>MEU</td>';
                        echo '<td class="hidden-xs">' . $this->relatorio['quantidadeLideres'] . '</td>';
                        echo '<td>' . $this->relatorio['membresiaMeta'] . '</td>';
                        echo '<td>' . $this->relatorio['membresiaCulto'] . '</td>';
                        echo '<td>' . $this->relatorio['membresiaArena'] . '</td>';
                        echo '<td>' . $this->relatorio['membresiaDomingo'] . '</td>';
                        echo '<td>' . RelatorioController::formataNumeroRelatorio($this->relatorio['membresia']) . '</td>';
                        echo '<td>' . RelatorioController::formataNumeroRelatorio($this->relatorio['membresiaPerformance']) . '%</td>';
                        echo '</tr>';

                        if ($this->discipulosOrdenadoPorRelatorio[1]) {
                            $contagemRanking = 1;
                            foreach ($this->discipulosOrdenadoPorRelatorio[1] as $gpFilho) {
                                $grupoFilho = $gpFilho->getGrupoPaiFilhoFilho();
                                $entidadeFilho = $grupoFilho->getEntidadeAtiva();

                                $relatorioDiscipulo = $this->discipulosRelatorio[$grupoFilho->getId()];

                                $soma[$dimensaoTipoCulto] = $relatorioDiscipulo['membresiaCulto'];
                                $soma[$dimensaoTipoArena] = $relatorioDiscipulo['membresiaArena'];
                                $soma[$dimensaoTipoDomingo] = $relatorioDiscipulo['membresiaDomingo'];
                                $meta = $relatorioDiscipulo['membresiaMeta'];
                                $membresia = $relatorioDiscipulo['membresia'];
                                $performance = $relatorioDiscipulo['membresiaPerformance'];

                                /* Cor da linha */
                                $corDaLinha = 'default';
                                if ($performance >= 0 && $performance < 70) {
                                    $corDaLinha = 'danger';
                                }
                                if ($performance >= 70 && $performance < 85) {
                                    $corDaLinha = 'warning';
                                }
                                if ($performance > 85) {
                                    $corDaLinha = 'success';
                                }

                                echo '<tr class="' . $corDaLinha . '">';
                                echo '<td class="hidden-xs">' . $contagemRanking . '°</td>';
                                echo '<td>' . $entidadeFilho->infoEntidade() . '</td>';
                                echo '<td class="hidden-xs">' . $relatorioDiscipulo['quantidadeLideres'] . '</td>';
                                echo '<td>' . $meta . '</td>';
                                echo '<td>' . $soma[$dimensaoTipoCulto] . '</td>';
                                echo '<td>' . $soma[$dimensaoTipoArena] . '</td>';
                                echo '<td>' . $soma[$dimensaoTipoDomingo] . '</td>';
                                echo '<td>' . RelatorioController::formataNumeroRelatorio($membresia) . '</td>';
                                echo '<td>' . RelatorioController::formataNumeroRelatorio($performance) . '%</td>';
                                echo '</tr>';
                                $contagemRanking++;

                                $somaGeralLideres += $relatorioDiscipulo['quantidadeLideres'];
                                $somaGeral[$dimensaoTipoCulto] += $relatorioDiscipulo['membresiaCulto'];
                                $somaGeral[$dimensaoTipoArena] += $relatorioDiscipulo['membresiaArena'];
                                $somaGeral[$dimensaoTipoDomingo] += $relatorioDiscipulo['membresiaDomingo'];
                            }
                        }

                        $meta = Constantes::$META_LIDER * $somaGeralLideres;
                        $membresia = $somaGeral[$dimensaoTipoCulto] / 3 + $somaGeral[$dimensaoTipoArena] / 2 + $somaGeral[$dimensaoTipoDomingo];
                        $performance = $membresia / $meta * 100;
                        echo '<tr class="dark">';
                        echo '<td class="hidden-xs"></td>';
                        echo '<td>TOTAL</td>';
                        echo '<td class="hidden-xs">' . $somaGeralLideres . '</td>';
                        echo '<td>' . $meta . '</td>';
                        echo '<td>' . $somaGeral[$dimensaoTipoCulto] . '</td>';
                        echo '<td>' . $somaGeral[$dimensaoTipoArena] . '</td>';
                        echo '<td>' . $somaGeral[$dimensaoTipoDomingo] . '</td>';
                        echo '<td>' . RelatorioController::formataNumeroRelatorio($membresia) . '</td>';
                        echo '<td>' . RelatorioController::formataNumeroRelatorio($performance) . '%</td>';
                        echo '</tr>';
                        ?>                     
                    </tbody>
                </table>
                <hr />
                <table class="text-center table table-condensed bg-light" style="font-size:10px;">
                    <thead>
                        <tr>                   
                            <th colspan="5" class="text-center"  style="font-size:12px;">
                                Células Realizadas
                            </th>                    
                        </tr>
                        <tr>                   
                            <th colspan="5" class="text-center"  style="font-size:12px;">
                                Período <?php echo $this->periodoSelecionado ?>
                            </th>                    
                        </tr>
                        <tr>
                            <th>#</th>
                            <th>TIMES</th>
                            <th>CÉLULAS</th>
                            <th>REALIZADAS</th>
                            <th>%</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $somaQuantidadeCelulas += $this->relatorio['celulaQuantidade'];
                        $somaQuantidadeCelulasRealizadas += $this->relatorio['celulaRealizadas'];
                        echo '<tr>';
                        echo '<td></td>';
                        echo '<td>MEU</td>';
                        echo '<td>' . $this->relatorio['celulaQuantidade'] . '</td>';
                        echo '<td>' . $this->relatorio['celulaRealizadas'] . '</td>';
                        echo '<td>' . RelatorioController::formataNumeroRelatorio($this->relatorio['celulaRealizadasPerformance']) . '%</td>';
                        echo '</tr>';

                        if ($this->discipulosOrdenadoPorRelatorio[2]) {
                            $contagemRanking = 1;
                            foreach ($this->discipulosOrdenadoPorRelatorio[2] as $gpFilho) {
                                $grupoFilho = $gpFilho->getGrupoPaiFilhoFilho();
                                $entidadeFilho = $grupoFilho->getEntidadeAtiva();

                                $relatorioDiscipulo = $this->discipulosRelatorio[$grupoFilho->getId()];

                                $quantidadeCelulas = $relatorioDiscipulo['celulaQuantidade'];
                                $quantidadeCelulasRealizadas = $relatorioDiscipulo['celulaRealizadas'];
                                $performanceCelulas = $relatorioDiscipulo['celulaRealizadasPerformance'];

                                /* Cor da linha */
                                $corDaLinha = 'default';
                                if ($performanceCelulas >= 0 && $performanceCelulas < 70) {
                                    $corDaLinha = 'danger';
                                }
                                if ($performanceCelulas >= 70 && $performanceCelulas < 85) {
                                    $corDaLinha = 'warning';
                                }
                                if ($performanceCelulas > 85) {
                                    $corDaLinha = 'success';
                                }

                                echo '<tr class="' . $corDaLinha . '">';
                                echo '<td>' . $contagemRanking . '°</td>';
                                echo '<td>' . $entidadeFilho->infoEntidade() . '</td>';
                                echo '<td>' . $quantidadeCelulas . '</td>';
                                echo '<td>' . $quantidadeCelulasRealizadas . '</td>';
                                echo '<td>' . RelatorioController::formataNumeroRelatorio($performanceCelulas) . '%</td>';
                                echo '</tr>';
                                $contagemRanking++;

                                $somaQuantidadeCelulas += $relatorioDiscipulo['celulaQuantidade'];
                                $somaQuantidadeCelulasRealizadas += $relatorioDiscipulo['celulaRealizadas'];
                            }
                        }

                        $performanceSomaCelulas = 0;
                        if ($somaQuantidadeCelulas) {
                            $performanceSomaCelulas = $somaQuantidadeCelulasRealizadas / $somaQuantidadeCelulas * 100;
                        }
                        echo '<tr class="dark">';
                        echo '<td></td>';
                        echo '<td>TOTAL</td>';
                        echo '<td>' . $somaQuantidadeCelulas . '</td>';
                        echo '<td>' . $somaQuantidadeCelulasRealizadas . '</td>';
                        echo '<td>' . RelatorioController::formataNumeroRelatorio($performanceSomaCelulas) . '%</td>';
                        echo '</tr>';
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>