<style type="text/css">
	th {
		text-align: center;
	}
	.table-condensed>tbody>tr>td, .table-condensed>tbody>tr>th, .table-condensed>tfoot>tr>td, .table-condensed>tfoot>tr>th, .table-condensed>thead>tr>td, .table-condensed>thead>tr>th {
		padding: 0px;
	}
	.table-condensed>tbody>tr:hover{
		font-weight: bold;
	}
</style>
<?php
echo $this->templateFormularioTopo('Quantidade de pessoas enviadas para o revisão');
?>
<form action="/relatorioQuantidadeDePessoasPorRevisao" method="post">
<?php
$mesInicial = 1;
$mesFinal = 12;
$anoInicial = 2017;
$anoFinal = date('Y');

?>
<div class="row p5">
	<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12 pb10 pt10">Ano</div>
		<div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
			<select name="ano" id="ano" class="form-control">
<?php 					
for ($indice = $anoFinal; $indice >= $anoInicial; $indice--) {
	$selected = '';
	if ($this->ano == $indice) {
		$selected = 'selected';
	}
	echo '<option value="' . $indice . '" ' . $selected . '>' . $indice . '</option>';
}
?>
			</select>
		</div>

	<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
		<button type="button" onclick="this.form.submit();" class="btn ladda-button btn-primary btn-block " data-style="zoom-in">
			<span class="ladda-label">Filtrar</span>
			<span class="ladda-spinner"></span>
		</button>
	</div>
</div>
<?php
echo '</form>';

?>

	<div class="p5">
			<table class="text-center table table-condensed table-hover bg-light" style="font-size:8px;">
				<thead>
					<tr class="dark">
		<td></td>	
<?php
for($i = 0;$i < count($this->listaDeIndices); $i++){
echo '<td>'.$this->listaDeIndices[$i].'</td>';
}
?>
</tr>
</thead>
<tbody>
<?php
foreach($this->relatorio as $chave => $valor){
	echo '<tr>';
	echo '<td>'.$chave.'</td>';
for($i = 0;$i < count($this->listaDeIndices); $i++){
	echo '<td>'.$valor[$this->listaDeIndices[$i]].'</td>';
}
	echo '</tr>';
}
?>
</tbody>
</table>
	</div>
<?php
echo $this->templateFormularioRodape();
