 <style type="text/css">
 th {
   text-align: center;
 }
 .table-condensed>tbody>tr>td, .table-condensed>tbody>tr>th, .table-condensed>tfoot>tr>td, .table-condensed>tfoot>tr>th, .table-condensed>thead>tr>td, .table-condensed>thead>tr>th {
   padding: 0px;
 }
 .table-condensed>tbody>tr:hover{
   font-weight: bold;
 }
 </style>
<?php

use Application\Controller\Helper\Funcoes;

$mesInicial = 1;
$mesFinal = 12;
$anoInicial = 2017;
$anoFinal = date('Y');

$html = '';
$label = 'Ranking Setenta';
$html .= $this->templateFormularioTopo($label);
$html .= '<div class="panel-body bg-light" style="padding: 15px 5px 5px 5px;">';

$html .= '<form id="formulario" method="POST" action="/relatorioRankingSetenta" >';

// div mes ano
$html .= '<div class="row p5">';
$html .= '<div class="col-lg-1 col-md-1 col-sm-1 col-xs-12 pb10 pt10">';
$html .= 'Mês';
$html .= '</div>';
$html .= '<div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">';
$html .= '<select name="mes" id="mes" class="form-control">';
for ($indice = $mesInicial; $indice <= $mesFinal; $indice++) {
	$selected = '';
	if ($this->mes == $indice) {
		$selected = 'selected';
	}

	$html .= '<option value="' . $indice . '" ' . $selected . '>' . Funcoes::mesPorExtenso($indice, 1) . '</option>';
}
$html .= '</select>';
$html .= '</div>';
$html .= '<div class="col-lg-1 col-md-1 col-sm-1 col-xs-12 pb10 pt10"">';
$html .= 'Ano';
$html .= '</div>';
$html .= '<div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">';
$html .= '<select name="ano" id="ano" class="form-control">';
for ($indice = $anoFinal; $indice >= $anoInicial; $indice--) {
	$selected = '';
	if ($this->ano == $indice) {
		$selected = 'selected';
	}
	$html .= '<option value="' . $indice . '" ' . $selected . '>' . $indice . '</option>';
}
$html .= '</select>';
$html .= '</div>';
$html .= '</div>';
// fim div mes ano

$html .= '<div class="row p10">';
$html .= '<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 pb10 pt10">';
$html .= '<button type="button" class="btn btn-primary form-control" onClick="mostrarSplash(); this.form.submit()" >Filtrar</button>';
$html .= '</div>';
$html .= '</div>';

$html .= '</form>';
if($this->postado){
	for($indice = 1; $indice <=  3; $indice++){
		$html .= '<div class="panel">';
		$html .= '<table class="table table-condesend table-bordered" style="font-size: 8px">';
		$html .= '<tr>'; 
		$html .= '<td></td>';
		$html .= '<td>IGREJA</td>';
		$html .= '<td class="hidden-xs">EQUIPE</td>';
		$html .= '<td>LIDER(ES)</td>';
		$html .= '<td>VALOR</td>';
		$html .= '</tr>';
		$html .= '<tbody>';
		$contador = 1;
		foreach($this->lideres as $fato){
			$mostrar = false;
			switch($indice){
			case 1:
				if($fato['igreja'] === 1){
					$mostrar = true;
				}
				break;
			case 2:
				if($fato['igreja'] === 1225){
					$mostrar = true;
				}
				break;
			case 3:
				if($fato['igreja'] === 0){
					$mostrar = true;
				}
				break;
			}
			if($mostrar){
				$grupo = $this->repositorio->getGrupoORM()->encontrarporId($fato['id']);
				if($grupo->getResponsabilidadesAtivas()){
					$infoEntidade = $grupo->getEntidadeAtiva()->infoEntidade();
					$nomeLideres = $grupo->getNomeLideresAtivos();
					$nomeIgreja = $grupo->getGrupoIgreja()->getEntidadeAtiva()->getNome();

					$html .= '<tr>'; 
					$html .= '<td>'.$contador.'</td>';
					$html .= '<td>'.$nomeIgreja.'</td>';
					$html .= '<td class="hidden-xs">'.$infoEntidade.'</td>';
					$html .= '<td>'.$nomeLideres.'</td>';
					$html .= '<td>'.$fato['soma'].'</td>';
					$html .= '</tr>';
					$contador++;
				}
			}
		}
		$html .= '</tbody>';
		$html .= '</table>';
		$html .= '</div>';
	}
}
$html .= $this->templateFormularioRodape();

echo $html;
