<?php

use Application\Controller\Helper\Funcoes;

$label = 'Resumo idiota';
echo $this->templateFormularioTopo($label);
echo '<div class="panel-body bg-light" style="padding: 15px 5px 5px 5px;">';
echo '<form action="/relatorioResumo" method="post">';
echo $this->cabecalhoDeMeses();
echo '</form>';

$html = '';
if($this->filtrado){
	$html .= '<table style="text-align: \'center\'; font-size: 10px;" class="table table-hover table-responsive table-condensed">';
	$html .= '<thead class="dark">';
	$html .= '<tr>';
	$html .= '<th>Time</th>';
	$html .= '<th>Líderes</th>';
			$html .= '<td class="default"></td>';
	$html .= '<th>Quantidade de Líderes</th>';
//	for($i = 1; $i <= 4; $i++){
//		for($j = 1; $j <= 5; $j++){
//			$label = '';
//			switch($i){
//			case 1: $label = 'C'; break;
//			case 2: $label = 'CU'; break;
//			case 3: $label = 'A'; break;
//			case 4: $label = 'D'; break;
//			}
//			$html .= '<th>' . $label . $j . '</th>';
//		}
//			$html .= '<td class="default"></td>';
//	}
	$html .= '<th></th>';
	$html .= '</tr>';
	$html .= '</thead>';
	$html .= '<tbody>';
	foreach($this->relatorios as $relatorio){
		$corLinha = '';
		if($relatorio[12] == true){
			$corLinha = 'primary';
		}
		$html .= '<tr class="'.$corLinha.'">';
		$html .= '<td>'.$relatorio['info'].'</td>';
		$html .= '<td>'.$relatorio['lideres'].'</td>';
		$html .= '<td class="default"></td>';
		$html .= '<td>'.$relatorio['quantidadeDeLideres'].'</td>';

//		for($i = 1; $i <= 4; $i++){
//			$contagem = 0;
//			foreach($relatorio[$i] as $ciclos){
//				$html .= '<td>'.$ciclos.'</td>';
//				$contagem++;
//			}
//			if($contagem !== 5){
//
//				for($x = $contagem; $x <= 4; $x++){
//					$html .= '<td><i class="fa fa-ban"></i></td>';
//				}
//			}
//			$html .= '<td class="default"></td>';
//		}
		if(!$relatorio['pessoal']){
			$html .= '<td id="icone'.$relatorio['idGrupo'].'"><span onClick="buscarDiscipulos('.$relatorio['idGrupo'].', '.$relatorio['profundidade'].', '.$this->mes.', '.$this->ano.');" class="btn btn-dark btn-xs"><i class="fa fa-chevron-down"></i></span></td>';
		}
		$html .= '</tr>';
		if(!$relatorio['pessoal']){
			$html .= '<tr id="tr'.$relatorio['idGrupo'].'" class="hidden"><td align="center" style="width: \'100%\'" colSpan="24" id="td'.$relatorio['idGrupo'].'"></td></tr>';
		}
	}
	$html .= '</tbody>';
	$html .= '</table>';

	echo $html;
}
?>
<script type='text/javascript'>
	function buscarDiscipulos(idGrupo, profundidade, mes, ano){

	const elementoIcone = document.getElementById('icone'+idGrupo)
	elementoIcone.innerHTML = '<img src="/img/loader.gif" />'
	const url = '/relatorioResumoDiscipulos'
		fetch(
			url,
			{
				method: 'POST',	
				body: JSON.stringify({
					idGrupo,
					profundidade,
					mes,
					ano,
				}),
			},
		)
		.then(resultado => {
			if(!resultado.ok){
				console.log('erro ao buscar')
			}
			return resultado.json()
		})
		.then(json => {
			elementoIcone.innerHTML = ''
			const elementoTr = document.getElementById('tr'+idGrupo)
			const elementoTd = document.getElementById('td'+idGrupo)

			let html = ''
			html += '<table class="table table-condensed" style="float: \'center\';text-align: \'center\'; font-size: 10px;" >'
			html += '<tr>'
			html += '<td>Times</td>';
			html += '<td>Líderes</td>';
			html += '<td class="default"></td>';
//			for(let i = 1; i <= 4; i++){
//				let label = ''
//				switch(i){
//					case 1: label = 'C'; break;
//					case 2: label = 'CU'; break;
//					case 3: label = 'A'; break;
//					case 4: label = 'D'; break;
//				}
//				contagem = 0;
//				if(contagem !== 5){
//					for(x = contagem; x <= 4; x++){
//						html += '<td>'+label+x+'</td>';
//					}
//				}
//				html += '<td class="default"></td>';
//			}
			html += '</tr>'
	
			json.relatorios.forEach(relatorio => {
			html += '<tr>'
			html += '<td>'+relatorio['info']+'</td>';
			html += '<td>'+relatorio['lideres']+'</td>';
			html += '<td class="default"></td>';
//			for(let i = 1; i <= 4; i++){
//				contagem = 0;
//				if(relatorio[i]){
//					relatorio[i].forEach(valor => {
//						if(valor === null){
//							valor = 0
//						}
//						html += '<td>'+valor+'</td>';
//						contagem++;
//					})
//				}
//				if(contagem !== 5){
//					for(x = contagem; x <= 4; x++){
//						html += '<td><i class="fa fa-ban"></i></td>';
//					}
//				}
//				html += '<td class="default"></td>';
//			}
			html += '</tr>'
			})
			html += '</table>'

			elementoTr.classList.remove('hidden')
			elementoTd.innerHTML = html
		})
	
	}
</script>
