<?php

use Application\Controller\Helper\Funcoes;

$label = 'Resumo';
echo $this->templateFormularioTopo($label);
echo '<div class="panel-body bg-light" style="padding: 15px 5px 5px 5px;">';
echo '<form action="/relatorioResumo" method="post">';
echo $this->cabecalhoDeMeses();
echo '</form>';

$html = '';
if($this->filtrado){
	$html .= '<table style="text-align: center; font-size: 10px;" class="table table-hover table-responsive table-condensed">';
	$html .= '<thead class="dark" style="text-align: center">';
	$html .= '<tr>';
	$html .= '<th>Time</th>';
	$html .= '<th>Líderes</th>';
	$html .= '<th>Quantidade de Líderes</th>';
	$html .= '<th>Quantidade de Células</th>';
	$html .= '<th>Quantidade de Células Betas</th>';
	$html .= '<th>Quantidade de Discipulados</th>';
	for($i = 1; $i <= 4; $i++){
		$label = '';
		switch($i){
		case 1: $label = 'Célula'; break;
		case 2: $label = 'Culto'; break;
		case 3: $label = 'Arena'; break;
		case 4: $label = 'Domingo'; break;
		}
		$html .= '<th>' . $label . '</th>';
	}
	$html .= '<th></th>';
	$html .= '</tr>';
	$html .= '</thead>';
	$html .= '<tbody id="tbody" style="text-align: center">';
	foreach($this->relatorios as $relatorio){
		$corLinha = $relatorio['corDaLinha'];
		$html .= '<tr id="tr'.$relatorio['idGrupo'].'" class="'.$corLinha.'">';
		$html .= '<td>'.$relatorio['info'].'</td>';
		$html .= '<td>'.$relatorio['lideres'].'</td>';
		$html .= '<td>'.$relatorio['quantidadeDeLideres'].'</td>';
		$html .= '<td>'.$relatorio['quantidadeDeCelulas'].'</td>';
		$html .= '<td>'.$relatorio['quantidadeDeCelulasBetas'].'</td>';
		$html .= '<td>'.$relatorio['quantidadeDeDiscipulados'].'</td>';
		for($i = 1; $i <= 4; $i++){
			$html .= '<td>' . $relatorio['valores'][$i]['valor'] . '</td>';
		}
		if($relatorio['mostrarOpcao']){
			$html .= '<td id="icone'.$relatorio['idGrupo'].'"><span onClick="buscarDiscipulos('.$relatorio['idGrupo'].', '.$relatorio['profundidade'].', '.$this->mes.', '.$this->ano.');"><i class="fa fa-plus"></i></span></td>';
		}else{
			$html .= '<td></td>';
		}
		$html .= '</tr>';
	}
	$html .= '</tbody>';
	$html .= '</table>';

	echo $html;
}
?>
<script type='text/javascript'>
function buscarDiscipulos(idGrupo, profundidade, mes, ano){

	const elementoIcone = document.getElementById('icone'+idGrupo)
		elementoIcone.innerHTML = '<img src="/img/loader.gif" />'
		const url = '/relatorioResumoDiscipulos'
		fetch(
			url,
			{
				method: 'POST',	
				body: JSON.stringify({
					idGrupo,
					profundidade,
					mes,
					ano,
				}),
			},
		)
		.then(resultado => {
			if(!resultado.ok){
				console.log('erro ao buscar')
			}
			return resultado.json()
		})
		.then(json => {
				elementoIcone.innerHTML = '<i class="fa fa-minus"></i>'
				const elementoTbody = document.getElementById('tbody')
				const elementoTr = document.getElementById('tr'+idGrupo)
				elementoTr.innerHTML = '<td colspan="11"></td>';
				elementoTr.classList.remove('primary')
				elementoTr.classList.add('dark')
				let contagem = 0
				json.relatorios.forEach(relatorio => {
					let quantidadeDeLideres = relatorio['quantidadeDeLideres']
					if(quantidadeDeLideres == null){
						quantidadeDeLideres = 0
					}
					let quantidadeDeCelulas = relatorio['quantidadeDeCelulas']
					if(quantidadeDeCelulas == null){
						quantidadeDeCelulas = 0
					}
					let quantidadeDeCelulasBetas = relatorio['quantidadeDeCelulasBetas']
					if(quantidadeDeCelulasBetas == null){
						quantidadeDeCelulasBetas = 0
					}
					let quantidadeDeDiscipulados = relatorio['quantidadeDeDiscipulados']
					if(quantidadeDeDiscipulados == null){
						quantidadeDeDiscipulados = 0
					}
	
					const corDaLinha = relatorio['corDaLinha']
					let html = ''
					html += '<tr class="'+corDaLinha+'">'
					html += '<td>'+relatorio['info']+'</td>';
					html += '<td>'+relatorio['lideres']+'</td>';
					html += '<td>'+quantidadeDeLideres+'</td>';
					html += '<td>'+quantidadeDeCelulas+'</td>';
					html += '<td>'+quantidadeDeCelulasBetas+'</td>';
					html += '<td>'+quantidadeDeDiscipulados+'</td>';
					for(let i = 1; i <= 4; i++){
						let valor = relatorio['valores'][i]['valor']
						if(valor == null){
							valor = 0
						}
						html += '<td>'+valor+'</td>';
					}

					if(relatorio['mostrarOpcao']){
						html += '<td id="icone'+relatorio['idGrupo']+'"><span onClick="buscarDiscipulos('+relatorio['idGrupo']+', '+relatorio['profundidade']+', '+mes+', '+ano+');" ><i class="fa fa-plus"></i></span></td>';
					}else{
						html += '<td></td>'
					}
					html += '</tr>'

					let novaLinha = elementoTbody.insertRow(elementoTr.rowIndex + contagem)
					contagem++
					novaLinha.innerHTML = html
					novaLinha.id = `tr${relatorio['idGrupo']}` 
					novaLinha.classList.add(corDaLinha)
				})
			})
	}
</script>
