<?php

use Application\Controller\Helper\Constantes;
use Application\Controller\Helper\Funcoes;
?>
<div class="center-block mw600">
	<div class="panel">
		<div class="panel-heading text-center">Setenta - Para atualizar envie o relatório</div>
		<div class="panel-body pn">
<?php
echo '<form action="/relatorioSetenta" method="post">';
echo $this->cabecalhoDeMeses();
echo '</form>';

if($this->filtrado){
	for($indice = 1; $indice <= 2; $indice++){
		$label = 'SETENTAS';
		$icone = 'trophy';
		$chave = 'setenta';
		if($indice === 2){
			$label = 'ELO FORTE';
			$icone = 'link';
			$chave = 'elo';
		}
		echo '<div class="panel user-group-widget mt10">';
		echo '<div class="panel-heading text-center"><span class="panel-icon"><i class="fa fa-'.$icone.'"></i></span><span class="panel-title">'.$label.'</span></div>';
		echo '<div class="panel-body pn">';
		foreach($this->lideres[$chave] as $fatoMensal){
			$idGrupo = substr($fatoMensal->getNumero_identificador(), (count($fatoMensal->getNumero_identificador())-8));					
			$grupo = $this->repositorio->getGrupoORM()->encontrarporId($idGrupo);
			$foto = $grupo->getFotosLideresAtivos(56);
			$infoEntidade = $grupo->getEntidadeAtiva()->infoEntidade();
			$nomeLideres = $grupo->getNomeLideresAtivos();
			$funcaoOnClick = $this->funcaoOnClick('$("#dados'.$idGrupo.'").toggleClass("hidden")');
			echo '<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 p10 text-center" '.$funcaoOnClick.'>';
			echo $foto;
			echo '<div class="caption">';
			echo '<h5>'.$nomeLideres;
			echo '<br />';
			echo '<small>'.$infoEntidade. '</small>';
			echo '</h5>';
			echo '<span class="label label-primary" style="cursor: pointer;" >Clique Para Mais Informações</span>';
			echo '</div>';

			echo '<div id="dados'.$idGrupo.'" class="hidden">';
			echo '<div class="panel">';
			echo '<div class="panel-body">';
			Funcoes::var_dump($fatoMensal);
			if($fatoMensal->multiplicadormetasetenta > 0){
				echo '<p>Pessoas | Meta</p>';
				echo '<p>' . $fatoMensal->somacelula. ' | ' . ($fatoMensal->multiplicadormetasetenta * 35) . '</p>';
				echo '<p>Visitantes | Meta</p>';
				echo '<p>' . $fatoMensal->somavisitantes. ' | ' . ($fatoMensal->multiplicadormetasetenta * 2) . '</p>';
				echo '<p>Parceiro | Meta</p>';
				echo '<p>' . $fatoMensal->somaparceiro . ' | ' . ($fatoMensal->multiplicadormetasetenta * 40) . '</p>';
			}else{
				echo '<p>Para atualizar envio o relatório</p>';
			}
			echo '</div>';
			echo '</div>';
			echo '</div>';

			echo '</div>';
		}
		echo '</div>';// fim panel body
		echo '</div>';// fim panel
	}

}
echo '</div>';
