<?php

use Application\Controller\Helper\Constantes;
use Application\Controller\Helper\Funcoes;
?>
<div class="center-block mw600">
	<div class="panel">
		<div class="panel-heading text-center">Setenta</div>
		<div class="panel-body pn">
<?php
echo '<form action="/relatorioSetenta" method="post">';
echo $this->cabecalhoDeMeses();
echo '</form>';

for($indice = 1; $indice <= 2; $indice++){
	$label = 'SETENTAS';
	$icone = 'trophy';
	if($indice === 2){
		$label = 'ELO FORTE';
		$icone = 'link';
	}
	echo '<div class="panel user-group-widget mt10">';
	echo '<div class="panel-heading text-center"><span class="panel-icon"><i class="fa fa-'.$icone.'"></i></span><span class="panel-title">'.$label.'</span></div>';
	echo '<div class="panel-body pn">';
	foreach($this->lideres as $chave => $valor){
		$mostrar = false;
		if($indice === 1 && $valor['setenta'] == 'S'){
			$mostrar = true;
		}
		if($indice === 2 && $valor['setenta'] != 'S'){
			$mostrar = true;
		}
		if($mostrar){
			$grupo = $this->repositorio->getGrupoORM()->encontrarporId($chave);
			$foto = $grupo->getFotosLideresAtivos(56);
			$infoEntidade = $grupo->getEntidadeAtiva()->infoEntidade();
			$nomeLideres = $grupo->getNomeLideresAtivos();
			echo '<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 p10 text-center">';
			echo $foto;
			echo '<div class="caption">';
			echo '<h5>'.$nomeLideres;
			echo '<br />';
			echo '<small>'.$infoEntidade. '<small>';
			echo '</h5>';
			echo '</div>';
			echo '</div>';
		}
	}
	echo '</div>';// fim panel body
	echo '</div>';// fim panel
}

echo '</div>';
