<?php echo $this->doctype(); ?>

<?php
$versao = '?v=1.1.8';

use Application\Controller\Helper\Constantes;
?>

<html lang="pt-BR">
    <head>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
        <!-- Title Head -->
        <?php
        $NAME_APPLICATION = $this->translate(Constantes::$TRADUCAO_NOME_APLICACAO);
        echo $this
                ->headTitle($NAME_APPLICATION)
                ->setSeparator(' - ')
                ->setAutoEscape(false)
        ;
        ?>

        <!-- Meta Head -->
        <?php
        echo $this
                ->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1')
                ->appendName('theme-color', '#3498db')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ;
        ?>

        <!-- Styles -->
        <?php
        echo $this
                ->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.png'))
                ->headLink(array('rel' => 'apple-touch-icon', 'href' => $this->basePath() . '/img/icons/touch-icon-ipad.png'))
                ->headLink(array('rel' => 'apple-touch-icon', 'sizes' => '76x76', 'href' => $this->basePath() . '/img/icons/touch-icon-ipad.png'))
                ->headLink(array('rel' => 'apple-touch-icon', 'sizes' => '120x120', 'href' => $this->basePath() . '/img/icons/touch-icon-iphone-retina.png'))
                ->headLink(array('rel' => 'apple-touch-icon', 'sizes' => '152x152', 'href' => $this->basePath() . '/img/icons/touch-icon-ipad-retina.png'))
                ->headLink(array('rel' => 'apple-touch-icon', 'sizes' => '256x256', 'href' => $this->basePath() . '/img/icons/touch-icon-iphone.png'))
                ->prependStylesheet($this->basePath() . '/css/estilos-circuito/splash.css' . $versao)
                ->prependStylesheet($this->basePath() . '/vendor/plugins/ladda/ladda.min.css')
                ->prependStylesheet($this->basePath() . '/vendor/plugins/magnific/magnific-popup.css')
                ->prependStylesheet($this->basePath() . '/vendor/plugins/footable/css/footable.core.min.css')
                ->prependStylesheet($this->basePath() . '/vendor/plugins/animate/animate.min.css')
                ->prependStylesheet($this->basePath() . '/css/estilos-circuito/cv-cadastro/estilos-cadastro.css' . $versao)
                ->prependStylesheet($this->basePath() . '/css/estilos-circuito/cv-lancamentos/estilos-lancamentos.css' . $versao)
                ->prependStylesheet($this->basePath() . '/css/estilos-circuito/cv-login/estilos-login.css' . $versao)
                ->prependStylesheet($this->basePath() . '/assets/admin-forms.min.css')
                ->prependStylesheet($this->basePath() . '/assets/skin/default_skin/css/theme.min.css')
                ->prependStylesheet('https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700')
        ;
        ?>       
    </head>
    <body class="external-page external-alt sb-l-c sb-r-c">
        <!-- Start: Main -->
        <div id="main">
            <?php
            if ($this->pessoa) {
                if ($this->mostrarMenu !== 0) {
                    echo $this->menu();
                }
            }
            ?> 
            <section id="content_wrapper" style="margin-top: 50px;">
                <div id="content">
                    <?php echo $this->content; ?>
                </div>
            </section>
        </div>
        <!-- End: Main -->

        <!-- BEGIN: PAGE SCRIPTS -->
        <?php
        echo $this->modalLoader();

        echo $this
                ->headScript()
                ->prependFile($this->basePath() . '/js/circuito_da_visao/modal-loader.js' . $versao)
                ->prependFile($this->basePath() . '/js/circuito_da_visao/modal-selecionar-perfil.js' . $versao)
                ->prependFile($this->basePath() . '/js/circuito_da_visao/funcao-cadastro.js' . $versao)
                ->prependFile($this->basePath() . '/assets/js/main.js')
                ->prependFile($this->basePath() . '/assets/js/utility/utility.js')
                ->prependFile('https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile('https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/vendor/plugins/footable/js/footable.filter.min.js')
                ->prependFile($this->basePath() . '/vendor/plugins/footable/js/footable.all.min.js')
                ->prependFile($this->basePath() . '/vendor/plugins/ladda/ladda.min.js')
                ->prependFile($this->basePath() . '/vendor/plugins/highcharts/highcharts.js')
                ->prependFile($this->basePath() . '/vendor/plugins/magnific/jquery.magnific-popup.js')
                ->prependFile($this->basePath() . '/vendor/jquery/jquery_ui/jquery-ui.min.js')
                ->prependFile($this->basePath() . '/vendor/jquery/jquery-1.11.1.min.js')
        ;
        echo $this->inlineScript();
        ?>
        <script type="text/javascript">
            $('.discipulo12')
                    .css("border-left", "4px solid #4a89dc")
                    .css("pointer-events", "none");

            $('.discipulo144')
                    .css("border-left", "4px solid #967adc")
                    .css("pointer-events", "none");



            jQuery(document).ready(function () {

                "use strict";

                // Init Theme Core
                Core.init();

                // Init Ladda Plugin on buttons
                Ladda.bind('.ladda-button', {
                    timeout: 500
                });

                $('.footable').footable();

                // Init Admin Panels on widgets inside the ".admin-panels" container
                $('.admin-panels').adminpanel({
                    grid: '.admin-grid',
                    draggable: true,
                    preserveGrid: true,
                    // mobile: true,
                    onStart: function () {
                        // Do something before AdminPanels runs
                    },
                    onFinish: function () {
                        $('.admin-panels').addClass('animated fadeIn').removeClass('fade-onload');
                    },
                    onSave: function () {
                        $(window).trigger('resize');
                    }
                });

                var highColors = [bgSystem, bgSuccess, bgWarning, bgPrimary];

                // Chart data
                var seriesData = [{
                        name: 'Membresia',
                        data: [5.0, 9, 17, 22, 19, 11.5, 5.2, 9.5, 11.3, 15.3, 19.9, 24.6]
                    }, {
                        name: 'Células',
                        data: [2.9, 3.2, 4.7, 5.5, 8.9, 12.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8]
                    }, {
                        name: 'Meta',
                        data: [15, 19, 22.7, 29.3, 22.0, 17.0, 23.8, 19.1, 22.1, 14.1, 11.6, 7.5]
                    }];

                var ecomChart = $('#ecommerce_chart1');
                if (ecomChart.length) {
                    ecomChart.highcharts({
                        credits: false,
                        colors: highColors,
                        chart: {
                            backgroundColor: 'transparent',
                            className: '',
                            type: 'line',
                            zoomType: 'x',
                            panning: true,
                            panKey: 'shift',
                            marginTop: 45,
                            marginRight: 1,
                        },
                        title: {
                            text: null
                        },
                        xAxis: {
                            gridLineColor: '#EEE',
                            lineColor: '#EEE',
                            tickColor: '#EEE',
                            categories: ['Jan', 'Feb', 'Mar', 'Apr',
                                'May', 'Jun', 'Jul', 'Aug',
                                'Sep', 'Oct', 'Nov', 'Dec'
                            ]
                        },
                        yAxis: {
                            min: 0,
                            tickInterval: 5,
                            gridLineColor: '#EEE',
                            title: {
                                text: null,
                            }
                        },
                        plotOptions: {
                            spline: {
                                lineWidth: 3,
                            },
                            area: {
                                fillOpacity: 0.2
                            }
                        },
                        legend: {
                            enabled: true,
                            floating: false,
                            align: 'right',
                            verticalAlign: 'top',
                            x: -15
                        },
                        series: seriesData
                    });
                }

            });

            $(window).bind("load", function () {
                // Remove splash screen after load
                $('.splash').css('display', 'none');

                var url = window.location.href;
                var splitUrl = url.split('/');
                if (splitUrl[3].includes('principal')
                        || splitUrl[3].includes('cadastro')
                        || splitUrl[3].includes('lancamento')
                        || splitUrl[3].includes('relatorio')) {

                    $('body')
                            .removeClass('external-page')
                            .removeClass('external-alt');
                }
            });
        </script>
        <!-- END: PAGE SCRIPTS -->
    </body>
</html>
