<?php
echo $this->doctype();
$versao = '?v=1.6.12';

use Application\Controller\Helper\Constantes;
?>
<html lang="pt-BR">
    <head>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
        <!-- Title Head -->
        <?php
        $NAME_APPLICATION = $this->translate(Constantes::$TRADUCAO_NOME_APLICACAO);
        echo $this
                ->headTitle($NAME_APPLICATION)
                ->setSeparator(' - ')
                ->setAutoEscape(false)
        ;
        ?>
        <!-- Meta Head -->
        <?php
        echo $this
                ->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no')
                ->appendName('theme-color', '#3498db')
                ->appendName('google-site-verification', 'b4wOHXCDC8BakDzVfow_NeYwAGGBAEv-sCdKLsDAQUs')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ;
        ?>
        <!-- Styles -->
        <?php
        echo $this
                ->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logos/favicon.ico' . $versao))
                ->prependStylesheet($this->basePath() . '/css/estilos-circuito/splash.css' . $versao)
                ->prependStylesheet($this->basePath() . '/vendor/plugins/footable/css/footable.core.min.css')
                ->prependStylesheet($this->basePath() . '/vendor/plugins/ladda/ladda.min.css')
                ->prependStylesheet($this->basePath() . '/vendor/plugins/magnific/magnific-popup.css')
                ->prependStylesheet($this->basePath() . '/vendor/plugins/animate/animate.min.css')
                ->prependStylesheet($this->basePath() . '/css/estilos-circuito/cv-cadastro/estilos-cadastro.css' . $versao)
                ->prependStylesheet($this->basePath() . '/css/estilos-circuito/cv-lancamentos/estilos-lancamentos.css' . $versao)
                ->prependStylesheet($this->basePath() . '/css/estilos-circuito/cv-login/estilos-login.css' . $versao)
                ->prependStylesheet($this->basePath() . '/assets/admin-forms.min.css')
                ->prependStylesheet($this->basePath() . '/assets/skin/default_skin/css/theme.min.css')
                ->prependStylesheet('https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700')
        ;
        ?>
    </head>
    <body class="external-page external-alt sb-l-c sb-r-c">
        <?php echo $this->modalLoader(); ?>
        <!-- Start: Main -->
        <div id="main">
            <?php
            if ($this->pessoa) {
                if ($this->mostrarMenu !== 0) {
                    echo $this->menu();
                }
            }
            ?>
            <section id="content_wrapper">
                <div id="content">
                    <?php echo $this->content; ?>
                </div>
            </section>
        </div>
        <!-- End: Main -->

        <!-- BEGIN: PAGE SCRIPTS -->
        <?php
        echo $this
                ->headScript()
                ->prependFile($this->basePath() . '/js/circuito_da_visao/gauge.min.js')
                ->prependFile($this->basePath() . '/js/circuito_da_visao/modal-selecionar-perfil.js' . $versao)
                ->prependFile($this->basePath() . '/js/circuito_da_visao/funcao-circuito.js' . $versao)
                ->prependFile($this->basePath() . '/js/circuito_da_visao/funcao-cadastro.js' . $versao)
                ->prependFile($this->basePath() . '/js/circuito_da_visao/analyticstracking.js')
                ->prependFile($this->basePath() . '/assets/js/main.js')
                ->prependFile($this->basePath() . '/assets/js/utility/utility.js')
                ->prependFile('https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile('https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/vendor/plugins/holder/holder.min.js')
                ->prependFile($this->basePath() . '/vendor/plugins/fileupload/fileupload.js')
                ->prependFile($this->basePath() . '/vendor/plugins/cropper/cropper.min.js')
                ->prependFile($this->basePath() . '/vendor/plugins/footable/js/footable.filter.min.js')
                ->prependFile($this->basePath() . '/vendor/plugins/footable/js/footable.all.min.js')
                ->prependFile($this->basePath() . '/vendor/plugins/ladda/ladda.min.js')
                ->prependFile($this->basePath() . '/vendor/plugins/magnific/jquery.magnific-popup.js')
                ->prependFile($this->basePath() . '/vendor/jquery/jquery_ui/jquery-ui.min.js')
                ->prependFile($this->basePath() . '/vendor/jquery/jquery-1.11.1.min.js')
        ;
        echo $this->inlineScript();
        ?>
        <script type="text/javascript">
            jQuery(document).ready(function () {

                "use strict";

                // Init Theme Core
                Core.init();

                // Init Ladda Plugin on buttons
                Ladda.bind('.ladda-button', {
                    timeout: 1000
                });

                // Init FooTable Examples
                $('.footable').footable({paginate: false});

                // Modal de publicidade na página de login

                // $(document).ready(function () {
                //     let ls = localStorage.getItem("modalIndexx");
                //     if(!ls){
                //         $('#alertIndex').modal('show');
                //     }
                // });

                $('#alertIndex').on('shown.bs.modal', function(){
                    localStorage.setItem("modalIndex", false);
                });

                $('.admin-panels').adminpanel({
                    grid: '.admin-grid',
                    draggable: true,
                    preserveGrid: true,
                    // mobile: true,
                    onStart: function () {
                        // Do something before AdminPanels runs
                    },
                    onFinish: function () {
                        $('.admin-panels').addClass('animated fadeIn').removeClass('fade-onload');
                    },
                    onSave: function () {
                        $(window).trigger('resize');
                    }
                });

                (function () {
                    var $image = $('.img-container > img'),
                            $dataX = $('#dataX'),
                            $dataY = $('#dataY'),
                            $dataHeight = $('#dataHeight'),
                            $dataWidth = $('#dataWidth'),
                            $dataRotate = $('#dataRotate'),
                            options = {
                                aspectRatio: 1,
                                preview: '.img-preview',
                                crop: function (data) {
                                    $dataX.val(Math.round(data.x));
                                    $dataY.val(Math.round(data.y));
                                    $dataHeight.val(Math.round(data.height));
                                    $dataWidth.val(Math.round(data.width));
                                    $dataRotate.val(Math.round(data.rotate));
                                }
                            };

                    $image.cropper(options);

                    // Methods
                    $(document.body).on('click', '[data-method]', function () {
                        var data = $(this).data(),
                                $target,
                                result;

                        if (data.method) {
                            data = $.extend({}, data); // Clone a new one

                            if (typeof data.target !== 'undefined') {
                                $target = $(data.target);

                                if (typeof data.option === 'undefined') {
                                    try {
                                        data.option = JSON.parse($target.val());
                                    } catch (e) {
                                        console.log(e.message);
                                    }
                                }
                            }

                            result = $image.cropper(data.method, data.option);

                            if (data.method === 'getCroppedCanvas') {
                                salvarFoto(result);
                            }

                            if ($.isPlainObject(result) && $target) {
                                try {
                                    $target.val(JSON.stringify(result));
                                } catch (e) {
                                    console.log(e.message);
                                }
                            }

                        }
                    });

                    // Import image
                    var $inputImage = $('#inputImage'),
                            URL = window.URL || window.webkitURL,
                            blobURL;

                    if (URL) {
                        $inputImage.change(function () {
                            var files = this.files,
                                    file;

                            if (files && files.length) {
                                file = files[0];

                                if (/^image\/\w+$/.test(file.type)) {
                                    blobURL = URL.createObjectURL(file);
                                    $image.one('built.cropper', function () {
                                        URL.revokeObjectURL(blobURL); // Revoke when load complete
                                    }).cropper('reset', true).cropper('replace', blobURL);
                                    $inputImage.val('');

                                    $('#fotoCrop').removeClass('hidden');
                                    $('#fotoPerfil').addClass('hidden');
                                    $('.subirFoto').addClass('hidden');
                                    $('.alterarFoto').removeClass('hidden');
                                } else {
                                    showMessage('Please choose an image file.');
                                }
                            }
                        });
                    } else {
                        $inputImage.parent().remove();
                    }

                }());

            });

            function mostrarSplash() {
                $('#splash').css('display', 'block');
            }
            function esconderSplash() {
                $('#splash').css('display', 'none');
            }
            $(window).bind("load", function () {
                // Remove splash screen after load
                $('#splash').css('display', 'none');

                var url = window.location.href;
                var splitUrl = url.split('/');
                if (splitUrl[3].includes('principal')
                        || splitUrl[3].includes('cadastro')
                        || splitUrl[3].includes('lancamento')
                        || splitUrl[3].includes('relatorio')) {

                    $('body')
                            .removeClass('external-page')
                            .removeClass('external-alt');
                }
            });
        </script>
        <!-- END: PAGE SCRIPTS -->
    </body>
</html>
