<?php

use Application\Controller\Helper\Constantes;

$versao = '?v=1.7';

echo $this
        ->headScript()
        ->prependFile($this->basePath() . '/vendor/plugins/pnotify/pnotify.js')
        ->prependFile($this->basePath() . '/js/circuito_da_visao/funcao-pessoa-lancamento.js' . $versao)
        ->prependFile($this->basePath() . '/js/circuito_da_visao/alterar-nome.js' . $versao)
        ->prependFile($this->basePath() . '/js/circuito_da_visao/mudar-frequencia.js' . $versao)
        ->prependFile($this->basePath() . '/js/circuito_da_visao/modal-selecionar-aba.js' . $versao)
        ->prependFile($this->basePath() . '/js/circuito_da_visao/ajustar-tabela-lancamento.js' . $versao)
        ->prependFile($this->basePath() . '/js/circuito_da_visao/modal-muitos-cadastros.js' . $versao)
;
echo $this->inlineScript();
?>
<script type = "text/javascript">
<?php if (!empty($this->nomePessoaCadastrada)) { ?>
        window.onload = modalCadastro;
<?php } ?>

    function modalCadastro() {
        var stack_bar_bottom = {
            "dir1": "up",
            "dir2": "right",
            "spacing1": 0,
            "spacing2": 0
        }

        var noteStyle = 'success';
        var noteShadow = true;
        var noteOpacity = 1;

        new PNotify({
            title: '<?php echo $this->translate(Constantes::$TRADUCAO_PESSOA_CADASTRADA); ?>!',
            text: '<?php echo $this->nomePessoaCadastrada; ?>',
            shadow: noteShadow,
            opacity: noteOpacity,
            addclass: 'stack_bar_bottom',
            type: noteStyle,
            stack: stack_bar_bottom,
            width: '70%',
            delay: 10000
        });

    }
</script>