<?php

use Application\Controller\Helper\Constantes;
?> 
<script type="text/javascript">
    window.onload = initPage;
    /**
     * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com> & Sergio Bezerra da Silva <sergio.silva.unb@gmail.com>
     * Descricao: Função para validar os campos do formulário de cadastro de célula
     */
    function initPage() {

        $('#<?php echo $this->translate(Constantes::$FORM); ?>').validate({
            /* @validation states + elements 
             ------------------------------------------- */

            errorClass: "state-error",
            validClass: "state-success",
            errorElement: "em",
            /* @validation rules 
             ------------------------------------------ */

            rules: {
<?php echo $this->translate(Constantes::$FORM_DIA_DA_SEMANA); ?>: {
                    required: true
                },
<?php echo $this->translate(Constantes::$FORM_HORA); ?>: {
                    required: true
                },
<?php echo $this->translate(Constantes::$FORM_MINUTOS); ?>: {
                    required: true
                },
<?php echo $this->translate(Constantes::$FORM_NOME); ?>: {
                    required: true,
                    minlength: 3,
                    maxlength: 30
                }
            },
            /* @validation error messages 
             ---------------------------------------------- */

            messages: {
<?php echo $this->translate(Constantes::$FORM_DIA_DA_SEMANA); ?>: {
                    required: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_DIA_DA_SEMANA_REQUERIDO); ?>'
                },
<?php echo $this->translate(Constantes::$FORM_HORA); ?>: {
                    required: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_HORA_REQUERIDO); ?>'
                },
<?php echo $this->translate(Constantes::$FORM_MINUTOS); ?>: {
                    required: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_MINUTOS_REQUERIDO); ?>'
                },
<?php echo $this->translate(Constantes::$FORM_NOME); ?>: {
                    required: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_NOME_REQUERIDO); ?>',
                    minlength: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_NOME_MINIMO); ?>',
                    maxlength: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_NOME_MAXIMO); ?>'
                }
            },
            /* @validation highlighting + error placement  
             ---------------------------------------------------- */

            highlight: function (element, errorClass, validClass) {
                $(element).closest('.field').addClass(errorClass).removeClass(validClass);
            },
            unhighlight: function (element, errorClass, validClass) {
                $(element).closest('.field').removeClass(errorClass).addClass(validClass);
            },
            errorPlacement: function (error, element) {
                if (element.is(":radio") || element.is(":checkbox")) {
                    element.closest('.option-group').after(error);
                } else {
                    error.insertAfter(element.parent());
                }
            }

        });

        $('#<?php echo $this->translate(Constantes::$FORM_CELULA); ?>').validate({
            /* @validation states + elements 
             ------------------------------------------- */

            errorClass: "state-error",
            validClass: "state-success",
            errorElement: "em",
            /* @validation rules 
             ------------------------------------------ */

            rules: {
<?php echo $this->translate(Constantes::$FORM_DIA_DA_SEMANA); ?>: {
                    required: true
                },
<?php echo $this->translate(Constantes::$FORM_HORA); ?>: {
                    required: true
                },
<?php echo $this->translate(Constantes::$FORM_MINUTOS); ?>: {
                    required: true
                },
<?php echo $this->translate(Constantes::$FORM_CEP_LOGRADOURO); ?>: {
                    required: true,
                    minlength: 8,
                    maxlength: 8,
                    number: true
                },
<?php echo $this->translate(Constantes::$FORM_NOME_HOSPEDEIRO); ?>: {
                    required: true,
                    minlength: 3,
                    maxlength: 80
                },
<?php echo $this->translate(Constantes::$FORM_DDD_HOSPEDEIRO); ?>: {
                    required: true,
                    minlength: 2,
                    maxlength: 2,
                    number: true
                },
<?php echo $this->translate(Constantes::$FORM_TELEFONE_HOSPEDEIRO); ?>: {
                    required: true,
                    minlength: 8,
                    maxlength: 9,
                    number: true
                }
            },
            /* @validation error messages 
             ---------------------------------------------- */

            messages: {
<?php echo $this->translate(Constantes::$FORM_DIA_DA_SEMANA); ?>: {
                    required: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_DIA_DA_SEMANA_REQUERIDO); ?>'
                },
<?php echo $this->translate(Constantes::$FORM_HORA); ?>: {
                    required: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_HORA_REQUERIDO); ?>'
                },
<?php echo $this->translate(Constantes::$FORM_MINUTOS); ?>: {
                    required: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_MINUTOS_REQUERIDO); ?>'
                },
<?php echo $this->translate(Constantes::$FORM_CEP_LOGRADOURO); ?>: {
                    required: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_CEP_LOGRADOURO_REQUERIDO); ?>',
                    minlength: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_CEP_LOGRADOURO_INVALIDO); ?>',
                    maxlength: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_CEP_LOGRADOURO_INVALIDO); ?>',
                    number: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_CEP_LOGRADOURO_REQUERIDO); ?>'
                },
<?php echo $this->translate(Constantes::$FORM_NOME_HOSPEDEIRO); ?>: {
                    required: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_NOME_HOSPEDEIRO_REQUERIDO); ?>',
                    minlength: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_NOME_HOSPEDEIRO_MINIMO); ?>',
                    maxlength: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_NOME_HOSPEDEIRO_MAXIMO); ?>'
                },
<?php echo $this->translate(Constantes::$FORM_DDD_HOSPEDEIRO); ?>: {
                    required: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_DDD_HOSPEDEIRO_REQUERIDO); ?>',
                    minlength: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_DDD_HOSPEDEIRO_INVALIDO); ?>',
                    maxlength: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_DDD_HOSPEDEIRO_INVALIDO); ?>',
                    number: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_DDD_HOSPEDEIRO_INVALIDO); ?>'
                },
<?php echo $this->translate(Constantes::$FORM_TELEFONE_HOSPEDEIRO); ?>: {
                    required: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_TELEFONE_HOSPEDEIRO_REQUERIDO); ?>',
                    minlength: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_TELEFONE_HOSPEDEIRO_INVALIDO); ?>',
                    maxlength: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_TELEFONE_HOSPEDEIRO_INVALIDO); ?>',
                    number: '<?php echo $this->translate(Constantes::$TRADUCAO_VALIDACAO_TELEFONE_HOSPEDEIRO_INVALIDO); ?>'
                }
            },
            /* @validation highlighting + error placement  
             ---------------------------------------------------- */

            highlight: function (element, errorClass, validClass) {
                $(element).closest('.field').addClass(errorClass).removeClass(validClass);
            },
            unhighlight: function (element, errorClass, validClass) {
                $(element).closest('.field').removeClass(errorClass).addClass(validClass);
            },
            errorPlacement: function (error, element) {
                if (element.is(":radio") || element.is(":checkbox")) {
                    element.closest('.option-group').after(error);
                } else {
                    error.insertAfter(element.parent());
                }
            }

        });
    }

    function preValidacao(tipo) {

        var validator;
        if (tipo === 1) {
            validator = $('#<?php echo $this->translate(Constantes::$FORM_CELULA); ?>').validate();
            if (validator.form()) {
                // Preenchendo os campos
                var valorDiaDaSemana = $('#<?php echo Constantes::$FORM_DIA_DA_SEMANA; ?>').val();
                var diaDaSemanaPorExtenso = retornaDiaDaSemanaPorExtenso(valorDiaDaSemana);
                var spanDiaHora = diaDaSemanaPorExtenso + '/' + $('#<?php echo Constantes::$FORM_HORA; ?>').val() + ':' + $('#<?php echo Constantes::$FORM_MINUTOS; ?>').val();
                var spanNome = $('#<?php echo Constantes::$FORM_NOME_HOSPEDEIRO; ?>').val();
                spanNome = spanNome.toUpperCase();
                var spanTelefone =
                        '(' + $('#<?php echo Constantes::$FORM_DDD_HOSPEDEIRO; ?>').val() + ') '
                        + $('#<?php echo Constantes::$FORM_TELEFONE_HOSPEDEIRO; ?>').val();
                var spanLogradouroComplemento = $('#<?php echo Constantes::$FORM_LOGRADOURO; ?>').val() + ', ' +
                        $('#<?php echo Constantes::$FORM_COMPLEMENTO; ?>').val();
                var spanEndereco = $('#<?php echo Constantes::$FORM_CIDADE; ?>').val() + '&nbsp;-&nbsp;' +
                        $('#<?php echo Constantes::$FORM_BAIRRO; ?>').val() + ',&nbsp;' +
                        $('#<?php echo Constantes::$FORM_UF; ?>').val() + '&nbsp; CEP:' +
                        $('#<?php echo Constantes::$FORM_CEP_LOGRADOURO; ?>').val();
                $('#spanDiaHora').html(spanDiaHora);
                $('#spanNome').html(spanNome);
                $('#spanTelefone').html(spanTelefone);
                $('#spanLogradouroComplemento').html(spanLogradouroComplemento);
                $('#spanEndereco').html(spanEndereco);

                $('#divDados').toggleClass('<?php echo Constantes::$FORM_HIDDEN; ?>');
                $('#divFormulario').toggleClass('<?php echo Constantes::$FORM_HIDDEN; ?>');
            }
        }
        if (tipo === 2) {
            validator = $('#<?php echo $this->translate(Constantes::$FORM); ?>').validate();
            if (validator.form()) {
                // Preenchendo os campos
                var valorDiaDaSemana = $('#<?php echo Constantes::$FORM_DIA_DA_SEMANA; ?>').val();
                var diaDaSemanaPorExtenso = retornaDiaDaSemanaPorExtenso(valorDiaDaSemana);
                var spanDiaHora = diaDaSemanaPorExtenso + '/' + $('#<?php echo Constantes::$FORM_HORA; ?>').val() + ':' + $('#<?php echo Constantes::$FORM_MINUTOS; ?>').val();
                var spanNome = $('#<?php echo Constantes::$FORM_NOME; ?>').val();
                spanNome = spanNome.toUpperCase();

                $('#spanDiaHora').html(spanDiaHora);
                $('#spanNome').html(spanNome);

                var nomeEquipesSelecionadas = '';
                var todosElementos = document.Form.elements;
                for (i = 0; i < todosElementos.length; i++) {
                    if (todosElementos[i].type == "checkbox" && todosElementos[i].checked) {
                        nomeEquipesSelecionadas += '<br />' + todosElementos[i].value;
                    }
                }
                if (nomeEquipesSelecionadas === '') {
                    nomeEquipesSelecionadas = 'Nenhuma equipe selecionada';
                }
                $('#spanEquipes').html(nomeEquipesSelecionadas);

                $('#divDados').toggleClass('<?php echo Constantes::$FORM_HIDDEN; ?>');
                $('#divFormulario').toggleClass('<?php echo Constantes::$FORM_HIDDEN; ?>');
            }
        }

    }

    function retornaDiaDaSemanaPorExtenso(diaDaSemana) {
        var diaDaSemanaPorExtenso;
        var valorInteiro = parseInt(diaDaSemana);
        switch (valorInteiro) {
            case 1:
                diaDaSemanaPorExtenso = 'SUNDAY';
                break;
            case 2:
                diaDaSemanaPorExtenso = 'MONDAY';
                break;
            case 3:
                diaDaSemanaPorExtenso = 'TUESDAY';
                break;
            case 4:
                diaDaSemanaPorExtenso = 'WEDNESDAY';
                break;
            case 5:
                diaDaSemanaPorExtenso = 'THURSDAY';
                break;
            case 6:
                diaDaSemanaPorExtenso = 'FRIDAY';
                break;
            case 7:
                diaDaSemanaPorExtenso = 'SATURDAY';
                break;
        }
        return diaDaSemanaPorExtenso;
    }
</script>
