<?php

use Application\Controller\Helper\Constantes;
use Zend\Session\Container;

$versao = '?v=1.1.4';

echo $this
        ->headScript()
        ->prependFile($this->basePath() . '/vendor/plugins/pnotify/pnotify.js')
;
echo $this->inlineScript();

$mensagemPNotify = '';
$nomePessoa = '';
$sessao = new Container(Constantes::$NOME_APLICACAO);
$mostrarNotificacao = false;
if ($sessao->mostrarNotificacao) {
    $mostrarNotificacao = true;
    $mensagemPNotify = $this->translate(Constantes::$TRADUCAO_PESSOA_CADASTRADA);
    if ($sessao->exclusao) {
        $mensagemPNotify = $this->translate(Constantes::$TRADUCAO_PESSOA_INATIVADA_LANCAMENTO);
    }
    if ($sessao->emailEnviado) {
        $mensagemPNotify = 'Email(s) reenviado(s)';
    }
    if ($sessao->nomePessoa) {
        $nomePessoa = $sessao->nomePessoa;
    }
    $sessao->jaMostreiANotificacao = true;
}
?>
<script type = "text/javascript">
<?php if ($mostrarNotificacao) { ?>
        window.onload = modalPNotify;
<?php } ?>

    function modalPNotify() {
        var stack_bar_bottom = {
            "dir1": "up",
            "dir2": "right",
            "spacing1": 0,
            "spacing2": 0
        }

        var noteStyle = 'success';
        var noteShadow = true;
        var noteOpacity = 1;

        new PNotify({
            title: '<?php echo $mensagemPNotify; ?>!',
            text: '<?php echo $nomePessoa; ?>',
            shadow: noteShadow,
            opacity: noteOpacity,
            addclass: 'stack_bar_bottom',
            type: noteStyle,
            stack: stack_bar_bottom,
            width: '70%',
            delay: 10000
        });

    }

    function mostrarModalClasse() {
        $.magnificPopup.open({
            removalDelay: 500, //delay removal by X to allow out-animation,
            items: {
                src: "#modalClassificacao"
            },
            modal: true,
            callbacks: {
                beforeOpen: function (e) {
                    var Animation = "mfp-zoomIn";
                    this.st.mainClass = Animation;
                }
            },
            midClick: true // allow opening popup on middle mouse click. Always set it to true if you don't provide alternative source.
        });
    }
</script>