<?php 
$versao = 0.1;
echo $this
        ->headScript()
        ->prependFile($this->basePath() . '/js/circuito_da_visao/funcao-lancamento.js' . $versao)
;
echo $this->inlineScript();
?>
<div class="mw1000 center-block p10">
    <div class="admin-form theme-danger">
        <blockquote class = "blockquote-danger">
            <small>
                Relat&oacute;rio de <span class="text-danger">Atendimento</span>
            </small>
        </blockquote>
        <div id="atendimento" class="panel heading-border panel-danger">
            <div class="panel-body bg-light">
                <div class="row">
                    <div class="section-divider mt30">
                        <span>13 de 23 discipulos foram atendidos</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 col-xs-12">
                        <div class="progress progress-bar-xl">
                            <div id="divProgressBar" class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%;">50%</div>
                        </div>
                    </div>
                </div>
                <?php
                foreach ($gruposAbaixo as $gpFilho) {
                    $grupoFilho = $gpFilho->getGrupoPaiFilhoFilho();
                    $entidadeFilho = $grupoFilho->getEntidadeAtiva();
                    $grupoResponsavel = $grupoFilho->getResponsabilidadesAtivas();
                    if ($grupoResponsavel) {
                        $pessoas = array();
                        foreach ($grupoResponsavel as $gr) {
                            $p = $gr->getPessoa();
                            $imagem = 'placeholder.png';
                            if (!empty($p->getFoto())) {
                                $imagem = $p->getFoto();
                            }
                            $pessoas[] = $p;
                        }

                        $html = '';
                        $htmlFoto = '';
                        $contagem = 1;
                        $totalPessoas = count($pessoas);

                        foreach ($pessoas as $p) {
                            if ($contagem == 2) {
                                $html .= '&nbsp;&&nbsp;';
                                $htmlFoto .= '';
                            }
                            $imagem = 'placeholder.png';
                            $tamanho = 45;
                            if (!empty($p->getFoto())) {
                                $imagem = $p->getFoto();
                            }
                            $htmlFoto .= '<img src="/img/avatars/' . $imagem . '" class="img-thumbnail" width="' . $tamanho . '%"  height="' . $tamanho . '%" />&nbsp;';
                            if ($totalPessoas == 1) {
                                $html .= $p->getNomePrimeiroUltimo();
                            } else {// duas pessoas
                                $html .= $p->getNomePrimeiroPrimeiraSiglaUltimo();
                            }
                            $contagem++;
                        }
                    }
                    ?>
                    <div class="row mt10">
                        <div class="col-md-3 col-xs-5" style="padding-right: 0px;">
                            <span class="" href="#" >
                                <?php echo $htmlFoto; ?>
                            </span>
                        </div>    
                        <div class="col-md-9 col-xs-7" style="padding-left: 2px; padding-right: 0px;">
                            <div class="row">
                                <div class="col-md-11 col-xs-10" style="padding-top: 3px; padding-right: 4px;">

                                    <div class="progress progress-bar-xl" style="margin-bottom: 0px;">
                                        <div id="divProgressBar" class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="5" style="width: 10%;">0%</div>
                                    </div>
                                    <span style="padding-top: 0px;"><?php echo $html; ?></span>
                                </div>
                                <?php $onClick = 'onclick="funcaoLancamento(lancarAtendimento,'. $gpFilho->getId() . ')"'; ?>
                                <div class="col-md-1 col-xs-2" style="padding-left: 0px; padding-top: 3px; vertical-align: middle;">
                                    <button type="button" <?php echo $onClick;?> class="btn btn-xs btn-primary" style="padding-top: 0px; padding-bottom: 0px;">
                                        <i class="fa fa-plus" aria-hidden="true"></i>
                                    </button>
                                </div>                           
                            </div>  
                        </div>
                    </div> 

    <?php
}
?>
                <!--                <div class="row mt10">
                                    <div class="col-md-3 col-xs-5" style="padding-right: 0px;">
                                        <span class="" href="#" >
                                            <img src="/img/avatars/1.jpg" class="img-thumbnail" width="45%"  height="auto" />
                                            <img src="/img/avatars/2.jpg" class="img-thumbnail" width="45%"  height="auto" />
                                        </span>
                                    </div>    
                                    <div class="col-md-9 col-xs-7" style="padding-left: 2px; padding-right: 0px;">
                                        <div class="row">
                                            <div class="col-md-11 col-xs-10" style="padding-top: 3px; padding-right: 4px;">
                
                                                <div class="progress progress-bar-xl" style="margin-bottom: 0px;">
                                                    <div id="divProgressBar" class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="5" style="width: 10%;">0%</div>
                                                </div>
                                                <span style="padding-top: 0px;">João e Maria</span>
                                            </div>
                                            <div class="col-md-1 col-xs-2" style="padding-left: 0px; padding-top: 3px; vertical-align: middle;">
                                                <button type="button" onclick="location.href = '/lancamentoLancarAtendimento';" class="btn btn-xs btn-primary" style="padding-top: 0px; padding-bottom: 0px;">
                                                    <i class="fa fa-plus" aria-hidden="true"></i>
                                                </button>
                                            </div>                           
                                        </div>  
                                    </div>
                                </div>     
                            </div>-->