<?php

use Cadastro\Form\ConstantesForm;
use Lancamento\Controller\Helper\ConstantesLancamento;


$tituloDaPagina = $this->translate(ConstantesForm::$TRADUCAO_CONFIRMACAO_EXCLUSAO);
$atendimento = $this->atendimento;
$pessoaLider = $this->pessoaLider;
echo $this->templateFormularioTopo($tituloDaPagina, ConstantesForm::$STRING_DIV_CONFIRMACAO);
?>
<div class="panel-body bg-light">
    <div class="section-divider">
        <span>
            <?php
                echo $this->translate(ConstantesForm::$TRADUCAO_PERGUNTA_EXCLUSAO_ATENDIMENTO);            
            ?>
        </span>
    </div>
    <div class="panel heading-border panel-danger">
        <div class="panel-body">
            
            
           
                    <address>
                        <div><strong>Dia do Atendimento:</strong></div>
                        <div><?php echo $atendimento->getDia(); ?></div>
                    </address>   
                    <address>
                        <div><strong>Quem Atendeu?</strong></div>
                        <div><?php echo $pessoaLider; ?></div>
                    </address>   
                    
        </div>                 
    </div>
    <div class="row">
        <div class="col-sm-12 col-xs-12">
            <div class="section text-center">
                <label class="option block mt15">
                    <input type="checkbox" name="checked" value="checked" onclick="
                            $('#divConfirmacao2').toggleClass('<?php echo ConstantesForm::$FORM_HIDDEN; ?>');
                           ">
                    <span class="checkbox"></span>
                    <?php
                   
                            echo ConstantesForm::$TRADUCAO_CIENCIA_EXCLUSAO_ATENDIMENTO;
                     
                    ?>
                </label> 
            </div>
        </div>
    </div>
    
    <div class="panel-footer text-right hidden" id="divConfirmacao2" style="height:65px;">
        <button type="button" onclick="location.href = '/lancamentoAtendimento';" class="btn ladda-button btn-default dark  mr10" data-style="zoom-in">
                    <span class="ladda-label">
                        <i class="fa fa-arrow-left" aria-hidden="true"></i> 
                        Voltar
                    </span>
                </button>
        <?php
        /* Botões */
        $labelConfirmar = $this->translate(ConstantesForm::$TRADUCAO_CONFIRMACAO);
        $stringNomeDaFuncaoOnClickConfimarExclusao = 'funcaoLancamento("' . ConstantesLancamento::$PAGINA_ATENDIMENTO_EXCLUSAO_CONFIRMACAO . '", ' . $atendimento->getId() . ')';

        echo $this->botaoLink($labelConfirmar, ConstantesForm::$STRING_HASHTAG, 0, $this->funcaoOnClick($stringNomeDaFuncaoOnClickConfimarExclusao));
        ?>      
    </div>
    <?php
    echo $this->templateFormularioRodape();
    