<?php

use Lancamento\Controller\Helper\ConstantesLancamento;
use Login\Controller\Helper\Constantes;

/**
 * Nome: cadastrar-pessoa.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com> e Sergio Bezerra da Silva <sergio.silva.unb@gmail.com>
 * Descricao: Página de cadastro de pessoa para tela de lançamento
 */
$form = $this->CadastrarPessoaForm;
$form->prepare();
$form->setAttribute(Constantes::$ACTION, $this->url(ConstantesLancamento::$ROUTE_LANCAMENTO, array(ConstantesLancamento::$PAGINA => ConstantesLancamento::$PAGINA_SALVAR_PESSOA)));
?>  
<div class="row background-mobile">
    <div id="content" class="animated fadeIn">
        <div class="row">
            <!-- Cadastro de Pessoa -->
            <div class="admin-form theme-danger tab-pane mw700 pl20 pr20" id="register1" role="tabpanel">
                <blockquote class="blockquote-danger">
                    <p><?php echo $this->translate(ConstantesLancamento::$TRADUCAO_NOVO_CADASTRO); ?></p>
                    <small><?php echo $this->translate(ConstantesLancamento::$TRADUCAO_NOVO_CADASTRO_LABEL); ?></small>
                </blockquote>
                <div class="panel panel-danger heading-border">
                    <?php echo $this->form()->openTag($form); ?>
                    <div class="panel-body p25">

                        <!-- Nome Input -->
                        <div class="section">
                            <?php echo $this->inputFormulario(ConstantesLancamento::$TRADUCAO_NOME, $form, ConstantesLancamento::$INPUT_NOME, ConstantesLancamento::$ICONE_USER); ?>
                        </div>
                        <!-- Telefone Input -->
                        <div class="row section">
                            <div class="col-xs-5 col-sm-5 col-md-2">
                                <?php echo $this->inputFormulario(ConstantesLancamento::$TRADUCAO_DDD, $form, ConstantesLancamento::$INPUT_DDD, ConstantesLancamento::$ICONE_PHONE); ?>
                            </div>
                            <div class="col-xs-7 col-sm-7 col-md-10">
                                <?php echo $this->inputFormulario(ConstantesLancamento::$TRADUCAO_TELEFONE, $form, ConstantesLancamento::$INPUT_TELEFONE, ConstantesLancamento::$ICONE_PHONE); ?>
                            </div>
                        </div>
                        <!-- Tipo Input Select --> 
                        <div class="section">
                            <label for="<?php echo ConstantesLancamento::$TRADUCAO_TIPO; ?>" class="field-label">
                                <?php echo $this->translate(ConstantesLancamento::$TRADUCAO_TIPO); ?>
                            </label>
                            <label for="<?php echo ConstantesLancamento::$TRADUCAO_TIPO; ?>" class="field prepend-icon">
                                <?php echo $this->formSelect($form->get(ConstantesLancamento::$INPUT_TIPO)); ?>
                            </label>    
                        </div> 
                        <!-- Tipo Input Radio --> 
                        <div id="ocultar_checkbox" class="mb15" style="display: none;">
                            <label for="<?php echo ConstantesLancamento::$TRADUCAO_NUCLEO_CELULA; ?>" class="field-label">
                                <?php echo $this->translate(ConstantesLancamento::$TRADUCAO_NUCLEO_CELULA); ?>
                            </label>
                            <div class="option-group field">
                                <?php echo $this->formRadio($form->get(ConstantesLancamento::$INPUT_NUCLEO_PERFEITO)); ?>
                            </div>
                        </div>
                    </div>
                    <!-- end .form-body section -->
                    <div class="panel-footer text-right">
                        <?php echo $this->formHidden($form->get(Constantes::$INPUT_CSRF)); ?>
                        <?php echo $this->botaoLink(Constantes::$TRADUCAO_VOLTAR, ConstantesLancamento::$ROUTE_LANCAMENTO, 2); ?>
                        <?php echo $this->botaoSubmit(ConstantesLancamento::$TRADUCAO_CADASTRAR, ConstantesLancamento::$CLASS_BTN_DANGER_DARK); ?>
                    </div>
                    <!-- end .form-footer section -->
                    <?php echo $this->form()->closeTag() ?>
                </div>
                <!-- end .admin-form section -->
            </div>
            <!-- end: .admin-form -->
        </div>
    </div>
</div>
<?php
/* Layout com javascript para tela de index */
echo $this->layoutJSCadastrarPessoaValidacao;
