<?php

use Lancamento\Controller\Helper\ConstantesLancamento;
use Login\Controller\Helper\Constantes;
 
/**
 * Nome: cadastrar-pessoa.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com> e Sergio Bezerra da Silva <sergio.silva.unb@gmail.com>
 * Descricao: Página de cadastro de pessoa para tela de lançamento
 */
$form = $this->CadastrarPessoaForm;
$form->prepare();
$form->setAttribute(Constantes::$ACTION, $this->url(ConstantesLancamento::$ROUTE_LANCAMENTO, array(Constantes::$ACTION => ConstantesLancamento::$ACTION_SALVAR_PESSOA)));
?> 
<div class="row background-mobile">
    <div id="content" class="animated fadeIn">
        <div class="row">

            <!-- Cadastro de Pessoa -->
            <div class="admin-form theme-danger tab-pane mw700 pl20 pr20" id="register1" role="tabpanel">
                <blockquote class="blockquote-danger">
                    <p><?php echo $this->translate(ConstantesLancamento::$TRADUCAO_NOVO_CADASTRO); ?></p>
                    <small><?php echo $this->translate(ConstantesLancamento::$TRADUCAO_NOVO_CADASTRO_LABEL); ?></small>
                </blockquote>
                <div class="panel panel-danger heading-border">
                    <?php echo $this->form()->openTag($form); ?>
                    <div class="panel-body p25">

                        <!-- Nome Input -->
                        <div class="section">
                            <label for="<?php echo ConstantesLancamento::$TRADUCAO_NOME; ?>" class="field-label">
                                <?php echo $this->translate(ConstantesLancamento::$TRADUCAO_NOME); ?>
                            </label>
                            <label for="<?php echo ConstantesLancamento::$TRADUCAO_NOME; ?>" class="field prepend-icon">
                                <?php echo $this->formInput($form->get(ConstantesLancamento::$INPUT_NOME)); ?>
                                <label for="<?php echo ConstantesLancamento::$TRADUCAO_NOME; ?>" class="field-icon">
                                    <i class="fa fa-user"></i>
                                </label>
                            </label>
                        </div>
                        <!-- Telefone Input -->
                        <div class="section">
                            <label for="<?php echo ConstantesLancamento::$TRADUCAO_TELEFONE; ?>" class="field-label">
                                <?php echo $this->translate(ConstantesLancamento::$TRADUCAO_TELEFONE); ?>
                            </label>
                            <label for="<?php echo ConstantesLancamento::$TRADUCAO_TELEFONE; ?>" class="field prepend-icon">
                                <?php echo $this->formInput($form->get(ConstantesLancamento::$INPUT_TELEFONE)); ?>
                                <label for="<?php echo ConstantesLancamento::$TRADUCAO_TELEFONE; ?>" class="field-icon">
                                    <i class="fa fa-phone-square"></i>
                                </label>
                            </label>
                        </div>
                        <!-- Tipo Input Select --> 
                        <div class="section">
                            <label for="<?php echo ConstantesLancamento::$TRADUCAO_TIPO; ?>" class="field-label">
                                <?php echo $this->translate(ConstantesLancamento::$TRADUCAO_TIPO); ?>
                            </label>
                            <?php
                            // renderiza html input
                            echo $this->formSelect($form->get(ConstantesLancamento::$INPUT_TIPO));
                            ?>
                        </div> 
                        <!-- Tipo Input Radio --> 
                        <div id="ocultar_checkbox" class="mb15" style="display: none;">
                            <label for="<?php echo ConstantesLancamento::$TRADUCAO_NUCLEO_CELULA; ?>" class="field-label">
                                <?php echo $this->translate(ConstantesLancamento::$TRADUCAO_NUCLEO_CELULA); ?>
                            </label>
                            <div class="option-group field">
                                <?php echo $this->formRadio($form->get(ConstantesLancamento::$INPUT_NUCLEO_PERFEITO)); ?>
                            </div>
                        </div>
                    </div>
                    <!-- end .form-body section -->
                    <div class="panel-footer text-right">
                        <button name="cancelar" id="cancelar" class="btn ladda-button btn-default dark" data-style="zoom-in" value="Back" onclick="location.href = '/'"><span class="ladda-label">Voltar</span><span class="ladda-spinner"></span></button>
                        <span>&nbsp;</span>
                        <?php echo $this->botaoSubmit('Nova Pessoa','btn-danger dark'); ?>
                    </div>
                    <!-- end .form-footer section -->
                    <?php echo $this->form()->closeTag() ?>
                </div>
                <!-- end .admin-form section -->
            </div>

            <!-- end: .admin-form -->
        </div>

        <!--        <div class="row">
                     Cadastro de Sub-Equipe / Alterno 
                    <div class="admin-form theme-danger tab-pane mw800 pl20 pr20" id="survey1" role="tabpanel">
                        <blockquote class="blockquote-danger">
                            <p>Cadastro Sub-Equipe/Alterno</p>
                            <small>Registro Convencional</small>
                        </blockquote>
                        <div class="panel panel-danger heading-border">
                            <form method="post" action="/" id="form-survey1">
                                <div class="panel-body p25">
                                    <div class="section-divider mv40">
                                        <span>Estado Civil</span>
                                    </div>
                                     .section-divider 
        
                                    <div class="section text-center">
                                        <div class="option-group field">
                                            <label for="tv" class="option">
                                                <input type="radio" name="reach" id="campos_casado" value="tv">
                                                <span class="radio" title="Com apenas 1 na igreja"></span>Solteiro / Casado</label>
                                            <label for="int" class="option">
                                                <input type="radio" name="reach" id="campos_solteiro" value="int">
                                                <span class="radio" title="Com ambos na igreja"></span>Casado</label>
                                        </div>
                                    </div>
                                     end .section section 
        
                                    <div class="section-divider mv40 disabled-section">
                                        <span>Endereço</span>
                                    </div>
                                     .section-divider 
        
                                    <div class="section row disabled-section">
                                        <div class="col-md-6">
                                            <div class="section">
                                                <label for="cep" class="field-label">CEP</label>
                                                <div class="smart-widget sm-right smr-50">
                                                    <label class="field">
                                                        <input type="text" name="cep" id="cep" class="gui-input" placeholder="CEP">
                                                    </label>
                                                    <button type="submit" class="button btn-danger">
                                                        <i class="fa fa-search"></i>
                                                    </button>
                                                </div>
                                                 end .smart-widget section 
                                            </div>
        
                                            <div class="section">
                                                <label for="city" class="field-label">Bairro</label>
                                                <label for="city" class="field">
                                                    <label class="field select prepend-icon">
                                                        <select id="country" name="country">
                                                            <option value="0">Selecione</option>
                                                            <option value="AC">Acre</option>
                                                            <option value="AL">Alagoas</option>
                                                            <option value="AP">Amapá</option>
                                                            <option value="AM">Amazonas</option>
                                                            <option value="BA">Bahia</option>
                                                            <option value="CE">Ceara</option>
                                                            <option value="DF">Distrito Federal</option>
                                                            <option value="ES">Espirito Santo</option>
                                                            <option value="GO">Goias</option>
                                                            <option value="MA">Maranhão</option>
                                                            <option value="MT">Mato Grosso</option>
                                                            <option value="MS">Mato Grosso do Sul</option>
                                                            <option value="MG">Minas Gerais</option>
                                                            <option value="PA">Pará</option>
                                                            <option value="PB">Paraíba</option>
                                                            <option value="PR">Parana</option>
                                                            <option value="PE">Pernambuco</option>
                                                            <option value="PI">Piauí</option>
                                                            <option value="RJ">Rio de Janeiro</option>
                                                            <option value="RN">Rio Grande do Norte</option>
                                                            <option value="RS">Rio Grande do Sul</option>
                                                            <option value="RO">Rondonia</option>
                                                            <option value="RR">Roraima</option>
                                                            <option value="SC">Santa Catarina</option>
                                                            <option value="SP">São Paulo</option>
                                                            <option value="SE">Sergipe</option>
                                                        </select>
                                                        <i class="arrow double"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
        
                                        </div>
                                         end .colm section 
        
                                        <div class="col-md-6">
                                            <div class="section">
                                                <label for="mobile" class="field-label">UF</label>
                                                <label class="field select prepend-icon">
                                                    <select id="country" name="country">
                                                        <option value="0">Selecione</option>
                                                        <option value="AC">Acre</option>
                                                        <option value="AL">Alagoas</option>
                                                        <option value="AP">Amapá</option>
                                                        <option value="AM">Amazonas</option>
                                                        <option value="BA">Bahia</option>
                                                        <option value="CE">Ceara</option>
                                                        <option value="DF">Distrito Federal</option>
                                                        <option value="ES">Espirito Santo</option>
                                                        <option value="GO">Goias</option>
                                                        <option value="MA">Maranhão</option>
                                                        <option value="MT">Mato Grosso</option>
                                                        <option value="MS">Mato Grosso do Sul</option>
                                                        <option value="MG">Minas Gerais</option>
                                                        <option value="PA">Pará</option>
                                                        <option value="PB">Paraíba</option>
                                                        <option value="PR">Parana</option>
                                                        <option value="PE">Pernambuco</option>
                                                        <option value="PI">Piauí</option>
                                                        <option value="RJ">Rio de Janeiro</option>
                                                        <option value="RN">Rio Grande do Norte</option>
                                                        <option value="RS">Rio Grande do Sul</option>
                                                        <option value="RO">Rondonia</option>
                                                        <option value="RR">Roraima</option>
                                                        <option value="SC">Santa Catarina</option>
                                                        <option value="SP">São Paulo</option>
                                                        <option value="SE">Sergipe</option>
                                                    </select>
                                                    <i class="arrow double"></i>
                                                </label>
                                            </div>
                                             end section 
        
                                            <div class="section">
                                                <label for="city" class="field-label">Cidade</label>
                                                <label for="city" class="field prepend-icon">
                                                    <label class="field select prepend-icon">
                                                        <select id="country" name="country">
                                                            <option value="0">Selecione</option>
                                                            <option value="AC">Acre</option>
                                                            <option value="AL">Alagoas</option>
                                                            <option value="AP">Amapá</option>
                                                            <option value="AM">Amazonas</option>
                                                            <option value="BA">Bahia</option>
                                                            <option value="CE">Ceara</option>
                                                            <option value="DF">Distrito Federal</option>
                                                            <option value="ES">Espirito Santo</option>
                                                            <option value="GO">Goias</option>
                                                            <option value="MA">Maranhão</option>
                                                            <option value="MT">Mato Grosso</option>
                                                            <option value="MS">Mato Grosso do Sul</option>
                                                            <option value="MG">Minas Gerais</option>
                                                            <option value="PA">Pará</option>
                                                            <option value="PB">Paraíba</option>
                                                            <option value="PR">Parana</option>
                                                            <option value="PE">Pernambuco</option>
                                                            <option value="PI">Piauí</option>
                                                            <option value="RJ">Rio de Janeiro</option>
                                                            <option value="RN">Rio Grande do Norte</option>
                                                            <option value="RS">Rio Grande do Sul</option>
                                                            <option value="RO">Rondonia</option>
                                                            <option value="RR">Roraima</option>
                                                            <option value="SC">Santa Catarina</option>
                                                            <option value="SP">São Paulo</option>
                                                            <option value="SE">Sergipe</option>
                                                        </select>
                                                        <i class="arrow double"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
        
                                        </div>
                                         end .colm section 
        
                                        <div class="col-md-12">
                                            <div class="section">
                                                <label for="firstaddr" class="field-label">Logradouro</label>
                                                <label for="firstaddr" class="field prepend-icon">
                                                    <input type="text" name="firstaddr" id="firstaddr" class="gui-input" placeholder="Logradouro">
                                                    <label for="firstaddr" class="field-icon">
                                                        <i class="fa fa-map-marker"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
                                        </div>
        
                                        <div class="col-md-12">
                                            <div class="section">
                                                <label for="firstaddr" class="field-label">Complemento</label>
                                                <label for="firstaddr" class="field prepend-icon">
                                                    <input type="text" name="firstaddr" id="firstaddr" class="gui-input" placeholder="Complemento">
                                                    <label for="firstaddr" class="field-icon">
                                                        <i class="fa fa-location-arrow"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
                                        </div>
        
                                    </div>
                                     end .section row section 
                                    <div id="ocultar_dados">
        
                                        <div class="section-divider mv40">
                                            <span>Dados Pessoais</span>
                                        </div>
                                         .section-divider 
        
                                        <div class="section row">
                                            <div class="col-md-6">
                                                <div class="section">
                                                    <label for="cep" class="field-label">CPF</label>
                                                    <div class="smart-widget sm-right smr-50">
                                                        <label class="field">
                                                            <input type="text" name="cep" id="cep" class="gui-input" placeholder="Informe seu CPF">
                                                        </label>
                                                        <button type="submit" class="button btn-danger">
                                                            <i class="fa fa-search"></i>
                                                        </button>
                                                    </div>
                                                     end .smart-widget section 
                                                </div>
        
                                            </div>
                                             end .colm section 
        
                                            <div class="col-md-6">
                                                <div class="section">
                                                    <label for="mobile" class="field-label">Sexo</label>
                                                    <div style="width:100%; padding-bottom:5px;"></div>
                                                    <div class="section">
                                                        <div class="option-group field">
                                                            <label for="tv" class="option">
                                                                <input type="radio" name="reach" id="tv" value="tv">
                                                                <span class="radio"></span>Masculino</label>
                                                            <label for="int" class="option">
                                                                <input type="radio" name="reach" id="int" value="int">
                                                                <span class="radio"></span>Feminino</label>
                                                        </div>
                                                    </div>
                                                     end .section section 
                                                </div>
                                                 end section 
        
                                            </div>
                                             end .colm section 
        
                                            <div class="col-md-12">
                                                <div class="section">
                                                    <label for="firstaddr" class="field-label">Nome Completo</label>
                                                    <label for="firstaddr" class="field prepend-icon">
                                                        <input type="text" name="firstaddr" id="firstaddr" class="gui-input" placeholder="Nome Completo">
                                                        <label for="firstaddr" class="field-icon">
                                                            <i class="fa fa-terminal"></i>
                                                        </label>
                                                    </label>
                                                </div>
                                                 end section 
                                            </div>
        
                                            <div class="col-md-6">
                                                <div class="section">
                                                    <label for="firstaddr" class="field-label">Data de Nascimento</label>
                                                    <label for="datepicker1" class="field prepend-icon">
                                                        <input type="text" id="datepicker1" name="datepicker1" class="gui-input" placeholder="Data de Nascimento">
                                                        <label class="field-icon">
                                                            <i class="fa fa-calendar-o"></i>
                                                        </label>
                                                    </label>
                                                </div>
                                                 end section 
        
                                                <div class="section">
                                                    <label for="mobile" class="field-label">Telefone Celular</label>
                                                    <label for="mobile" class="field prepend-icon">
                                                        <input type="tel" name="mobile" id="mobile" class="gui-input phone" placeholder="Telefone Celular" required="required">
                                                        <label for="mobile" class="field-icon">
                                                            <i class="fa fa-phone-square"></i>
                                                        </label>
                                                    </label>
                                                </div>
                                                 end section 
        
                                                <div class="section">
                                                    <label for="mobile" class="field-label">Repita o Email</label>
                                                    <label for="useremail" class="field prepend-icon">
                                                        <input type="email" name="useremail" id="useremail" class="gui-input" placeholder="Repita o Email">
                                                        <label for="useremail" class="field-icon">
                                                            <i class="fa fa-envelope"></i>
                                                        </label>
                                                    </label>
                                                </div>
                                                 end section 
        
                                                <div class="section">
                                                    <label for="city" class="field-label">Profissão</label>
                                                    <label for="city" class="field">
                                                        <label class="field select">
                                                            <select id="country" name="profissao">
                                                                <option value="0">Selecione</option>
                                                                <option value="1">Líder em Treinamento</option>
                                                                <option value="2">Alterno</option>
                                                                <option value="3">Co-Líder</option>
                                                                <option value="4">Outro</option>
                                                            </select>
                                                            <i class="arrow"></i>
                                                        </label>
                                                    </label>
                                                </div>
                                                 end section 
                                            </div>
        
                                            <div class="col-md-6">
                                                <div class="section">
                                                    <label for="mobile" class="field-label">Telefone Residencial</label>
                                                    <label for="mobile" class="field prepend-icon">
                                                        <input type="tel" name="mobile" id="mobile" class="gui-input phone" placeholder="Telefone Residencial" required="required">
                                                        <label for="mobile" class="field-icon">
                                                            <i class="fa fa-phone-square"></i>
                                                        </label>
                                                    </label>
                                                </div>
                                                 end section 
        
                                                <div class="section">
                                                    <label for="mobile" class="field-label">Email</label>
                                                    <label for="useremail" class="field prepend-icon">
                                                        <input type="email" name="useremail" id="useremail" class="gui-input" placeholder="Email">
                                                        <label for="useremail" class="field-icon">
                                                            <i class="fa fa-envelope"></i>
                                                        </label>
                                                    </label>
                                                </div>
                                                 end section 
        
                                                <div class="section">
                                                    <label for="city" class="field-label">Hierarquia</label>
                                                    <label for="city" class="field">
                                                        <label class="field select">
                                                            <select id="country" name="country">
                                                                <option value="0">Selecione</option>
                                                                <option value="1">Líder em Treinamento</option>
                                                                <option value="2">Alterno</option>
                                                                <option value="3">Co-Líder</option>
                                                                <option value="4">Outro</option>
                                                            </select>
                                                            <i class="arrow"></i>
                                                        </label>
                                                    </label>
                                                </div>
                                                 end section 
        
                                                <div class="section">
                                                    <label for="mobile" class="field-label">Endereço Local de Trabalho</label>
                                                    <label for="useremail" class="field prepend-icon">
                                                        <input type="email" name="useremail" id="useremail" class="gui-input" placeholder="Endereço Local de Trabalho">
                                                        <label for="useremail" class="field-icon">
                                                            <i class="fa fa-map-marker"></i>
                                                        </label>
                                                    </label>
                                                </div>
                                                 end section 
                                            </div>
        
                                        </div>
                                    </div>
        
                                     end .section row section 
                                    <div id="ocultar_aluno">
                                        <div class="section-divider mv40">
                                            <span>Selecione um aluno para cadastro</span>
                                        </div>
                                         .section-divider 
        
                                        <div class="col-md-12">
                                            <div class="section row text-center">
                                                <button type="button" class="btn disabled btn-default btn-block">Não existem alunos registrados.</button>
                                            </div>
                                            <div class="section row">
                                                <label for="city" class="field-label">Aluno do IV</label>
                                                <label for="city" class="field">
                                                    <label class="field select">
                                                        <select id="country" name="country">
                                                            <option value="0">Selecione</option>
                                                            <option value="1">Sérgio Bezerra da Silva</option>
                                                            <option value="2">Francisco da Silva</option>
                                                            <option value="3">Rômulo Sem Rumo</option>
                                                            <option value="4">Vivian Xavier</option>
                                                        </select>
                                                        <i class="arrow"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
                                        </div>
                                    </div>
                                     end .section section 
        
                                </div>
                                 end .form-body section 
                                <div class="panel-footer text-right">
                                    <button type="submit" class="btn btn-danger">Avançar</button>
                                </div>
                                 end .form-footer section 
                            </form>
                        </div>
                         end .admin-form section 
                    </div>
                     end: .admin-form 
                </div>
        
                <div class="row">
                     Cadastro de Responsável 
                    <div class="admin-form theme-success tab-pane mw800 pl20 pr20" id="survey1" role="tabpanel">
                        <blockquote class="blockquote-success">
                            <p>Cadastro Responsável</p>
                            <small>Registro Convencional</small>
                        </blockquote>
                        <div class="panel panel-success heading-border">
                            <form method="post" action="/" id="form-survey1">
                                <div class="panel-body p25">
                                    <div class="section-divider mv40">
                                        <span>Dados Pessoais</span>
                                    </div>
                                     .section-divider 
        
                                    <div class="section row">
                                        <div class="col-md-6">
                                            <div class="section">
                                                <label for="cep" class="field-label">CPF</label>
                                                <div class="smart-widget sm-right smr-50">
                                                    <label class="field">
                                                        <input type="text" name="cep" id="cep" class="gui-input" placeholder="Informe seu CPF">
                                                    </label>
                                                    <button type="submit" class="button btn-success">
                                                        <i class="fa fa-search"></i>
                                                    </button>
                                                </div>
                                                 end .smart-widget section 
                                            </div>
        
                                        </div>
                                         end .colm section 
        
                                        <div class="col-md-6">
                                            <div class="section">
                                                <label for="mobile" class="field-label">Sexo</label>
                                                <div style="width:100%; padding-bottom:5px;"></div>
                                                <div class="section">
                                                    <div class="option-group field">
                                                        <label for="tv" class="option">
                                                            <input type="radio" name="reach" id="tv" value="tv">
                                                            <span class="radio"></span>Masculino</label>
                                                        <label for="int" class="option">
                                                            <input type="radio" name="reach" id="int" value="int">
                                                            <span class="radio"></span>Feminino</label>
                                                    </div>
                                                </div>
                                                 end .section section 
                                            </div>
                                             end section 
        
                                        </div>
                                         end .colm section 
        
                                        <div class="col-md-12">
                                            <div class="section">
                                                <label for="firstaddr" class="field-label">Nome Completo</label>
                                                <label for="firstaddr" class="field prepend-icon">
                                                    <input type="text" name="firstaddr" id="firstaddr" class="gui-input" placeholder="Nome Completo">
                                                    <label for="firstaddr" class="field-icon">
                                                        <i class="fa fa-terminal"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
                                        </div>
        
                                        <div class="col-md-6">
                                            <div class="section">
                                                <label for="firstaddr" class="field-label">Data de Nascimento</label>
                                                <label for="datepicker1" class="field prepend-icon">
                                                    <input type="text" id="datepicker1" name="datepicker1" class="gui-input" placeholder="Data de Nascimento">
                                                    <label class="field-icon">
                                                        <i class="fa fa-calendar-o"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
        
                                            <div class="section">
                                                <label for="mobile" class="field-label">Telefone Celular</label>
                                                <label for="mobile" class="field prepend-icon">
                                                    <input type="tel" name="mobile" id="mobile" class="gui-input phone" placeholder="Telefone Celular" required="required">
                                                    <label for="mobile" class="field-icon">
                                                        <i class="fa fa-phone-square"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
        
                                            <div class="section">
                                                <label for="mobile" class="field-label">Repita o Email</label>
                                                <label for="useremail" class="field prepend-icon">
                                                    <input type="email" name="useremail" id="useremail" class="gui-input" placeholder="Repita o Email">
                                                    <label for="useremail" class="field-icon">
                                                        <i class="fa fa-envelope"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
        
                                            <div class="section">
                                                <label for="city" class="field-label">Profissão</label>
                                                <label for="city" class="field">
                                                    <label class="field select">
                                                        <select id="country" name="profissao">
                                                            <option value="0">Selecione</option>
                                                            <option value="1">Líder em Treinamento</option>
                                                            <option value="2">Alterno</option>
                                                            <option value="3">Co-Líder</option>
                                                            <option value="4">Outro</option>
                                                        </select>
                                                        <i class="arrow"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
                                        </div>
        
                                        <div class="col-md-6">
                                            <div class="section">
                                                <label for="mobile" class="field-label">Telefone Residencial</label>
                                                <label for="mobile" class="field prepend-icon">
                                                    <input type="tel" name="mobile" id="mobile" class="gui-input phone" placeholder="Telefone Residencial" required="required">
                                                    <label for="mobile" class="field-icon">
                                                        <i class="fa fa-phone-square"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
        
                                            <div class="section">
                                                <label for="mobile" class="field-label">Email</label>
                                                <label for="useremail" class="field prepend-icon">
                                                    <input type="email" name="useremail" id="useremail" class="gui-input" placeholder="Email">
                                                    <label for="useremail" class="field-icon">
                                                        <i class="fa fa-envelope"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
        
                                            <div class="section">
                                                <label for="city" class="field-label">Hierarquia</label>
                                                <label for="city" class="field">
                                                    <label class="field select">
                                                        <select id="country" name="country">
                                                            <option value="0">Selecione</option>
                                                            <option value="1">Líder em Treinamento</option>
                                                            <option value="2">Alterno</option>
                                                            <option value="3">Co-Líder</option>
                                                            <option value="4">Outro</option>
                                                        </select>
                                                        <i class="arrow"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
        
                                            <div class="section">
                                                <label for="mobile" class="field-label">Endereço Local de Trabalho</label>
                                                <label for="useremail" class="field prepend-icon">
                                                    <input type="email" name="useremail" id="useremail" class="gui-input" placeholder="Endereço Local de Trabalho">
                                                    <label for="useremail" class="field-icon">
                                                        <i class="fa fa-map-marker"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
                                        </div>
        
                                    </div>
                                     end .section row section 
        
                                    <div class="section-divider mv40">
                                        <span>Selecione um aluno para cadastro</span>
                                    </div>
                                     .section-divider 
        
                                    <div class="col-md-12">
                                        <div class="section row text-center">
                                            <button type="button" class="btn disabled btn-default btn-block">Não existem alunos registrados.</button>
                                        </div>
                                        <div class="section row">
                                            <label for="city" class="field-label">Aluno do IV</label>
                                            <label for="city" class="field">
                                                <label class="field select">
                                                    <select id="country" name="country">
                                                        <option value="0">Selecione</option>
                                                        <option value="1">Sérgio Bezerra da Silva</option>
                                                        <option value="2">Francisco da Silva</option>
                                                        <option value="3">Rômulo Sem Rumo</option>
                                                        <option value="4">Vivian Xavier</option>
                                                    </select>
                                                    <i class="arrow"></i>
                                                </label>
                                            </label>
                                        </div>
                                         end section 
                                    </div>
        
                                </div>
                                 end .form-body section 
                                <div class="panel-footer text-right">
                                    <button type="button" name="cancelar" id="cancelar" class="btn ladda-button btn-default dark" data-style="zoom-in" value="Back" onclick="location.href = '/'"><span class="ladda-label">Cancelar</span><span class="ladda-spinner"></span></button>
                                    <button type="submit" class="btn btn-success">Cadastrar</button>
                                </div>
                                 end .form-footer section 
                            </form>
                        </div>
                         end .admin-form section 
                    </div>
                     end: .admin-form 
                </div>
        
                <div class="row">
                     Cadastro de Responsável 
                    <div class="admin-form theme-primary tab-pane mw800 pl20 pr20" id="survey1" role="tabpanel">
                        <blockquote class="blockquote-primary">
                            <p>Cadastro Responsável</p>
                            <small>Masculino</small>
                        </blockquote>
                        <div class="panel panel-primary heading-border">
                            <form method="post" action="/" id="form-survey1">
                                <div class="panel-body p25">
                                    <div class="section-divider mv40">
                                        <span>Dados Pessoais</span>
                                    </div>
                                     .section-divider 
        
                                    <div class="section row">
                                        <div class="col-md-6">
                                            <div class="section">
                                                <label for="cep" class="field-label">CPF</label>
                                                <div class="smart-widget sm-right smr-50">
                                                    <label class="field">
                                                        <input type="text" name="cep" id="cep" class="gui-input" placeholder="Informe seu CPF">
                                                    </label>
                                                    <button type="submit" class="button btn-primary">
                                                        <i class="fa fa-search"></i>
                                                    </button>
                                                </div>
                                                 end .smart-widget section 
                                            </div>
        
                                        </div>
                                         end .colm section 
        
                                        <div class="col-md-6">
                                            <div class="section">
                                                <label for="mobile" class="field-label">Sexo</label>
                                                <div style="width:100%; padding-bottom:5px;"></div>
                                                <div class="section">
                                                    <div class="option-group field">
                                                        <label for="tv" class="option">
                                                            <input type="radio" name="reach" id="tv" value="tv" checked="checked" disabled>
                                                            <span class="radio"></span>Masculino</label>
                                                        <label for="int" class="option">
                                                            <input type="radio" name="reach" id="int" value="int" disabled>
                                                            <span class="radio"></span>Feminino</label>
                                                    </div>
                                                </div>
                                                 end .section section 
                                            </div>
                                             end section 
        
                                        </div>
                                         end .colm section 
        
                                        <div class="col-md-12">
                                            <div class="section">
                                                <label for="firstaddr" class="field-label">Nome Completo</label>
                                                <label for="firstaddr" class="field prepend-icon">
                                                    <input type="text" name="firstaddr" id="firstaddr" class="gui-input" placeholder="Nome Completo">
                                                    <label for="firstaddr" class="field-icon">
                                                        <i class="fa fa-terminal"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
                                        </div>
        
                                        <div class="col-md-6">
                                            <div class="section">
                                                <label for="firstaddr" class="field-label">Data de Nascimento</label>
                                                <label for="datepicker1" class="field prepend-icon">
                                                    <input type="text" id="datepicker1" name="datepicker1" class="gui-input" placeholder="Data de Nascimento">
                                                    <label class="field-icon">
                                                        <i class="fa fa-calendar-o"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
        
                                            <div class="section">
                                                <label for="mobile" class="field-label">Telefone Celular</label>
                                                <label for="mobile" class="field prepend-icon">
                                                    <input type="tel" name="mobile" id="mobile" class="gui-input phone" placeholder="Telefone Celular" required="required">
                                                    <label for="mobile" class="field-icon">
                                                        <i class="fa fa-phone-square"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
        
                                            <div class="section">
                                                <label for="mobile" class="field-label">Repita o Email</label>
                                                <label for="useremail" class="field prepend-icon">
                                                    <input type="email" name="useremail" id="useremail" class="gui-input" placeholder="Repita o Email">
                                                    <label for="useremail" class="field-icon">
                                                        <i class="fa fa-envelope"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
        
                                            <div class="section">
                                                <label for="city" class="field-label">Profissão</label>
                                                <label for="city" class="field">
                                                    <label class="field select">
                                                        <select id="country" name="profissao">
                                                            <option value="0">Selecione</option>
                                                            <option value="1">Líder em Treinamento</option>
                                                            <option value="2">Alterno</option>
                                                            <option value="3">Co-Líder</option>
                                                            <option value="4">Outro</option>
                                                        </select>
                                                        <i class="arrow"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
                                        </div>
        
                                        <div class="col-md-6">
                                            <div class="section">
                                                <label for="mobile" class="field-label">Telefone Residencial</label>
                                                <label for="mobile" class="field prepend-icon">
                                                    <input type="tel" name="mobile" id="mobile" class="gui-input phone" placeholder="Telefone Residencial" required="required">
                                                    <label for="mobile" class="field-icon">
                                                        <i class="fa fa-phone-square"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
        
                                            <div class="section">
                                                <label for="mobile" class="field-label">Email</label>
                                                <label for="useremail" class="field append-icon">
                                                    <input type="email" name="useremail" id="useremail" class="gui-input" placeholder="Email" style="background:#ddd;">
                                                    <b class="tooltip tip-right-top"><em> I am a top right aligned tooltip! Pretty useful huh.</em></b>
                                                    <label for="useremail" class="field-icon">
                                                        <i class="fa">
                                                            <img src="/img/bars.svg" style="width:16px;" />
                                                        </i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
        
                                            <div class="section">
                                                <label for="city" class="field-label">Hierarquia</label>
                                                <label for="city" class="field">
                                                    <label class="field select">
                                                        <select id="country" name="country">
                                                            <option value="0">Selecione</option>
                                                            <option value="1">Líder em Treinamento</option>
                                                            <option value="2">Alterno</option>
                                                            <option value="3">Co-Líder</option>
                                                            <option value="4">Outro</option>
                                                        </select>
                                                        <i class="arrow"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
        
                                            <div class="section">
                                                <label for="mobile" class="field-label">Endereço Local de Trabalho</label>
                                                <label for="useremail" class="field prepend-icon">
                                                    <input type="email" name="useremail" id="useremail" class="gui-input" placeholder="Endereço Local de Trabalho">
                                                    <label for="useremail" class="field-icon">
                                                        <i class="fa fa-map-marker"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
                                        </div>
        
                                    </div>
                                     end .section row section 
        
                                    <div class="section-divider mv40">
                                        <span>Selecione um aluno para cadastro</span>
                                    </div>
                                     .section-divider 
        
                                    <div class="col-md-12">
                                        <div class="section row">
                                            <label for="city" class="field-label">Aluno do IV</label>
                                            <label for="city" class="field">
                                                <label class="field select">
                                                    <select id="country" name="country">
                                                        <option value="0">Selecione</option>
                                                        <option value="1">Sérgio Bezerra da Silva</option>
                                                        <option value="2">Francisco da Silva</option>
                                                        <option value="3">Rômulo Sem Rumo</option>
                                                        <option value="4">Vivian Xavier</option>
                                                    </select>
                                                    <i class="arrow"></i>
                                                </label>
                                            </label>
                                        </div>
                                         end section 
                                    </div>
        
                                </div>
                                 end .form-body section 
                                <div class="panel-footer text-right">
                                    <button type="button" name="cancelar" id="cancelar" class="btn ladda-button btn-default dark" data-style="zoom-in" value="Back" onclick="location.href = '/'"><span class="ladda-label">Cancelar</span><span class="ladda-spinner"></span></button>
                                    <button type="submit" class="btn btn-primary">Cadastrar</button>
                                </div>
                                 end .form-footer section 
                            </form>
                        </div>
                         end .admin-form section 
                    </div>
                     end: .admin-form 
                </div>
        
                <div class="row">
                     Cadastro de Responsável 
                    <div class="admin-form theme-warning tab-pane mw800 pl20 pr20" id="survey1" role="tabpanel">
                        <blockquote class="blockquote-warning">
                            <p>Cadastro Responsável</p>
                            <small>Feminino</small>
                        </blockquote>
                        <div class="panel panel-warning heading-border">
                            <form method="post" action="/" id="form-survey1">
                                <div class="panel-body p25">
                                    <div class="section-divider mv40">
                                        <span>Dados Pessoais</span>
                                    </div>
                                     .section-divider 
        
                                    <div class="section row">
                                        <div class="col-md-6">
                                            <div class="section">
                                                <label for="cep" class="field-label">CPF</label>
                                                <div class="smart-widget sm-right smr-50">
                                                    <label class="field">
                                                        <input type="text" name="cep" id="cep" class="gui-input" placeholder="Informe seu CPF">
                                                    </label>
                                                    <button type="submit" class="button btn-warning">
                                                        <i class="fa fa-search"></i>
                                                    </button>
                                                </div>
                                                 end .smart-widget section 
                                            </div>
        
                                        </div>
                                         end .colm section 
        
                                        <div class="col-md-6">
                                            <div class="section">
                                                <label for="mobile" class="field-label">Sexo</label>
                                                <div style="width:100%; padding-bottom:5px;"></div>
                                                <div class="section">
                                                    <div class="option-group field">
                                                        <label for="tv" class="option">
                                                            <input type="radio" name="reach" id="tv" value="tv" disabled>
                                                            <span class="radio"></span>Masculino</label>
                                                        <label for="int" class="option">
                                                            <input type="radio" name="reach" id="int" value="int" checked="checked" disabled>
                                                            <span class="radio"></span>Feminino</label>
                                                    </div>
                                                </div>
                                                 end .section section 
                                            </div>
                                             end section 
        
                                        </div>
                                         end .colm section 
        
                                        <div class="col-md-12">
                                            <div class="section">
                                                <label for="firstaddr" class="field-label">Nome Completo</label>
                                                <label for="firstaddr" class="field prepend-icon">
                                                    <input type="text" name="firstaddr" id="firstaddr" class="gui-input" placeholder="Nome Completo">
                                                    <label for="firstaddr" class="field-icon">
                                                        <i class="fa fa-terminal"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
                                        </div>
        
                                        <div class="col-md-6">
                                            <div class="section">
                                                <label for="firstaddr" class="field-label">Data de Nascimento</label>
                                                <label for="datepicker1" class="field prepend-icon">
                                                    <input type="text" id="datepicker1" name="datepicker1" class="gui-input" placeholder="Data de Nascimento">
                                                    <label class="field-icon">
                                                        <i class="fa fa-calendar-o"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
        
                                            <div class="section">
                                                <label for="mobile" class="field-label">Telefone Celular</label>
                                                <label for="mobile" class="field prepend-icon">
                                                    <input type="tel" name="mobile" id="mobile" class="gui-input phone" placeholder="Telefone Celular" required="required">
                                                    <label for="mobile" class="field-icon">
                                                        <i class="fa fa-phone-square"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
        
                                            <div class="section">
                                                <label for="mobile" class="field-label">Repita o Email</label>
                                                <label for="useremail" class="field prepend-icon">
                                                    <input type="email" name="useremail" id="useremail" class="gui-input" placeholder="Repita o Email">
                                                    <label for="useremail" class="field-icon">
                                                        <i class="fa fa-envelope"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
        
                                            <div class="section">
                                                <label for="city" class="field-label">Profissão</label>
                                                <label for="city" class="field">
                                                    <label class="field select">
                                                        <select id="country" name="profissao">
                                                            <option value="0">Selecione</option>
                                                            <option value="1">Líder em Treinamento</option>
                                                            <option value="2">Alterno</option>
                                                            <option value="3">Co-Líder</option>
                                                            <option value="4">Outro</option>
                                                        </select>
                                                        <i class="arrow"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
                                        </div>
        
                                        <div class="col-md-6">
                                            <div class="section">
                                                <label for="mobile" class="field-label">Telefone Residencial</label>
                                                <label for="mobile" class="field prepend-icon">
                                                    <input type="tel" name="mobile" id="mobile" class="gui-input phone" placeholder="Telefone Residencial" required="required">
                                                    <label for="mobile" class="field-icon">
                                                        <i class="fa fa-phone-square"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
        
                                            <div class="section">
                                                <label for="mobile" class="field-label">Email</label>
                                                <label for="useremail" class="field append-icon">
                                                    <input type="email" name="useremail" id="useremail" class="gui-input" placeholder="Email" style="background:#ddd;">
                                                    <b class="tooltip tip-right-top"><em> I am a top right aligned tooltip! Pretty useful huh.</em></b>
                                                    <label for="useremail" class="field-icon">
                                                        <i class="fa">
                                                            <img src="/img/bars.svg" style="width:16px; fill:#bbb;" />
                                                        </i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
        
                                            <div class="section">
                                                <label for="city" class="field-label">Hierarquia</label>
                                                <label for="city" class="field">
                                                    <label class="field select">
                                                        <select id="country" name="country">
                                                            <option value="0">Selecione</option>
                                                            <option value="1">Líder em Treinamento</option>
                                                            <option value="2">Alterno</option>
                                                            <option value="3">Co-Líder</option>
                                                            <option value="4">Outro</option>
                                                        </select>
                                                        <i class="arrow"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
        
                                            <div class="section">
                                                <label for="mobile" class="field-label">Endereço Local de Trabalho</label>
                                                <label for="useremail" class="field prepend-icon">
                                                    <input type="email" name="useremail" id="useremail" class="gui-input" placeholder="Endereço Local de Trabalho">
                                                    <label for="useremail" class="field-icon">
                                                        <i class="fa fa-map-marker"></i>
                                                    </label>
                                                </label>
                                            </div>
                                             end section 
                                        </div>
        
                                    </div>
                                     end .section row section 
        
                                    <div class="section-divider mv40">
                                        <span>Selecione um aluno para cadastro</span>
                                    </div>
                                     .section-divider 
        
                                    <div class="col-md-12">
                                        <div class="section row text-center">
                                            <button type="button" class="btn disabled btn-default btn-block">Não existem alunos registrados.</button>
                                        </div>
                                        <div class="section row">
                                            <label for="city" class="field-label">Aluno do IV</label>
                                            <label for="city" class="field">
                                                <label class="field select">
                                                    <select id="country" name="country">
                                                        <option value="0">Selecione</option>
                                                        <option value="1">Sérgio Bezerra da Silva</option>
                                                        <option value="2">Francisco da Silva</option>
                                                        <option value="3">Rômulo Sem Rumo</option>
                                                        <option value="4">Vivian Xavier</option>
                                                    </select>
                                                    <i class="arrow"></i>
                                                </label>
                                            </label>
                                        </div>
                                         end section 
                                    </div>
        
                                </div>
                                 end .form-body section 
                                <div class="panel-footer text-right">
                                    <button type="button" name="cancelar" id="cancelar" class="btn ladda-button btn-default dark" data-style="zoom-in" value="Back" onclick="location.href = '/'"><span class="ladda-label">Cancelar</span><span class="ladda-spinner"></span></button>
                                    <button type="submit" class="btn btn-warning">Cadastrar</button>
                                </div>
                                 end .form-footer section 
                            </form>
                        </div>
                         end .admin-form section 
                    </div>
                     end: .admin-form 
                </div>-->
    </div>
</div>

<svg fill="#bbb" width="16" height="16" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"></svg>
<script type="text/javascript" src="/js/vendor/plugins/jquerymask/jquery.maskedinput.min.js"></script>
<script src="assets/admin-tools/admin-forms/js/jquery-ui-datepicker.min.js"></script>
<script type="text/javascript" src="/js/circuito_da_visao/ocultar-campos-formularios.js?v=1.0"></script>
<script type="text/javascript">
                            window.onload = initPage;
                            function initPage() {
                                // Init jQuery Masked inputs
                                $('.phone').mask('(99)99999-9999');
                            }

                            /* @custom validation method (smartCaptcha) 
                             ------------------------------------------------------------------ */

                            $.validator.methods.smartCaptcha = function (value, element, param) {
                                return value == param;
                            };

                            $("#admin-form").validate({
                                /* @validation states + elements 
                                 ------------------------------------------- */

                                errorClass: "state-error",
                                validClass: "state-success",
                                errorElement: "em",
                                /* @validation rules 
                                 ------------------------------------------ */

                                rules: {
                                    firstname: {
                                        required: true
                                    },
                                    lastname: {
                                        required: true
                                    },
                                    useremail: {
                                        required: true,
                                        email: true
                                    },
                                    website: {
                                        required: true,
                                        url: true
                                    },
                                    language: {
                                        required: true
                                    },
                                    upload1: {
                                        required: true,
                                        extension: "jpg|png|gif|jpeg|doc|docx|pdf|xls|rar|zip"
                                    },
                                    mobileos: {
                                        required: true
                                    }, comment: {
                                        required: true,
                                        minlength: 30
                                    },
                                    mobile_phone: {
                                        require_from_group: [1, ".phone-group"]
                                    },
                                    home_phone: {
                                        require_from_group: [1, ".phone-group"]
                                    },
                                    password: {
                                        required: true,
                                        minlength: 6,
                                        maxlength: 16
                                    },
                                    repeatPassword: {
                                        required: true,
                                        minlength: 6,
                                        maxlength: 16, equalTo: '#password'
                                    },
                                    gender: {
                                        required: true
                                    },
                                    languages: {
                                        required: true
                                    },
                                    verification: {
                                        required: true,
                                        smartCaptcha: 19
                                    },
                                    applicant_age: {
                                        required: true,
                                        min: 16
                                    },
                                    licence_no: {
                                        required: function (element) {
                                            return $("#applicant_age").val() > 19;
                                        }
                                    },
                                    child_name: {required: "#parents:checked"
                                    }

                                },
                                /* @validation error messages 
                                 ---------------------------------------------- */

                                messages: {
                                    firstname: {
                                        required: 'Enter first name'
                                    },
                                    lastname: {
                                        required: 'Enter last name'
                                    },
                                    useremail: {
                                        required: 'Enter email address',
                                        email: 'Enter a VALID email address'
                                    },
                                    website: {
                                        required: 'Enter your website URL',
                                        url: 'URL should start with - http://www'
                                    },
                                    language: {
                                        required: 'Choose a language'
                                    },
                                    upload1: {
                                        required: 'Please browse a file',
                                        extension: 'File format not supported'
                                    },
                                    mobileos: {
                                        required: 'Please select a mobile platform'
                                    },
                                    comment: {
                                        required: 'Oops you forgot to comment',
                                        minlength: 'Enter at least 30 characters or more'
                                    },
                                    mobile_phone: {
                                        require_from_group: 'Fill at least a mobile contact'
                                    },
                                    home_phone: {
                                        require_from_group: 'Fill at least a home contact'
                                    },
                                    password: {
                                        required: 'Please enter a password'
                                    },
                                    repeatPassword: {
                                        required: 'Please repeat the above password',
                                        equalTo: 'Password mismatch detected'
                                    },
                                    gender: {
                                        required: 'Please choose specie'
                                    },
                                    languages: {
                                        required: 'Select laguages spoken'
                                    },
                                    verification: {
                                        required: 'Please enter verification code',
                                        smartCaptcha: 'Oops - enter a correct verification code'
                                    },
                                    applicant_age: {
                                        required: 'Enter applicant age',
                                        min: 'Must be 16 years and above'
                                    },
                                    licence_no: {
                                        required: 'Enter licence number'
                                    },
                                    child_name: {
                                        required: 'Please enter your childs name'
                                    }

                                },
                                /* @validation highlighting + error placement  
                                 ---------------------------------------------------- */

                                highlight: function (element, errorClass, validClass) {
                                    $(element).closest('.field').addClass(errorClass).removeClass(validClass);
                                },
                                unhighlight: function (element, errorClass, validClass) {
                                    $(element).closest('.field').removeClass(errorClass).addClass(validClass);
                                },
                                errorPlacement: function (error, element) {
                                    if (element.is(":radio") || element.is(":checkbox")) {
                                        element.closest('.option-group').after(error);
                                    } else {
                                        error.insertAfter(element.parent());
                                    }
                                }

                            });

                            /* @date picker
                             ------------------------------------------------------------------ */
                            $("#datepicker1").datepicker({
                                prevText: '<i class="fa fa-chevron-left"></i>',
                                nextText: '<i class="fa fa-chevron-right"></i>',
                                showButtonPanel: false,
                                beforeShow: function (input, inst) {
                                    var newclass = 'admin-form';
                                    var themeClass = $(this).parents('.admin-form').attr('class');
                                    var smartpikr = inst.dpDiv.parent();
                                    if (!smartpikr.hasClass(themeClass)) {
                                        inst.dpDiv.wrap('<div class="' + themeClass + '"></div>');
                                    }
                                }
                            });

                            $('.inline-dp').datepicker({
                                numberOfMonths: 1,
                                prevText: '<i class="fa fa-chevron-left"></i>',
                                nextText: '<i class="fa fa-chevron-right"></i>',
                                showButtonPanel: false
                            });

                            /* @date picker
                             ------------------------------------------------------------------ */
                            $("#datepicker1").datepicker({
                                prevText: '<i class="fa fa-chevron-left"></i>',
                                nextText: '<i class="fa fa-chevron-right"></i>',
                                showButtonPanel: false,
                                beforeShow: function (input, inst) {
                                    var newclass = 'admin-form';
                                    var themeClass = $(this).parents('.admin-form').attr('class');
                                    var smartpikr = inst.dpDiv.parent();
                                    if (!smartpikr.hasClass(themeClass)) {
                                        inst.dpDiv.wrap('<div class="' + themeClass + '"></div>');
                                    }
                                }
                            });


</script>

<?php
/* Layout com javascript para tela de CadastrarPessoa */
echo $this->layoutJSCadastrarPessoa;
