<?php

use Lancamento\Controller\Helper\ConstantesLancamento;
use Login\Controller\Helper\Constantes;

/**
 * Nome: cadastrar-pessoa.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com> e Sergio Bezerra da Silva <sergio.silva.unb@gmail.com>
 * Descricao: Página de cadastro de pessoa para tela de lançamento
 */
$form = $this->CadastrarPessoaForm;
$form->prepare();
$form->setAttribute(Constantes::$ACTION, $this->url(ConstantesLancamento::$ROUTE_LANCAMENTO, array(ConstantesLancamento::$PAGINA => ConstantesLancamento::$PAGINA_SALVAR_PESSOA)));
?> 
<div class="row background-mobile">
    <div id="content" class="animated fadeIn">
        <div class="row">
            <!-- Cadastro de Pessoa -->
            <div class="admin-form theme-danger tab-pane mw700 pl20 pr20" id="register1" role="tabpanel">
                <blockquote class="blockquote-danger">
                    <p><?php echo $this->translate(ConstantesLancamento::$TRADUCAO_NOVO_CADASTRO); ?></p>
                    <small><?php echo $this->translate(ConstantesLancamento::$TRADUCAO_NOVO_CADASTRO_LABEL); ?></small>
                </blockquote>
                <div class="panel panel-danger heading-border">
                    <?php echo $this->form()->openTag($form); ?>
                    <div class="panel-body p25">

                        <!-- Nome Input -->
                        <div class="section">
                            <label for="<?php echo ConstantesLancamento::$TRADUCAO_NOME; ?>" class="field-label">
                                <?php echo $this->translate(ConstantesLancamento::$TRADUCAO_NOME); ?>
                            </label>
                            <label for="<?php echo ConstantesLancamento::$TRADUCAO_NOME; ?>" class="field prepend-icon">
                                <?php echo $this->formInput($form->get(ConstantesLancamento::$INPUT_NOME)); ?>
                                <label for="<?php echo ConstantesLancamento::$TRADUCAO_NOME; ?>" class="field-icon">
                                    <i class="fa fa-user"></i>
                                </label>
                            </label>
                        </div>
                        <!-- Telefone Input -->
                        <div class="row section">
                            <div class="col-xs-5 col-sm-5 col-md-2">
                                <label for="<?php echo ConstantesLancamento::$TRADUCAO_DDD; ?>" class="field-label">
                                    <?php echo $this->translate(ConstantesLancamento::$TRADUCAO_DDD); ?>
                                </label>
                                <label for="<?php echo ConstantesLancamento::$TRADUCAO_DDD; ?>" class="field prepend-icon">
                                    <?php echo $this->formInput($form->get(ConstantesLancamento::$INPUT_DDD)); ?>
                                    <label for="<?php echo ConstantesLancamento::$TRADUCAO_DDD; ?>" class="field-icon">
                                        <i class="fa fa-phone-square"></i>
                                    </label>
                                </label>
                            </div>
                            <div class="col-xs-7 col-sm-7 col-md-10">
                                <label for="<?php echo ConstantesLancamento::$TRADUCAO_TELEFONE; ?>" class="field-label">
                                    <?php echo $this->translate(ConstantesLancamento::$TRADUCAO_TELEFONE); ?>
                                </label>
                                <label for="<?php echo ConstantesLancamento::$TRADUCAO_TELEFONE; ?>" class="field prepend-icon">
                                    <?php echo $this->formInput($form->get(ConstantesLancamento::$INPUT_TELEFONE)); ?>
                                    <label for="<?php echo ConstantesLancamento::$TRADUCAO_TELEFONE; ?>" class="field-icon">
                                        <i class="fa fa-phone-square"></i>
                                    </label>
                                </label>
                            </div>
                        </div>
                        <!-- Tipo Input Select --> 
                        <div class="section">
                            <label for="<?php echo ConstantesLancamento::$TRADUCAO_TIPO; ?>" class="field-label">
                                <?php echo $this->translate(ConstantesLancamento::$TRADUCAO_TIPO); ?>
                            </label>
                            <label for="<?php echo ConstantesLancamento::$TRADUCAO_TIPO; ?>" class="field prepend-icon">
                                <?php
// renderiza html input
                                echo $this->formSelect($form->get(ConstantesLancamento::$INPUT_TIPO));
                                ?>
                            </label>    
                        </div> 
                        <!-- Tipo Input Radio --> 
                        <div id="ocultar_checkbox" class="mb15" style="display: none;">
                            <label for="<?php echo ConstantesLancamento::$TRADUCAO_NUCLEO_CELULA; ?>" class="field-label">
                                <?php echo $this->translate(ConstantesLancamento::$TRADUCAO_NUCLEO_CELULA); ?>
                            </label>
                            <div class="option-group field">
                                <?php echo $this->formRadio($form->get(ConstantesLancamento::$INPUT_NUCLEO_PERFEITO)); ?>
                            </div>
                        </div>
                    </div>
                    <!-- end .form-body section -->
                    <div class="panel-footer text-right">
                        <?php echo $this->formHidden($form->get(Constantes::$INPUT_CSRF)); ?>
                        <button name="cancelar" id="cancelar" class="btn ladda-button btn-default dark" data-style="zoom-in" value="Back" onclick="location.href = '/'"><span class="ladda-label">Voltar</span><span class="ladda-spinner"></span></button>
                        <span>&nbsp;</span>
                        <?php echo $this->botaoSubmit('Nova Pessoa', 'btn-danger dark'); ?>
                    </div>
                    <!-- end .form-footer section -->
                    <?php echo $this->form()->closeTag() ?>
                </div>
                <!-- end .admin-form section -->
            </div>
            <!-- end: .admin-form -->
        </div>
    </div>
</div>