
<div class="row background-mobile">
    <div id="content">
        <div class="row">
            <div class="admin-form theme-danger tab-pane mw700 pl20 pr20">
                <div class="row">
                    <div class="admin-form theme-danger tab-pane mw800 pl20 pr20" id="survey1" role="tabpanel">
                        <blockquote class="blockquote-danger">
                            <p>Cadastro Sub-Equipe/Alterno</p>
                            <small>Registro Convencional</small>
                        </blockquote>
                        <div class="panel panel-danger heading-border">
                            <form method="post" action="/" id="CadastrarGrupoPessoaForm" name="CadastrarGrupoPessoaForm">
                                <div class="panel-body p25">
                                    <div class="section-divider mv40">
                                        <span>Estado Civil</span>
                                    </div>
                                    <!-- .section-divider -->

                                    <div class="section text-center">
                                        <div class="option-group field">
                                            <label for="campos_solteiro" class="option">
                                                <input type="radio" name="estado_civil" id="campos_solteiro" value="tv">
                                                <span class="radio" title="Com apenas 1 na igreja"></span>Solteiro / Casado</label>
                                            <label for="campos_casado" class="option">
                                                <input type="radio" name="estado_civil" id="campos_casado" value="int">
                                                <span class="radio" title="Com ambos na igreja"></span>Casado</label>
                                        </div>
                                    </div>
                                    <!-- end .section section -->
                                    
                                    <div class="section row">
                                        <div id="ocultar_dados" class="col-md-12">
                                            <div class="section row">
                                                <label for="city" class="field-label">Aluno do IV</label>
                                                <label for="city" class="field">
                                                    <label class="field select">
                                                        <select id="country" name="country">
                                                            <option value="0">Selecione</option>
                                                            <option value="1">Sérgio Bezerra da Silva</option>
                                                            <option value="2">Francisco da Silva</option>
                                                            <option value="3">Rômulo Sem Rumo</option>
                                                            <option value="4">Vivian Xavier</option>
                                                        </select>
                                                        <i class="arrow"></i>
                                                    </label>
                                                </label>
                                            </div>
                                            <!-- end section -->
                                        </div>
                                    </div>

                                    <div class="section-divider mv40">
                                        <span>Endereço</span>
                                    </div>
                                    <!-- .section-divider -->

                                    <div class="section row">
                                        <div class="col-md-6">
                                            <div class="section">
                                                <label for="cep" class="field-label">CEP</label>
                                                <div class="smart-widget sm-right smr-50">
                                                    <label class="field">
                                                        <input type="text" name="cep" id="cep" class="gui-input" placeholder="CEP">
                                                    </label>
                                                    <button type="submit" class="button btn-danger">
                                                        <i class="fa fa-search"></i>
                                                    </button>
                                                </div>
                                                <!-- end .smart-widget section -->
                                            </div>

                                            <div class="section">
                                                <label for="city" class="field-label">Bairro</label>
                                                <label for="city" class="field">
                                                    <label class="field select prepend-icon">
                                                        <select id="bairro" name="bairro">
                                                            <option value="0">Selecione</option>
                                                            <option value="AC">Acre</option>
                                                            <option value="AL">Alagoas</option>
                                                            <option value="AP">Amapá</option>
                                                            <option value="AM">Amazonas</option>
                                                            <option value="BA">Bahia</option>
                                                            <option value="CE">Ceara</option>
                                                            <option value="DF">Distrito Federal</option>
                                                            <option value="ES">Espirito Santo</option>
                                                            <option value="GO">Goias</option>
                                                            <option value="MA">Maranhão</option>
                                                            <option value="MT">Mato Grosso</option>
                                                            <option value="MS">Mato Grosso do Sul</option>
                                                            <option value="MG">Minas Gerais</option>
                                                            <option value="PA">Pará</option>
                                                            <option value="PB">Paraíba</option>
                                                            <option value="PR">Parana</option>
                                                            <option value="PE">Pernambuco</option>
                                                            <option value="PI">Piauí</option>
                                                            <option value="RJ">Rio de Janeiro</option>
                                                            <option value="RN">Rio Grande do Norte</option>
                                                            <option value="RS">Rio Grande do Sul</option>
                                                            <option value="RO">Rondonia</option>
                                                            <option value="RR">Roraima</option>
                                                            <option value="SC">Santa Catarina</option>
                                                            <option value="SP">São Paulo</option>
                                                            <option value="SE">Sergipe</option>
                                                        </select>
                                                        <i class="arrow double"></i>
                                                    </label>
                                                </label>
                                            </div>
                                            <!-- end section -->

                                        </div>
                                        <!-- end .colm section -->

                                        <div class="col-md-6">
                                            <div class="section">
                                                <label for="mobile" class="field-label">UF</label>
                                                <label class="field select prepend-icon">
                                                    <select id="uf" name="uf">
                                                        <option value="0">Selecione</option>
                                                        <option value="AC">Acre</option>
                                                        <option value="AL">Alagoas</option>
                                                        <option value="AP">Amapá</option>
                                                        <option value="AM">Amazonas</option>
                                                        <option value="BA">Bahia</option>
                                                        <option value="CE">Ceara</option>
                                                        <option value="DF">Distrito Federal</option>
                                                        <option value="ES">Espirito Santo</option>
                                                        <option value="GO">Goias</option>
                                                        <option value="MA">Maranhão</option>
                                                        <option value="MT">Mato Grosso</option>
                                                        <option value="MS">Mato Grosso do Sul</option>
                                                        <option value="MG">Minas Gerais</option>
                                                        <option value="PA">Pará</option>
                                                        <option value="PB">Paraíba</option>
                                                        <option value="PR">Parana</option>
                                                        <option value="PE">Pernambuco</option>
                                                        <option value="PI">Piauí</option>
                                                        <option value="RJ">Rio de Janeiro</option>
                                                        <option value="RN">Rio Grande do Norte</option>
                                                        <option value="RS">Rio Grande do Sul</option>
                                                        <option value="RO">Rondonia</option>
                                                        <option value="RR">Roraima</option>
                                                        <option value="SC">Santa Catarina</option>
                                                        <option value="SP">São Paulo</option>
                                                        <option value="SE">Sergipe</option>
                                                    </select>
                                                    <i class="arrow double"></i>
                                                </label>
                                            </div>
                                            <!-- end section -->

                                            <div class="section">
                                                <label for="city" class="field-label">Cidade</label>
                                                <label for="city" class="field prepend-icon">
                                                    <label class="field select prepend-icon">
                                                        <select id="cidade" name="cidade">
                                                            <option value="0">Selecione</option>
                                                            <option value="AC">Acre</option>
                                                            <option value="AL">Alagoas</option>
                                                            <option value="AP">Amapá</option>
                                                            <option value="AM">Amazonas</option>
                                                            <option value="BA">Bahia</option>
                                                            <option value="CE">Ceara</option>
                                                            <option value="DF">Distrito Federal</option>
                                                            <option value="ES">Espirito Santo</option>
                                                            <option value="GO">Goias</option>
                                                            <option value="MA">Maranhão</option>
                                                            <option value="MT">Mato Grosso</option>
                                                            <option value="MS">Mato Grosso do Sul</option>
                                                            <option value="MG">Minas Gerais</option>
                                                            <option value="PA">Pará</option>
                                                            <option value="PB">Paraíba</option>
                                                            <option value="PR">Parana</option>
                                                            <option value="PE">Pernambuco</option>
                                                            <option value="PI">Piauí</option>
                                                            <option value="RJ">Rio de Janeiro</option>
                                                            <option value="RN">Rio Grande do Norte</option>
                                                            <option value="RS">Rio Grande do Sul</option>
                                                            <option value="RO">Rondonia</option>
                                                            <option value="RR">Roraima</option>
                                                            <option value="SC">Santa Catarina</option>
                                                            <option value="SP">São Paulo</option>
                                                            <option value="SE">Sergipe</option>
                                                        </select>
                                                        <i class="arrow double"></i>
                                                    </label>
                                                </label>
                                            </div>
<!--                                            end section -->

                                        </div>
<!--                                        end .colm section -->

                                        <div class="col-md-12">
                                            <div class="section">
                                                <label for="firstaddr" class="field-label">Logradouro</label>
                                                <label for="firstaddr" class="field prepend-icon">
                                                    <input type="text" name="logradouro" id="logradouro" class="gui-input" placeholder="Logradouro">
                                                    <label for="firstaddr" class="field-icon">
                                                        <i class="fa fa-map-marker"></i>
                                                    </label>
                                                </label>
                                            </div>
<!--                                            end section -->
                                        </div>

                                        <div class="col-md-12">
                                            <div class="section">
                                                <label for="firstaddr" class="field-label">Complemento</label>
                                                <label for="firstaddr" class="field prepend-icon">
                                                    <input type="text" name="complemento" id="complemento" class="gui-input" placeholder="Complemento">
                                                    <label for="firstaddr" class="field-icon">
                                                        <i class="fa fa-location-arrow"></i>
                                                    </label>
                                                </label>
                                            </div>
<!--                                            end section -->
                                        </div>

                                    </div>
<!--                                    end .section row section -->

                                    <div id="ocultar_dados">
                                        <div class="section-divider mv40">
                                            <span>Dados Pessoais</span>
                                        </div>
<!--                                        .section-divider -->

                                        <div class="section row">
                                            <div class="col-md-6">
                                                <div class="section">
                                                    <label for="cep" class="field-label">CPF</label>
                                                    <div class="smart-widget sm-right smr-50">
                                                        <label class="field">
                                                            <input type="text" name="cpf" id="cpf" class="gui-input" placeholder="Informe seu CPF">
                                                        </label>
                                                        <button type="submit" class="button btn-danger">
                                                            <i class="fa fa-search"></i>
                                                        </button>
                                                    </div>
<!--                                                    end .smart-widget section -->
                                                </div>

                                            </div>
<!--                                            end .colm section -->

                                            <div class="col-md-6">
                                                <div class="section">
                                                    <label for="mobile" class="field-label">Sexo</label>
                                                    <div style="width:100%; padding-bottom:5px;"></div>
                                                    <div class="section">
                                                        <div class="option-group field">
                                                            <label for="masculino" class="option">
                                                                <input type="radio" name="sexo" id="masculino" value="masculino">
                                                                <span class="radio"></span>Masculino</label>
                                                            <label for="feminino" class="option">
                                                                <input type="radio" name="sexo" id="feminino" value="feminino">
                                                                <span class="radio"></span>Feminino</label>
                                                        </div>
                                                    </div>
<!--                                                    end .section section -->
                                                </div>
<!--                                                end section -->

                                            </div>
<!--                                            end .colm section -->

                                            <div class="col-md-12">
                                                <div class="section">
                                                    <label for="firstaddr" class="field-label">Nome Completo</label>
                                                    <label for="nome_completo" class="field prepend-icon">
                                                        <input type="text" name="nome_completo" id="nome_completo" class="gui-input" placeholder="Nome Completo">
                                                        <label for="firstaddr" class="field-icon">
                                                            <i class="fa fa-terminal"></i>
                                                        </label>
                                                    </label>
                                                </div>
<!--                                                end section -->
                                            </div>

                                            <div class="col-md-6">
                                                <div class="section">
                                                    <label for="data_nascimento" class="field-label">Data de Nascimento</label>
                                                    <label for="data_nascimento" class="field prepend-icon">
                                                        <input type="text" id="data_nascimento" name="data_nascimento" class="gui-input" placeholder="Data de Nascimento">
                                                        <label class="field-icon">
                                                            <i class="fa fa-calendar-o"></i>
                                                        </label>
                                                    </label>
                                                </div>
<!--                                                end section -->

                                                <div class="section">
                                                    <label for="telefone_celular" class="field-label">Telefone Celular</label>
                                                    <label for="telefone_celular" class="field prepend-icon">
                                                        <input type="tel" name="telefone_celular" id="telefone_celular" class="gui-input phone" placeholder="Telefone Celular" required="required">
                                                        <label for="mobile" class="field-icon">
                                                            <i class="fa fa-phone-square"></i>
                                                        </label>
                                                    </label>
                                                </div>
<!--                                                end section -->

                                                <div class="section">
                                                    <label for="mobile" class="field-label">Repita o Email</label>
                                                    <label for="useremail" class="field prepend-icon">
                                                        <input type="email" name="useremail" id="useremail" class="gui-input" placeholder="Repita o Email">
                                                        <label for="useremail" class="field-icon">
                                                            <i class="fa fa-envelope"></i>
                                                        </label>
                                                    </label>
                                                </div>
<!--                                                end section -->

                                                <div class="section">
                                                    <label for="city" class="field-label">Profissão</label>
                                                    <label for="city" class="field">
                                                        <label class="field select">
                                                            <select id="country" name="profissao">
                                                                <option value="0">Selecione</option>
                                                                <option value="1">Líder em Treinamento</option>
                                                                <option value="2">Alterno</option>
                                                                <option value="3">Co-Líder</option>
                                                                <option value="4">Outro</option>
                                                            </select>
                                                            <i class="arrow"></i>
                                                        </label>
                                                    </label>
                                                </div>
<!--                                                end section -->
                                            </div>

                                            <div class="col-md-6">
                                                <div class="section">
                                                    <label for="mobile" class="field-label">Telefone Residencial</label>
                                                    <label for="mobile" class="field prepend-icon">
                                                        <input type="tel" name="mobile" id="mobile" class="gui-input phone" placeholder="Telefone Residencial" required="required">
                                                        <label for="mobile" class="field-icon">
                                                            <i class="fa fa-phone-square"></i>
                                                        </label>
                                                    </label>
                                                </div>
<!--                                                end section -->

                                                <div class="section">
                                                    <label for="mobile" class="field-label">Email</label>
                                                    <label for="useremail" class="field prepend-icon">
                                                        <input type="email" name="useremail" id="useremail" class="gui-input" placeholder="Email">
                                                        <label for="useremail" class="field-icon">
                                                            <i class="fa fa-envelope"></i>
                                                        </label>
                                                    </label>
                                                </div>
<!--                                                end section -->

                                                <div class="section">
                                                    <label for="city" class="field-label">Hierarquia</label>
                                                    <label for="city" class="field">
                                                        <label class="field select">
                                                            <select id="country" name="country">
                                                                <option value="0">Selecione</option>
                                                                <option value="1">Líder em Treinamento</option>
                                                                <option value="2">Alterno</option>
                                                                <option value="3">Co-Líder</option>
                                                                <option value="4">Outro</option>
                                                            </select>
                                                            <i class="arrow"></i>
                                                        </label>
                                                    </label>
                                                </div>
<!--                                                end section -->

                                                <div class="section">
                                                    <label for="mobile" class="field-label">Endereço Local de Trabalho</label>
                                                    <label for="useremail" class="field prepend-icon">
                                                        <input type="email" name="useremail" id="useremail" class="gui-input" placeholder="Endereço Local de Trabalho">
                                                        <label for="useremail" class="field-icon">
                                                            <i class="fa fa-map-marker"></i>
                                                        </label>
                                                    </label>
                                                </div>
<!--                                                end section -->
                                            </div>

                                        </div>
                                    </div>

<!--                                    end .section row section -->
                                    <div id="ocultar_aluno">
                                        <div class="section-divider mv40">
                                            <span>Selecione um aluno para cadastro</span>
                                        </div>
<!--                                        .section-divider -->

                                        <div class="col-md-12">
                                            <div class="section row text-center">
                                                <button type="button" class="btn disabled btn-default btn-block">Não existem alunos registrados.</button>
                                            </div>
                                            <div class="section row">
                                                <label for="city" class="field-label">Aluno do IV</label>
                                                <label for="city" class="field">
                                                    <label class="field select">
                                                        <select id="country" name="country">
                                                            <option value="0">Selecione</option>
                                                            <option value="1">Sérgio Bezerra da Silva</option>
                                                            <option value="2">Francisco da Silva</option>
                                                            <option value="3">Rômulo Sem Rumo</option>
                                                            <option value="4">Vivian Xavier</option>
                                                        </select>
                                                        <i class="arrow"></i>
                                                    </label>
                                                </label>
                                            </div>
                                            <!-- end section -->
                                        </div>
                                    </div>
                                    <!--end .section section--> 

                                </div>
                                <!-- end .form-body section -->
                                <div class="panel-footer text-right">
                                    <button type="submit" class="btn btn-danger dark">Cadastrar</button>
                                </div>
                                <!-- end .form-footer section -->
                            </form>
                        </div>
                        <!-- end .admin-form section -->
                    </div>
                    <!-- end: .admin-form -->
                </div>
            </div>
        </div> 
        
        <div class="row">
            <!-- Cadastro de Sub-Equipe / Alterno -->
            <div class="admin-form theme-danger tab-pane mw800 pl20 pr20" id="CadastroCelula" role="tabpanel">
                <blockquote class="blockquote-danger">
                    <p>Cadastro de Célula</p>
                    <small>Multiplicação</small>
                </blockquote>
                <div class="panel panel-danger heading-border">
                    <form method="post" action="/" id="form-survey1">
                        <div class="panel-body p25">
                            <div class="section-divider mv40">
                                <span>Dia / Hora</span>
                            </div>
                            <!-- .section-divider -->

                            <div class="col-xs-6 col-sm-6 col-xd-6 col-md-6">
                                <div class="section">
                                    <label for="dia" class="field-label">Dia</label>
                                    <label for="dia" class="field">
                                        <label class="field select prepend-icon">
                                            <select id="dia" name="dia">
                                                <option value="0">Selecione</option>
                                                <option value="dom">Domingo</option>
                                                <option value="seg">Segunda-Feira</option>
                                                <option value="ter">Terça-Feira</option>
                                                <option value="qua">Quarta-Feira</option>
                                                <option value="qui">Quinta-Feira</option>
                                                <option value="sex">Sexta-Feira</option>
                                                <option value="sab">Sábado</option>
                                            </select>
                                            <i class="arrow double"></i>
                                        </label>
                                    </label>
                                </div>
                                <!-- end section -->     
                            </div>

                            <div class="col-xs-6 col-sm-6 col-xd-6 col-md-6">
                                <div class="section">
                                    <label for="hora" class="field-label">Hora</label>
                                    <label for="hora" class="field prepend-icon">
                                        <input type="time" name="hora" id="hora" class="gui-input" placeholder="Hora">
                                        <label for="hora" class="field-icon">
                                            <i class="fa fa-clock-o"></i>
                                        </label>
                                    </label>
                                </div>
                                <!-- end section -->
                            </div>

                            <div class="col-xs-12 col-sm-12 col-xd-12 col-md-12">
                                <div class="section">
                                    <label for="cep" class="field-label">Logradouro ou CEP</label>
                                    <div class="smart-widget sm-right smr-50">
                                        <label class="field">
                                            <input type="text" name="cep" id="cep" class="gui-input" placeholder="Logradouro ou CEP">
                                        </label>
                                        <button type="submit" class="button btn-danger">
                                            <i class="fa fa-search"></i>
                                        </button>
                                        <!-- end .smart-widget section -->
                                    </div>
                                </div>
                            </div>


                            <div class="col-xs-12 col-sm-12 col-xd-12 col-md-12">
                                <div class="section">
                                    <label for="firstaddr" class="field-label">Complemento</label>
                                    <label for="firstaddr" class="field prepend-icon">
                                        <input type="text" name="complemento" id="complemento" class="gui-input" placeholder="Complemento">
                                        <label for="firstaddr" class="field-icon">
                                            <i class="fa fa-location-arrow"></i>
                                        </label>
                                    </label>
                                </div>
                            </div>
                        </div>
                        
                        <div class="panel-body">
                            <div class="section-divider mv40">
                                <span>Hospedeiro</span>
                            </div>
                            <!-- .section-divider -->
                            
                            <div class="col-xs-12 col-sm-12 col-xd-12 col-md-12">
                                <div class="section">
                                    <label for="nome_hospedeiro" class="field-label">Nome do Hospedeiro</label>
                                    <label for="nome_hospedeiro" class="field prepend-icon">
                                        <input type="text" name="nome_hospedeiro" id="nome_hospedeiro" class="gui-input" placeholder="Nome do Hospedeiro">
                                        <label for="nome_hospedeiro" class="field-icon">
                                            <i class="fa fa-terminal"></i>
                                        </label>
                                    </label>
                                </div>
                                
                                <div class="row section">
                                    <div class="col-xs-5 col-sm-5 col-md-2">
                                        <label for="DDD" class="field-label">DDD</label><label for="DDD" class="field prepend-icon"><input type="text" name="ddd" class="gui-input" id="ddd" placeholder="DDD" value=""><label for="DDD" class="field-icon"><i class="fa fa-phone-square"></i></label></label>                            </div>
                                    <div class="col-xs-7 col-sm-7 col-md-10">
                                        <label for="Phone" class="field-label">Telefone</label><label for="Phone" class="field prepend-icon"><input type="text" name="telefone" class="gui-input" id="telefone" placeholder="Telefone" value=""><label for="Phone" class="field-icon"><i class="fa fa-phone-square"></i></label></label>                            </div>
                                </div>
                            </div>
                        </div>
                        
                        <!-- end .section row section -->
                        <div class="panel-footer text-right">
                            <button type="submit" class="btn btn-danger">Cadastrar Célula</button>
                        </div>
                </div>
                <!-- end .form-footer section -->

            </div>
            </form>
        </div>
        <!-- end .admin-form section -->
        </div>
        <!-- end: .admin-form -->
</div>
    </div>
</div>




