<link class="main-stylesheet" href="/css/estilos-circuito/cv-impressos/pages.css" rel="stylesheet" type="text/css" />

<!-- START PAGE CONTENT WRAPPER -->
<div class="page-content-wrapper">
    <!-- START PAGE CONTENT -->
    <div class="content">
        <nav class="navbar navbar-default bg-master-lighter sm-padding-10" role="navigation">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sub-nav">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="sub-nav">
                    <div class="row">
                        <div class="col-sm-4">
                            <ul class="nav navbar-nav">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle text-black" data-toggle="dropdown"><i class="fa fa-file-text m-r-10 text-black"></i> Ficha do Revisão <span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="#">Action</a>
                                        </li>
                                        <li><a href="#">Another action</a>
                                        </li>
                                        <li><a href="#">Something else here</a>
                                        </li>
                                        <li class="divider"></li>
                                        <li><a href="#">Separated link</a>
                                        </li>
                                        <li class="divider"></li>
                                        <li><a href="#">One more separated link</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="col-sm-4">
                            <ul class="nav navbar-nav navbar-center">
                                <li><a href="#" data-toggle="tooltip" data-placement="bottom" title="Imprimir"><i class="fa fa-print text-black"></i></a>
                                </li>
                                <li><a href="#" data-toggle="tooltip" data-placement="bottom" title="Baixar"><i class="fa fa-download text-black"></i></a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-sm-4">
                            <ul class="nav navbar-nav navbar-right">
                                <li>
                                    <a href="#" class="p-r-10"><img width="25" height="25" alt="" class="icon-pdf" data-src-retina="/img/invoice/pdf2x.png" data-src="/img/invoice/pdf.png" src="img/invoice/pdf2x.png">
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="p-r-10"><img width="25" height="25" alt="" class="icon-image" data-src-retina="/img/invoice/image2x.png" data-src="/img/invoice/image.png" src="/img/invoice/image2x.png">
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="p-r-10"><img width="25" height="25" alt="" class="icon-doc" data-src-retina="/img/invoice/doc2x.png" data-src="/img/invoice/doc.png" src="/img/invoice/doc2x.png">
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container-fluid -->
        </nav>
        <!-- START CONTAINER FLUID -->
        <div class="container-fluid container-fixed-lg">
            <!-- START PANEL -->
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="invoice padding-50 sm-padding-10">
                        <div>
                            <div class="pull-left">
                                <img width="235" height="23" alt="" class="invoice-logo" data-src-retina="/img/logos/circuito_visao-color.png" data-src="/img/logos/circuito_visao-color.png" src="/img/logos/circuito_visao-color.png">
                                <address class="m-t-10">
                                    Agosto/2016
                                    <br>Revisão de Vidas
                                    <br>
                                </address>
                            </div>
                            <div class="pull-right sm-m-t-20">
                                <h4 class="font-montserrat all-caps hint-text">Ficha de Inscrição</h4>
                                <img width="150" height="75" alt="" class="pull-right" data-src-retina="/img/invoice/barcode.png" data-src="/img/invoice/barcode.png" src="/img/invoice/barcode.png">
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <br>
                        <br>
                        <div class="container-sm-height">
                            <div class="row-sm-height">
                                <div class="col-md-9 col-sm-height sm-no-padding">
                                    <p class="small no-margin">Revisionista: </p>
                                    <h5 class="semi-bold m-t-0">Camila Batista da Silva | <b>24 anos</b></h5>
                                </div>
                                <div class="col-md-3 col-sm-height col-bottom sm-no-padding sm-p-b-20">
                                    <br>
                                    <div>
                                        <div class="pull-left font-montserrat bold all-caps">Data de Envío :</div>
                                        <div class="pull-right">29/06/16</div>
                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table m-t-50">
                                <thead>
                                    <tr>
                                        <th class="">Igreja</th>
                                        <th class="text-center">Líder</th>
                                        <th class="text-right">Contato(s)</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td  style="border-bottom-color: #fff;">
                                            <p class="text-black">SNT Ceilândia Centro</p>
                                            <p class="small hint-text">
                                                Endereço da Igreja - Quinta-Feira às 18:00.
                                            </p>
                                        </td>
                                        <td class="text-center" style="border-bottom-color: #fff;">Sérgio Silva</td>
                                        <td class="text-right" style="border-bottom-color: #fff;">(61)994102960</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="pull-right">
                            <i class="fa fa-cut"></i>
                        </div>
                        <hr>
                        <div class="pull-right sm-m-t-20">
                            <h4 class="font-montserrat all-caps hint-text">Recibo</h4>
                        </div>
                        <div class="table-responsive">
                            <table class="table m-t-50">
                                <thead>
                                    <tr>
                                        <th class="">Igreja</th>
                                        <th class="text-center">Líder</th>
                                        <th class="text-center">Idade</th>
                                        <th class="text-right">Contato(s)</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="">
                                            <p class="text-black">SNT Ceilândia Centro</p>
                                            <p class="small hint-text">
                                                Revisão de Vidas 00/00/00 - Quinta-Feira às 18:00.
                                            </p>
                                        </td>
                                        <td class="text-center">Sérgio Silva</td>
                                        <td class="text-center">24</td>
                                        <td class="text-right">(61)994102960</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <br>
                        <div class="footer-print">
                            <img src="/img/logos/circuito_visao-preto.png" alt="logo" data-src="/img/logos/circuito_visao-preto.png" data-src-retina="/img/logos/circuito_visao-preto.png" width="228" height="22">
                            <span class="m-l-40 text-black sm-pull-right">supporte@circuitodavisao.com</span>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END PANEL -->
        </div>
        <!-- END CONTAINER FLUID -->
    </div>
    <!-- END PAGE CONTENT -->
</div>
<!-- END PAGE CONTENT WRAPPER -->

<!-- START PAGE CONTENT WRAPPER -->
<div class="page-content-wrapper">
    <!-- START PAGE CONTENT -->
    <div class="content">
        <!-- START CONTAINER FLUID -->
        <div class="container-fluid container-fixed-lg">
            <!-- START PANEL -->
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="invoice padding-50 sm-padding-10">
                        <div>
                            <div class="pull-left">
                                <img width="235" height="23" alt="" class="invoice-logo" data-src-retina="/img/logos/circuito_visao-color.png" data-src="/img/logos/circuito_visao-color.png" src="/img/logos/circuito_visao-color.png">
                            </div>
                            <div class="pull-right sm-m-t-20">
                                <h4 class="font-montserrat all-caps hint-text">Autorização</h4>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <br>
                        <div class="container-sm-height">
                            <div class="row-sm-height">
                                <p class="hint-text">Eu, ____________________________________________________ autorizo meu(inha) filho(a) _____________________________________________________ a participar do Revisão de Vida, no periódo de ______ a ______ de _____________________ de 20______.</p>
                                <p class="hint-text">Estou ciente de que ele(a) estará em um ônibus fretado pela igreja Sara Nossa Terra e saindo na sexta-feira, às 19 horas, aonde o(a) pegarei no domingo à noite. Nestes dias meus telefones de contato são: ______________________/_________________________, para falar comigo caso precisem. </p>
                            </div>
                        </div>
                        
                        <br>
                        <hr>
                        <div class="footer-print">
                            <img src="/img/logos/circuito_visao-preto.png" alt="logo" data-src="/img/logos/circuito_visao-preto.png" data-src-retina="/img/logos/circuito_visao-preto.png" width="228" height="22">
                            <span class="m-l-40 text-black sm-pull-right">supporte@circuitodavisao.com</span>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END PANEL -->
        </div>
        <!-- END CONTAINER FLUID -->
    </div>
    <!-- END PAGE CONTENT -->
    <!-- START COPYRIGHT -->
    <!-- START CONTAINER FLUID -->
    <div class="container-fluid container-fixed-lg footer">
        <div class="copyright sm-text-center">
            <p class="small no-margin pull-left sm-pull-reset">
                <span class="hint-text">Copyright © 2016 </span>
                <span class="font-montserrat">SARA NOSSA TERRA</span>.
                <span class="hint-text">Todos os direitos reservados. </span>
                <span class="sm-block"><a href="#" class="m-l-10 m-r-10">Termos de Uso</a> | <a href="#" class="m-l-10">Política de Privacidade</a></span>
            </p>
            <div class="clearfix"></div>
        </div>
    </div>
    <!-- END COPYRIGHT -->
</div>
<!-- END PAGE CONTENT WRAPPER -->