<?php

use Lancamento\Controller\Helper\ConstantesLancamento;
use Lancamento\Controller\Helper\FuncoesLancamento;

$mesSelecionado = FuncoesLancamento::mesPorAbaSelecionada($this->abaSelecionada);
$anoSelecionado = FuncoesLancamento::anoPorAbaSelecionada($this->abaSelecionada);
?>

<!-- MODAL PARA MUITOS ELEMENTOS -->
<?php echo $this->modalMuitosEventos(); ?>

<!-- Abertura de Abas -->
<div class="row">
    <div class="col-md-6">
        <?php echo $this->dadosEntidade(); ?>
    </div>
</div>
<!-- MODAL COM LOADER -->
<?php echo $this->modalAba(); ?>
<div class="panel">
    <div class="panel-heading">
        <ul class="nav panel-tabs-border panel-tabs panel-tabs-left">
            <?php
            $urlBase = $this->url(ConstantesLancamento::$ROUTE_LANCAMENTO);
            $urlBase2 = $urlBase . '/2';
            ?>
            <li role="presentation" <?php echo ConstantesLancamento::$ONCLICK_ABRIR_MODAL; ?> <?php echo $this->abaSelecionada($this->abaSelecionada, 1); ?>><a href="<?php echo $urlBase; ?>">M&ecirc;s Atual</a></li>
            <li role="presentation" <?php echo ConstantesLancamento::$ONCLICK_ABRIR_MODAL; ?> <?php echo $this->abaSelecionada($this->abaSelecionada, 2); ?>><a href="<?php echo $urlBase2; ?>">M&ecirc;s Anterior</a></li>
        </ul>
        <div class="pull-right">
            <div class="btn-group">
                <button class="btn btn-primary btn-sm" onclick="location.href = '/lancamentoCadastrarPessoa';" title="Adicionar Pessoa"><i class="fa fa-plus"></i></button>
            </div>
            <div class="btn-group">
                <button class="btn btn-success btn-sm" onclick="location.href = '/lancamentoEnviarRelatorio';" title="Enviar Relatório"><i class="fa fa-file-text-o"></i></button>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <!-- Tabela de lançamento de dados --> 
        <?php echo $this->cabecalhoDeCiclos(); ?>

        <!-- Tabela de lançamento de dados --> 
        <?php echo $this->tabelaLancamento(); ?>
    </div>
</div>
<?php
/* Layout com javascript para tela de index */
echo $this->layoutJSLancamento;
