<?php

use Doctrine\Common\Collections\Criteria;
use Lancamento\Controller\Helper\ConstantesLancamento;
use Lancamento\Controller\Helper\FuncoesLancamento;

$mesSelecionado = FuncoesLancamento::mesPorAbaSelecionada($this->abaSelecionada);
$anoSelecionado = FuncoesLancamento::anoPorAbaSelecionada($this->abaSelecionada);
?>
<div class="panel-body">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-visible" id="spy2">
                <div class="panel-body pn">
                    <table class="table table-striped table-hover text-center" id="datatable2" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th colspan="2"></th>
                                <?php echo $this->cabecalhoDeEventos(); ?>
                            </tr>
                        </thead>
                        <tbody>
                            <?php echo $this->ListagemDePessoasComEventos(); ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<hr />

<div class="row">
    <div class="col-md-6">
        <?php echo $this->dadosEntidade(); ?>
    </div> 
    <div class="col-md-6">
        <?php echo $this->alertaEnvioRelatorio(1); ?>
        <?php echo $this->alertaEnvioRelatorio(2); ?>
        <?php echo $this->alertaEnvioRelatorio(3); ?>
    </div> 
</div>
<div class="row">
    <div class="tab-block mb25">
        <!--ABAS SELECIONADAS--> 
        <ul class="nav nav-tabs tabs-bg">
            <?php
            $urlBase = $this->url(ConstantesLancamento::$ROUTE_LANCAMENTO);
            $urlBase2 = $urlBase . '/2';
            ?>
            <li role="presentation" <?php echo ConstantesLancamento::$ONCLICK_ABRIR_MODAL; ?> <?php echo $this->abaSelecionada($this->abaSelecionada, 1); ?>><a href="<?php echo $urlBase; ?>"><i class="fa fa-wheelchair text-purple"></i> M&ecirc;s Atual</a></li>
            <li role="presentation" <?php echo ConstantesLancamento::$ONCLICK_ABRIR_MODAL; ?> <?php echo $this->abaSelecionada($this->abaSelecionada, 2); ?>><a href="<?php echo $urlBase2; ?>"><i class="fa fa-bolt text-purple"></i>M&ecirc;s Anterior</a></li>
        </ul>
<!--        FIM ABAS SELECIONADAS 
        MODAL COM LOADER GIGANTE -->
        <?php echo $this->modalAba(); ?>
        <!--FIM MODAL COM LOADER GIGANTE--> 
        <button class="btn btn-danger btn-lg" onclick="location.href = '/lancamentoCadastrarPessoa';" >NOVO CADSTRO</button>
        <button class="btn btn-danger btn-lg" onclick="location.href = '/lancamentoEnviarRelatorio';" >ENVIAR RELATORIO</button>
        <div class="tab-content">
            <div id="tab10_1" class="tab-pane active">
                <div id="cabecalhoCiclo" class="row">
                    <div class="col-md-6">
                        <!--Lista de lançamento-->
                        <button class=" btn btn-success" >
                            <i class="fa fa-bolt text-purple"></i>
                        </button>
                    </div>
                    <div class="col-md-6 text-center">
                        <?php
                        $urlBaseCiclo = $urlBase . '/' . $this->abaSelecionada . '_';
                        if ($this->cicloSelecionado > 1) {
                            $urlCicloAnterior = $urlBaseCiclo . ($this->cicloSelecionado - 1);
                            ?>
                            <a <?php echo ConstantesLancamento::$ONCLICK_ABRIR_MODAL; ?> href="<?php echo $urlCicloAnterior; ?>"><i class="btn fa fa-angle-double-left text-purple"></i></a>
                            <?php
                        }
                        ?>    
                        Ciclo {<?php echo $this->cicloSelecionado; ?>} <?php echo 'Periodo ' . FuncoesLancamento::periodoCicloMesAno($this->cicloSelecionado, $mesSelecionado, $anoSelecionado); ?>
                        <?php
                        $totalDeCiclos = FuncoesLancamento::totalCiclosMes($mesSelecionado, $anoSelecionado);
                        if ($this->cicloSelecionado < $totalDeCiclos) {
                            $urlCicloPosterior = $urlBaseCiclo . ($this->cicloSelecionado + 1);
                            ?>
                            <a <?php echo ConstantesLancamento::$ONCLICK_ABRIR_MODAL; ?> href="<?php echo $urlCicloPosterior; ?>"><i class="btn fa fa-angle-double-right text-purple"></i></a>
                            <?php
                        }
                        ?>
                    </div>
                </div>
                <div id="cabecalhoEventos" class="row">
                    <div class="col-md-6">
                        <input class="form-control" placeholder="Buscar nome" />
                    </div>
                    <div class="col-md-6 text-center">
                        {
                        <?php
                        /* Listagem dos eventos */
                        $grupo = $this->entidade->getGrupo();
                        $eventos = $grupo->getGrupoEventoNoCiclo($this->cicloSelecionado);
                        if (count($eventos) > 0) {
                            echo "<div class='row btn-success'>";
                            foreach ($eventos as $ge) {

                                /* Verificar se o evento existe nesse ciclo */
                                echo $ge->getEvento()->getEventoTipo()->getNome() . "|";
                                echo $ge->getEvento()->getDia() . "|";
                                echo $ge->getEvento()->getHora() . " - ";
                            }
                            echo "</div>";
                            echo "<div class='row'>";
                            $cont = 1;
                            foreach ($eventos as $ge) {
                                /* Totais */
                                $evento = $ge->getEvento();
                                $cont++;
                                if ($cont % 2 == 0) {
                                    $class = 'btn-info';
                                } else {
                                    $class = 'btn-danger';
                                }
                                echo "<span id='total_{$evento->getId()}' class='$class'>";
                                $eventoFrequencia = $evento->getEventoFrequencia();
                                $total = 0;
                                if (count($eventoFrequencia) > 0) {
                                    $criteria = Criteria::create()
                                            ->andWhere(Criteria::expr()->eq("ano", $anoSelecionado))
                                            ->andWhere(Criteria::expr()->eq("mes", $mesSelecionado))
                                            ->andWhere(Criteria::expr()->eq("ciclo", $this->cicloSelecionado))
                                            ->andWhere(Criteria::expr()->eq("frequencia", "S"))
                                    ;
                                    $eventosFiltrados = $eventoFrequencia->matching($criteria);
                                    $total = count($eventosFiltrados);
                                }
                                echo "$total";
                                echo "</span>";
                            }
                            echo "</div>";
                        }
                        ?>}
                    </div>
                </div>
                <div id="listaEventos" class="row">
                    <?php
                    $responsabilidades = $grupo->getResponsabilidadesAtivas();
                    foreach ($responsabilidades as $gr) {
                        $pessoa = $gr->getPessoa();
                        echo '<div class="row">';
                        echo '<div class="col-md-3 btn-success">' . $pessoa->getNomeListaDeLancamento() . '</div>';
                        echo '<div class="col-md-2 btn-danger">Lider</div>';
                        /* Listagem dos eventos */
                        $grupo = $this->entidade->getGrupo();
                        $eventos = $grupo->getGrupoEventoNoCiclo($this->cicloSelecionado);
                        if (count($eventos) > 0) {
                            echo '<div class="col-md-7 btn-default">';
                            foreach ($eventos as $ge) {
                                $valor = '';
                                $class = 'btn-danger';
                                $classIco = 'fa-user';
                                $evento = $ge->getEvento();
                                $eventoFrequencia = $evento->getEventoFrequencia();
                                $idEventoFrequencia = 'checkbox_' . $pessoa->getId() . '_' . $evento->getId();
                                if (count($eventoFrequencia) > 0) {
                                    $criteria = Criteria::create()
                                            ->andWhere(Criteria::expr()->eq("pessoa_id", $pessoa->getId()))
                                            ->andWhere(Criteria::expr()->eq("ano", $anoSelecionado))
                                            ->andWhere(Criteria::expr()->eq("mes", $mesSelecionado))
                                            ->andWhere(Criteria::expr()->eq("ciclo", $this->cicloSelecionado))
                                    ;
                                    $eventosFiltrados = $eventoFrequencia->matching($criteria);
                                    if ($eventosFiltrados->count() == 1) {
                                        $valor = $eventosFiltrados->first()->getFrequencia();
                                        if ($valor == 'S') {
                                            $class = 'btn-success';
                                            $classIco = 'fa-bolt';
                                        } else {
                                            $class = 'btn-danger';
                                            $classIco = 'fa-user';
                                        }
                                        $idEventoFrequencia = 'ico_' . $eventosFiltrados->first()->getId();
                                    }
                                }

                                echo '<div class="col-md-2 text-center ">';
                                echo "<a id='a_" . $idEventoFrequencia . "' class='btn $class' href='#' onclick='mudarFrequencia(\"$idEventoFrequencia\", $this->cicloSelecionado, $this->abaSelecionada);'>";
                                echo "<i id='i_" . $idEventoFrequencia . "' class='fa $classIco' ></i>";
                                echo '</a>';
                                echo '</div>';
                            }
                            echo '</div>';
                        }
                        echo '</div>';
                    }
                    if (count($grupo->getGrupoPessoa()) > 0) {
                        foreach ($grupo->getGrupoPessoa() as $gp) {
                            $pessoa = $gp->getPessoa();
                            $pessoaTipo = $gp->getGrupoPessoaTipo();
                            echo '<div class="row">';
                            echo '<div class="col-md-3 btn-success">' . $pessoa->getNomeListaDeLancamento() . '</div>';
                            echo '<div class="col-md-2 btn-danger">' . $pessoaTipo->getNome() . '</div>';
                            /* Listagem dos eventos */
                            $grupo = $this->entidade->getGrupo();
                            $eventos = $grupo->getGrupoEventoNoCiclo($this->cicloSelecionado);
                            if (count($eventos) > 0) {
                                echo '<div class="col-md-7 btn-default">';
                                foreach ($eventos as $ge) {
                                    $valor = '';
                                    $class = 'btn-danger';
                                    $classIco = 'fa-user';
                                    $evento = $ge->getEvento();
                                    $eventoFrequencia = $evento->getEventoFrequencia();
                                    $idEventoFrequencia = 'checkbox_' . $pessoa->getId() . '_' . $evento->getId();
                                    if (count($eventoFrequencia) > 0) {
                                        $criteria = Criteria::create()
                                                ->andWhere(Criteria::expr()->eq("pessoa_id", $pessoa->getId()))
                                                ->andWhere(Criteria::expr()->eq("ano", $anoSelecionado))
                                                ->andWhere(Criteria::expr()->eq("mes", $mesSelecionado))
                                                ->andWhere(Criteria::expr()->eq("ciclo", $this->cicloSelecionado))
                                        ;
                                        $eventosFiltrados = $eventoFrequencia->matching($criteria);
                                        if ($eventosFiltrados->count() == 1) {
                                            $valor = $eventosFiltrados->first()->getFrequencia();
                                            if ($valor == 'S') {
                                                $class = 'btn-success';
                                                $classIco = 'fa-bolt';
                                            } else {
                                                $class = 'btn-danger';
                                                $classIco = 'fa-user';
                                            }
                                            $idEventoFrequencia = 'ico_' . $eventosFiltrados->first()->getId();
                                        }
                                    }

                                    echo '<div class="col-md-2 text-center ">';
                                    echo "<a id='a_" . $idEventoFrequencia . "' class='btn $class' href='#' onclick='mudarFrequencia(\"$idEventoFrequencia\", $this->cicloSelecionado, $this->abaSelecionada);'>";
                                    echo "<i id='i_" . $idEventoFrequencia . "' class='fa $classIco' ></i>";
                                    echo '</a>';
                                    echo '</div>';
                                }
                                echo '</div>';
                            }
                            echo '</div>';
                        }
                    }
                    ?>
                </div>
            </div>
            <div id="tab10_2" class="tab-pane">
                TAB 2
            </div>
        </div>
    </div>
</div>
<?php
/* Layout com javascript para tela de index */
echo $this->layoutJSLancamento;
