<?php

use Cadastro\Form\ConstantesForm;
use Lancamento\Controller\Helper\ConstantesLancamento;
use Login\Controller\Helper\Constantes;

$grupoResponsavel = $grupo->getResponsabilidadesAtivas();
if ($grupoResponsavel) {
    $pessoas = array();
    foreach ($grupoResponsavel as $gr) {
        $p = $gr->getPessoa();
        $imagem = 'placeholder.png';
        if (!empty($p->getFoto())) {
            $imagem = $p->getFoto();
        }
        $pessoas[] = $p;
    }

    $html = '';
    $htmlFoto = '';
    $contagem = 1; 
    $totalPessoas = count($pessoas);

    foreach ($pessoas as $p) {
        if ($contagem == 2) {
            $html .= '&nbsp;&&nbsp;';
            $htmlFoto .= '';
        }
        $imagem = 'placeholder.png';
        $tamanho = 45;
        if (!empty($p->getFoto())) {
            $imagem = $p->getFoto();
        }
        $htmlFoto .= '<img src="/img/avatars/' . $imagem . '" class="img-thumbnail" width="' . $tamanho . '%"  height="' . $tamanho . '%" />&nbsp;';
        if ($totalPessoas == 1) {
            $html .= $p->getNomePrimeiroUltimo(); 
        } else {// duas pessoas
            $html .= $p->getNomePrimeiroPrimeiraSiglaUltimo();
        }
        $contagem++;
    }
}

/* percentagem da meta, sendo que a meta é 2 atendimentos por mes */
if($numeroAtendimentos == 0){
    $valueNow = 10;
    $labelProgressBar = 0;
    $colorBar =  "progress-bar-danger";
}else if($numeroAtendimentos == 1){
    $valueNow = 50;
    $labelProgressBar = 50;
    $colorBar = "progress-bar-warning";
}else if($numeroAtendimentos >= 2){
    $valueNow = 100;
    $labelProgressBar = 100;
    $colorBar = "progress-bar-success";
}

$form = $this->CadastrarAtendimentoForm;
$form->prepare();
$form->setAttribute(Constantes::$ACTION, $this->url(ConstantesLancamento::$ROUTE_LANCAMENTO, array(ConstantesLancamento::$PAGINA => ConstantesLancamento::$PAGINA_SALVAR_ATENDIMENTO)));
?> 
<div class="mw1000 center-block p10">
    <div class="admin-form theme-primary">
        <blockquote class = "blockquote-primary">
            <small>
                Lan&ccedil;ar <span class="text-primary">Atendimento</span>
            </small>
        </blockquote>
        <div id="atendimento" class="panel heading-border panel-primary">
            <div class="panel-body bg-light">


                <div class="row mt10">
                    <div class="col-md-3 col-xs-5" style="padding-left: 0px; padding-right: 0px;" >
                        <span class="" href="#" >
                            <?php echo $htmlFoto; ?>
                        </span>
                    </div>     
                    <div class="col-md-9 col-xs-7" style="padding-left: 2px; padding-right: 2px;">
                        <div class="row">
                            <div class="col-md-12 col-xs-12" style="padding-top: 3px;">

                                <div class="progress progress-bar-xl" style="margin-bottom: 0px;">
                                    <div id="divProgressBar" class="progress-bar <?php echo $colorBar; ?>" role="progressbar" aria-valuenow="<?php echo $valueNow; ?>" aria-valuemin="0" aria-valuemax="5" style="width: <?php echo $valueNow; ?>%;"><?php echo $labelProgressBar; ?>%</div>
                                </div>
                                <span style="padding-top: 0px;"><?php echo $html; ?></span>
                            </div>

                        </div>  
                    </div>
                </div>
                <?php echo $this->form()->openTag($form); ?>
                    <div class="row mt10">

                        <div class="row">
                            <div class="col-sm-12 col-xs-12" >
                                <div class="section" style="margin-bottom: 5px; ">
                                    <label class="field-label">Que dia foi o Atendimento?</label>
                                    <label class="field prepend-icon">
                                        <?php echo $this->formInput($form->get(ConstantesLancamento::$INPUT_DATA_ATENDIMENTO)); ?>
                                    </label>
                                </div>
                            </div>
                        </div>


                    </div>
                    <div class="row mt10">


                        <div class="row">
                            <div class="col-sm-12 col-xs-12" >
                                <div class="section">
                                    <label class="field-label">Quem realizou o atendimento?</label>
                                    <label class="field prepend-icon">
                                        <?php echo $this->formSelect($form->get(ConstantesLancamento::$INPUT_QUEM_ATENDEU)); ?>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
            
            <div id="divBotaoVoltar" class="panel-footer text-right" style="height:65px;">

                <?php echo $this->formHidden($form->get(ConstantesLancamento::$INPUT_ID_GRUPO_ATENDIDO)); ?>
                  
                <?php echo $this->formHidden($form->get(Constantes::$INPUT_CSRF)); ?>
                 
                <button type="button" onclick="location.href = '/lancamentoAtendimento';" class="btn ladda-button btn-default dark  mr10" data-style="zoom-in">
                    <span class="ladda-label">
                        <i class="fa fa-arrow-left" aria-hidden="true"></i> 
                        Voltar
                    </span>
                </button>
                <?php 
                $funcaoPreValidacao = $this->funcaoOnClick(ConstantesLancamento::$STRING_FUNCAO_VALIDACAO_ATENDIMENTO);
                echo $this->botaoLink(ConstantesLancamento::$PAGINA_LANCAR_ATENDIMENTO, ConstantesForm::$STRING_HASHTAG, 0,$funcaoPreValidacao); 
                ?>                

            </div>
            <?php echo $this->form()->closeTag() ?>



        </div>
    </div>
</div>    
<script>
window.onload = initPage;
    
    function initPage() {

        $('#<?php echo ConstantesLancamento::$FORM_CADASTRAR_ATENDIMENTO; ?>').validate({
            /* @validation states + elements 
             ------------------------------------------- */

            errorClass: "state-error",
            validClass: "state-success",
            errorElement: "em",
            /* @validation rules 
             ------------------------------------------ */

            rules: {
                dataAtendimento: {
                    required: true,
                    date: true,
                    maxlength: 10,
                    minlength: 10
                    
                },
                quem: {
                    required: true
                }
            },
            /* @validation error messages 
             ---------------------------------------------- */

            messages: {
                dataAtendimento: {
                    required: 'Insert date',
                    maxlength: 'Please enter a valid date. Max: 10 characters',
                    minlength: 'Please enter a valid date. Min: 10 characters'
                },
                quem: {
                    required: 'Select Leader'
                }
            },
            /* @validation highlighting + error placement  
             ---------------------------------------------------- */

            highlight: function (element, errorClass, validClass) {
                $(element).closest('.field').addClass(errorClass).removeClass(validClass);
            },
            unhighlight: function (element, errorClass, validClass) {
                $(element).closest('.field').removeClass(errorClass).addClass(validClass);
            },
            errorPlacement: function (error, element) {
                if (element.is(":radio") || element.is(":checkbox")) {
                    element.closest('.option-group').after(error);
                } else {
                    error.insertAfter(element.parent());
                }
            }

        });
    }
        

    function preValidacao() {
        var validator;
            validator = $('#<?php echo ConstantesLancamento::$FORM_CADASTRAR_ATENDIMENTO; ?>').validate();
            if (validator.form()) {
                $(<?php echo ConstantesLancamento::$FORM_CADASTRAR_ATENDIMENTO; ?>).submit();
            }
    }
</script>