
<div class="mw1000 center-block p10">
    <div class="admin-form theme-danger">
        <blockquote class = "blockquote-danger">
            <small>
                Lan&ccedil;ar <span class="text-danger">Atendimento</span>
            </small>
        </blockquote>
        <div id="atendimento" class="panel heading-border panel-danger">
            <div class="panel-body bg-light">


                <div class="row mt10">
                    <div class="col-md-3 col-xs-5" style="padding-left: 0px; padding-right: 0px;" >
                        <span class="" href="#" >
                            <img src="/img/avatars/1.jpg" class="img-thumbnail" width="45%"  height="auto" />
                            <img src="/img/avatars/2.jpg" class="img-thumbnail" width="45%"  height="auto" />
                        </span>
                    </div>    
                    <div class="col-md-9 col-xs-7" style="padding-left: 2px; padding-right: 2px;">
                        <div class="row">
                            <div class="col-md-12 col-xs-12" style="padding-top: 3px;">

                                <div class="progress progress-bar-xl" style="margin-bottom: 0px;">
                                    <div id="divProgressBar" class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="5" style="width: 10%;">0%</div>
                                </div>
                                <span style="padding-top: 0px;">Diego e Ursula</span>
                            </div>

                        </div>  
                    </div>
                </div>
                <form>
                    <div class="row mt10">

                        <div class="row">
                            <div class="col-sm-12 col-xs-12" >
                                <div class="section" style="margin-bottom: 5px; ">
                                    <label class="field-label">Que dia foi o Atendimento?</label>
                                    <label class="field prepend-icon">
                                        <input type="date" name="dataNascimento" class="form-control date" id="dataLancamento" placeholder="" value="">
                                    </label>
                                </div>
                            </div>
                        </div>


                    </div>
                    <div class="row mt10">


                        <div class="row">
                            <div class="col-sm-12 col-xs-12" >
                                <div class="section">
                                    <label class="field-label">Quem realizou o atendimento?</label>
                                    <label class="field prepend-icon">
                                        <select name="dia_da_semana" class="gui-input" id="dia_da_semana">
                                            <option value="">SELECIONE</option>
                                            <option value="1">LUCAS</option>
                                            <option value="2">PRISCILA</option>
                                            <option value="3">AMBOS</option>
                                        </select>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>

            <div id="divBotaoVoltar" class="panel-footer text-right" style="height:65px;">


                <button type="button" onclick="location.href = '/lancamentoAtendimento';" class="btn ladda-button btn-default dark  mr10" data-style="zoom-in">
                    <span class="ladda-label">
                        <i class="fa fa-arrow-left" aria-hidden="true"></i> 
                        Voltar
                    </span>
                </button>
                <button class="btn ladda-button btn-danger dark mr10 pull-right"   data-style="zoom-in">
                    <span class="ladda-label">Lan&ccedil;ar</span>
                </button>                  

            </div>
            </form>



        </div>
    </div>
</div>    