<?php

$versao = '?v=0.1';

echo $this
        ->headScript()
        ->prependFile($this->basePath() . '/js/circuito_da_visao/capslock.js' . $versao)
        ->prependFile($this->basePath() . '/js/circuito_da_visao/circuito-mascaras_e_validacoes.js' . $versao)
        ->prependFile($this->basePath() . '/js/circuito_da_visao/opcoes-recuperar-senha.js' . $versao)
;
echo $this->inlineScript();
?>