<?php echo $this->doctype(); ?>

<?php
$versao = '?v=1.0.7';

use Login\Controller\Helper\Constantes;
?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">

        <!-- Title Head -->
        <?php
        $NAME_APPLICATION = $this->translate(Constantes::$TRADUCAO_NOME_APLICACAO);
        echo $this
                ->headTitle($NAME_APPLICATION)
                ->setSeparator(' - ')
                ->setAutoEscape(false)
        ;
        ?>

        <!-- Meta Head -->
        <?php
        echo $this
                ->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ;
        ?>

        <!-- Styles -->
        <?php
        echo $this
                ->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.png'))
                ->headLink(array('rel' => 'apple-touch-icon', 'href' => $this->basePath() . '/img/icons/touch-icon-ipad.png'))
		->headLink(array('rel' => 'apple-touch-icon', 'sizes' => '76x76', 'href' => $this->basePath() . '/img/icons/touch-icon-ipad.png'))
		->headLink(array('rel' => 'apple-touch-icon', 'sizes' => '120x120', 'href' => $this->basePath() . '/img/icons/touch-icon-iphone-retina.png'))
		->headLink(array('rel' => 'apple-touch-icon', 'sizes' => '152x152', 'href' => $this->basePath() . '/img/icons/touch-icon-ipad-retina.png'))
		->headLink(array('rel' => 'apple-touch-icon', 'sizes' => '256x256', 'href' => $this->basePath() . '/img/icons/touch-icon-iphone.png'))   
                ->prependStylesheet($this->basePath() . '/css/estilos-circuito/cv-lancamentos/estilos-lancamentos.css' . $versao)
                ->prependStylesheet($this->basePath() . '/js/vendor/plugins/ladda/ladda.min.css')
                ->prependStylesheet($this->basePath() . '/js/vendor/plugins/magnific/magnific-popup.css')
                ->prependStylesheet($this->basePath() . '/css/estilos-circuito/admin-forms.css')
                ->prependStylesheet($this->basePath() . '/css/estilos-circuito/cv-login/estilos-login.css' . $versao)
                ->prependStylesheet($this->basePath() . '/css/estilos-circuito/default_skin/css/theme.css')
                ->prependStylesheet($this->basePath() . '/css/estilos-circuito/page-loading/normalize.css')
                ->prependStylesheet($this->basePath() . '/css/estilos-circuito/page-loading/demo.css')
                ->prependStylesheet($this->basePath() . '/css/estilos-circuito/page-loading/component.css')
                ->prependStylesheet('https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700')
        ;
        ?>
    </head>
    <body id="body" class="external-page external-alt sb-l-c sb-r-c">
        <?php echo $this->content; ?>

        <!-- BEGIN: PAGE SCRIPTS -->
        <?php
        echo $this
                ->headScript()
                ->prependFile($this->basePath() . '/js/assets/js/main.js')
                ->prependFile($this->basePath() . '/js/assets/js/utility/utility.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/vendor/plugins/ladda/ladda.min.js')
                ->prependFile($this->basePath() . '/js/vendor/plugins/magnific/jquery.magnific-popup.js')
                ->prependFile($this->basePath() . '/js/vendor/plugins/jquerymask/jquery.maskedinput.min.js')
                ->prependFile($this->basePath() . '/js/page-loading/snap.svg-min.js')
                ->prependFile($this->basePath() . '/js/page-loading/classie.js')
                ->prependFile($this->basePath() . '/js/page-loading/svgLoader.js')
                ->prependFile($this->basePath() . '/js/vendor/jquery/jquery_ui/jquery-ui.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
        ;
        echo $this->inlineScript();
        ?>
        <script type="text/javascript">
            jQuery(document).ready(function () {

                "use strict";

                // Init Theme Core
                Core.init();

                // Init Ladda Plugin on buttons
                Ladda.bind('.ladda-button', {
                    timeout: 2000
                });

            });
        </script>
        
        <!-- BEGIN: PAGE-LOADING -->
        <script>
            (function() {
              var pageWrap = document.getElementById( 'pagewrap' ),
                pages = [].slice.call( pageWrap.querySelectorAll( 'div.container' ) ),
                currentPage = 0,
                triggerLoading = [].slice.call( pageWrap.querySelectorAll( 'div.pageload-link' ) ),
                loader = new SVGLoader( document.getElementById( 'loader' ), { speedIn : 300, easingIn : mina.easeinout } );

              function init() {
                triggerLoading.forEach( function( trigger ) {
                  trigger.addEventListener( 'click', function( ev ) {
                    ev.preventDefault();
                    loader.show();
                    // after some time hide loader
                    setTimeout( function() {
                      loader.hide();

                      classie.removeClass( pages[ currentPage ], 'show' );
                      // update..
                      currentPage = currentPage ? 0 : 1;
                      classie.addClass( pages[ currentPage ], 'show' );

                    }, 2000 );
                  } );
                } );
              }

              init();
            })();
        </script>
        <!-- END: PAGE-LOADING -->
        <!-- END: PAGE SCRIPTS -->
    </body>
</html>
