<?php echo $this->doctype(); ?>

<?php
$versao = '?v=1.7.2';

use Login\Controller\Helper\Constantes;
?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">

        <!-- Title Head -->
        <?php
        $NAME_APPLICATION = $this->translate(Constantes::$TRADUCAO_NOME_APLICACAO);
        echo $this
                ->headTitle($NAME_APPLICATION)
                ->setSeparator(' - ')
                ->setAutoEscape(false)
        ;
        ?>

        <!-- Meta Head -->
        <?php
        echo $this
                ->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ;
        ?>

        <!-- Styles -->
        <?php
        echo $this
                ->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.png'))
                ->prependStylesheet($this->basePath() . '/css/bootstrap/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap/bootstrap.min.css')
                ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700')
                ->prependStylesheet($this->basePath() . '/css/estilos-circuito/admin-forms.css')
                ->prependStylesheet($this->basePath() . '/css/estilos-circuito/default_skin/css/theme.css')
                ->prependStylesheet($this->basePath() . '/css/estilos-circuito/cv-login/estilos-login.css' . $versao)
        ;
        ?>
    </head>
    <body class="external-page external-alt sb-l-c sb-r-c">
        <!-- Start: Main -->
        <div id="main-photo" class="animated fadeIn">
            <!-- Start: Header -->
            <header class="navbar-fixed-top" style="background:transparent; padding-left:20px; padding-top:25px;">
                <a href="<?php echo Constantes::$INDEX; ?>">
                    <img src="<?php echo Constantes::$IMAGEM_LOGO_BRANCA; ?>" title="<?php echo $this->translate(Constantes::$TRADUCAO_NOME_APLICACAO) ?>" class="img-responsive" style="max-width: 275px;">
                </a>
            </header>
            <!-- End: Header -->
            <!-- Start: Content-Wrapper -->
            <section id="content_wrapper">
                <!-- Begin: Content -->
                <section id="content">
                    <?php echo $this->content; ?>
                </section>
                <!-- End: Content -->
            </section>
            <!-- End: Content-Wrapper -->
        </div>
        <!-- End: Main -->
        <!-- BEGIN: PAGE SCRIPTS -->
        <?php
        echo $this
                ->headScript()
                ->prependFile($this->basePath() . '/js/circuito_da_visao/timeout.js' . $versao)
                ->prependFile($this->basePath() . '/js/circuito_da_visao/botao-loader.js' . $versao)
                ->prependFile($this->basePath() . '/js/assets/js/main.js')
                ->prependFile($this->basePath() . '/js/assets/js/utility/utility.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/vendor/jquery/jquery_ui/jquery-ui.min.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
        ;
        echo $this->inlineScript();
        ?>
        <script type="text/javascript">
            jQuery(document).ready(function () {

                "use strict";

                // Init Theme Core
                Core.init();

            });
        </script>
        <!-- END: PAGE SCRIPTS -->
    </body>
</html>
