<div class="span2 sidebar">
    layout 2
</div>
<?php
echo $this
        ->headScript()
        ->prependFile($this->basePath() . '/js/circuito_da_visao/botao-loader.js')
        ->prependFile($this->basePath() . '/js/circuito_da_visao/capslock.js')
        ->prependFile($this->basePath() . '/js/circuito_da_visao/circuito-mascaras_e_validacoes.js')
        ->prependFile($this->basePath() . '/js/circuito_da_visao/opcoes-recuperar-senha.js')
;
echo $this->inlineScript();
?>
