<?php echo $this->doctype(); ?>

<?php

use Login\Controller\Helper\Constantes; ?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">

        <!-- Title Head -->
        <?php
        $NAME_APPLICATION = $this->translate(Constantes::$TRADUCAO_NOME_APLICACAO);
        echo $this
                ->headTitle($NAME_APPLICATION)
                ->setSeparator(' - ')
                ->setAutoEscape(false)
        ;
        ?>

        <!-- Meta Head -->
        <?php
        echo $this
                ->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ;
        ?>

        <!-- Styles -->
        <?php
        echo $this
                ->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/bootstrap/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap/bootstrap.min.css')
                ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700')
                ->prependStylesheet($this->basePath() . '/css/estilos-circuito/admin-forms.css')
                ->prependStylesheet($this->basePath() . '/css/estilos-circuito/default_skin/css/theme.css')
        ;
        ?>
    </head>
    <body class="external-page external-alt sb-l-c sb-r-c">

        <?php echo $this->content; ?>

        <!-- BEGIN: PAGE SCRIPTS -->
        <?php
        echo $this
                ->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/vendor/jquery/jquery_ui/jquery-ui.min.js')
                ->prependFile($this->basePath() . '/js/assets/js/utility/utility.js')
                ->prependFile($this->basePath() . '/js/assets/js/demo/demo.js')
                ->prependFile($this->basePath() . '/js/assets/js/main.js')
                ->prependFile($this->basePath() . '/js/capslock.js')
        ;
        echo $this->inlineScript();
        ?>
        <!-- Page Javascript -->
        <script type="text/javascript">
            jQuery(document).ready(function () {

                "use strict";

                // Init Theme Core
                Core.init();

                // Init Demo JS
                Demo.init();
            });
        </script>
        <!-- END: PAGE SCRIPTS -->
    </body>
</html>
