<?php

use Application\Controller\Helper\Constantes;
use Application\Controller\Helper\Funcoes;
use Application\View\Helper\BotaoSimples;
use Application\View\Helper\ListagemDePessoasComEventos;
use DateTime;
use Doctrine\Common\Collections\Criteria;
					$periodoAtual = 0;
					$periodoAnterior = -1;
?>
<div class="mw1000 center-block">
    <div id='panelLancamento' class="panel mw1000">
        <div class="panel-body center-block" style="padding: 5px;">
			<?php
				if($this->possoAlterar){
					echo '<div class="mb5">';
					if ($this->periodo == $periodoAnterior || $this->periodo == $periodoAtual) {
						$extra = $this->funcaoOnClick('mostrarSplash(); funcaoCircuito("lancamentoEnviar", ' . $this->periodo . ')');
						echo '&nbsp;&nbsp;'.$this->botaoSimples('Enviar Relatório', $extra, BotaoSimples::botaoSucesso, BotaoSimples::larguraMaxima);
					}
					echo '</div>';
				}	
				echo $this->cabecalhoDePeriodos();
				echo $this->tabelaLancamento();
			?>
        </div>
        <div class="panel-footer text-center">
            <div class="row">
                <?php
				if($this->possoAlterar){
					$label = $this->translate(Constantes::$TRADUCAO_CADASTRAR_PESSOA);
					$extra = $this->funcaoOnClick('verificarMuitosCadastros(' . 0 . ', ' . $this->periodo . ')');
					echo $this->botaoSimples($label, $extra, BotaoSimples::botaoImportante, BotaoSimples::posicaoAoCentro);

					$extra = $this->funcaoOnClick('mostrarSplash(); funcaoCircuito("lancamentoEnviar", ' . $this->periodo . ')');
					echo '&nbsp;&nbsp;'.$this->botaoSimples('Enviar Relatório', $extra, BotaoSimples::botaoSucesso, BotaoSimples::posicaoAoCentro);
				}
                ?>
            </div>
        </div>
    </div>
</div>
<!-- MODAL PARA MUITOS ELEMENTOS -->
<?php
echo $this->modalMuitosCadastros();
echo $this->layoutJSLancamento;
