<?php

use Application\Controller\Helper\Constantes;

/**
 * Nome: atendimento.phtml
 * @author Lucas Filipe de Carvalho Cunha <lucascarvalho.esw@gmail.com>
 * Descricao: Página para mostrar eficiência em atendimentos e a quantidade que cada disicpulo foi atendido.
 */

$html = '';
$html .= $this->templateFormularioTopo('Lançamento de <b class="text-danger">Atendimento</b>');
$html .= '<div class="panel-body bg-light">';
$html .= '<form action="/lancamentoAtendimento" method="post">';
$html .= $this->cabecalhoDeMeses();
$html .= '</form>';
$html .=  $this->atendimentoGruposAbaixo(); 
$html .= '</div>';
$html .= $this->templateFormularioRodape();
echo $html;             
            
?>

