
<!-- Nome: atendimento.phtml
     @author Lucas Filipe de Carvalho Cunha <lucascarvalho.esw@gmail.com>
     Descricao: Página para mostrar eficiência em atendimentos e a quantidade que cada disicpulo foi atendido.
  -->
<div class="mw1000 center-block p10">

    <?php echo $this->modalAba(); ?>

    <blockquote class = "blockquote-primary">
        <small>
            Relat&oacute;rio de <span class="text-primary">Atendimento</span>
        </small>
    </blockquote>
    <div id="atendimento" class="panel">
        <div class="panel-heading">
            <?php echo $this->abasAtendimento(); ?>

        </div> 
        <div class="panel-body center-block">

            <?php
            echo $this->cabecalhoDeAtendimentos();
            echo $this->atendimentoGruposAbaixo();
            ?>        
        </div>
    </div>

    <?php
    /* Layout com javascript para tela de index */

    