<?php

use Application\Controller\Helper\Constantes;

/**
 * Nome: cadastrar-pessoa.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com> e Sergio Bezerra da Silva <sergio.silva.unb@gmail.com>
 * Descricao: Página de cadastro de pessoa para tela de lançamento
 */
$form = $this->CadastrarPessoaForm;
$form->prepare();
$form->setAttribute(Constantes::$ACTION, $this->url(Constantes::$ROUTE_LANCAMENTO, array(Constantes::$PAGINA => Constantes::$PAGINA_SALVAR_PESSOA)));
?>  
<div class="row background-mobile">
    <div id="content" class="animated fadeIn">
        <div class="row">
            <!-- Cadastro de Pessoa -->
            <div class="admin-form theme-danger tab-pane mw700 pl20 pr20" id="register1" role="tabpanel">
                <blockquote class="blockquote-danger">
                    <p><?php echo $this->translate(Constantes::$TRADUCAO_NOVO_CADASTRO); ?></p>
                    <small><?php echo $this->translate(Constantes::$TRADUCAO_NOVO_CADASTRO_LABEL); ?></small>
                </blockquote>
                <div class="panel panel-danger heading-border">
                    <?php echo $this->form()->openTag($form); ?>
                    <div class="panel-body bg-light p25">
                        <?php
                        echo $this->divMensagens();
                        echo $this->inputFormularioSimples(Constantes::$TRADUCAO_NOME, $form->get(Constantes::$INPUT_NOME));
                        echo $this->inputFormularioSimples(Constantes::$TRADUCAO_DDD, $form->get(Constantes::$INPUT_DDD), 3);
                        echo $this->inputFormularioSimples(Constantes::$TRADUCAO_TELEFONE, $form->get(Constantes::$INPUT_TELEFONE), 9);
                        echo $this->inputFormularioSimples(Constantes::$TRADUCAO_TIPO, $form->get(Constantes::$INPUT_TIPO), null, 2);
                        echo '<div id="ocultar_checkbox" class="hidden">';
                        echo $this->inputFormularioSimples(Constantes::$TRADUCAO_NUCLEO_CELULA, $form->get(Constantes::$INPUT_NUCLEO_PERFEITO), null, 3);
                        echo '</div>';
                        ?> 
                    </div>
                    <!-- end .form-body section -->
                    <div class="panel-footer text-right">
                        <?php echo $this->formHidden($form->get(Constantes::$INPUT_CSRF)); ?>
                        <?php echo $this->botaoLink(Constantes::$TRADUCAO_VOLTAR, Constantes::$ROUTE_LANCAMENTO, 2); ?>
                        <?php
                        /* Submit */
                        $funcaoVerificarCadastroPessoa = $this->funcaoOnClick('validarLancamentoCadastrarPessoa(this.form)');
                        echo $this->botaoSimples(Constantes::$TRADUCAO_CADASTRAR, $funcaoVerificarCadastroPessoa);
                        ?>
                    </div>
                    <!-- end .form-footer section -->
                    <?php echo $this->form()->closeTag() ?>
                </div>
                <!-- end .admin-form section -->
            </div>
            <!-- end: .admin-form -->
        </div>
    </div>
</div>
<?php
/* Layout com javascript para tela de index */
echo $this->layoutJSCadastrarPessoaValidacao;
