<?php

use Application\Controller\Helper\Constantes;
?>
<div class="panel-body bg-light text-center">
    <h1><span class = "text-success">Relat&oacute;rio está sendo processado em breve os dados estarão contabilizados, você pode utilizar o sistema normalmente.</span></h1>
    <div class = "col-xs-12">
        <h2 class = "text-default mbn confirmation-header"><i class="fa fa-check text-success"></i></h2>
    </div>
    <div class = "col-xs-12 mt10">
        <?php echo $this->botaoLink(Constantes::$TRADUCAO_BOTAO_PRONTO, Constantes::$ACTION_LANCAMENTO_ARREGIMENTACAO . '/'.$this->periodo, 0, ''); ?>
    </div>
</div>
