<?php
use Application\Controller\Helper\Funcoes;
use Application\Controller\Helper\Constantes;
use Application\View\Helper\BotaoSimples;
?>
<div class="panel-body bg-light text-center">
	<h1>Parceiro de Deus Extrato</h1>
<?php
$html = '';
if($this->fatos){
	$html .= '<input id="fooFilter" type="text" class="form-control" placeholder="Filtro">';

	$html .= '<div class="table-responsive">';
	$html .= '<table class="table table-condensed table-hover bg-light mt15 footable" data-filter="#fooFilter">';
	$html .= '<thead>';
	$html .= '<tr class="text-left">';
	$html .= '<th>Data</th>';
	$html .= '<th>Time</th>';
	$html .= '<th>Pessoa</th>';
	$html .= '<th>Valor</th>';
	$html .= '<th>Tipo</th>';
	$html .= '<td></td>';
	$html .= '</tr>';
	$html .= '</thead>';
	$html .= '<tbody>';
	$somaTotal = 0;
	foreach($this->fatos as $fatoFinanceiro){
		$funcaoExcluir = $this->funcaoOnClick('mostrarSplash(); validarExclusao('.$fatoFinanceiro->getId().')');
		$botaoExcluir = $this->botaoSimples('<i class="fa fa-times"></i>', $funcaoExcluir, BotaoSimples::botaoMuitoPequenoPerigoso);

		$html .= '<tr class="text-left">';
		$html .= '<td>'.Funcoes::mudarPadraoData($fatoFinanceiro->getData(),1).'</td>';
		$html .= '<td>'.$fatoFinanceiro->getGrupo()->getEntidadeAtiva()->infoEntidade();
		$html .= '<td>'.$fatoFinanceiro->getPessoa()->getNome().'</td>';
		$html .= '<td>'.number_format($fatoFinanceiro->getValor(),2,',','.').'</td>';
		$html .= '<td>'.$fatoFinanceiro->getFatoFinanceiroTipo()->getNome().'</td>';
		$html .= '<td>' . $botaoExcluir . '</td>';
		$html .= '</tr>';

		$somaTotal += $fatoFinanceiro->getValor();
	}
	$html .= '<tr class="dark text-left">';
	$html .= '<td colspan="5" class="text-right">Total</td>';
	$html .= '<td>'.number_format($somaTotal,2,',','.').'</td>';
	$html .= '<td></td>';
	$html .= '</tr>';

	$html .= '</tbody>';
	$html .= '</table>';
	$html .= '</div>';

}else{
	$html .= '<div class="alert alert-warning text-center">Sem lançamentos</div>';
}

$html .= '<div class="panel-footer text-right">';
$stringNomeDaFuncaoOnClickCadastro = 'funcaoCircuito("lancamentoParceiroDeDeus", 0)';
$html .= $this->botaoLink('Lançar', Constantes::$STRING_HASHTAG, 0, $this->funcaoOnClick($stringNomeDaFuncaoOnClickCadastro));
$html .= '</div>';
echo $html;
?>
</div>
<script type="text/javascript">
function validarExclusao(idFatoParceiroDeDeus){
	let resposta = confirm('Realmente quer excluir esse lançamento?')
	if(resposta){
		funcaoCircuito('lancamentoParceiroDeDeusExcluir', idFatoParceiroDeDeus)
	}
}
</script>
