<?php

use Application\Controller\Helper\Constantes;
use Application\View\Helper\BotaoSimples;
$formulario = $this->formulario;
$formulario->prepare();
$formulario->setAttribute(Constantes::$ACTION, $this->url(Constantes::$ROUTE_LANCAMENTO, array(Constantes::$ACTION => 'parceiroDeDeusFinalizar')));
echo $this->form()->openTag($formulario); 
?>
<div class="panel-body bg-light text-center mt50">
	<h1>Parceiro de Deus</h1>
<?php 
echo $this->divMensagens();
?>
	<div class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">
<label class="field-label text-muted fs18 mb10">Selecione o líder</label>
	<select id="idGrupo" name="idGrupo" class="form-control" onChange="selecionarLider();">
	<option value="0"><?php echo $this->translate(Constantes::$TRADUCAO_SELECIONE); ?></option>
	<?php echo $this->listagemLideresTransferencia($this->discipulos); ?>
</select>
</div>
<?php
echo $this->inputFormularioSimples('Dia', $formulario->get(Constantes::$FORM_INPUT_DIA), 4, 2);
echo $this->inputFormularioSimples('Mês', $formulario->get(Constantes::$FORM_INPUT_MES), 4, 2);
echo $this->inputFormularioSimples('Ano', $formulario->get(Constantes::$FORM_INPUT_ANO), 4, 2);

echo $this->inputFormularioSimples('Valor Individual', $formulario->get('individual'), 12);
echo $this->inputFormularioSimples('Qual Célula', $formulario->get('idGrupoEvento'), 12, 2);
echo $this->inputFormularioSimples('Valor Célula', $formulario->get('celula'), 12);
?>

<div>TOTAL: <span id="total">0.00</span></div>

</div>
<div class="panel-footer text-right">
<?php
echo $this->formHidden($formulario->get(Constantes::$INPUT_CSRF));
$stringNomeDaFuncaoOnClickCadastro = 'validar(this.form)';
echo $this->botaoLink('Salvar Valores', Constantes::$STRING_HASHTAG, 0, $this->funcaoOnClick($stringNomeDaFuncaoOnClickCadastro));
$funcaoVoltar = $this->funcaoOnClick('location.href="/lancamentoParceiroDeDeusExtrato"');
echo $this->botaoSimples('Voltar', $funcaoVoltar, BotaoSimples::botaoMenorImportancia, BotaoSimples::posicaoAEsquerda);
?>        
	</div>
</div>
<?php 
echo $this->form()->closeTag();
?>
<script>
function atualizarTotal(){
	let valorIndividual = $('#individual').val()
	let valorCelula = $('#celula').val()
	if(valorIndividual == ''){
		valorIndividual = '0'
	}
	if(valorCelula == ''){
		valorCelula = '0'
	}

	valorIndividual = valorIndividual.replace(',','.')
	valorIndividual = parseFloat(valorIndividual)

	valorCelula = valorCelula.replace(',','.')
	valorCelula = parseFloat(valorCelula)

	let soma = valorIndividual + valorCelula
	console.log('Individual', valorIndividual)
	console.log('Celula', valorCelula)
	$('#total').html(soma.toFixed(2))
}
</script>
