<?php

use Application\Controller\Helper\Constantes;
use Application\View\Helper\BotaoSimples;
$formulario = $this->formulario;
$formulario->prepare();
$formulario->setAttribute(Constantes::$ACTION, $this->url(Constantes::$ROUTE_LANCAMENTO, array(Constantes::$ACTION => 'parceiroDeDeusFinalizar')));

$htmlBody = '';
$htmlBody .= '<h1>Parceiro de Deus</h1>';
$htmlBody .=  $this->divMensagens();

$htmlBody .= '<div id="divSelecionarFatoFinanceiroTipo" class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">';
$htmlBody .= '<label for="selecionaTipo">' . $this->translate('Selecione o Tipo') . '</label>';
$htmlBody .= '<select class="form-control" name="idFatoFinanceiroTipo" id="idFatoFinanceiroTipo" onchange="mostrarBotaoSelecionarFatoFinanceiroTipo()">';
$htmlBody .= '<option value="0" >' . $this->translate(Constantes::$TRADUCAO_SELECIONE) . '</option>';
foreach ($this->fatoFinanceiroTiposParceiroDeDeus as $fatoFinanceiroTipo) {
	$htmlBody .= '<option value="' . $fatoFinanceiroTipo->getId() . '" >' . $fatoFinanceiroTipo->getNome() . '</option>';
}
$htmlBody .= '</select>';

$htmlBody .= '<div id="divBotaoSelecionarFatoFinanceiroTipo" class="hidden mt10">';
$htmlBody .= $this->botaoSimples(Constantes::$TRADUCAO_SELECIONAR, $this->funcaoOnClick('selecionarFatoFinanceiroTipo()'));
$htmlBody .= '</div>';

$htmlBody .= '</div>';

$htmlBody .= '<div id="divLancamento" class="hidden">';

$htmlBody .= '<div class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">';
$htmlBody .= '<label for="selecionaEquipe">' . $this->translate('Selecione o Time') . '</label>';
$htmlBody .= '<select class="form-control" name="idEquipe" id="idEquipe" onChange="selecionarEquipe()">';
$htmlBody .= '<option value="0" >' . $this->translate(Constantes::$TRADUCAO_SELECIONE) . '</option>';
$informacao = $this->grupo->getEntidadeAtiva()->infoEntidade() . ' - ' . $this->grupo->getNomeLideresAtivos();
$htmlBody .= '<option value="' . $this->grupo->getId() . '" >' . $informacao . '</option>';
foreach ($this->discipulos as $grupoPaiFilhoFilho) {
	$informacao = $grupoPaiFilhoFilho->getGrupoPaiFilhoFilho()->getEntidadeAtiva()->infoEntidade() . ' - ' . $grupoPaiFilhoFilho->getGrupoPaiFilhoFilho()->getNomeLideresAtivos();
	$htmlBody .= '<option value="' . $grupoPaiFilhoFilho->getGrupoPaiFilhoFilho()->getId() . '" >' . $informacao . '</option>';
}
$htmlBody .= '</select>';
$htmlBody .= '</div>';
$htmlBody .= '<div class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">';
$htmlBody .= '<label for="selecionarSub">' . $this->translate('Qual Líder') . '<img src="img/loader.gif" id="loaderSub" class="hidden" /></label>';
$htmlBody .= '<select class="form-control" name="idGrupo" id="idGrupo" onChange="selecionarLider()">';
$htmlBody .= '<option value="0" >' . $this->translate(Constantes::$TRADUCAO_SELECIONE) . '</option>';
$htmlBody .= '</select>';
$htmlBody .= '</div>';

$htmlBody .= '<div id="divTipoIndividual" >';
$htmlBody .=  $this->inputFormularioSimples('Valor Individual', $formulario->get('individual'), 12);
/* div tipo individual */
$htmlBody .=  $this->inputFormularioSimples('Dia', $formulario->get(Constantes::$FORM_INPUT_DIA), 4, 2);
$htmlBody .=  $this->inputFormularioSimples('Mês', $formulario->get(Constantes::$FORM_INPUT_MES), 4, 2);
$htmlBody .=  $this->inputFormularioSimples('Ano', $formulario->get(Constantes::$FORM_INPUT_ANO), 4, 2);

$htmlBody .= '</div>';

$htmlBody .= '<div id="divTipoCelula" class="hidden">';
$htmlBody .= '<div class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">';
$htmlBody .= '<label for="selecionarCelula">' . $this->translate('Qual Célula') . '<img src="img/loader.gif" id="loaderCelula" class="hidden" /></label>';
$htmlBody .= '<select class="form-control" name="idGrupoEvento" id="idGrupoEvento" onChange="selecionarCelula()" >';
$htmlBody .= '<option value="0" >' . $this->translate(Constantes::$TRADUCAO_SELECIONE) . '</option>';
$htmlBody .= '</select>';
$htmlBody .= '</div>';
$htmlBody .=  $this->inputFormularioSimples('Valor Célula', $formulario->get('celula'), 12);
$htmlBody .= '<div class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">';
$htmlBody .= '<label for="selecionarDia">' . $this->translate('Qual Data') . '<img src="img/loader.gif" id="loaderData" class="hidden" /></label>';
$htmlBody .= '<select class="form-control" name="data" id="data" >';
$htmlBody .= '<option value="0" >' . $this->translate(Constantes::$TRADUCAO_SELECIONE) . '</option>';
$htmlBody .= '</select>';
$htmlBody .= '</div>';
/* div tipo celula */
$htmlBody .= '</div>';

$htmlBody .=  $this->formHidden($formulario->get(Constantes::$INPUT_CSRF));
$stringNomeDaFuncaoOnClickCadastro = 'validar(this.form)';
$htmlBody .= $this->botaoSimples('Lançar', $this->funcaoOnClick($stringNomeDaFuncaoOnClickCadastro));
$funcaoVoltar = $this->funcaoOnClick('location.href="/lancamentoParceiroDeDeusExtrato"');
$htmlBody .=  $this->botaoSimples('Voltar', $funcaoVoltar, BotaoSimples::botaoMenorImportancia);

/* div lancamento */
$htmlBody .= '</div>';

$tamanho = 600;
$html = '';
$html .= $this->form()->openTag($formulario);
$html .= '<div align="center">';
$html .= '<div class="panel mw'.$tamanho.'">';

$html .= '<div class="panel-body bg-light text-center">';
$html .= $htmlBody;
$html .= '</div>';

$html .= '</div>';
$html .= '</div>';
$html .= $this->form()->closeTag();
echo $html;
