<?php
use Application\Controller\Helper\Funcoes;
use Application\Controller\Helper\Constantes;
use Application\View\Helper\BotaoSimples;
?>
<div class="panel-body bg-light text-center mt50">
	<h1>Parceiro de Deus Extrato</h1>
<?php
$html = '';
if($this->fatos){
	$html .= '<input id="fooFilter" type="text" class="form-control" placeholder="Filtro">';
	$html .= '<table class="table table-condensed table-hover bg-light mt15 footable" data-filter="#fooFilter">';
	$html .= '<thead>';
	$html .= '<tr class="text-left">';
	$html .= '<th>Data</th>';
	$html .= '<th>Time</th>';
	$html .= '<th>Valor Individual</th>';
	$html .= '<th>Célula</th>';
	$html .= '<th>Valor Célula</th>';
	$html .= '<th>Sub Total</th>';
	$html .= '<td></td>';
	$html .= '</tr>';
	$html .= '</thead>';
	$html .= '<tbody>';
	$somaTotal = 0;
	foreach($this->fatos as $fatoParceiroDeDeus){
		$total = $fatoParceiroDeDeus->getIndividual() + $fatoParceiroDeDeus->getCelula();
		$htmlCelula = $this->translate(Funcoes::diaDaSemanaPorDia($fatoParceiroDeDeus->getEvento()->getDia(),1)).'-' . $fatoParceiroDeDeus->getEvento()->getHora() ;
		$funcaoExcluir = $this->funcaoOnClick('validarExclusao('.$fatoParceiroDeDeus->getId().')');
		$botaoExcluir = $this->botaoSimples('<i class="fa fa-times"></i>', $funcaoExcluir, BotaoSimples::botaoMuitoPequenoPerigoso); 

		$html .= '<tr class="text-left">';
		$html .= '<td>'.Funcoes::mudarPadraoData($fatoParceiroDeDeus->getData(),1).'</td>';
		$html .= '<td>'.$fatoParceiroDeDeus->getGrupo()->getEntidadeAtiva()->infoEntidade(). ' - ' . $fatoParceiroDeDeus->getGrupo()->getNomeLideresAtivos().'</td>';
		$html .= '<td>'.number_format($fatoParceiroDeDeus->getIndividual(),2,',','.').'</td>';
		$html .= '<td>'.$htmlCelula.'</td>';
		$html .= '<td>'.number_format($fatoParceiroDeDeus->getCelula(),2,',','.').'</td>';
		$html .= '<td>'.number_format($total,2,',','.').'</td>';
		$html .= '<td>' . $botaoExcluir . '</td>';
		$html .= '</tr>';

		$somaTotal += $total;
	} 
	$html .= '<tr class="dark text-left">';
	$html .= '<td colspan="5" class="text-right">Total</td>';
	$html .= '<td>'.number_format($somaTotal,2,',','.').'</td>';
	$html .= '<td></td>';
	$html .= '</tr>';

	$html .= '</tbody>';
	$html .= '</table>';

}else{
	$html .= '<div class="alert alert-warning text-center">Sem lançamentos</div>';
}

$html .= '<div class="panel-footer text-right">';
$stringNomeDaFuncaoOnClickCadastro = 'funcaoCircuito("lancamentoParceiroDeDeus", 0)';
$html .= $this->botaoLink('Lançar', Constantes::$STRING_HASHTAG, 0, $this->funcaoOnClick($stringNomeDaFuncaoOnClickCadastro));
$html .= '</div>';
echo $html;
?>
</div>
<script type="text/javascript">
function validarExclusao(idFatoParceiroDeDeus){
	let resposta = confirm('Realmente quer excluir esse lançamento?')
	if(resposta){
		funcaoCircuito('lancamentoParceiroDeDeusExcluir', idFatoParceiroDeDeus)
	}
}
</script>
