<?php use Application\Controller\Helper\Constantes; 
echo $this->templateFormularioTopo('Secretário Parceiro de Deus');
?>  
<form action="lancamentoParceiroDeDeusUsuarioFinalizar" method="POST">
<div class="panel-body bg-light">
    <div class="row">
        <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
            <div class="form-group">
                <select id="idPessoa" name="idPessoa" class="form-control mb10">
                    <option value="0"><?php echo $this->translate(Constantes::$TRADUCAO_SELECIONE); ?></option>
                    <?php 
                        if($this->lideres){
                            foreach($this->lideres as $lider){
                                echo '<option value="'.$lider->getId().'">'.$lider->getResponsabilidadesAtivas()[0]->getGrupo()->getEntidadeAtiva()->infoEntidade() . ' - ' . $lider->getNome().'</option>';
                            }
                        }
                    ?>
                </select>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
            <div class="row text-center">
                <div class="col">
                    <div class="option-group field section mb15">                       
                        <label class="block mb5 option option-primary" style="margin-left: 9px;">
                        <input type="radio" name="qualPerfilUsar" value="1" checked="checked">
                        <span class="radio"></span>Secretário de Equipe</label>
                        <label class="block mb5 option option-primary">
                        <input type="radio" name="qualPerfilUsar" value="2">
                        <span class="radio"></span>Secretário de Igreja</label>
                    </div>
                </div>
            </div>        
        </div>
    </div>
</div>
<!-- end .form-body section -->
<div class="panel-footer text-right">
<?php
    $stringNomeDaFuncaoOnClickCadastro = 'mostrarSplash(); funcaoCircuito("lancamentoParceiroDeDeusUsuarios", 0)';
    echo $this->botaoLink($this->translate(Constantes::$TRADUCAO_VOLTAR), Constantes::$STRING_HASHTAG, 2, $this->funcaoOnClick($stringNomeDaFuncaoOnClickCadastro));
    /* Submit */
    $funcaoVerificarCadastroPessoa = $this->funcaoOnClick('validar(this.form)');
    echo $this->botaoSimples(Constantes::$TRADUCAO_CADASTRAR, $funcaoVerificarCadastroPessoa);
    ?>
</div>  
</form>
<?php
$this->templateFormularioRodape();
/* Layout com javascript para tela de index */
echo $this->layoutJSCadastrarPessoaRevisao;
?>
<script type="text/javascript">
    function validar(form) {

        var idPessoa = $('#idPessoa').val();

        var temErro = false;
        var divMensagens = $('#divMensagens');
        var mensagem = '';
        var mensagemReal = '';

        if (idPessoa === '0') {
            temErro = true;
            if (mensagem == '') {
                mensagem = 'Líder';
            } else {
                mensagem += ', Líder';
            }
        }
        if (temErro) {
            mensagemReal = 'Preencha o(s) seguinte(s) campo(s): ' + mensagem;
            divMensagens
                    .html(mensagemReal)
                    .removeClass('alert-success')
                    .removeClass('hidden')
                    .addClass('alert-danger');
        } else {
            mostrarSplash();
            divMensagens
                    .addClass('hidden');
            form.submit();
        }
    }
</script>
