


<?php

use Application\Controller\Helper\Constantes;

?>
<!-- Nome: atendimento.phtml
     @author Lucas Filipe de Carvalho Cunha <lucascarvalho.esw@gmail.com>
     Descricao: Página para mostrar eficiência em atendimentos e a quantidade que cada disicpulo foi atendido.
  -->
<div class="mw1000 center-block p10">

    <?php echo $this->modalAba(); ?>

    <blockquote class = "blockquote-primary">
        <small>
          <?php  echo $this->translate(Constantes::$TRADUCAO_CABECALHO_TITULO_ATENDIMENTOS); ?>
        </small>
    </blockquote>
    <div class="row">
    <div id="atendimento" class="panel">
        <div class="panel-heading">
            <?php echo $this->abasAtendimento(); ?>

        </div> 
    </div>    
    </div>

            <?php
//            echo $this->cabecalhoDeAtendimentos();
            echo $this->atendimentoGruposAbaixoRelatorio();
            ?>        
        
    
<script type="text/javascript">
    function abrir144(idGrupo12) {
        var div144 = $('#grupos144'+ idGrupo12);
        var botaoMais = $('#botaoMais'+ idGrupo12);
        var botaoMenos = $('#botaoMenos'+ idGrupo12);
        div144.removeClass('hidden');
        botaoMais.addClass('hidden');
        botaoMenos.removeClass('hidden');
    }
    function fechar144(idGrupo12) {
        var div144 = $('#grupos144'+ idGrupo12);
        var botaoMenos = $('#botaoMenos'+ idGrupo12);
        var botaoMais = $('#botaoMais'+ idGrupo12);
        div144.addClass('hidden');
        botaoMenos.addClass('hidden');
        botaoMais.removeClass('hidden');
    }
</script>
    <?php
    /* Layout com javascript para tela de index */
    

    